### ISSUE TITLE
bigip_irule module not idempotent in ansible 2.1

### ISSUE THREAD

**Issue by gormeroth** [F5Networks/f5-ansible#10]
I know that ansible 2.1 isn't a stable release yet, but there are some bug fixes for f5 extras modules that are necessary.  However, when switching from 1.9.4 to 2.1, idempotence no longer works.  This happens with the most basic level:

- name: Create testproduct iRules
  local_action: >
    bigip_irule
    name=testproduct1_irule
    content="{{ lookup('file', 'testproduct1_irule.tcl') }}"
    server=f5server
    user=user
    password=secret
    module=ltm
    state=present
    validate_certs=False

**Comment by caphrim007** [comment]
@gormeroth I believe the recent update I made to the irule module should make it work again. Please try it out and let me know. If it still does not, I might need to see the irule in question to figure out why it is not working.

**Comment by dbeckham** [comment]
@caphrim007, I can confirm that the `bigip_rule` module is still not idempotent as of a few days ago.  Ansible shows the task changed everytime I run it whether or not the content of the rule has actually changed.  If it would help, I can create a new issue with a config example and debug output from `ansible-playbook`.

**Comment by caphrim007** [comment]
@dbeckham please do

**Comment by dbeckham** [comment]
@caphrim007 I created #42 with details. It seems to only happen if the content/src ends in a newline character.
