### ISSUE TITLE
bigip_device_facts - connection refused when trying to get all facts

### ISSUE THREAD

**Issue by JapaneseMuscleDE** [F5Networks/f5-ansible#1017]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_facts

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017

```

##### LIBRARY VERSIONS
```
f5-sdk==3.0.17
```

##### SUMMARY
When I try to use the Module with the gather_subset set to "all" I the "connection refused" error. However no connection is refused at all (I checked this with tcpdump and a packet anylsis) Last thing happens there is a Reset from the Ansible Server to the F5 to close the session, so thats the reason of the confusing error message.

[f5_facts.zip](https://github.com/F5Networks/f5-ansible/files/2509997/f5_facts.zip)

However if I use the same Playbook below with an other subset selection like "pool" i dont get an error at all and it returns the facts as intended

##### STEPS TO REPRODUCE
I can reproduce the issue with following playbook

```
---

-
  hosts:
    localhost

  vars:
    f5:
      server: f5-ltm
      user: admin
      password: ansible
      server_port: 443
      validate_certs: no
      transport: rest


  tasks:
    - name: Gather Facts
      bigip_device_facts:
        provider: "{{ f5 }}"
        gather_subset:
          - all
      register: bigip_facts

...
```

##### EXPECTED RESULTS
I expected to see the Facts for ALL of the choices possible

##### ACTUAL RESULTS
No Facts are gathered at all because the following error:

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 13378, in main
    results = mm.exec_module()
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 13126, in exec_module
    result = self.execute_managers(managers)
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 13202, in execute_managers
    result = manager.exec_module()
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 5924, in exec_module
    facts = self._exec_module()
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 5929, in _exec_module
    facts = self.read_facts()
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 5934, in read_facts
    collection = self.read_collection_from_device()
  File "/tmp/********_bigip_device_facts_payload_8Jd7P0/__main__.py", line 5950, in read_collection_from_device
    raise F5ModuleError(response['message'])

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "gather_subset": [
                "all"
            ],
            "password": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "f5-ltm",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "server": null,
            "server_port": null,
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    },
    "msg": "java.net.ConnectException: Connection refused"
}
```

**Comment by caphrim007** [comment]
this looks like an error coming directly from the REST API. Can you try doing `bigstart restart restjavad` on your bigip?

**Comment by JapaneseMuscleDE** [comment]
I also thought is was the F5 at first but I already reloaded it completely without any change. And as stated above same playbook works with 

```
gather_subset:
          - monitors
```

its just the "all" that doenst work.

However, I tried doing the restart and I get this form the CLI

```
[root@f5-ltm:Active:Standalone] config # bigstart restart restjaved
Couldn't find service: restjaved
Couldn't find service: restjaved
```

**Comment by caphrim007** [comment]
restjavAd; ie, "rest", "java", "d".

Yours has an "e" instead of an "a"

**Comment by caphrim007** [comment]
ok. my 2nd guess then in that we are denial of servicing the REST API and it returns that error while it's in the middle of restarting itself. I'll have a look.

**Comment by JapaneseMuscleDE** [comment]
Check out the archive that I dropped in here as well, it contains the tcpdump. You ll see its right at the beginning, so I am not positive about the DoS thought you have.

**Comment by caphrim007** [comment]
@JapaneseMuscleDE can you provide the list of bigip modules that you have provisioned?

**Comment by pg0581** [comment]
@caphrim007 I'm experiencing the same issue @JapaneseMuscleDE is seeing as well. The "- all" option doesn't work and you get the "msg": "java.net.ConnectException: Connection refused" error. So far the other options under "gather_subset" works.

**Comment by JapaneseMuscleDE** [comment]
@caphrim007 Hope thats what you were looking for? We only provisioned the LTM on the VE F5

root@(f5-ltm)(cfg-sync Standalone)(Active)(/Common)(tmos)# list sys provision
sys provision afm { }
sys provision am { }
sys provision apm { }
sys provision asm { }
sys provision avr { }
sys provision fps { }
sys provision gtm { }
sys provision ilx { }
sys provision lc { }
sys provision ltm {
    level nominal
}
sys provision pem { }
sys provision swg { }

**Comment by caphrim007** [comment]
@JapaneseMuscleDE identified the problem. This appears to be being caused by ASM not being provisioned. I'll fix this.

**Comment by babaksabooniha** [comment]
Hi,

I had the same problem and "bigstart restart restjavad" didn't help me.
Is there any other step to go?

**Comment by JapaneseMuscleDE** [comment]
> Hi,
> 
> I had the same problem and "bigstart restart restjavad" didn't help me.
> Is there any other step to go?

Try specifing the facts you want to get or at leas exclude the ASM related ones.
