### ISSUE TITLE
Pool members from Common partition add to pool in any other partition

### ISSUE THREAD

**Issue by chiccat** [F5Networks/f5-ansible#1027]
Hi,
We keep all our nodes in Common partition.
Is it possible to add functionality to allow attach those nodes to pools in any other partition?
My understanding that f5 python module support this (I, also, used to to this with f5 api through chef).

Thanks

**Comment by caphrim007** [comment]
@chiccat this should be possible, but is not currently due to the way that the pool member module handles pool names. I have a fix for this though that I am testing now.
