### ISSUE TITLE
bigip_device_dns module 'forwarders' parameter is not getting populated

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#103]
Hi Team.....

Task is as follows:
- name: Manage BIG-IP DNS settings
    bigip_device_dns:
     server: "{{ inventory_hostname }}"
     user: "{{ username }}"
     password: "{{ password }}"
     name_servers:
       - "{{ dns_server1 }}"
       - "{{ dns_server2 }}"
     search:
       - "{{ dns_search_domain1 }}"
       - "{{ dns_search_domain2 }}"
     forwarders:
       - "{{ bind_server1 }}"
       - "{{ bind_server2 }}"
     ip_version: "{{ ip_version }}"
     validate_certs: False

However the BIND forwarder list is not getting updated on the BIG-IP. (All other parameters are updated correctly)

BIG-IP version - 12.0

**Comment by payalsin** [comment]
hey its happening with the module available with ansible 2.2 (did not pull modules from dev branch). Thanks

**Comment by caphrim007** [comment]
can you try the dev branch module? it would be the successor that is going to go upstream eventually

**Comment by caphrim007** [comment]
@mryanlam can you look at this?

**Comment by mryanlam** [comment]
Yes, I can

**Comment by payalsin** [comment]
I tried the dev branch module and am still seeing the issue...thanks

**Comment by mryanlam** [comment]
How are you checking the value of the forwarders after setting them via ansible?
Are you checking via the Management GUI?

**Comment by payalsin** [comment]
Yes that's correct checking them via the management GUI

**Comment by mryanlam** [comment]
F5 Product Development has assigned ID 567490 to this issue.
It is not an issue with F5-ansible, but with the management gui.

**Comment by caphrim007** [comment]
@mryanlam @payalsin can you set this forwarders value using tmsh?

**Comment by delgadillo22** [comment]
Not clear if this a bug with F5 Ansible

**Comment by caphrim007** [comment]
removed this option. It is a bug in BIG-IP @delgadillo22. You can only modify this setting via TMUI, and there is no movement to fix that. Unfortunate
