### ISSUE TITLE
bigip_asm_policy: no policy created when neither template nor file is specified

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible#1030]
within:
https://github.com/F5Networks/f5-ansible/blob/97917c53466e54a1601873209925bda1db827c53/library/modules/bigip_asm_policy.py#L566
https://github.com/F5Networks/f5-ansible/blob/97917c53466e54a1601873209925bda1db827c53/library/modules/bigip_asm_policy.py#L577-L578
indicates a blank policy should be created when neither a `template` nor `file` is specified. Documentation doesn't require `template` nor `file` to be specified.

However traceback is thrown instead:
```in _file_is_missing\n  File \"../lib/python3.7/genericpath.py\", line 19, in exists\n    os.stat(path)\nTypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType\n",```

this is due to the logic in:
https://github.com/F5Networks/f5-ansible/blob/97917c53466e54a1601873209925bda1db827c53/library/modules/bigip_asm_policy.py#L559-L561

called in `create`:
https://github.com/F5Networks/f5-ansible/blob/97917c53466e54a1601873209925bda1db827c53/library/modules/bigip_asm_policy.py#L569-L572

Removing `self.want.template` from `_file_is_missing` would solve the problem, also `_file_is_missing` indicates a clear purpose, which is checking for file existence not checking for `self.want.template`:
```
def _file_is_missing(self):
   if self.want.file is None:
    return False
```

**Comment by wojtek0806** [comment]
This module will not support creating empty policies at this stage, the simple fact being that we do not offer any kind of policy settings tweaking with ansible. I can include a boolean to indicate a desire for empty policy creation. However no modification of its settings would be possible, as this requires careful planning given the amount of REST endpoints involved. If you have desire for such options to be added apart from empty policy creation, modify this issue with the specifics. I will talk to you tomorrow on the details cause if this a bigger job we might have to coordinate with Kevin.

**Comment by wojtek0806** [comment]
@simonkowallik submitting PR shortly
