### ISSUE TITLE
bigip_ppol_member priority-group settings

### ISSUE THREAD

**Issue by sfriz** [F5Networks/f5-ansible#106]
##### ISSUE TYPE

 - Feature Idea
##### COMPONENT NAME

bigip_pool_member
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       5.0.429
  Edition     Hotfix HF5
  Date        Thu Jun 18 17:57:52 PDT 2015

```

##### SUMMARY

We are trying to use ansible to automate changing Priority Group settings of pool members. bigip_pool and bigip_pool_member don't currently have the ability to modify or set Priority Group.  This is something we are trying to implement as part of a blue/green strategy. 
Our current versions of Ansible and BIG-IP prevent us from taking advantage of the bigip_command module. 
Still investigating use of the 'raw' module to execute the F5 cli commands.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@sfriz this should be complete thanks to @ossark and their commit here https://github.com/ansible/ansible/pull/23128

I have backported that commit into this repository here. The option is `priority_group` as you would see it in tmui and tmsh
