### ISSUE TITLE
bigip_rules module will not allow src file anywhere but directory where playbook is run

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1080]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
this was reported as no longer being an issue. closing
