### ISSUE TITLE
bigip_user module doesn't allow update_password = always on new user

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1085]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_user module
##### ANSIBLE VERSION

```
2.71
```

##### PYTHON VERSION

```
2.71
```

##### BIGIP VERSION

```
13.1.1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4
##### SUMMARY

Creating a new user ID requires update_password = on_create, but must be changed to always in order to update the password.  There is no error indication that the password was not changed when update_password = always, but the password is not changed.  This is inconsistent with the doc and requires a separate playbook to create vs. manage user IDs.

##### STEPS TO REPRODUCE

```
  - name:                               "Local user {{ UserID }}"
    bigip_user:
      username_credential:              "{{ UserID }}"
      password_credential:              "{{ NewPass }}"
      full_name:                        "{{ FullName }}"
      partition_access:                 "{{ Access }}"
      shell:                            "{{ Shell }}"
      update_password:                  always
```

##### EXPECTED RESULTS

That a new user would be created with the provided password
##### ACTUAL RESULTS

```
fatal: [cpf5dv.sherwin.com]: FAILED! => {"changed": false, "msg": "The 'update_password' option needs to be set to 'on_create' when creating a resource with a password."}
```

**Comment by caphrim007** [comment]
weird. i dont know why we would care to enforce on_create like we do here. lemme fix that

**Comment by C0missar** [comment]
The behavior hasn't changed.  Just pulled the master 5 minutes ago.

**Comment by C0missar** [comment]
fatal: [cpf5dv.sherwin.com]: FAILED! => {"changed": false, "msg": "The 'update_password' option needs to be set to 'on_create' when creating a resource with a password."}

**Comment by caphrim007** [comment]
@C0missar make sure you force update the role. That error message is no longer in the source code, so if you're still receiving it, then you can be sure you're not running the current code.
