### ISSUE TITLE
bigip_asm_policy module fails if source path is ~-relative AND policy does not exist on destination

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1087]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_asm_policy
##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.47.4
  Edition     Engineering Hotfix
  Date        Fri Sep 14 17:15:18 PDT 2018

Hotfix List
ID743437-1    ID724868-1  ID700827-4  ID630137-2  ID722893-1  ID692158-1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4
##### SUMMARY

Module fails to create or update the ASM policy at the destination if the source file path is $HOME relative, but only if the policy does not exist on the destination.  This also implies that if it had changed at the source, the module flagged the destination as OK even though it couldn't find the source to compare it with.
##### STEPS TO REPRODUCE

```
https://gist.github.com/C0missar/d2e9b5c61119879e29783fa0aa4086ce

This shows a ~-relative source file path, and updates against two hosts; cpf5dv did not have the ASM policy, and cpdfwdv did.  The log output shows that the first failed, but the second one worked.  Changing the source file path to an absolute reference allowed it to update properly, but I wonder if it is actually checking to see if the policy had changed.
```

https://gist.github.com/C0missar/d2e9b5c61119879e29783fa0aa4086ce

##### EXPECTED RESULTS

I expected both devices to be updated; a ~-relative file path should work, similar to Bug #1080.

But if the path failed, it should have failed for both, not one of each.

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
as the role is updated nightly I would recommend to pull down the latest role and retest, as @caphrim007 fixed it already by adding 'path' type to file parameter.
