### ISSUE TITLE
bigip_virtual_server module cannot leave existing VS in disabled state

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1088]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.47.4
  Edition     Engineering Hotfix
  Date        Fri Sep 14 17:15:18 PDT 2018

Hotfix List
ID743437-1    ID724868-1  ID700827-4  ID630137-2  ID722893-1  ID692158-1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4
##### SUMMARY

"state=present" on an existing VS changes the VS state to "enabled".  If the VS already exists, it should leave the state as it was before, which might have been "disabled"; otherwise, there is no way to make a change to a VS that does not enable it unintentionally.  If that has an impact on some other use case, then consider adding a value of "unchanged" or similar, that on a new VS would mean create enabled, and on an existing VS would mean present and unchanged/don't modify.

As a feature request for consideration, how about having a separate enabled=yes/no field (for all modules that support being disabled), and who's value would take precedent over the state parameter?  State is an Ansible concept and parameter that has a meaning outside of the F5 usage, and the F5 definition extension is counter-intuitive and dangerous.

##### STEPS TO REPRODUCE

```
<script src="https://gist.github.com/C0missar/a3d4b82704f0be775f728b028272e7c4.js"></script>

Existing VS before play:

ltm virtual vs_Test {
    destination 10.10.10.10:https
    disabled
    ip-protocol tcp
   <snip>

Play:

  - name:                               "vs_Test"
    bigip_virtual_server:
      name:                             "vs_Test"
      state:                            present
```

<script src="https://gist.github.com/C0missar/a3d4b82704f0be775f728b028272e7c4.js"></script>
##### EXPECTED RESULTS

No change to the VS (remain disabled)
##### ACTUAL RESULTS

Disabled VS was enabled

```
VS after play:

ltm virtual vs_Test {
    destination 192.168.111.73:https
    ip-protocol tcp
   <snip>
(VS is no longer disabled)
```

**Comment by caphrim007** [comment]
@C0missar  this is expected behavior.

From the documentation

"""
C(present) creates the virtual server and enable it.
"""

**Comment by C0missar** [comment]
Updating just the descriptions on a dozen disabled virtual servers and suddenly having them go active is NOT expected behavior, and there is no workaround.  Please reopen this as a feature request.

**Comment by caphrim007** [comment]
@C0missar no. use `state: disabled`
