### ISSUE TITLE
bigip_asm_policy fails with "ImportError: cannot import name HAS_F5SDK" after code update

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1110]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool
##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.47.4
  Edition     Engineering Hotfix
  Date        Fri Sep 14 17:15:18 PDT 2018

Hotfix List
ID743437-1    ID724868-1  ID700827-4  ID630137-2  ID722893-1  ID692158-1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4
##### SUMMARY

This code worked prior to pulling ansible-galaxy install -f f5devcentral.f5ansible,master today.
##### STEPS TO REPRODUCE

```
https://gist.github.com/C0missar/96df970cc23e62b8ddd0e1d50c9064fd (ASMtest.yaml)
```

##### EXPECTED RESULTS

Policy creation
##### ACTUAL RESULTS

TASK [asm_Master_Unix_Linux] *********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name HAS_F5SDK
fatal: [cpf5dv.sherwin.com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/sxw455/.ansible/tmp/ansible-tmp-1544315395.31-11006418684414/AnsiballZ_bigip_asm_policy.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/sxw455/.ansible/tmp/ansible-tmp-1544315395.31-11006418684414/AnsiballZ_bigip_asm_policy.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/sxw455/.ansible/tmp/ansible-tmp-1544315395.31-11006418684414/AnsiballZ_bigip_asm_policy.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_asm_policy_payload_OjrCTA/__main__.py\", line 236, in <module>\nImportError: cannot import name HAS_F5SDK\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
https://gist.github.com/C0missar/96df970cc23e62b8ddd0e1d50c9064fd (ASMtest.log)
```

**Comment by wojtek0806** [comment]
the error relates to old version of code, which does not exist, the module changed its name to reflect that with _ at the start, so its possible you are calling a module outside of the role. In any case this is a local error not an issue with the role or code, closing
