### ISSUE TITLE
bigip_asm_policy_import not idempotent

### ISSUE THREAD

**Issue by VeselaHouba** [F5Networks/f5-ansible#1113]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_asm_policy_import

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /opt/ansible-ab/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

```
CentOS Linux release 7.6.1810 (Core)
```
##### SUMMARY

When running `bigip_asm_policy_import` repeatedly, it always shows `changed` even when *not* using `force` option.

##### STEPS TO REPRODUCE

ansible-playbook playbooks/debug.yml  -vvv
ansible-playbook playbooks/debug.yml  -vvv

https://gist.github.com/VeselaHouba/2f61fdf04362b19fdc51d22af090cd47

##### EXPECTED RESULTS

- 1st run - [changed]
- 2nd run - [ok]

##### ACTUAL RESULTS

- 1st run - [changed]
- 2nd run - [changed]

https://gist.github.com/VeselaHouba/18da7ce85f31bb2ae811306180fa0cd4

**Comment by wojtek0806** [comment]
I suspect this could be to this line: https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_asm_policy_import.py#L273

I found cases where fullstops, spaces or dashes cause the oData filter to break, will fix shortly

**Comment by VeselaHouba** [comment]
Confirmed working. Thanks.
