### ISSUE TITLE
bigip_virtual_server erroneously reports success deleting a VS

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1114]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.47.4
  Edition     Engineering Hotfix
  Date        Fri Sep 14 17:15:18 PDT 2018

Hotfix List
ID743437-1    ID724868-1  ID700827-4  ID630137-2  ID722893-1  ID692158-1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4
##### SUMMARY

TASK [Delete vs_websso.sherwin.com_waf] completes with OK (Green), implying that the VS no longer exists (since no change, meaning it didn't have to delete anything), but attempt to delete pool fails because of the existing VS reference.  A check on the bigip shows that the VS still exists.

##### STEPS TO REPRODUCE

```
https://gist.github.com/C0missar/a5c02db345b2407f2da80a0ca1e5392c (WAF_Delete.yaml)
```

##### EXPECTED RESULTS

The VS vs_websso.sherwin.com_waf would be deleted
##### ACTUAL RESULTS

The task completed with "OK (Green)" meaning that the VS did not exist to be deleted, but the VS did exist.

```
https://gist.github.com/C0missar/a5c02db345b2407f2da80a0ca1e5392c (WAF_Delete.log)
```

**Comment by wojtek0806** [comment]
just looked at the output, is this a typo, cause having state as 'present' will not delete VS for you?

https://gist.github.com/C0missar/a5c02db345b2407f2da80a0ca1e5392c#file-waf_delete-yaml-L51

**Comment by C0missar** [comment]
Ouch! That's embarrassing; you can close this issue. Thanks!
