### ISSUE TITLE
"...value is not a valid IP address" When Using Route Domain ID

### ISSUE THREAD

**Issue by js-f5** [F5Networks/f5-ansible#1124]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME
ipaddress.py

##### ANSIBLE VERSION

```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017
```

##### LIBRARY VERSIONS

```
ansible==2.7.5
Babel==0.9.6
backports.ssl-match-hostname==3.5.0.1
certifi==2018.11.29
cffi==1.6.0
chardet==3.0.4
cryptography==1.7.2
enum34==1.0.4
f5-icontrol-rest==1.3.11
f5-sdk==3.0.20
httplib2==0.9.2
idna==2.8
iniparse==0.4
ipaddress==1.0.16
Jinja2==2.7.2
jmespath==0.9.0
MarkupSafe==0.11
paramiko==2.1.1
ply==3.4
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.0
pygpgme==0.3
pyliblzma==0.5.3
python-keyczar==0.71rc0
pyxattr==0.5.1
PyYAML==3.10
requests==2.21.0
six==1.9.0
style==1.1.0
update==0.0.1
urlgrabber==3.10
urllib3==1.24.1
yum-metadata-parser==1.1.4
```

##### CONFIGURATION

host_key_checking = False

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY
Attempt to create a Pool and add Pool-Members with IP Addresses that have a Route Domain ID which failed.

##### STEPS TO REPRODUCE

Run a playbook to add a Pool-Member to a Pool with the "host:" configured with a Route Domain ID.
Snippet of playbook used...
_- name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        **host: 192.168.3.11%1**
        name: "some.node.name"
        pool: "poolname"
        port: 80_

Modified "is_vaild_ip()" method in ipaddress.py module and added these methods. The resulting changes check for a valid Route Domain ID, and if found strips it off before sending to python "validate_ip_address()" method. If the Route Domain ID is invalid (Ex. 01, 645535 or 000, etc.), the original address with the invalid Route Domain ID gets passed to "validate_ip_address()" and will fail using the default internal behavior. The same functionality was also extended to IPv6 as well. 

```
def is_route_domain(addr):
    try:
        id = addr.split("%")[1]
        if str(int(id)) == id and 0 <= int(id) <= 65534:
              return True
    except:
        return False


def remove_route_domain_id(addr):
    return addr.split("%")[0]


def is_valid_ip(addr, type='all'):
    if type in ['all', 'ipv4']:
        if is_route_domain(addr):
            addr = remove_route_domain_id(addr)
        if validate_ip_address(addr):
            return True
    if type in ['all', 'ipv6']:
        if is_route_domain(addr):
            addr = remove_route_domain_id(addr)
        if validate_ip_v6_address(addr):
            return True
    return False
```

```
- name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        host: 192.168.3.11%1
        name: "some.node.name"
        pool: "poolname"
        port: 80
```

##### EXPECTED RESULTS

A Pool-Member to be added to the Pool using its IP Address & Route Domain ID
##### ACTUAL RESULTS

```
<SCRUBBED> EXEC /bin/sh -c 'echo ~root && sleep 0'
<SCRUBBED> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296 `" && echo ansible-tmp-1545244493.85-56804936933296="` echo /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool_member.py
<SCRUBBED> PUT /root/.ansible/tmp/ansible-local-3363MiiHmE/tmpKyVGf3 TO /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296/AnsiballZ_bigip_pool_member.py
<SCRUBBED> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296/ /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296/AnsiballZ_bigip_pool_member.py && sleep 0'
<SCRUBBED> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296/AnsiballZ_bigip_pool_member.py && sleep 0'
<SCRUBBED> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1545244493.85-56804936933296/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_pool_member_payload_Cc697A/__main__.py", line 834, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_pool_member_payload_Cc697A/__main__.py", line 578, in exec_module
    changed = self.present()
  File "/tmp/ansible_bigip_pool_member_payload_Cc697A/__main__.py", line 603, in present
    return self.create()
  File "/tmp/ansible_bigip_pool_member_payload_Cc697A/__main__.py", line 702, in create
    if self.want.name and not any(x for x in [self.want.address, self.want.fqdn_name]):
  File "/tmp/ansible_bigip_pool_member_payload_Cc697A/__main__.py", line 390, in address
    "The specified 'address' value is not a valid IP address."

failed: [SCRUBBED] (item=3) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address": "192.168.3.11%1",
            "auth_provider": null,
            "connection_limit": null,
            "description": "server 3",
            "fqdn": null,
            "fqdn_auto_populate": null,
            "host": "192.168.3.11%1",
            "name": "server-1",
            "partition": "Common",
            "password": null,
            "pool": "pool-3",
            "port": 80,
            "preserve_node": null,
            "priority_group": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "SCRUBBED",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "rate_limit": null,
            "ratio": null,
            "reuse_nodes": true,
            "server": null,
            "server_port": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    },
    "item": "3",
    "msg": "The specified 'address' value is not a valid IP address."
}
```

**Comment by wojtek0806** [comment]
this issue has been fixed, it won't be released until 2.8, if you want to use the current lib please use role:
https://galaxy.ansible.com/f5devcentral/f5ansible

or use the modules from our devel branch

**Comment by js-f5** [comment]
I didn't find a devel branch on Github, all there seems to be is the master. Is the devel branch located elsewhere?

-Cheers
James

**Comment by wojtek0806** [comment]
there is no master branch devel branch and stable 2.7 branch but stable is not used.

 If you intend to copy the branch code then you need to accept that you do so at your own peril, so it will be up to you to make sure the code is updated. 

I suggest using the ansible role as we run nightly builds on that so if you find issue i can fix it and you have it in galaxy the next day.

**Comment by js-f5** [comment]
So far the only issues is the Route Domains. I tried creating a Virtual Server with a Route Domain ID and that didn't work as well.  It didn’t fail or throw and error but I can see there is a discrepancy between the "module_args" and the final destination value. Here is a snippet from the -vvv output,.

"address_translation": false,
    "changed": true,
    "description": "VS #4",
    "destination": "10.3.1.104",
    "invocation": {
        "module_args": {
            "address_translation": null,
            "auth_provider": null,
            "default_persistence_profile": null,
            "description": " VS #4",
            "destination": "10.3.1.104%1",
            "disabled_vlans": null,
            "enabled_vlans": null,


I'm looking through the bigip_virtual_server.py module now and see references to route domains in some of the destination formatting methods but doesn’t seem to work. Is this also something that is being correct in 2.8 or should this already be working in 2.7?

-Cheers
James

**Comment by wojtek0806** [comment]
I would suggest looking in the integration tests, specifically the one I wrote when I fixed issue 751, which is what you were looking for:

Playbook:

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_virtual_server/tasks/provider/issue-00751.yaml#L136

Variables:

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_virtual_server/vars/issue-00751.yaml#L6

**Comment by js-f5** [comment]
And did this work because I am have no success on v2.7 I just setup. Even doing a basic playbook with no variables like I showed creates the VS unlike failing when trying to create Pool-Members but it just omits the RD ID every time.

-Cheers
James

**Comment by vikas7999** [comment]
Is this issue resolved as unable to add pool member when using Route Domain % sign ex 3.3.3.3%2.
Interesting ansible able to create node with the Route domain but unable to add the node to Pool member due to issue with Route domain. I am using ansible ver 2.7. Any body knows the workaround.

**Comment by vikas7999** [comment]
Anybody can confirm if this bug with ansible F5 pool member is fixed
