### ISSUE TITLE
bigip_user not allowing admin partition access for all partitions

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#113]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
@caphrim007 
is this fixed, i think you pushed changes for this already ?

**Comment by caphrim007** [comment]
yep
