### ISSUE TITLE
bigip_ucs_fetch hangs

### ISSUE THREAD

**Issue by auto2mate** [F5Networks/f5-ansible#1152]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_ucs_fetch

##### ANSIBLE VERSION

```

ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]

```

##### PYTHON VERSION

```
 python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]

```

##### BIGIP VERSION

```
12.1.2
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Linux testbed1 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

playbooks hangs 

##### STEPS TO REPRODUCE
- name: Download a new UCS
  hosts: LB01
  connection: local
  gather_facts: false

  vars_prompt:
   - name: username
     prompt: "Enter Username to Loigin to F5"
   - name: password
     prompt: "Enter password to Login to F5"

  tasks:
      - name: backup
        bigip_ucs_fetch:
          server: LB01
          user: "{{ username }}"
          password: "{{ password }}"
          src: cs_backup.ucs
          dest: /tmp/cs_backup.ucs
          validate_certs: False
        delegate_to: localhos

```
ansible-playbook f5-backup.yml -vvvv

```

##### EXPECTED RESULTS

It should generate the ucs file at "/tmp/cs_backup.ucs"
##### ACTUAL RESULTS

It hangs  here....

```


ansible-playbook 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: f5-backup.yml *********************************************************************************************************************************************************
1 plays in f5-backup.yml
Enter Username to Loigin to F5:
Enter password to Login to F5:

PLAY [Download a new UCS] *******************************************************************************************************************************************************
META: ran handlers

TASK [backup] *******************************************************************************************************************************************************************
task path: /home/f5-backup.yml:14
<10.2.97.1> connection transport is rest
<10.2.97.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.2.97.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.2.97.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1546222451.7-76494957509506 `" && echo ansible-tmp-1546222451.7-76494957509506="` echo /root/.ansible/tmp/ansible-tmp-1546222451.7-76494957509506 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_ucs_fetch.py
<10.2.97.1> PUT /root/.ansible/tmp/ansible-local-88288sAjh6/tmprVSMZF TO /root/.ansible/tmp/ansible-tmp-1546222451.7-76494957509506/AnsiballZ_bigip_ucs_fetch.py
<10.2.97.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1546222451.7-76494957509506/ /root/.ansible/tmp/ansible-tmp-1546222451.7-76494957509506/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<10.2.97.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1546222451.7-76494957509506/AnsiballZ_bigip_ucs_fetch.py && sleep 0'

```

**Comment by wojtek0806** [comment]
please try this using the ansible galaxy role, this allows you to test with the latest F5 devel code:

https://galaxy.ansible.com/f5devcentral/f5ansible

**Comment by wojtek0806** [comment]
i have fixed the issue with the role it should be good to go now, if you need to reinstall it use the following command:

```
ansible-galaxy install -f f5devcentral.f5ansible,master
```

**Comment by wojtek0806** [comment]
@auto2mate have you had a chance to test it?

**Comment by auto2mate** [comment]
I have attempted to installed it, got below error - 

# ansible-galaxy install -f f5devcentral.f5ansible,master
 [WARNING]: - f5devcentral.f5ansible was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL
certificate for galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9
on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]) or you can install the `urllib3`,
`pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the
servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-
certificates/cacert.org, /etc/ansible. The exception msg was: hostname u'galaxy.ansible.com' doesn't match either of '*.c1e4.galaxy.openshiftapps.com',
'c1e4.galaxy.openshiftapps.com'.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by wojtek0806** [comment]
This is an issue with your environment, most likely some packages are missing, I would suggesting heading to ansible galaxy forums/mailing list for further support to resolve this error message.

**Comment by wojtek0806** [comment]
@auto2mate have you managed to test this ?

**Comment by wojtek0806** [comment]
closing for now, let me know when you had a chance to test this and it fails with the role
