### ISSUE TITLE
Provide a way to set Admin password via SSL for onboarding a new device

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1165]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

Feature request

##### COMPONENT NAME

None exists
##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
(Actually applies to all version)

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When spinning up a new image (such as in AWS using the F5 CFTs) and Ansible, there is no way to set the admin and/or root passwords programatically; without this, no REST calls can be made, so no Ansible playbooks or AS3 declarations can be made.  It requires a manual SSH to the device to set up a user account/password before any further automated tasks can be performed.

The AWS QuickStart guide states that the user ID of quickstart and password (InstanceID) will work when using the F5 supported CFTs, but this UID is not created by the CFT.  There are several other errors in the AWS Quick Start guide related to SSH connectivity (it implies that a bastion host configuration is required, for instance).

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
@C0missar 
Have you checked this role as it seems to do what you are asking:

https://galaxy.ansible.com/f5devcentral/bigip_onboard

**Comment by C0missar** [comment]
That role didn't exist when we wrote all of our onboarding stuff, and it's still not documented on clouddocs.  I'm a little reluctant to do everything over,  especially as I can't really tell how it works.

Besides, I can't get the installation to run:

$ ansible-galaxy install -f f5devcentral.bigip-onboarding,master
- downloading role 'bigip-onboarding', owned by f5devcentral
 [WARNING]: - f5devcentral.bigip-onboarding was NOT installed successfully: - sorry, f5devcentral.bigip-onboarding was not found on https://galaxy.ansible.com.

But the normal role install/update works:

$ ansible-galaxy install -f f5devcentral.f5ansible,master
- downloading role 'f5ansible', owned by f5devcentral
- downloading role from https://github.com/f5devcentral/ansible-role-f5ansible/archive/master.tar.gz
- extracting f5devcentral.f5ansible to /home/sxw455/.ansible/roles/f5devcentral.f5ansible
- f5devcentral.f5ansible (master) was installed successfully

Cheers,

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by C0missar** [comment]
Umm, also, the Declarative Onboarding page starts right off (https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/prereqs.html) with

"You must have an existing user account with the Administrator role. If you are using 13.1.x, the BIG-IP contains an admin user by default. If you are using 14.x, you must reset the admin password before installing Declarative Onboarding".  (And even in v13.1.x, the Admin password must be reset if built via the CFT).

As that was the specific issue I wanted addressed with #1165, I'm not sure how this helps.  We can programmatically onboard a BigIP now if it has a functional Admin password. 

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----Stan Ward/NA/Sherwin-Williams wrote: -----
To: "F5Networks/f5-ansible" <reply@reply.github.com>
From: Stan Ward/NA/Sherwin-Williams
Date: 2019/01/27 21:50
Cc: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>, "Mention" <mention@noreply.github.com>
Subject: Re: [EXTERNAL] Re: [F5Networks/f5-ansible] Provide a way to set Admin password via SSL for onboarding a new device (#1165)

That role didn't exist when we wrote all of our onboarding stuff, and it's still not documented on clouddocs.  I'm a little reluctant to do everything over,  especially as I can't really tell how it works.

Besides, I can't get the installation to run:

$ ansible-galaxy install -f f5devcentral.bigip-onboarding,master
- downloading role 'bigip-onboarding', owned by f5devcentral
 [WARNING]: - f5devcentral.bigip-onboarding was NOT installed successfully: - sorry, f5devcentral.bigip-onboarding was not found on https://galaxy.ansible.com.

But the normal role install/update works:

$ ansible-galaxy install -f f5devcentral.f5ansible,master
- downloading role 'f5ansible', owned by f5devcentral
- downloading role from https://github.com/f5devcentral/ansible-role-f5ansible/archive/master.tar.gz
- extracting f5devcentral.f5ansible to /home/sxw455/.ansible/roles/f5devcentral.f5ansible
- f5devcentral.f5ansible (master) was installed successfully

Cheers,

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by C0missar** [comment]
The example playbook at https://galaxy.ansible.com/f5devcentral/bigip_onboard seems to have a typo in the name, but that install fails as well.

- { role: f5devcentral.bigip-onboarding }

$ ansible-galaxy install -f f5devcentral.bigip_onboarding,master
- downloading role 'bigip_onboarding', owned by f5devcentral
 [WARNING]: - f5devcentral.bigip_onboarding was NOT installed successfully: - sorry, f5devcentral.bigip_onboarding was not found on https://galaxy.ansible.com.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----Stan Ward/NA/Sherwin-Williams wrote: -----
To: "F5Networks/f5-ansible" <reply@reply.github.com>
From: Stan Ward/NA/Sherwin-Williams
Date: 2019/01/27 21:59
Cc: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>, "Mention" <mention@noreply.github.com>
Subject: Re: [EXTERNAL] Re: [F5Networks/f5-ansible] Provide a way to set Admin password via SSL for onboarding a new device (#1165)

Umm, also, the Declarative Onboarding page starts right off (https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/prereqs.html) with

"You must have an existing user account with the Administrator role. If you are using 13.1.x, the BIG-IP contains an admin user by default. If you are using 14.x, you must reset the admin password before installing Declarative Onboarding".  (And even in v13.1.x, the Admin password must be reset if built via the CFT).

As that was the specific issue I wanted addressed with #1165, I'm not sure how this helps.  We can programmatically onboard a BigIP now if it has a functional Admin password. 

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----Stan Ward/NA/Sherwin-Williams wrote: -----
To: "F5Networks/f5-ansible" <reply@reply.github.com>
From: Stan Ward/NA/Sherwin-Williams
Date: 2019/01/27 21:50
Cc: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>, "Mention" <mention@noreply.github.com>
Subject: Re: [EXTERNAL] Re: [F5Networks/f5-ansible] Provide a way to set Admin password via SSL for onboarding a new device (#1165)

That role didn't exist when we wrote all of our onboarding stuff, and it's still not documented on clouddocs.  I'm a little reluctant to do everything over,  especially as I can't really tell how it works.

Besides, I can't get the installation to run:

$ ansible-galaxy install -f f5devcentral.bigip-onboarding,master
- downloading role 'bigip-onboarding', owned by f5devcentral
 [WARNING]: - f5devcentral.bigip-onboarding was NOT installed successfully: - sorry, f5devcentral.bigip-onboarding was not found on https://galaxy.ansible.com.

But the normal role install/update works:

$ ansible-galaxy install -f f5devcentral.f5ansible,master
- downloading role 'f5ansible', owned by f5devcentral
- downloading role from https://github.com/f5devcentral/ansible-role-f5ansible/archive/master.tar.gz
- extracting f5devcentral.f5ansible to /home/sxw455/.ansible/roles/f5devcentral.f5ansible
- f5devcentral.f5ansible (master) was installed successfully

Cheers,

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by wojtek0806** [comment]
I will ask around and see if there are any solutions to this, in regards to the module for ansible that would do this, I would not get my hopes up this will be resolved inside an ansible F5 module for now, once I know more I can tell definitely

**Comment by focrensh** [comment]
Depending on the environment you can use the ssh keys baked into the ecosystem (such as AWS) and the CLI transport within bigip_command module to set the password on the box. Another example in a vmware ecosystem would be to create a "template" with a generic password set which is used for onboarding with another playbook.

**Comment by wojtek0806** [comment]
@C0missar see above

**Comment by C0missar** [comment]
I have not been able to get the cli_transport to work; it's not clear to me exactly what that does or how it works, but when using REST transport, it prefixes everything with tmsh, even though the command description says it supports bash commands.

I have been able to get the ansible generic "command" over ssh to work, and then pushed a tmsh modify auth user admin password xxxx.  But then I had to tackly SSHkeys, known_host key checking, etc.  The entire process is rather involved, and each step had to be researched.

The mechanism isn't important to me, but someone should document a method for this from start to finish, as every single F5 shop using Ansible will have this problem, and they shouldn't have to reinvent the wheel.

**Comment by wojtek0806** [comment]
If the REST transport is selected, the command module will run the commands using util/bash endpoint, this will be the equivalent of running:

tmsh run util bash <your command here>

The documentation explains how to use SSH transport:
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_command.py#L76

If you need examples I think I already stated that in the Slack channel, look at our integration tests they show you how to do most of the things you are trying to do without having to provide a written explanation, here is an example of SSH key usage:

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_command/tasks/provider-cli/ssh-key.yaml

Closing this topic as we will not be providing on-boarding module with Ansible. I will look however of having an example of what @focrensh mentioned with the use of SSH keys in cloud env.

**Comment by C0missar** [comment]
I'm not seeing a message on Slack.  Can you provide a link or a date?  Was it under #ansible or #general?

I think I see why I was having trouble with the CLI transport, and an opening an issue on that - bigip_command does not appear to honor the F5_SERVER environment variable when transport=CLI.

**Comment by wojtek0806** [comment]
this was not directly to you but i mentioned looking at integration tests whenever somebody asked how to do something in a module.
