### ISSUE TITLE
ImportError: No module named network after role f5devcentral.f5ansible update

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1168]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

All

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4
##### SUMMARY

Updated the role f5devcentral.f5ansible with the following command:

#ansible-galaxy install -f f5devcentral.f5ansible,master
- downloading role 'f5ansible', owned by f5devcentral
- downloading role from https://github.com/f5devcentral/ansible-role-f5ansible/archive/master.tar.gz
- extracting f5devcentral.f5ansible to /home/sxw455/.ansible/roles/f5devcentral.f5ansible
- f5devcentral.f5ansible (master) was installed successfully

After that, playbooks all fail, regardless of module, with the following error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named network
fatal: [awsf5devb.sherwin.com]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

 (Tried bigip_hostname, bigip_sys_global, bigip_asm_policy_import)

##### STEPS TO REPRODUCE

```

```

https://gist.github.com/C0missar/d5e0aa8b1410cbcf4212230cbd3075a8
##### EXPECTED RESULTS

See gist Onboard.yaml
This playbook ran successfully 10 minutes before the role update

##### ACTUAL RESULTS

See gist Onboard.log

```

```

**Comment by wojtek0806** [comment]
when have you updated it? delete the role completely and re-download it again.

If the issue persist, go to this folder in the role: action_plugins, and display its contents. Following that, look into bigip.py file located in action_plugins and confirm you have these lines:

```
try:
    from library.plugins.action.network import ActionModule as ActionNetworkModule
except Exception:
    try:
        from action_plugins.network import ActionModule as ActionNetworkModule
    except Exception:
        from ansible.plugins.action.network import ActionModule as ActionNetworkModule
```

This issue has been fixed last week

**Comment by wojtek0806** [comment]
i found another issue, I reverted the change that broke this, i released new version just now should be fixed

**Comment by C0missar** [comment]
That resolved it, thanks!
