### ISSUE TITLE
ansible.module_utils.f5_utils.F5ModuleError: The python f5-sdk module is required

### ISSUE THREAD

**Issue by compyy** [F5Networks/f5-ansible#117]
There is one issue already filed for this but workaround dint fix any thing.
https://github.com/F5Networks/f5-ansible/issues/64
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/beta/Documents/Backbone/ansible.cfg
  configured module search path = [u'/home/beta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### PYTHON VERSION

```
Python 2.7.13

```

##### BIGIP VERSION

```
11.6.1 HF2
```

##### CONFIGURATION

[defaults]
inventory=./hosts
gathering=explicit
transport=local
host_key_checking = false

[paramiko_connection]
host_key_auto_add = True
##### OS / ENVIRONMENT

Ubuntu 17.04 Beta
Linux beta 4.10.0-14-generic #16-Ubuntu SMP Fri Mar 17 15:19:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Its simple can't run playbook based on bigip_command
##### STEPS TO REPRODUCE

Install ansible 2.3 or 2.4
Install F5-sdk
git clone f5-ansible, and copy library modules to ansible modules folder
/usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5
/usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5

```
---
# Show version for F5 Hosts
- 
  hosts: F5
  tasks: 
    - 
      bigip_command:
        commands: show sys version
        provider: "{{ cli }}"
      register: out
    
    - debug: msg="{{ out.stdout_lines }}"

  vars: 
    cli:
      host: "{{ ansible_host }}"
      username: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      transport: cli
```

##### EXPECTED RESULTS

playbook should run
##### ACTUAL RESULTS

TASK [bigip_command] ****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.f5_utils.F5ModuleError: The python f5-sdk module is required
fatal: [bru-11-H500]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lNHPBp/ansible_module_bigip_command.py\", line 382, in <module>\n    main()\n  File \"/tmp/ansible_lNHPBp/ansible_module_bigip_command.py\", line 364, in main\n    raise F5ModuleError(\"The python f5-sdk module is required\")\nansible.module_utils.f5_utils.F5ModuleError: The python f5-sdk module is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

```

```

**Comment by caphrim007** [comment]
@compyy this module should be used like so

```
- name: perform some task
   bigip_command:
       commands: show sys version
       server: "lb.mydomain.com"
       password: "secret"
       user: "admin"
       validate_certs: "no"
```

The format that you mention in this issue is from an older version of the module.

**Comment by compyy** [comment]
Hi,

Thanks for responding, I tried it, had same error, will do again tomorrow and share update.

**Comment by compyy** [comment]
Not sure why but it gives me syntax error.

- name: perform some task
   bigip_command:
       commands: show sys version
       server: "lb.mydomain.com"
       password: "secret"
       user: "admin"
       validate_certs: "no"
   delegate_to: localhost

ansible-playbook F5Version.yaml --syntax-check
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/home/beta/Documents/Backbone/F5Version.yaml': line 2, column 17, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: perform some task
   bigip_command:
                ^ here

**Comment by compyy** [comment]
Tried this Playbook, same error.

```
# Show version for F5 Hosts
- 
  hosts: F5
  tasks: 
    - name: Check F5 Server Version
      bigip_command:
         commands: show sys version
         server: "F5host"
         password: "admin"
         user: "admin"
         validate_certs: "no"
      delegate_to: localhost
```
```
beta@beta:~/Documents/Backbone$ ansible-playbook F5Version.yaml 

PLAY [F5] ***************************************************************************************************************************************************************

TASK [perform some task] ************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.f5_utils.F5ModuleError: The python f5-sdk module is required
fatal: [bru-11-H500 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_elqR43/ansible_module_bigip_command.py\", line 382, in <module>\n    main()\n  File \"/tmp/ansible_elqR43/ansible_module_bigip_command.py\", line 364, in main\n    raise F5ModuleError(\"The python f5-sdk module is required\")\nansible.module_utils.f5_utils.F5ModuleError: The python f5-sdk module is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/beta/Documents/Backbone/F5Version.retry

PLAY RECAP **************************************************************************************************************************************************************
bru-11-H500                : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by caphrim007** [comment]
@compyy there's one of several things happening

1. You're ansible version isnt 2/3 or greater. To remedy that, you must install from their devel branch until 2.3 final is released.

`pip install --upgrade git+https://github.com/ansible/ansible.git`

2. You have upgraded, but trace files from the older installation still exist. In particular, the old module_utils file. You can find that with this command

`locate f5.py | grep module_utils`

or by using the similar `find` command.

If that file exists, delete it. It's not used anymore and will only causing namespace conflicts when ansible creates the tarball that it sends to the remote device.

3. You've done all the above, and it's still not working.

At this point the best guess that I can offer without debugging it with you in depth is that I've seen folks run into this problem when they run ansible in a virtualenv.

When you do that, you need to ensure that the `localhost` in your host_vars has the `ansible_python_interpreter` set. For example, in our functional tests we do this and you can view our inventory host var for localhost here

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/inventory/hosts.example

4. If you are *still* receiving errors, then file a separate issue to have access to our Slack channel and I will assist you in debugging it live.

**Comment by caphrim007** [comment]
Additionally, if you installed Ansible from a package manager like apt or yum, remove it first and (if using apt) purge it. Package managers screw with your ability to install updates from pip because they put files in locations that pip does not know and those locations take priority over the pip locations.

**Comment by compyy** [comment]
Thanks for your great help.

One more question, i have specified connection: ssh, but even then it uses https.

Can we run these modules with ssh ? i dont have https opened for my dev machine towards F5.

**Comment by caphrim007** [comment]
at this time, no. this may be pursued in the future, but at this time it is not a priority and the cli makes it especially difficult as there is not a well-defined format for the output across the different modules

If you're all set with this current issue, feel free to close it.

**Comment by compyy** [comment]
Thanks, i can run the playbooks now.
