### ISSUE TITLE
Improve bigip_user.py unit tests

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#118]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_user.py module

##### ANSIBLE VERSION
```

```

##### PYTHON VERSION
```

```

##### BIGIP VERSION
```

```

##### SUMMARY
Unit tests for bigip_user.py are lacking proper update checking with example json. Also Partitioned manager class is not tested.

##### STEPS TO REPRODUCE
```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
i've covered this. closing
