### ISSUE TITLE
Need way to enable AS3 framework programatically

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1183]
##### ISSUE TYPE

 
- Feature request

##### COMPONENT NAME

N/A

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4

##### SUMMARY

There is no way to enable iApps programatically as part of an automated device onboarding.  For instance, it is possible to download and install the AS3 rpm using the Ansible 'uri' module, but without an SSH to the device to do the "touch /var/config/rest/iapps/enable", the framework is not enabled.

##### STEPS TO REPRODUCE

```
(This shows the AS3 module installation and stub for the 'touch' command)

https://gist.github.com/C0missar/598ff2ffaf94d577c3a7324942bd2d60
```

https://gist.github.com/C0missar/d5e0aa8b1410cbcf4212230cbd3075a8
##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
@C0missar 
Please use bigip_iapplx_package module it does exactly what you are asking :)

Also I noticed your role has an old error, I would suggest removal and reinstallation of it as I have fixed this issue. Closing for now.
