### ISSUE TITLE
bigip_virtual_server issue

### ISSUE THREAD

**Issue by jcshelby** [F5Networks/f5-ansible#12]
Hi - I have a quick question. I'm working with this module and am attempting to create a VS according to the documentation provided on Ansible's website. Currently the module is failing to build the VS as specified on my F5 in the lab. The message I am receiving is msg: received exception urlopen error [Errno -5] No address associated with hostname. I'm using Ansible v2.2.0 last updated this morning at 09:28 which is running on Fedora 23. I'm using an IP address to access my device so there should be no issue with DNS resolution. My F5 in the lab is running v11.5.4. Please let me know if I can provide any other information to assist with this. Thanks!

**Comment by caphrim007** [comment]
can you post the playbook you're using so I can look?

**Comment by jcshelby** [comment]
Thanks for taking a look at this. I've attached the playbook as requested.` - name: Create a VIP in my BIG-IP
 78          bigip_virtual_server:
 79                    server: '10.0.32.l50'
 80                    user: 'admin'
 81                    password:
 82                    state: 'present'
 83                    partition: 'Common'
 84                    destination: '3.3.3.4:80'
 85                    name: 'ansible-vip_v1.1'
 86                    port: '80'
 87                    pool: 'ansible-pool_v1.1'
 88                    snat: 'Automap'
 89                    description: 'ansible_test_vip'
 90                    all_profiles:
 91                         - http
 92                         - clientssl
 93                    validate_certs: 'no'`

**Comment by caphrim007** [comment]
what does your "hosts:" and "connection:" lines say in the playbook?

**Comment by jcshelby** [comment]
Hosts is the IP address of the F5 (10.0.32.150) and the connection is local

**Comment by caphrim007** [comment]
Ok, what is the ansible-playbook command being run and the contents of your inventory file? Can you try setting the hosts: line to "localhost" and see if it has any effect?

**Comment by jcshelby** [comment]
I'm running ansible-playbook <name_of_playbook> -vvvvv. The inventory file is the stock inventory file with a single host which is the IP address of the same F5 I'm testing against

**Comment by jcshelby** [comment]
I just changed both the playbook and the inventory file to localhost and it had no effect on the behavior that I'm seeing

**Comment by caphrim007** [comment]
are you using ipv6 on any interface? ipv6 in your hosts file? I suspect this is a linux issue and not an issue with the library.

**Comment by jcshelby** [comment]
IPv6 isn't configured but there are entries for IPv6 addresses in /etc/hosts/ and on my interface. This would be the out of the box configuration native to Fedora

**Comment by buzzsurfr** [comment]
@jcshelby: I just noticed that the linked file has the IP as 10.0.32.l50 instead of 10.0.32.150 (lowercase L instead of 1).  Can you confirm it's correct on your instance?

I was able to take your file and run a playbook against my lab in Ansible 2.2.0 (virtualenv)

**Comment by jcshelby** [comment]
Thanks for noticing that - not sure how I missed it originally since I usually cut/paste those lines. Always helps to have a second pair of eyes on something. It works now - much appreciate the attention to this. I'll try to make any questions I have in the future a little more interesting

**Comment by caphrim007** [comment]
@buzzsurfr you have eyes like a hawk! Well done sir!
