### ISSUE TITLE
notify handler broken / KeyError: None

### ISSUE THREAD

**Issue by dano0b** [F5Networks/f5-ansible#120]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_pool
bigip_virtual_server

maybe more

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.93.249
  Edition     Engineering Hotfix
  Date        Fri Jan 20 15:48:38 PST 2017

Hotfix List
ID624457-5    ID624023-3  ID623119  ID639492-1
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.3 (Maipo)
##### SUMMARY

As soon as I use `notify: "sync device-group"` with the virtualserver or pool module I get an exception:

I wanted to try the actual https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_virtual_server.py but trying I get the exception
```
    "failed": true,
    "msg": "Could not find imported module support code for bigip_virtual_server.  Looked for either * or f5_utils"
```
I could not find the f5_utils anywhere.

##### STEPS TO REPRODUCE

task:
```
- name: "create virtualserver {{ playF5serviceVirtualserverName }}"
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "cfgmanlb"
    password: "{{ groupLoadbalancerLdapSecret }}"
    state: "enabled"
    name: "{{ playF5serviceVirtualserverName }}"
    partition: "Common"
    destination: "{{ playF5serviceVirtualServerIP }}"
    port: "{{ playF5serviceVirtualServerPort }}"
    pool: "{{ playF5servicePoolName }}"
    enabled_vlans: "ALL"
    all_profiles: "{{ playF5serviceVirtualServerProfileList |default('http')}}"
    snat: "Automap"
  delegate_to: localhost
  notify: "sync device-group"
```
handler:
```
- name: "sync device-group {{ groupf5serviceDeviceGroup }}"
  command: "tmsh run /cm config-sync to-group {{ groupf5serviceDeviceGroup }}"
  listen: "sync device-group"
```

##### EXPECTED RESULTS

Handler will be notified correctly

##### ACTUAL RESULTS

change will be done but the handler don't run and the play is aborted
```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/network/f5/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ERROR! Unexpected Exception: None
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 282, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 278, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 534, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 417, in _process_pending_results
    if original_host not in self._notified_handlers[listening_handler]:
KeyError: None
```

**Comment by caphrim007** [comment]
@dano0b that's happening because your Notify is not matching your handler.

Your handler is defined as this

`name: "sync device-group {{ groupf5serviceDeviceGroup }}"`

but you're notifying this

`notify: "sync device-group"`

So this doesnt seem related to the F5 modules

The f5_utils error is being caused by not having Ansible 2.3, or later, installed. You can do so with this command

`pip install --upgrade git+https://github.com/ansible/ansible.git`

Additionally, if you installed Ansible from a package manager like apt or yum, remove it first and (if using apt) purge it. Package managers screw with your ability to install updates from pip because they put files in locations that pip does not know and those locations take priority over the pip locations.

**Comment by dano0b** [comment]
@caphrim007 I use the `listen:` (available since 2.2) to make it react to `sync device-group`

we are always using the stable release of ansible, my lab has no access to a f5 loadbalancer

**Comment by caphrim007** [comment]
@dano0b using the modules in this repo requires 2.3 or later. So I would recommend for now that you stick with the modules that come with Ansible until such time as 2.3 is released.

In the meantime, I dont have tests for using listen or notifications in my functional tests, so I will need to add some.

**Comment by dano0b** [comment]
I believe 2.3 will be released soon, rc4 is really close. I will update this issue as soon I've tested it with 2.3.

**Comment by dano0b** [comment]
Using Ansible 2.3 we can use `listen:` normally, closing.
