### ISSUE TITLE
Request Ansible module for message-routing framework (MRF)

### ISSUE THREAD

**Issue by torzillo** [F5Networks/f5-ansible#1205]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

message-routing

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```
14.1.0
```

##### SUMMARY

A module is needed for the message-routing profiles, including creating the transport-config, profiles, protocols, routes, routers, peers, and tying them to a virtual server.

Here is an example configuration:

ltm message-routing generic transport-config /Common/TPKT {
    ip-protocol tcp
    profiles {
        /Common/TPKT-protocol_profile { }
        /Common/f5-tcp-lan { }
    }
    rules {
        /Common/tpkt-message-processor
    }
    source-address-translation {
        type automap
    }
}
ltm message-routing generic transport-config /Common/BER {
    ip-protocol tcp
    profiles {
        /Common/BER-protocol_profile { }
        /Common/f5-tcp-lan { }
    }
    rules {
        /Common/ber-message-processor
    }
}
ltm profile tcp /Common/GDF_profile {
    app-service none
    defaults-from /Common/tcp-lan-optimized
}
ltm message-routing generic protocol /Common/TPKT-protocol_profile {
    app-service none
    description "RFC2126 TPKT"
    disable-parser yes
    no-response yes
}
ltm message-routing generic protocol /Common/BER-protocol_profile {
    app-service none
    description "BER Encoding"
    disable-parser yes
    no-response yes
}
ltm message-routing generic peer /Common/TPK_55000_pool_peer {
    pool /Common/CALEA-HSS-POOL
    transport-config /Common/TPKT
}
ltm message-routing generic peer /Common/BER_10000_pool_peer {
    pool /Common/CALEA-HLR-POOL
    transport-config /Common/BER
}
ltm message-routing generic route /Common/route-to-BER_10000_pool {
    peers {
        /Common/BER_10000_pool_peer
    }
}
ltm message-routing generic route /Common/route-to-TPK_55000_pool {
    peers {
        /Common/TPK_55000_pool_peer
    }
}
ltm message-routing generic router /Common/router-BER_10000 {
    app-service none
    routes {
        /Common/route-to-BER_10000_pool
    }
}
ltm message-routing generic router /Common/router-TPK_55000 {
    app-service none
    routes {
        /Common/route-to-TPK_55000_pool
    }
}
ltm virtual /Common/CALEA-HSS-1{
    destination /Common/172.26.24.12:55000
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/CALEA-HSS-POOL
    profiles {
        /Common/TPKT-protocol_profile { }
        /Common/f5-tcp-lan { }
        /Common/router-TPK_55000 { }
    }
    rules {
        /Common/tpkt-message-processor
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
}
ltm virtual /Common/GN_vip_10000 {
    destination /Common/172.26.24.12:10000
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/CALEA-HLR-POOL
    profiles {
        /Common/BER-protocol_profile { }
        /Common/f5-tcp-lan { }
        /Common/router-BER_10000 { }
    }
    rules {
        /Common/ber-message-processor
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
    vlans {
        /Common/CALEA
    }
    vlans-enabled
}

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Being reviewed under FMFA-191
