### ISSUE TITLE
bigip_command fails on 2nd attempt when transport=CLI

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1206]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

Win10/WSL/Ubuntu 18.0.4

##### SUMMARY

When using transport = CLI, the first call succeeds, but subsequent calls fail with 
```
fatal: [awsf5qaa.sherwin.com]: FAILED! => 
  msg: '''Connection'' object has no attribute ''reset_history'''
```
##### STEPS TO REPRODUCE

```
See Test.yaml in gist https://gist.github.com/C0missar/28d78cee4c7838f0d5afd4080bd8924b
```

##### EXPECTED RESULTS

I expected every task to provide the same results, i.e. the output of "list auth user admin", regardless of whether the call was made with rest or cli transport.

##### ACTUAL RESULTS

Calls with rest transport always worked; with cli transport, only the first one worked, and all subsequent calls returned the error message noted above.

It looks like the module is re-using a socket, but some information was lost.

```
See Test.log in gist https://gist.github.com/C0missar/28d78cee4c7838f0d5afd4080bd8924b
```

**Comment by C0missar** [comment]
Thanks for researching this.

I'm not terribly familiar with Ansible dev code, and not at all with Python, etc.  Could you provide the specific commands I would need to install the necessary components, or upgrade to a development branch that addresses the issue?

Also, it seems like a lot of people could be encountering this issue.  Would it make sense to add a note on the bigip_command documentation referencing a known bug, and the Ansible code version that addresses it?  One could waste a LOT of time on this (ask me how I know...<grin>)

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by wojtek0806** [comment]
this command should do it:

pip install git+https://github.com/ansible/ansible.git@devel

**Comment by C0missar** [comment]
That seems to have resolved the problem - thank you!

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>
