### ISSUE TITLE
bigip_monitor_http does not use default value for ip var

### ISSUE THREAD

**Issue by OncleDave** [F5Networks/f5-ansible#1208]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_monitor_http
bigip_monitor_https
bigip_monitor_tcp

##### ANSIBLE VERSION
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]

##### PYTHON VERSION
Python 2.7.9

##### BIGIP VERSION
12.3.1.7

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
bigip_monitor_http should use * as default when "ip" parameter is not explicitely set.
It currently returns an error message : msg: invalid monitor destination "None:81"
We can see here that the ip is not set to * as default.

##### STEPS TO REPRODUCE
Create a monitor without specifying the ip parameter.
The parameters I used in my test are 
(item={'name': u'MONITOR1Name', 'timeout': 19, 'serv_port': 81, 'receive': u'HTTP/1.[01] [23]0[0-6]', 'interval': 6, 'type': u'HTTP', 'send': u'HEAD HTTP/1.1\\r\\nConnection : Close\\r\\n\\r\\n'})

Extract of the yml : 

 - name: "HTTP Monitor"
   bigip_monitor_http:
     provider: "{{ credentials }}"
     state: "{{ act | default ('present')}}"
     name: "{{ item1.name }}"
     partition: "{{ params.general.partition }}"
     interval: "{{ item1.interval }}"
     timeout: "{{ item1.timeout }}"
     receive: "{{ item1.receive }}"
     send: "{{ item1.send }}"
     port: "{{ item1.serv_port | default(omit) }}"
     ip: "*"         <- This line was added as workaround to solve the issue, but should not be required.
   when: item1.type == "HTTP"
   tags: [print_action]
   with_items: "{{ params.pool.monitors }}"
   loop_control:
     loop_var: item1
   delegate_to: localhost

##### EXPECTED RESULTS
The monitor should be created with * as destination ip.

##### ACTUAL RESULTS
failed: [localhost -> localhost] (item={'name': u'MONITOR1Name', 'timeout': 19, 'serv_port': 81, 'receive': u'HTTP/1.[01] [23]0[0-6]', 'interval': 6, 'type': u'HTTP', 'send': u'HEAD HTTP/1.1\\r\\nConnection : Close\\r\\n\\r\\n'}) => changed=false
  item1:
    interval: 6
    name: MONITOR1Name
    receive: HTTP/1.[01] [23]0[0-6]
    send: 'HEAD  HTTP/1.1\r\nConnection : Close\r\n\r\n'
    serv_port: 81
    timeout: 19
    type: HTTP
  msg: invalid monitor destination "None:81"

**Comment by wojtek0806** [comment]
This has been already implemented, please read the updated on requirements before filing an issue:

https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/filing-issues.html

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_http.py#L313
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_tcp.py#L263
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_https.py#L318

We will not be setting a default when a parameter is not specified, if you require * then you need to set it in the playbook explicitly, with either * or 0.0.0.0

**Comment by OncleDave** [comment]
@wojtek0806 
Hi Wojtek,

I have no problem setting it explicitly in the playbook but then you should update the documentation.

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_http.py#L49
and
https://docs.ansible.com/ansible/latest/modules/bigip_monitor_http_module.html

Meanwhile, I don't understand why you would set this parameter to None by default as this generates an error and is not even possible on a bigip.  Or am I missing something ?

**Comment by wojtek0806** [comment]
The parameter is added during creation, but not during update, so you do not need to specify it when you create a monitor, but only when you update it, the documentation is correct in this aspect, the defaults are set by this function during create event:

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_monitor_http.py#L609
