### ISSUE TITLE
bigip_iapplx_package: No such file or directory

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1214]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_iapplx_package
##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

```

##### CONFIGURATION

```
How does one determine the version of the f5ansible galaxy role?
```

##### OS / ENVIRONMENT

```
Win10/WSL/Ubuntu 18.0.4
```
##### SUMMARY

The module is ignoring the file path provided in the package parameter, and generates an error message that the package was not found in the current directory (where the playbook was run).  Placing the package in that directory does not resolve the problem.
```
$ pwd
/home/sxw455/Ansible-F5/Playbooks
```
package: "~/Ansible-F5/Objects/Packages/f5-appsvcs-3.8.0-3.noarch.rpm"
```
fatal: [awsf5qab.sherwin.com]: FAILED! => changed=false
  msg: The specified iAppLX package was not found in /home/sxw455/Ansible-F5/Playbooks.
...ignoring
$ ll ~/Ansible-F5/Objects/Packages/f5-appsvcs-3.8.0-3.noarch.rpm
-rwxrwxrwx 1 sxw455 sxw455 16220835 Jan 23 17:09 /home/sxw455/Ansible-F5/Objects/Packages/f5-appsvcs-3.8.0-3.noarch.rpm*
```
Changing the package path from ~ relative to absolute generates a different error:
```
fatal: [awsf5qab.sherwin.com]: FAILED! => changed=false
  cmd: rpm -qp --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}' /home/sxw455/Ansible-F5/Objects/Packages/f5-appsvcs-3.8.0-3.noarch.rpm
  msg: '[Errno 2] No such file or directory'
  rc: 2
...ignoring
$ ll /home/sxw455/Ansible-F5/Objects/Packages/f5-appsvcs-3.8.0-3.noarch.rpm
-rwxrwxrwx 1 sxw455 sxw455 16220835 Jan 23 17:09 /home/sxw455/Ansible-F5/Objects/Packages/f5-appsvcs-3.8.0-3.noarch.rpm*
```
##### STEPS TO REPRODUCE

```
See Gist: https://gist.github.com/C0missar/c9237e9e61b0f718354ff06a6b130e88
```

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
the change i made is not in the role yet, the role is built every day at 1am PST. You need to wait and download it then and retest. Like I said the issue is not reproducible so posting GISTS will not help here, unless I can reproduce this behaviour, ergo if we cannot reproduce this then we cannot fix it.

This type of error is strictly related to your environment, I have noticed you have put Win10 in the OS, so what is the exact environment you are running this in? we only support either Virtual Machine running Linux, or native linux, or mac OS. 

With that said, one thing you could try is  running this in python 3.6 virtual env, i would like to see if that will also fail.

**Comment by wojtek0806** [comment]
I think I found your problem, i got a docker container with py3.6:

`fatal: [bigip_v12_docker -> localhost]: FAILED! => {"changed": false, "cmd": "rpm -qp --queryformat '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}' /settings/f5-appsvcs-3.8.1-1.noarch.rpm", "msg": "[Errno 2] No such file or directory: 'rpm': 'rpm'", "rc": 2}
`
Then I checked if the rpm command was running on its own:

```root@2134420ee9a2:/settings/repros# rpm
bash: rpm: command not found
```

So here is a change of plans, try to see if you can actually execute RPM command, in the documentation it clearly states that you need to have it installed on your controller:

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_iapplx_package.py#L48

verify this and let me know please

**Comment by C0missar** [comment]
It's Ubuntu 18.0.4 under WSL.

Where do you list the "supported" environments?

I don't know how to set up a virtual environment or force alternate versions of Python. I don't know python, and never expected to need to.  It seems like if one module can read my files, they all should be able to.

BTW, the description text recommends using the "{{ role_path }}" for locating the files (although it's spelled "{{ roles_path }}" in the examples).  I set roles_path in .ansible.cfg, but it always tells me the variable is undefined, so I'm not sure how to use that.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by C0missar** [comment]
By controller, you mean the machine that Ansible is running on (my Windows 10 machine)?  Why would that be needed?  It isn't installing anything.

How do I go about determining whether it is installed?  I would bet not; Ubuntu doesn't use RPM.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by C0missar** [comment]
Yay, that did it.  I installed rpm, and now I can add and delete packages.

What is RPM being used for, and why the bad error message?  I clearly don't understand what the module is doing.

It's been a very frustrating process for me.  Thank you for your patience.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----Stan Ward/NA/Sherwin-Williams wrote: -----
To: "F5Networks/f5-ansible" <reply@reply.github.com>
From: Stan Ward/NA/Sherwin-Williams
Date: 2019/02/07 21:35
Cc: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>, "Author" <author@noreply.github.com>
Subject: Re: [EXTERNAL] Re: [F5Networks/f5-ansible] bigip_iapplx_package: No such file or directory (#1214)

By controller, you mean the machine that Ansible is running on (my Windows 10 machine)?  Why would that be needed?  It isn't installing anything.

How do I go about determining whether it is installed?  I would bet not; Ubuntu doesn't use RPM.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Wojciech Wypior" <notifications@github.com> wrote: -----
To: "F5Networks/f5-ansible" <f5-ansible@noreply.github.com>

**Comment by wojtek0806** [comment]
The answers are found in the official Ansible documentation:

https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html

While you can run Ansible on WSL this does not mean it is supported, by being a part of Ansible core modules we follow the same suit.

This is why you have had problems with parameters that were using 'path'  in the past, simply because you are running on an unsupported system, the fact that we managed to address this, does not mean we will continue to do so.

To your issue, not only you run this on an unsupported controller, you also missing component to be installed as required by documentation, if you wish to know the reasons for installing RPM, look in the code for the module, doc strings explain the reason behind it in detail.
