### ISSUE TITLE
consider adding diff'ing ability to modules

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#122]
http://docs.ansible.com/ansible/playbooks_checkmode.html

an ask to provide diff ability was made. we already collect the changes made, so what would be required to show diffs of the have and the want instead of just saying that "something changed"

**Comment by delgadillo22** [comment]
Nice to have

**Comment by wojtek0806** [comment]
FMFA-246

**Comment by wojtek0806** [comment]
first iteration of diff utility pattern added to bigip_device_ntp module, we will work on refining it on more complex modules in time, we can consider this a resolved issue.
