### ISSUE TITLE
Request ansible module for "SNAT Translation List"

### ISSUE THREAD

**Issue by OncleDave** [F5Networks/f5-ansible#1227]
##### ISSUE TYPE

 - Feature Idea

##### CONFIGURATION
xxxxxx@(xxxxxxx)(cfg-sync In Sync)(/S1-green-P:Active)(/Common)(tmos)#  list ltm snat-translation
**ltm snat-translation 10.0.3.1** {
    address 10.0.3.1
    inherited-traffic-group true
    **tcp-idle-timeout 300**
    traffic-group traffic-group-1
    **udp-idle-timeout 300**
}

##### SUMMARY
Best practices for SNAT pools are to set a defined tcp-idle-timeout and udp-idle-timeout in the snat-translation list, depending on the tcp profile timeout.  There is currently no module to configure the snat-translation.

**Comment by wojtek0806** [comment]
merged into devel
