### ISSUE TITLE
GTM wideip creation failed

### ISSUE THREAD

**Issue by insidepacket** [F5Networks/f5-ansible#123]
ISSUE TYPE

Bug Report

COMPONENT NAME

network/f5/bigip_gtm_wide_ip

ANSIBLE VERSION

Ansible version 2.2.1.0
[root@localhost f5]# ansible --version
ansible 2.2.1.0
config file = /home/dzhang/f5/ansible.cfg
configured module search path = Default w/o overrides

PYTHON VERSION
Python 2.7.5
[root@localhost f5]# python --version
Python 2.7.5

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Centos 7.2

##### SUMMARY
Error

##### STEPS TO REPRODUCE
Run the playbook below:

[root@localhost f5]# vi gtm-v0.2a.yml

---
- name: f5 config
  hosts:  lb.davidwzhang.com
  connection: local
  tasks:
    - name: create a GTM DC
      bigip_gtm_datacenter:
        password: "password"
        server: "10.1.1.122"
        user: "admin"
        name: "SL-SYD-Site1"
        validate_certs: "no"
      delegate_to:  localhost
    - name: create a wideip
      local_action:  >
        bigip_gtm_wide_ip
        server=10.1.1.122
        user=admin
        password=password
        lb_method=round_robin
        wide_ip=mywideip.example.com

##### EXPECTED RESULTS
wide ip (mywideip.example.com) will be created.

##### ACTUAL RESULTS
[root@localhost f5]# ansible-playbook  gtm-v0.2a.yml

PLAY [f5 config] ***************************************************************

TASK [setup] *******************************************************************
ok: [lb.davidwzhang.com]

TASK [create a GTM DC] *********************************************************
ok: [lb.davidwzhang.com -> localhost]

**TASK [create a wideip] *********************************************************
fatal: [lb.davidwzhang.com -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "wide ip mywideip.example.com does not exist"}**
        to retry, use: --limit @/home/dzhang/f5/gtm-v0.2a.retry

PLAY RECAP *********************************************************************
lb.davidwzhang.com         : ok=2    changed=0    unreachable=0    failed=1   

[root@localhost f5]# ansible-playbook  -vvv gtm-v0.2a.yml
Using /home/dzhang/f5/ansible.cfg as config file

PLAYBOOK: gtm-v0.2a.yml ********************************************************
1 plays in gtm-v0.2a.yml

PLAY [f5 config] ***************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<lb.davidwzhang.com> ESTABLISH LOCAL CONNECTION FOR USER: dzhang
<lb.davidwzhang.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763 `" && echo ansible-tmp-1491714108.01-232946137811763="` echo ~/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763 `" ) && sleep 0'
<lb.davidwzhang.com> PUT /tmp/tmpOcLkbS TO /root/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763/setup.py
<lb.davidwzhang.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763/ /root/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763/setup.py && sleep 0'
<lb.davidwzhang.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1491714108.01-232946137811763/" > /dev/null 2>&1 && sleep 0'
ok: [lb.davidwzhang.com]

TASK [create a GTM DC] *********************************************************
task path: /home/dzhang/f5/gtm-v0.2a.yml:7
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/network/f5/bigip_gtm_datacenter.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dzhang
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301 `" && echo ansible-tmp-1491714108.39-194795154324301="` echo ~/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301 `" ) && sleep 0'
<localhost> PUT /tmp/tmpTNcQAU TO /root/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301/bigip_gtm_datacenter.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301/ /root/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301/bigip_gtm_datacenter.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301/bigip_gtm_datacenter.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1491714108.39-194795154324301/" > /dev/null 2>&1 && sleep 0'
ok: [lb.davidwzhang.com -> localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "contact": null, 
            "description": null, 
            "enabled": null, 
            "location": null, 
            "name": "SL-SYD-Site1", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server": "10.1.1.122", 
            "server_port": 443, 
            "state": "present", 
            "user": "admin", 
            "validate_certs": false
        }, 
        "module_name": "bigip_gtm_datacenter"
    }
}

TASK [create a wideip] *********************************************************
task path: /home/dzhang/f5/gtm-v0.2a.yml:15
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/network/f5/bigip_gtm_wide_ip.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dzhang
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146 `" && echo ansible-tmp-1491714108.88-276658829668146="` echo ~/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146 `" ) && sleep 0'
<localhost> PUT /tmp/tmp6LZ_Qv TO /root/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146/bigip_gtm_wide_ip.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146/ /root/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146/bigip_gtm_wide_ip.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146/bigip_gtm_wide_ip.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1491714108.88-276658829668146/" > /dev/null 2>&1 && sleep 0'
fatal: [lb.davidwzhang.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "lb_method": "round_robin", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server": "10.1.1.122", 
            "server_port": 443, 
            "state": "present", 
            "user": "admin", 
            "validate_certs": true, 
            "wide_ip": "mywideip.example.com"
        }, 
        "module_name": "bigip_gtm_wide_ip"
    }, 
    **"msg": "wide ip mywideip.example.com does not exist"**
}
        to retry, use: --limit @/home/dzhang/f5/gtm-v0.2a.retry

PLAY RECAP *********************************************************************
lb.davidwzhang.com         : ok=2    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment]
@insidepacket does this happen with the module in this repository? the module upstream is incomplete and I was going to push the module in this repository to Ansible upstream. I saw you opened this

https://github.com/ansible/ansible/issues/23437#issuecomment-292764743

**Comment by insidepacket** [comment]
@caphrim007 , I updated ansible/ansible#23437 (comment). Please check. In short, still doesn't work but different error

**Comment by caphrim007** [comment]
@insidepacket I've pushed a change that i believe fixes this issue. if you have a moment to test the module in this repository, lemme know here

**Comment by insidepacket** [comment]
@caphrim007 , re-tested and still no lucky, See the below:

[dzhang@localhost f5]$ ansible-playbook -vvv gtm-v0.2a.yml
/usr/lib/python2.7/site-packages/pkg_resources.py:1054: UserWarning: /home/dzhang/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Using /home/dzhang/f5/ansible.cfg as config file

PLAYBOOK: gtm-v0.2a.yml ********************************************************************************************************************************************************************************************************************
1 plays in gtm-v0.2a.yml

PLAY [f5 config] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible-2.3.0.0-py2.7.egg/ansible/modules/system/setup.py
<lb.davidwzhang.com> ESTABLISH LOCAL CONNECTION FOR USER: dzhang
<lb.davidwzhang.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<lb.davidwzhang.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169 `" && echo ansible-tmp-1491863315.54-186134071036169="` echo /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169 `" ) && sleep 0'
<lb.davidwzhang.com> PUT /tmp/tmp_qx8MB TO /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169/setup.py
<lb.davidwzhang.com> EXEC /bin/sh -c 'chmod u+x /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169/ /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169/setup.py && sleep 0'
<lb.davidwzhang.com> EXEC /bin/sh -c '/usr/bin/python /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169/setup.py; rm -rf "/home/dzhang/.ansible/tmp/ansible-tmp-1491863315.54-186134071036169/" > /dev/null 2>&1 && sleep 0'
ok: [lb.davidwzhang.com]
META: ran handlers

TASK [create a GTM DC] *********************************************************************************************************************************************************************************************************************
task path: /home/dzhang/f5/gtm-v0.2a.yml:7
Using module file /home/dzhang/f5-ansible-devel/library/bigip_gtm_datacenter.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dzhang
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467 `" && echo ansible-tmp-1491863315.97-141431809536467="` echo /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467 `" ) && sleep 0'
<localhost> PUT /tmp/tmpEuMGky TO /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467/bigip_gtm_datacenter.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467/ /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467/bigip_gtm_datacenter.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467/bigip_gtm_datacenter.py; rm -rf "/home/dzhang/.ansible/tmp/ansible-tmp-1491863315.97-141431809536467/" > /dev/null 2>&1 && sleep 0'
ok: [lb.davidwzhang.com -> localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "contact": null, 
            "description": null, 
            "enabled": null, 
            "location": null, 
            "name": "SL-SYD-Site1", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server": "10.1.1.122", 
            "server_port": 443, 
            "state": "present", 
            "user": "admin", 
            "validate_certs": false
        }
    }
}

TASK [create a wideip] *********************************************************************************************************************************************************************************************************************
task path: /home/dzhang/f5/gtm-v0.2a.yml:15
Using module file /home/dzhang/f5-ansible-devel/library/bigip_gtm_wide_ip.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dzhang
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216 `" && echo ansible-tmp-1491863316.66-144184668715216="` echo /home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216 `" ) && sleep 0'
<localhost> PUT /tmp/tmpM4Mqbv TO /home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216/bigip_gtm_wide_ip.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216/ /home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216/bigip_gtm_wide_ip.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216/bigip_gtm_wide_ip.py; rm -rf "/home/dzhang/.ansible/tmp/ansible-tmp-1491863316.66-144184668715216/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_J5zu3N/ansible_module_bigip_gtm_wide_ip.py", line 109, in <module>
    import q
ImportError: No module named q
fatal: [lb.davidwzhang.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_J5zu3N/ansible_module_bigip_gtm_wide_ip.py\", line 109, in <module>\n    import q\nImportError: No module named q\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
        to retry, use: --limit @/home/dzhang/f5/gtm-v0.2a.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
lb.davidwzhang.com         : ok=2    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment]
@insidepacket i'm sorry about that. that was debug information that I left in there. try again, I've since removed it.

**Comment by insidepacket** [comment]
@caphrim007 , restested and all good now. Thanks
