### ISSUE TITLE
Bigip_GTM_wide-ip "pool" option

### ISSUE THREAD

**Issue by insidepacket** [F5Networks/f5-ansible#124]
##### ISSUE TYPE
 - Feature Idea
Could we add "pool" option to wide-ip?
##### COMPONENT NAME
bigip_gtm_wide_ip.py
##### ANSIBLE VERSION
Version 2.3
##### PYTHON VERSION
Version 2.7.5

##### BIGIP VERSION
BIG-IP 12.1.2 Build 0.0.249 Final

**Comment by insidepacket** [comment]
@caphrim007 , any update?

**Comment by caphrim007** [comment]
@insidepacket this should now be fixed. please test

**Comment by caphrim007** [comment]
this is now merged upstream
