### ISSUE TITLE
bigip_gtm_server unable to add peer address

### ISSUE THREAD

**Issue by gullanetworkcode** [F5Networks/f5-ansible#1264]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_gtm_server

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION
```
Python 2.7.15rc1
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018
```

##### OS / ENVIRONMENT
XUBUNTU

##### SUMMARY
Unable to add Peer Addresses to server configuration in DNS\GSLB\SERVERS, no option in the module parameters

##### STEPS TO REPRODUCE

```
ansible-doc -t module bigip_gtm_server
```

##### EXPECTED RESULTS
Ability to add peer address

##### ACTUAL RESULTS

```
No ability to add peer address parameter
```

**Comment by wojtek0806** [comment]
as per issue opening guidelines, have you verified this with the latest f5-ansible galaxy role ?

**Comment by wojtek0806** [comment]
this has already been answered in #1266 if not please specify precisely what is missing, a tmsh command equivalent is sufficient for us, then we will reopen
