### ISSUE TITLE
all_profile not working.

### ISSUE THREAD

**Issue by mirzawaqasahmed** [F5Networks/f5-ansible#127]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.3.0.0 (detached HEAD f15e1f25ae) last updated 2017/04/01 17:55:23 (GMT +000)
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/ansible/lib/ansible/modules', u'/home/vagrant/modules', u'/home/vagrant/f5-ansible/library', u'/home/vagrant/ansible-pan/library', u'$ara_location/plugins/modules']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```
##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
11.6.1
```

##### STEPS TO REPRODUCE

```
- name: Add app virtual servers for APE
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "{{ f5_username }}"
    password: "{{ f5_password }}"
    partition: Common
    name: "{{ south_app_vs }}"
    destination: "{{ app_vip }}"
    port: "{{ app_port }}"
    pool: "{{ app_pool_name }}"
    snat: Automap
    description: APE app VIP Servers South side
    all_profiles:
      - tcp-wan-optimized
      - tcp-lan-optimized
    enabled_vlans:
      - Core_South_vlan
      - Core_North_vlan
    validate_certs: no
    state: absent
  delegate_to: localhost
  tags: vips,south,app
```

##### EXPECTED RESULTS

I would expect that both profiles be applied. Actually I can see on the docs two types:
http://f5-ansible.readthedocs.io/en/devel/modules/bigip_virtual_server2_module.html
http://f5-ansible.readthedocs.io/en/devel/modules/bigip_virtual_server_module.html

I have also tried with bigip_virtual_server2 module to use client side and server side profile but that it gives me another error....pasted below:..

##### ACTUAL RESULTS

'''
TASK [APE : Add console virtual servers for APE] **************************************
task path: /vagrant/roles/APE/tasks/F5_LTM.yaml:82
Using module file /home/vagrant/ansible/lib/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542 `" && echo ansible-tmp-1492121579.62-53809688470542="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542 `" ) && sleep 0'
<localhost> PUT /tmp/tmpj5KVpc TO /home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542/bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542/ /home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542/bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542/bigip_virtual_server.py; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1492121579.62-53809688470542/" > /dev/null 2>&1 && sleep 0'
fatal: [192.168.145.128 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "all_policies": null, 
            "all_profiles": [
                "tcp-wan-optimized", 
                "tcp-lan-optimized"
            ], 
            "all_rules": null, 
            "default_persistence_profile": null, 
            "description": "APE Console VIP Servers South side", 
            "destination": "199.233.26.28", 
            "enabled_vlans": [
                "Core_South_vlan", 
                "Core_North_vlan"
            ], 
            "fallback_persistence_profile": null, 
            "name": "console.apetest_vs", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "pool": "console.apetest_pl", 
            "port": "8443", 
            "route_advertisement_state": null, 
            "server": "192.168.145.128", 
            "server_port": 443, 
            "snat": "Automap", 
            "state": "present", 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": false
        }
    }, 
    "msg": "received exception: Error on creating Virtual Server : Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/VirtualServer::create()\nException: Common::OperationFailed\n\tprimary_error_code   : 17236119 (0x01070097)\n\tsecondary_error_code : 0\n\terror_string         : 01070097:3: Virtual server /Common/console.apetest_vs lists duplicate profiles.'"
} 

GET THIS ERROR WHEN USING bigip_virtual_server2

TASK [APE : Add app virtual servers for APE] ********************************************************
fatal: [192.168.145.128 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_ipMR1V/ansible_module_bigip_virtual_server2.py\", line 682, in <module>\n    main()\n  File \"/tmp/ansible_ipMR1V/ansible_module_bigip_virtual_server2.py\", line 676, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_ipMR1V/ansible_module_bigip_virtual_server2.py\", line 487, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_ipMR1V/ansible_module_bigip_virtual_server2.py\", line 499, in present\n    if self.exists():\n  File \"/tmp/ansible_ipMR1V/ansible_module_bigip_virtual_server2.py\", line 523, in exists\n    name=self.have.name,\nAttributeError: 'NoneType' object has no attribute 'name'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
...ignoring

'''

```

```

**Comment by mirzawaqasahmed** [comment]
Anyone here who could help?

**Comment by caphrim007** [comment]
@mirzawaqasahmed I have not had a chance to look into this yet

**Comment by caphrim007** [comment]
@mirzawaqasahmed the correct method is to use the virtual_server2 module as you have done. those modules need to be on the client side or the server side; they cannot be "all" like the original virtual_server module did.

So you're going in the right direction.

The bug you've raised about the name is something that I need to fix so that this module will work for you.

**Comment by caphrim007** [comment]
@mirzawaqasahmed the bigip_virtual_server module has been significantly updated recently. please try it out as it is being updated in ansible 2.5. I think this issue is no longer an issue with it.
