### ISSUE TITLE
add ability to specify which config settings are preserved on updates

### ISSUE THREAD

**Issue by netsential** [F5Networks/f5-ansible#1271]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- bigip_pool
- bigip_pool_member
- bigip_virtual_server

##### ANSIBLE VERSION

```
2.7.5
```

##### PYTHON VERSION

```
2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016

```

##### SUMMARY

We would like to have the ability to preserve current settings on specific configuration attributes while allowing for updates to other attributes. For example, update "description" but keep the current "state" on a pool. To put things in context of the module code, having the ability to define the "updatables" for each module from within the playbook. 
##### STEPS TO REPRODUCE

```
N/A
```

##### EXPECTED RESULTS

  N/A
##### ACTUAL RESULTS

```
N/A
```

**Comment by wojtek0806** [comment]
ansible already keeps the parameters that did not change unchanged. If you do not want to change state but only description just define description and leave out state.

Updatables are part of module

**Comment by netsential** [comment]
To provide further details: 

Lets say you have the following pool configuration in a yaml file. Then you run a playbook to enforce it. 

name: 				pool-1
state: 				present
description: 			app pool 1
lb_method: 			round-robin
priority_group_activation: 	1

When the playbook is run/re-run: if the object does not exist on the device, it will make a config change and set all the above parameters
However if it does exist, it will then try to update all the same parameters (as long as they are in the "updatables" list). This could result in resetting values that are constantly adjusted by operations (enablibng/disablig/changing priorities/etc).

All we're looking for is the ability to control what will be updatable without having to modify the corresponding library module. To put it in diferent way, the ability to do the equivalent of the following (commenting out specific entries in the bigip pools module) from within the playbook/yaml.

    updatables = [
        'rate_limit',
        'connection_limit',
        'description',
        #'ratio',
        #'priority_group',
        'fqdn_auto_populate',
        #'state',
        'monitors',
        'inherit_profile',
        'ip_encapsulation',
    ]

**Comment by wojtek0806** [comment]
it will not update the items if they are the same by default modules are idempotent

**Comment by netsential** [comment]
Yes, but some item settings like state/priority/etc will be changing constantly (by other tools or CLI) in the normal course of operations and the playbook will try to re-enforce them, therefore re-setting them to their initially defined values. So, we're hoping to have a feature where you could defined which attributes should be updated (enforced) if they are different. Something like this:
```

name: pool-member-1
description: web server 1
rate_limit: 1000
...
enforce_list:
- description
- rate_limit
- monitors

```
In this case, if the playbook find any changes for items, it will only update the ones defined in the 'enforce' list and ignore the values for others.

**Comment by onurbrc** [comment]
@netsential even if you run the playbook several times with the same values which already exist in the device, no change on those parameters will be made. 

Idempotency:
An operation is idempotent if the result of performing it once is exactly the same as the result of performing it repeatedly without any intervening actions.

If you can confirm this, you can view log messages in the device when the playbook is running:
tail -f /var/log/audit if you wanna see the commands passed by the your ansible 
tail -f /var/log/ltm if you wanna check that your ltm resources didn’t change the current state during the operation.

**Comment by netsential** [comment]
Yeah, I understand that. It works if nothing has changed, but the problem is that they may be different the next time. In that case it will try to make changes which may not want to (for example the new state may now be "disabled" temporarily) but the playbook will change it back to 'present' as initially defined.

**Comment by wojtek0806** [comment]
then use device facts to gather subset of interesting information if it changes frequently and build that logic in your playbook.

**Comment by onurbrc** [comment]
@netsential as wojtek0806 said, you can collect the current values of your ltm ressources in the device and register them inside an output variable. Please, check [register option](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#registering-variables).

- task1 you gather facts with bigip_device_facts + register option
- tasks2 you specify new values for the parameters that you wanna change  and the collected values for those parameters that you wanna to preserve.

**Comment by netsential** [comment]
That's a solution we're considering as well. Thank you @wojtek0806 and @onurbrc for the prompt responses and ideas.
