### ISSUE TITLE
Generate private key and download csr

### ISSUE THREAD

**Issue by OncleDave** [F5Networks/f5-ansible#1275]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_ssl_key

##### SUMMARY
I would like to generate a private key on the F5 and download the csr to request the certificate to a CA.  
This ca be done in the GUI under System --> File Management --> SSL Certificate List , select Create. Ensure that you choose "Certificate Authority" under Issuer.

**Comment by wojtek0806** [comment]
is there a tmsh command to do this task if not then there is no rest endpoint to do this, so implementation will not happen

**Comment by wojtek0806** [comment]
Likely tmsh commands that achieve this:

tmsh create sys crypto key ?
Options:
  gen-certificate      also generate a self signed certificate
  gen-csr              also generate a certificate signing request and display it
  prompt-for-password  Use password for key.

**Comment by wojtek0806** [comment]
FMFA-247
