### ISSUE TITLE
Error with task bigip_appsvcs_extension

### ISSUE THREAD

**Issue by xbill42** [F5Networks/f5-ansible#1282]
Hi,

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 bigip_appsvcs_extension

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 13 2019, 17:23:12) [GCC 8.3.0]
```

##### PYTHON VERSION
```
Python 2.7.15
```

##### BIGIP VERSION

```
Main Package
  Product     BIG-IP
  Version     14.1.0
  Build       0.0.116
  Edition     Final
```

##### OS / ENVIRONMENT
linux

##### SUMMARY
When trying to deploy an as3 jinja template I receive this error 

ValueError: invalid literal for int() with base 10: 'None'

The as3 template works when sent with a rest call.
I also have the same error if I provide an empty as3 file

##### STEPS TO REPRODUCE

---
- hosts: f5b
  connection: local
  gather_facts: no

  vars:
    # Set F5 provider for F5 api
    # Tower credentials or group/host variables
    provider:
      password: "{{ f5_password | default(lookup('env','ANSIBLE_NET_PASSWORD')) }}"
      server: "{{ ansible_host }}"
      user: "{{ f5_username | default(lookup('env','ANSIBLE_NET_USERNAME')) }}"
      validate_certs: no

  tasks:

    - name: Deploy an app service configuration
      bigip_appsvcs_extension:
        content: "{{ lookup('file', '/root/myansible/jinja/as3_test.j2') }}"
        state: present
        provider: "{{ provider }}"

...

##### ACTUAL RESULTS

Full error log

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: invalid literal for int() with base 10: 'None'
fatal: [f5b]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1554312833.86483-275005203194132/AnsiballZ_bigip_appsvcs_extension.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1554312833.86483-275005203194132/AnsiballZ_bigip_appsvcs_extension.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1554312833.86483-275005203194132/AnsiballZ_bigip_appsvcs_extension.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/__main__.py\", line 522, in <module>\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/__main__.py\", line 513, in main\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/__main__.py\", line 337, in exec_module\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/__main__.py\", line 350, in present\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/__main__.py\", line 368, in upsert\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/__main__.py\", line 389, in upsert_on_device\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 320, in post\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 279, in request\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/network/f5/icontrol.py\", line 293, in send\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/urls.py\", line 1162, in open_url\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/urls.py\", line 951, in open\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/urls.py\", line 804, in maybe_add_ssl_handler\n  File \"/tmp/ansible_bigip_appsvcs_extension_payload_rlm05g/ansible_bigip_appsvcs_extension_payload.zip/ansible/module_utils/urls.py\", line 407, in generic_urlparse\n  File \"/usr/lib/python2.7/urlparse.py\", line 113, in port\n    port = int(port, 10)\nValueError: invalid literal for int() with base 10: 'None'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

Best regards

**Comment by wojtek0806** [comment]
please test with ansible galaxy role as per the instructions on how to submit issues, closing until this is completed
