### ISSUE TITLE
Add Description Field To BIGIP_SNAT_POOL Module

### ISSUE THREAD

**Issue by CaptainBlasteroid** [F5Networks/f5-ansible#1284]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_snat_pool

##### SUMMARY

Please add the description field to the bigip_snat_pool module. It is an updatable field via the Rest API and it would be nice to do the same with the module, too.

**Comment by wojtek0806** [comment]
FMFA-232

**Comment by wojtek0806** [comment]
merged
