### ISSUE TITLE
gather facts from Bigip Facts is very slow.

### ISSUE THREAD

**Issue by rcedros** [F5Networks/f5-ansible#1286]
##### ISSUE TYPE

    Bug Report
    Feature Idea
    Documentation Report
    Bug Report

##### COMPONENT NAME

ansible facts

##### ANSIBLE VERSION

ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 13:30:17) [GCC 7.3.0]

##### BIGIP VERSION

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018

#### CONFIGURATION

---

- name: gather facts
  hosts: bigip01
  connection: local
  gather_facts: True

  vars:
    provider:
      password: PASSWD
      server: 10.10.10.10
      user: USER1
      validate_certs: no
      server_port: 443
  tasks:
    - name: Collect BIG-IP monitors facts
      register: monitors
      bigip_device_facts:
        gather_subset:
          - monitors  
        provider: "{{provider}}"
      delegate_to: localhost        

##### OS / ENVIRONMENT
Ubuntu

##### SUMMARY
I trying to use gather_facts from bigip, but when I specify some module, like "monitors" the execution time is very high.

##### EXPECTED RESULTS

i want decrease execution time. 

##### ACTUAL RESULTS

PLAY [gather facts] **********************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [10.10.10.10]

TASK [Collect BIG-IP monitors facts] *****************************************************************************************************************
changed: [10.10.10.10 -> localhost]

PLAY RECAP *******************************************************************************************************************************************
10.10.10.10             : ok=2    changed=1    unreachable=0    failed=0   

##### sys	0m0,480s

```

```

**Comment by wojtek0806** [comment]
Have you tested with the galaxy role? please review the documentation on how to open issues and paste results with the role in use, once this information is provided we will reopen
