### ISSUE TITLE
bigip_appsvcs_extension should return declaration

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-ansible#1288]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_appsvcs_extension

##### ANSIBLE VERSION

```
ansible 2.7.6
  config file = /home/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
```

##### PYTHON VERSION

```
Python 2.7.14
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Thu Oct 11 15:32:21 PDT 2018


```

##### CONFIGURATION

root@7258018cb0f1 /home/ansible> cat ansible.cfg 
[defaults]
inventory = ./hosts
library   = ./library
roles_path = .playbooks/roles
retry_files_enabled = False
host_key_checking = False
vault_password_file = ./.vault-pass.txt
remote_tmp = /tmp/.ansible/tmp
deprecation_warnings=False

[ssh_connection]
ssh_executable = /usr/bin/ssh
control_path_dir=/tmp/.ansible/cp

I am not using the f5ansible role.

##### OS / ENVIRONMENT

Ansible is being run from a docker container derived from Alpine 
root@7258018cb0f1 /home/ansible> cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
##### SUMMARY

The bigip_appsvcs_extension module should return the declaration as output.  If you use POSTMAN the declaration is returned.  

##### STEPS TO REPRODUCE

```
    - name: Deploy declaration
      bigip_appsvcs_extension:
        content: "{{ declaration }}"
        state:   "present"
        validate_certs: no
      delegate_to: localhost
      register: as3Out


    - debug:
        var: as3Out

```

##### EXPECTED RESULTS

The declaration to be returned.

##### ACTUAL RESULTS

TASK [Deploy declaration] *******************************************************************************
changed: [localhost -> localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "as3Out": {
        "action": "deploy", 
        "changed": true, 
        "deprecations": [
            {
                "msg": "Param 'server' is deprecated. See the module docs for more information", 
                "version": 2.9
            }, 
            {
                "msg": "Param 'user' is deprecated. See the module docs for more information", 
                "version": 2.9
            }, 
            {
                "msg": "Param 'server_port' is deprecated. See the module docs for more information", 
                "version": 2.9
            }, 
            {
                "msg": "Param 'password' is deprecated. See the module docs for more information", 
                "version": 2.9
            }, 
            {
                "msg": "Param 'validate_certs' is deprecated. See the module docs for more information", 
                "version": 2.9
            }
        ], 
        "failed": false
    }
}

```

```

**Comment by wojtek0806** [comment]
@focrensh can you see if this will be covered by the role? I do not see a need to have this in the module

**Comment by writemike** [comment]
We have a requirement for this as well. The customer would like to back-up their existing declarations before pushing new changes so it would be great if this module could not only return the declaration after a POST, but also support a GET to collect what the current declaration is.

**Comment by focrensh** [comment]
We will be adding GET functionality with existing declaration as output to our role in coming weeks:
https://galaxy.ansible.com/f5devcentral/atc_deploy

Tracking internally with FMFA-397

**Comment by focrensh** [comment]
The role now has GET included for Automation Toolchain:

https://galaxy.ansible.com/f5devcentral/atc_deploy
