### ISSUE TITLE
bigip_appsvcs_extension should support methods other than GET and PATCH methods

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-ansible#1289]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME

bigip_appsvcs_extension 
##### ANSIBLE VERSION

```
root@7258018cb0f1 /home/ansible> ansible --version
ansible 2.7.6
  config file = /home/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
```

##### PYTHON VERSION

```
root@7258018cb0f1 /home/ansible> python -V
Python 2.7.14
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Thu Oct 11 15:32:21 PDT 2018


```

##### CONFIGURATION

root@7258018cb0f1 /home/ansible> cat ansible.cfg 
[defaults]
inventory = ./hosts
library   = ./library
roles_path = .playbooks/roles
retry_files_enabled = False
host_key_checking = False
vault_password_file = ./.vault-pass.txt
remote_tmp = /tmp/.ansible/tmp
deprecation_warnings=False

[ssh_connection]
ssh_executable = /usr/bin/ssh
control_path_dir=/tmp/.ansible/cp

I am not using the f5ansible role. 

##### OS / ENVIRONMENT

This is being run from docker container derived from Alpine 3.7.0. 

##### SUMMARY

AS3 support GET and PATCH methods.  GET would return the currently deployed declaration and PATCH to add new application to an existing tenant/partition.   bigip_appsvcs_extension module does not currently have support for either of these methods.  If a user wants/needs to support either of these they need to use the built-in Ansible URI module (which isn't ideal).

##### STEPS TO REPRODUCE

```
n/a
```

##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

```
N/A
```

**Comment by wojtek0806** [comment]
@focrensh can you see if this will be covered by the role? I do not see a need to have this in the module

**Comment by writemike** [comment]
We have a requirement for this as well. The customer would like to back-up their existing declarations before pushing new changes so it would be great if this module could not only return the declaration after a POST, but also support a GET to collect what the current declaration is.

**Comment by focrensh** [comment]
Please the role on galaxy which covers all of automation toolchain and supports this functionality:

https://galaxy.ansible.com/f5devcentral/atc_deploy

This AS3 specific module will be marked deprecated in coming releases.
