### ISSUE TITLE
bigip-qkview throwing an 400 unexpected bad error

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#129]
Not sure if I am inputting some incorrect parameters?

*****************************************************************
PLAYBOOK

- name: Create qkview
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Generate and store qkview file
    bigip_qkview:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      asm_request_log: "yes"
      dest: "/tmp/localhost.localdomain.qkview"
      validate_certs: "no"
    delegate_to: localhost

***************************************
BIG-IP VERSION
 Version     12.1.2
  Build       0.0.249
***************************************

TASK [Generate and store qkview file] *******************************************************************************************************************************************************************************************************
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/util/qkview/\nText: u'{\"code\":400,\"message\":\"remoteSender:10.192.74.122, method:POST \",\"originalRequestBody\":\"{\\\\\"utilCmdArgs\\\\\": \\\\\"-s0 -f localhost.localdomain.qkview -o asm-request-log\\\\\", \\\\\"command\\\\\": \\\\\"run\\\\\"}\",\"referer\":\"10.192.74.122\",\"restOperationId\":4855169,\"errorStack\":[\"java.util.concurrent.TimeoutException: remoteSender:10.192.74.122, method:POST \",\"at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3057)\",\"at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3046)\",\"at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1411)\",\"at com.f5.rest.common.RestServer.access$400(RestServer.java:46)\",\"at com.f5.rest.common.RestServer$4.run(RestServer.java:1384)\",\"at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\",\"at java.lang.Thread.run(Thread.java:745)\\\\n\"],\"kind\":\":resterrorresponse\"}'"}
        to retry, use: --limit @/root/ps_ansible/playbooks/bigip-qkview.retry

**Comment by caphrim007** [comment]
@payalsin i've seen this occur in the past and i'm not sure what the cause is. qkview command seems to freeze for no reason when some combination of arguments is provided.

this seems to be an example of that.

we might need to file a BZ for this

**Comment by caphrim007** [comment]
@payalsin also, is ASM provisioned?

**Comment by payalsin** [comment]
no ASM is not provisioned, I tried with asm_request_log: "no" and still getting the same error

---
- name: Create qkview
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Generate and store qkview file
    bigip_qkview:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      asm_request_log: "no"
      dest: "/tmp/localhost.localdomain.qkview"
      validate_certs: "no"
    delegate_to: localhost

TASK [Generate and store qkview file] *******************************************************************************************************************************************************************************************************
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/util/qkview/\nText: u'{\"code\":400,\"message\":\"remoteSender:10.192.74.122, method:POST \",\"originalRequestBody\":\"{\\\\\"utilCmdArgs\\\\\": \\\\\"-s0 -f localhost.localdomain.qkview\\\\\", \\\\\"command\\\\\": \\\\\"run\\\\\"}\",\"referer\":\"10.192.74.122\",\"restOperationId\":55962,\"errorStack\":[\"java.util.concurrent.TimeoutException: remoteSender:10.192.74.122, method:POST \",\"at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3057)\",\"at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3046)\",\"at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1411)\",\"at com.f5.rest.common.RestServer.access$400(RestServer.java:46)\",\"at com.f5.rest.common.RestServer$4.run(RestServer.java:1384)\",\"at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\",\"at java.lang.Thread.run(Thread.java:745)\\\\n\"],\"kind\":\":resterrorresponse\"}'"}

*****************************

Also if I dont specify asm_request_log parameter altogether I get a different error:
- name: Create qkview
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Generate and store qkview file
    bigip_qkview:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      dest: "/tmp/localhost.localdomain.qkview"
      validate_certs: "no"
    delegate_to: localhost

fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 469, in <module>\n    main()\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 463, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 236, in exec_module\n    return manager.exec_module()\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 274, in exec_module\n    self.present()\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 287, in present\n    self.execute()\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 311, in execute\n    self._download_file()\n  File \"/tmp/ansible_iUBlwu/ansible_module_bigip_qkview.py\", line 391, in _download_file\n    madm = self.client.api.shared.file_transfer.madm\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/mixins.py\", line 102, in __getattr__\n    raise AttributeError(error_message)\nAttributeError: '<class 'f5.bigip.shared.file_transfer.File_Transfer'>' object has no attribute 'madm'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by caphrim007** [comment]
for the second error there, it looks like you need to update the version of f5-sdk

**Comment by payalsin** [comment]
ok, thanks yes updating the f5-sdk changed the error to the previous one. Do you have an example of which params work for sure so that we could document that. Using it with just a dest: might be a common way to do it and it will fail if there is a bigip bug

**Comment by caphrim007** [comment]
I would expect all of the options to work. wouldn't many much sense to not have all the options work.

can you enable ASM and try that option again?

**Comment by payalsin** [comment]
licensed ASM, still no luck...same issue....

**Comment by wojtek0806** [comment]
@payalsin i assume this is the same box as you gave me access yesterday ?

**Comment by payalsin** [comment]
Yup same box.... thanks

**Comment by payalsin** [comment]
@caphrim007 - Still seeing the issue

------------------------------------
[root@ansible-host ps_ansible]# ansible-playbook playbooks/bigip-qkview.yaml -vvvv
ansible-playbook 2.6.0
  config file = /root/ps_ansible/ansible.cfg
  configured module search path = [u'/root/ps_ansible/library/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Using /root/ps_ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /root/ps_ansible/dev inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: bigip-qkview.yaml ******************************************************************************************
1 plays in playbooks/bigip-qkview.yaml

PLAY [Create qkview] *************************************************************************************************
META: ran handlers

TASK [Generate and store qkview file] ********************************************************************************
task path: /root/ps_ansible/playbooks/bigip-qkview.yaml:8
<localhost> connection transport is rest
Using module file /root/ps_ansible/library/modules/bigip_qkview.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995 `" && echo ansible-tmp-1529512596.96-208947367493995="` echo /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-21053SPoRsx/tmpU3V8XD TO /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995/bigip_qkview.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995/ /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995/bigip_qkview.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995/bigip_qkview.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1529512596.96-208947367493995/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_b3Dlcy/ansible_module_bigip_qkview.py", line 458, in main
    results = mm.exec_module()
  File "/tmp/ansible_b3Dlcy/ansible_module_bigip_qkview.py", line 223, in exec_module
    return manager.exec_module()
  File "/tmp/ansible_b3Dlcy/ansible_module_bigip_qkview.py", line 274, in exec_module
    raise F5ModuleError(str(e))

fatal: [10.192.73.246 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "asm_request_log": false,
            "complete_information": false,
            "dest": "/tmp/localhost.localdomain.qkview",
            "exclude": null,
            "exclude_core": false,
            "filename": "localhost.localdomain.qkview",
            "force": true,
            "max_file_size": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "10.192.73.218",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "server": "10.192.73.218",
            "server_port": null,
            "transport": null,
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/util/qkview/\nText: u'{\"code\":400,\"message\":\"remoteSender:10.192.74.122, method:POST \",\"originalRequestBody\":\"{\\\\\"utilCmdArgs\\\\\": \\\\\"-s0 -f localhost.localdomain.qkview\\\\\", \\\\\"command\\\\\": \\\\\"run\\\\\"}\",\"referer\":\"10.192.74.122\",\"restOperationId\":13082494,\"errorStack\":[\"java.util.concurrent.TimeoutException: remoteSender:10.192.74.122, method:POST \",\"at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3067)\",\"at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3056)\",\"at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1440)\",\"at com.f5.rest.common.RestServer.access$400(RestServer.java:48)\",\"at com.f5.rest.common.RestServer$4.run(RestServer.java:1413)\",\"at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\",\"at java.lang.Thread.run(Thread.java:745)\\\\n\"],\"kind\":\":resterrorresponse\"}'"
}
        to retry, use: --limit @/root/ps_ansible/playbooks/bigip-qkview.retry

PLAY RECAP ***********************************************************************************************************
10.192.73.246              : ok=0    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment]
@payalsin this should now be fixed. If not, lemme know

**Comment by kleinsmk** [comment]
@caphrim007 What ended up fixing the timeout exception ?  I"m working on other REST based automation and run into this when working with ASM as well on only certain F5 Big-Ips

**Comment by caphrim007** [comment]
@kleinsmk originally we handled it by catching the timeout exception and then polling the device repeatedly to determine if the qkview command was still running

Since then we've switched to creating an async worker task on the box and polling for its completion.

Async script
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L372

Creating the script
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L386

Creating async task to poll
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L417

Executing the task
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L444

Waiting for task to finish
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L460

Removing temporary script
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L485

And finally moving the qkview to a place that we can download it from the REST API
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_qkview.py#L499

I don't know if any of the above is applicable to ASM though as my recollection of that product is that it has limited tmsh support. YMMV.

**Comment by kleinsmk** [comment]
Thanks for the quick response.

 I noticed as of 13.x the gui was simply calling the REST API to create and apply ASM polices so I simply cloned that.  Your links explain some of the async tasks it was calling and why.  Ironically applying the policy via REST seems to the offending operation. I'll look into seeing if that can't be done via task instead.

**Comment by narasims** [comment]
I'm having the issue with the same module. seems like a different one. And in my playbook I'm not using the asm request log.

BIGIP version: 14.1.2.3
Ansible version: 2.9.9
f5-sdk version: 3.0.21

Here is my error:

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/tmp/narasims/.ansible/ansible-tmp-1591900772.5692306-105815-251675632424209/AnsiballZ_bigip_qkview.py", line 102, in <module>
    _ansiballz_main()
  File "/tmp/narasims/.ansible/ansible-tmp-1591900772.5692306-105815-251675632424209/AnsiballZ_bigip_qkview.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/narasims/.ansible/ansible-tmp-1591900772.5692306-105815-251675632424209/AnsiballZ_bigip_qkview.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_qkview', init_globals=None, run_name='__main__', alter_sys=True)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 605, in <module>
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 598, in main
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 229, in exec_module
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 273, in exec_module
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 295, in present
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 321, in execute
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 368, in execute_on_device
  File "/tmp/ansible_bigip_qkview_payload_93emn6td/ansible_bigip_qkview_payload.zip/ansible/modules/network/f5/bigip_qkview.py", line 477, in _wait_for_async_task_to_finish_on_device
KeyError: '_taskState'
