### ISSUE TITLE
bigip_device_httpd implementation of ssl-protocol is broken

### ISSUE THREAD

**Issue by rmcolbert** [F5Networks/f5-ansible#1292]
ssl-protocol must be an ordered list but as currently implemented, the values are sorted. This results in all protocols being enabled because the end-result (if applying the default values) is "-SSLv2 -SSLv3 all" which does not work. It must be implemented as "all -SSLv2 -SSLv3"

Removing the sorting should resolve this defect.

_Originally posted by @rmcolbert in https://github.com/F5Networks/f5-ansible/issues/587#issuecomment-483372036_

**Comment by wojtek0806** [comment]
Please test with the galaxy role and post results before opening issues:
https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/filing-issues.html
Once this requirement if fulfilled we will reopen

**Comment by rmcolbert** [comment]
Tested w/ galaxy role with the same results.

LTM v13.1.0.1
ansible 2.7.10
python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Tested using the upstream role & this one.

Lines 440, 442 & 444 are sorting the input values which breaks the required ordering of the value. If there are any - entries in either the input or the stored value, the list can not be sorted.

https://github.com/F5Networks/f5-ansible/blob/6bdb902a5d8aabd6459b81daa4b11654a8ae7f1f/library/modules/bigip_device_httpd.py#L440

Below is a test script. The expected result is that SSLv2, SSLv3 & TLSv1 are all disabled. The actual result is that all protocols are enabled because "all" is sorted to the last position in the list.

[test-sslprotocol.zip](https://github.com/F5Networks/f5-ansible/files/3082015/test-sslprotocol.zip)

**Comment by wojtek0806** [comment]
looks like the fix for #1018 only addressed cipher suites not protocols:
https://github.com/F5Networks/f5-ansible/blob/bd1b81ddb62097ca4b1579031be5f7741406435d/library/modules/bigip_device_httpd.py

**Comment by wojtek0806** [comment]
internal tracking FMFA-229
