### ISSUE TITLE
bigip_hostname always reports failure first time, works thereafter

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1304]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_hostname
##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### CONFIGURATION

Updated yesterday
##### OS / ENVIRONMENT

```
Ubuntu 18.0.4
```
##### SUMMARY

The first time the module is run after a device is built with a standard CFT, it reports failure, with a msg of ''''''.  However, the hostname is actually changed anyway.  Any subsequent runs will always work unless the CFT is rebuilt.  The attached example calls bigip_hostname twice in the same playbook, but the problem occurs across playbooks.
##### STEPS TO REPRODUCE

```
See Gist: https://gist.github.com/C0missar/b790ea003ff6fb8d29ea85df49453f7f
```

##### EXPECTED RESULTS

That the device hostname would be changed, and the module would report success and continue.
##### ACTUAL RESULTS

The device hostname was changed, but the module reported failure the first time.  It worked correctly the second time.

```
See Gist: https://gist.github.com/C0missar/b790ea003ff6fb8d29ea85df49453f7f
```

**Comment by focrensh** [comment]
Thank you for the great logs/output. FMFA-224 opened for tracking internally.

**Comment by C0missar** [comment]
My pleasure.  No reason to make it hard on you folk…

**Comment by wojtek0806** [comment]
you have bigip_wait module to address these kind of situations

**Comment by C0missar** [comment]
What kind of situations?  The change actually occurred, it's the error message that is bogus.  And if it is a timing problem, there is no indication that the endpoint is not ready (but it must have been, or the change would not have occurred).

Since this has happened when this is literally the only play in the book, do I need to put a bigip_wait in front of every single module I ever call?

**Comment by wojtek0806** [comment]
when a device is newly booted you need to verify it is ready for you to start sending calls to it, the amount of time will depend on hardware platform and tmos version, so you need to tailor this with bigip_wait. This is literally what we do in every role we create we always check if the device is ready for the calls to be made. 

Second case where you use bigip_wait is when an operation on the device will cause a restart of some services: bigip_ucs comes to mind. While we do include a logic with timeouts in the modules that might get the device into a state where it will not accept REST calls for a while, these timers are arbitrary so might not suit your environment. Unfortunately there is no consistency in how much time you need to wait, hence bigip_wait module was create so users can tailor their plays to their environment

**Comment by C0missar** [comment]
Ok, but perhaps I misunderstood what bigip_wait does.  I thought that it made a call, and if it didn’t get a ready response went to sleep for a time (5 second default?) and then checked again in a loop until the device was ready.  That wouldn’t require tuning the time period to the function one was waiting on.

Is that description not correct?

Thanks,

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com<mailto:michael.s.tetreault@sherwin.com>
http://www.sherwin-williams.com<http://www.sherwin-williams.com/>

Stan

**Comment by wojtek0806** [comment]
bigip_wait is basically a way to hold the rest of the play, during that hold time (you define with bigip_wait) we check if bigip is ready for REST calls, if it is we then finish the bigip_wait task, and move on with the rest of the task in your playbook. If the device is still not responding after the period set in bigip_wait, we raise an error and playbook fails.

**Comment by sdaynjax** [comment]
I have this same issue and its not related to the F5 not being available.  I'm running this module against an LTM that is fully configured and functional and part of an HA pair.  I get the error  "01071581:3: The self device can not be moved if it is part of a trust group." and the status shows failed=1 but the change was actually made.  The second time I run it I don't get the error but I never get an update to the changed=0 status.
