### ISSUE TITLE
bigip_iapplx_package error - ImportError: cannot import name HAS_F5SDK

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1305]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_iapplx_package
##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### CONFIGURATION

Updated yesterday
##### OS / ENVIRONMENT

```
Ubuntu 18.0.4
```
##### SUMMARY

This playbook used to run without error.  Now it throws the 'ImportError: cannot import name HAS_F5SDK' message and fails.

This is similar to issue #1110, but I have updated the f5devcentral.f5ansible,master role today (and reinstalled f5-sdk, bigsuds, netaddr, and deepdiff).

It MAY have been triggered by my updating ansible and re-installing python 2.7.1 last week, but I just saw the problem today.  All of my other onboarding module calls still work normally.

##### STEPS TO REPRODUCE

```
See Gist: https://gist.github.com/C0missar/65a99aed02577453b78f50dbbc544faf
```

##### EXPECTED RESULTS

```
AS3 package would be installed.
```
##### ACTUAL RESULTS

```
ImportError: cannot import name HAS_F5SDK

See Gist: https://gist.github.com/C0missar/65a99aed02577453b78f50dbbc544faf
```

**Comment by wojtek0806** [comment]
This is a deprecated module, use bigip_lx_package

**Comment by C0missar** [comment]
There is no bigip_lx_package listed on https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/list_of_all_modules.html, and bigip_iapplx_package is not marked as deprecated.  In fact, it’s the module you pointed me at to resolve issue #1183.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com<mailto:michael.s.tetreault@sherwin.com>
http://www.sherwin-williams.com<http://www.sherwin-williams.com/>

**Comment by C0missar** [comment]
That doc indicates that bigip_iapplx_package is an alias for bigip_lx_package.  I tried both with identical results.  It works on a v14 box, but is failing on the 13.1.1 box I originally tested with, including this morning after a complete rebuild from scratch (redeploy of CFT and onboarding script).

Here's a new Gist that includes the device logs:  https://gist.github.com/C0missar/b4af0b34519b3d1f43cc85a2e826e6e8.

I also pulled a fresh copy of the role and re-ran it (after the above logs were taken), but get the same results.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com<mailto:michael.s.tetreault@sherwin.com>
http://www.sherwin-williams.com<http://www.sherwin-williams.com/>

**Comment by wojtek0806** [comment]
ill look at this later, but i still think this is your environment, cause I removed HAS_F5SDK variable from the code base..can you do a quick command and paste the output please:

`ansible-galaxy info f5devcentral.f5ansible`

**Comment by C0missar** [comment]
Here you go:

# ansible-galaxy info f5devcentral.f5ansible

Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 6af85de2b0f696e768c6c84a99b22a8489ebc98e
        commit_message: removed mention of SDK
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/6af85de2b0f696e768c6c84
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        dependencies: []
        download_count: 3851
        forks_count: 1
        galaxy_info:
                author: caphrim007
                company: F5 Networks
                galaxy_tags: ['f5', 'networking', 'bigip', 'bigiq']
                license: GPLv3
                min_ansible_version: 2.7
                platforms: [{'name': 'EL', 'versions': ['all']}, {'name': 'Fedora', 'versions': ['all']}, {'name': 'Ubun
                role_name: f5ansible
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-04-26T04:08:32.945387-04:00
        install_date: Mon Apr 29 16:35:08 2019
        installed_version: master
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.7
        modified: 2019-04-26T08:08:33.046875Z
        open_issues_count: 0
        path: [u'/home/sxw455/.ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=v2019.4.26

**Comment by wojtek0806** [comment]
As I suspected I found a problem, you need to change your module name in your place to bigip_lx_package. Normally this would not matter but it seems the symlinks do not work in the


https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/network/f5/bigip_iapplx_package.py#L105

**Comment by C0missar** [comment]
I tried that already, got exactly the same results.
