### ISSUE TITLE
bigip_asm_policy_import fails - 'The security policy file does not conform to the schema and cannot be imported'

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1306]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_asm_policy_import
##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### OS / ENVIRONMENT

```
Ubuntu 18.0.4
```
##### SUMMARY

```
Most ASM policies being imported now fail with 'Unexpected Error: Import policy failed. Messages: [fatal] The security policy file does not conform to the schema and cannot be imported.'  The policies are exported manually, and the device code version of both the source (13.1.1.-0.47.4) and destination (13.1.1-0.0.4) devices has not changed in the last two months.  This used to work 100%, and now is failing on four of the six policies I'm working with (which have undergone edits during that time).  The exact schema violations are listed in the output on the GIST.
```
##### STEPS TO REPRODUCE

```
#ansible-playbook ASM.yaml -e Host=awsf5proda.sherwin.com -e Name=Unix_Linux -vvvv &> ASM.log

See Gist for Playbook, debug output, and ASM .xml file
https://gist.github.com/C0missar/20fefe297e2697b069f88ebba0e7f180
``

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->
Successful policy import
##### ACTUAL RESULTS
<!--- What actually happened? If possible run with high verbosity (-vvvv) -->
<!--- Paste verbatim command output between quotes below -->
```
See Gist for Playbook, debug output, and ASM .xml file
https://gist.github.com/C0missar/20fefe297e2697b069f88ebba0e7f180

Unexpected Error: Import policy failed. Messages: [fatal] The security policy file does not conform to the schema and cannot be imported. (line 9163: element system_name: Schemas validity error : Element 'system_name': [facet 'enumeration'] The value 'JavaScript' is not an element of the set {'Microsoft Windows', 'Unix/Linux', 'MacOS/MacHTTP Server', 'IIS', 'Apache/NCSA HTTP Server', 'Apache', 'Apache Tomcat', 'Other Web Server', 'Proxy Servers', 'PHP', 'CGI', 'ASP', 'ASP.NET', 'SSI (Server Side Includes)', 'Java Servlets/JSP', 'Macromedia ColdFusion', 'Lotus Domino', 'IBM WebSphere', 'BEA Systems WebLogic Server', 'Macromedia JRun', 'Talentsoft Web+', 'Outlook Web Access', 'Front Page Server Extensions (FPSE)', 'WebDAV', 'Novell', 'Cisco', 'Microsoft SQL Server', 'Oracle', 'MySQL', 'Sybase/ASE', 'IBM DB2', 'PostgreSQL', 'General Database', 'Various systems', 'All systems', 'System Independent', 'XML', 'PSM', 'Apache Struts', 'Elasticsearch', 'jQuery', 'WordPress', 'JBoss', 'Citrix', 'Node.js', 'Django', 'MongoDB', 'Ruby', 'JavaServer Faces (JSF)', 'Joomla', 'SQLite'}.
    line 9163: element system_name: Schemas validity error : Element 'system_name': 'JavaScript' is not a valid value of the local atomic type.
    )
```

**Comment by wojtek0806** [comment]
This error comes from the BIGIP not the module, you can easily test this bypassing the module just attempt to upload the XML file to the device in questions via GUI, if you get the error you know this is not a problem here. If this fails without the Ansible then  I would suggest reaching out to F5 support for further assistance in this matter.

**Comment by wojtek0806** [comment]
@C0missar any updates ?

**Comment by C0missar** [comment]
It works now.  I have no idea why.

The same policies that were generating errors on import are now working, importing to both existing 13.1.1 devices, 14.1.0 devices, and AWS 13.1.1 devices being continuously rebuilt.  The data in the GIST I posted with the original problem was on a fresh image built from an F5 stock CFT.

The one difference I see is that I’ve rolled back to Ansible 2.7.1, whereas the problem was reported on Ansible 2.7.10.

I guess you can close this issue.  This doesn’t make me feel good about forward compatibility to 2.8, though.

Stan

**Comment by wojtek0806** [comment]
I am afraid that once the 2.8 hits the role will require 2.8 installed due to some changes in plugins, so you might have no choice. I would also suggest start moving towards python 3.x as 2.7 support will drop in 2020. The error you have is likely due to string encoding, that is why I asked to test with importing via GUI to eliminate Ansible module as the middle man, this way you can see if the policy files you have are corrupted or not.

**Comment by C0missar** [comment]
We can’t move to Python 3.x – tried, but Amazon’s boto library doesn’t support it.

Also, ASM import broke again, and this time I couldn’t import the policies via GUI, either.  I’m beginning to think there is some dependency I’m missing, such as signature updates; regardless, that’s certainly proof that it’s not a role issue.

Stan
