### ISSUE TITLE
bigip_provision rejecting valid provisioning options

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1307]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_provision
##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### OS / ENVIRONMENT

```
Ubuntu 18.0.4
```
##### SUMMARY

```
The following provisioning options are rejected in a call:
Level=None (required to de-provision any module; mentioned in the level description, but not available as a value for Level)
Mgmt (would require levels=small, medium, or large)
CGNat (exists, but level values of Enabled or Disabled aren't there)
AAM (not available)
URLDB (not available)
```
##### STEPS TO REPRODUCE

```
See Gist: https://gist.github.com/C0missar/0c4329b8a7562d6f048e5a39b0d622d2
``

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
```

That the Mgmt, AAM, CGNat, and URLDB modules would be provisioned
```

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with high verbosity (-vvvv) -->
<!--- Paste verbatim command output between quotes below -->
```
All four provisioning requests were rejected with invalid values.
See Gist: https://gist.github.com/C0missar/0c4329b8a7562d6f048e5a39b0d622d2
```

**Comment by wojtek0806** [comment]
approved

**Comment by wojtek0806** [comment]
Created FMFA-226

**Comment by crosbygw** [comment]
Hi @C0missar , thank you for your feedback!

As you know, level none deprovisions the module specified. Using a state of absent deletes (deprovisions in this case) the module specified. You should use state absent rather then level none to deprovision a specified module.

Same logic is being used for CGNAT; level is not required as state: present uses a level of enabled, and state: absent uses level disabled.

Application Acceleration Manger is an available option; it is notated as am rather then aam. 

I will add a few notes in the documentation to help clarify these points, as i can see how it is confusing. 

Working on adding support for URLDB into provision module. 

Also, looking into adding support with alternate provisioning levels for mgmt. MGMT is not a module that can be deprovisioned but rather is being used to set amount of memory dedicated to management actions. IE, small has 0 extra ram for management (1264 total), medium sets aside an additional 200 MB (1464 total), and large sets a side an additional 500 MB (1764 total).
