### ISSUE TITLE
APM Modules?

### ISSUE THREAD

**Issue by whytoe** [F5Networks/f5-ansible#131]
Hey Tim,

Is there any modules currently to provision to the APM module in F5?

Dan

**Comment by wojtek0806** [comment]
As far as I can see there are none. It is something I was considering for the SDK lib (so we use REST) and it has to be implemented there first. Are there any specifics you have in mind for now? 

@whytoe

**Comment by whytoe** [comment]
I was thinking 

- Access Policies
- SSO configurations

**Comment by wojtek0806** [comment]
ok I opened up issue for that in SDK , it needs to be implemented there before we can plan those for Ansible

**Comment by jmcalalang** [comment]
if this is to straight provision APM that module does exist: https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_provision.py, if this is to reference an APM policy for upload thats different (i also need the latter).

**Comment by delgadillo22** [comment]
This request is quite broad. Would be helpful if you can provide example configs for the use cases you have in mind.

**Comment by wojtek0806** [comment]
@whytoe we have implemented policy import/export modules, if you have anything else specific in please provide us with tmsh config examples and use cases? 

Keep in mind policy creation requires transactions and we already have issue opened for this here: #1130, we are still in the process of evaluating if this is feasible as a module.

**Comment by wojtek0806** [comment]
closing this as duplicate
