### ISSUE TITLE
Other solution than bigip_dns_record to create new DNS record (CNAME)

### ISSUE THREAD

**Issue by NyoTheNeko** [F5Networks/f5-ansible#1317]
##### ISSUE TYPE

 - Question

##### COMPONENT NAME

bigip_dns_record

##### ANSIBLE VERSION

```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### SUMMARY

Seeing as tis is more of a question than a real issue, I am simplifying this form a bit.

I have searched through the Ansible modules and through the F5 documentation and have found the bigip_dns_record module. With a bit more research, I found the issues here on GitHub and, as I understand, this module does not exist anymore and development on this module has been discontinued. 
Due to this, I also searched for any other way to automate this through command line or REST, but as I understand it, the Zonerunner is not accessible through tmsh nor REST API (most questions around this were from 2017 and before, so maybe I missed something that was created since then?).

I have to say I find it weird that there would be no way to automate the creation of a CNAME (or a DNS record) through Ansible (or any other way really) and suppose that there is a way to do it, but that I could not find it through a Google search. As such, I would like to ask how I could automate the creation of a DNS record (specifically CNAMEs), whatever the way (PowerShell, command line, Ansible, REST API, I don't care really).

Thank you in advance for your time.

**Comment by wojtek0806** [comment]
Unfortunately this has been asked, and there is no other way of getting this automated as there are no REST endpoints or TMSH as zone runner is a separate binary: 
```
# which zrd

/usr/local/bin/zrd

# file /usr/local/bin/zrd

/usr/local/bin/zrd: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped
```
You can try writing your bash scripts and execute them on BIGIP, but this is beyond what we can help with.
