### ISSUE TITLE
Issue https://github.com/F5Networks/f5-ansible/issues/1314 Reopen

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#1329]
ISSUE # 1314 SHOULD NOT BE CLOSED - BUG STILL PRESENT

Notes added to the parent issue, please flag back to Open and close this reference.

https://github.com/F5Networks/f5-ansible/issues/1314

##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### ROLE VERSION

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
no need to open new issues, a note in the closed issue is enough
