### ISSUE TITLE
Feature request: add/modify/install crl

### ISSUE THREAD

**Issue by ishuguru** [F5Networks/f5-ansible#1351]
##### ISSUE TYPE

 - Feature Idea

```

Not sure if this is already possible, but cant find any modules for it. But it would be good to be able to add/remove/import crl list.

**Comment by wojtek0806** [comment]
please provide more information on this feature, what tmsh commands you use, gui options, if this exists in REST api we will most likely implement it

**Comment by ishuguru** [comment]
Ok.


Today it is possible to install new certificates with ansible module bigip_ssl_certificate. We would like to have the same feature but with Certificate revocation list installation.With Ansible 2.8 it is possible to modify client-ssl profile with a number of different CRL options so this feels like a feature that need to be implemented. In the meantime it can be solved by first uploading the crl file to local storage. Then use bigip command module like this:bigip_command: commands: create sys file ssl-crl crl_bundle_name source-path file:/shared/tmp/crl_file_temp.pem



![crl](https://user-images.githubusercontent.com/39456041/58812103-6b139900-8621-11e9-8a1f-2893bc3c568c.PNG)

![crl2](https://user-images.githubusercontent.com/39456041/58812192-99917400-8621-11e9-90bc-1106127ffde3.PNG)

**Comment by focrensh** [comment]
Thanks for the information. FMFA-272 opened for internal tracking.

**Comment by ishuguru** [comment]
Any news regarding this?

**Comment by dbarreda** [comment]
There is any update on this? For the time being there is a way to do this thru the API?

**Comment by focrensh** [comment]
This item is still working its way through the backlog. 

Here is the API for it: https://clouddocs.f5.com/api/icontrol-rest/APIRef_tm_sys_crypto_crl.html

**Comment by olanystrom** [comment]
Any news on this?
Or is AS3 the way forward for requests like this?

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
