### ISSUE TITLE
bigip_gtm_topology_region missing subnet ?

### ISSUE THREAD

**Issue by markatdxb** [F5Networks/f5-ansible#1355]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_gtm_topology_region

##### ANSIBLE VERSION

```
ansible 2.8.0
 ```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
12.x
```

##### ROLE VERSION

```

```

##### SUMMARY

https://docs.ansible.com/ansible/latest/modules/bigip_gtm_topology_region_module.html#bigip-gtm-topology-region-manages-gtm-topology-regions
In Ansible manual is missing the option to add subnet to region - this is possible to add in F5 GUI configuration. Is it a bug in documentation or this option is missing in module ?

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking under FMFA-271

**Comment by markatdxb** [comment]
Hello, many thanks for fixing this !!!  
As Im fairly new here and dont really know how the process works, so i wanted to ask if there is any way how to get the updated module or do we need it to wait till 2.9 is out  ?

**Comment by focrensh** [comment]
Easiest way is to leverage our Galaxy Role. Follow the steps in the readme here:
https://galaxy.ansible.com/f5devcentral/f5ansible

**Comment by markatdxb** [comment]
hi sorry bothering again
role works as expected on Ansible

would you happen to know how to configure AWX requirements.yml file in
order to make this role running under AWX?
sorry im bit novice to git

thanks
marek
