### ISSUE TITLE
[RFE] deploy iApp with deployment options

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#137]
##### ISSUE TYPE
 - Feature Idea
##### COMPONENT NAME
bigip_iapp_service
##### SUMMARY
Hi

When deploying iApps within the BIG-IP it is possible to use the following options:

- ~~description~~
- ~~metadata~~
- ~~traffic-group~~
- ~~device-group~~
- ~~strict-updates~~ (See comment below)

Some of these options are visible in the GUI when using the "Advanced view" or all of them with tmsh by typing

> create sys application service something/something \<type question mark\>

which shows the following help in v12.1.2:

```
Identifier:
  [object identifier]  Name of the application service
Properties:
  "{"                  Optional delimiter
  description          User defined description.
  device-group         The name of the device group that the application service is assigned to.
  lists                The set of list variables and values that are passed to template scripts.
  metadata             User defined generic data for the application service. It is a name and value pair. Specifies the encapsulation metadata to use for the application service.
  strict-updates       Specifies whether configuration objects contained in the application may be directly modified, outside the context of the system's application management interfaces.
  tables               The set of table variables and values that are passed to template scripts.
  template             The template defines the configuration for the application. This may be changed after the application has been created to move the application to a new template.
  traffic-group        The name of the traffic group that the application service is assigned to.
  variables            The set of atomic variables and values that are passed to template scripts.

```

All these have been available from the beginning maybe with the exception of the metadata option

**Comment by alonsocamaro** [comment]
Actually, another option that is not shown explicitly in the tmsh output above but should be also a must have is allow specifying the partition where the iApp service will be deployed.

**Comment by caphrim007** [comment]
strict updates is being added and tracked here https://github.com/F5Networks/f5-ansible/issues/359

**Comment by delgadillo22** [comment]
Nice to have

**Comment by caphrim007** [comment]
partition support should already exist, though i've now enhanced it to also check for the template in the correct location.
