### ISSUE TITLE
Log/tracebility of api calls from modules on the ltm

### ISSUE THREAD

**Issue by ishuguru** [F5Networks/f5-ansible#1383]
Maybe this is more of a ltm-api related question, but in is there any way to get logging for the apicalls on the f5? in ltm i see nothing of my api calls.

**Comment by wojtek0806** [comment]
ansible does not log these calls, these are found on the device:
`/var/log/restjavad.*`
If you need further assistance in this matter please contact F5 Support via the usual methods.
