### ISSUE TITLE
GTM DNS Record needs refactor

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#139]
Heath and Jay(F5) were asking for this to be completed.

**Comment by BradFelmey** [comment]
Is there a particular ${DEITY} that could be sacrificed to in order to get this module ready for prime time?

**Comment by caphrim007** [comment]
@BradFelmey is this ZoneRunner?

**Comment by BradFelmey** [comment]
@caphrim007 Yes, sir, ZoneRunner on GTMs is what we use and are looking for an Ansible module to manage the entries of.

**Comment by caphrim007** [comment]
closing based on feedback from @delgadillo22

**Comment by BradFelmey** [comment]
So this is being closed as... what? Done? Not done? Never going to be done?

**Comment by delgadillo22** [comment]
Closed -- not going to implement this request. Account team will work some potential solutions with you. Kevin (Principal Product Manager)
