### ISSUE TITLE
module request for lsn-pool

### ISSUE THREAD

**Issue by 4Igit** [F5Networks/f5-ansible#1393]
##### ISSUE TYPE

 - Feature Idea

##### BIGIP VERSION

```
12.1
```

##### SUMMARY

I would like to use ansible for managing the "lsn-pool" that I use on AFM.
I didn't find any dedicated module for that, so as a workaround I'm using the bigip_command module.

##### STEPS TO REPRODUCE

```
modify ltm lsn-pool <pool_name> members ...
```

##### EXPECTED RESULTS

Having an idempotent module.

##### ACTUAL RESULTS

[WARNING]: Using "write" commands is not idempotent. You should use a module that is specifically made for
that. If such a module does not exist, then please file a bug. The command in question is "modify ltm lsn-
pool PoolName memb..."

```

```

**Comment by wojtek0806** [comment]
FMFA-302
