### ISSUE TITLE
Add health mornitor when creating GTM virtual server (bigip_gtm_virtual_server)

### ISSUE THREAD

**Issue by insidepacket** [F5Networks/f5-ansible#141]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Add health mornitor when creating GTM virtual server (bigip_gtm_virtual_server)

##### ANSIBLE VERSION
Version 2.3

##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016

**Comment by caphrim007** [comment]
agreed. this module needs a REST refactor though before this can happen. @wojtek0806 likes work, maybe he can field that refactor as well.

**Comment by insidepacket** [comment]
@caphrim007 , thank you very much for your update! Any ETA?

**Comment by caphrim007** [comment]
@insidepacket 

I believe this can make it into Ansible 2.4. The gtm pool module has been refactored already, so it should not be a stretch to refactor the GTM virtual server module.

Ansible 2.4 is still some time off though (august/sept timeframe). So I think we can get the GTM VS module finished sometime in the next month provided that other fires do not come up at work that distract me from that.

**Comment by insidepacket** [comment]
Thanks

**Comment by caphrim007** [comment]
@insidepacket this is complete. closing
