### ISSUE TITLE
bigip_policy_rule - enable asm_policy with conditions

### ISSUE THREAD

**Issue by dse002** [F5Networks/f5-ansible#1413]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_policy_rule

##### ANSIBLE VERSION

```
2.8.0
```

##### PYTHON VERSION

```
2.7.5
```

##### BIGIP VERSION

```
13.1.1.5
```

##### ROLE VERSION

```

```

##### SUMMARY

I would like to create a policy with conditions _http_host_ and _http_uri_ and actions _forward to pool_ and _enable asm_policy_. However, the module only allows _enable asm_policy_ under condition _all_traffic_. 

Why is that? Manually, via the GUI, this is possible.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
This appears to be related to the to the final condition of when to apply a condition or action which is something the module does not allow editing currently.


Defaults: `create ltm policy p1 { rules add { r1 { conditions add { 0 { http-uri path contains values  { 123 } proxy-connect }} actions add { 0 { asm enable policy np client-accepted } } }}}`


Request Time: `create ltm policy p1 { rules add { r1 { conditions add { 0 { http-uri path contains values  { 123 } request }} actions add { 0 { asm enable policy np request } } }}}`

I opened FMFA-305 internally for this RFE.

**Comment by dse002** [comment]
Ah ok, sounds plausible. Would be great if I'd be able to do this. We use this quite often to choose a different policy for a certain URI.
