### ISSUE TITLE
Module to change active volume

### ISSUE THREAD

**Issue by assareh** [F5Networks/f5-ansible#1419]
Currently, there’s the bigip_software_image task to manage images & hotfixes. There’s the bipgip_software_install task to install images & hotfixes onto a volume.
 
But I don’t see a bigip_software_volume task to manage the volumes themselves.
 
For example, we may want to switch between volumes by marking one volume as the active one and rebooting.

The context is performing a TMOS version upgrade. Following the upgrade we'd like to reboot into the new version.

**Comment by assareh** [comment]
Another great use case would be to clean up old volumes.
 
Some of our LTMs have been through several upgrade cycles. I’d like run a playbook to remove old, obsolete volumes.
 
I can certainly do that using the bigip_device_facts task to enumerate the volumes and then the bigip_command task to remove them.
 
Ideally, though, there should be a bigip_software_volume task to perform the removal (state: absent).

**Comment by focrensh** [comment]
Tracked with FMFA-307

**Comment by focrensh** [comment]
Using imperative commands is best for this type of action. Please reopen if you are not able to achieve this through creating a role/playbook.
