### ISSUE TITLE
Add health mornitor when creating GTM pool

### ISSUE THREAD

**Issue by insidepacket** [F5Networks/f5-ansible#142]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Add health mornitor when creating GTM pool (bigip_gtm_pool.py)

##### ANSIBLE VERSION
Version 2.3

##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016

**Comment by caphrim007** [comment]
agreed.

This module needs a refactor before this can be done though. I am almost finished with said refactor.

**Comment by insidepacket** [comment]
@caphrim007 , thank you very much for your udpate! Any ETA?

**Comment by caphrim007** [comment]
@insidepacket 

Since this module is now refactored, I think work can begin on this shortly. I think it's reasonable to expect that this feature would be completed before the GTM virtual server feature, and therefore also make it into Ansible 2.4

**Comment by insidepacket** [comment]
@caphrim007 thanks!
