### ISSUE TITLE
bigip_gtm_topology_region - create facts module

### ISSUE THREAD

**Issue by markatdxb** [F5Networks/f5-ansible#1423]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_gtm_topology_region

##### ANSIBLE VERSION

```
2.8.2
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### ROLE VERSION

```

```

##### SUMMARY

There is not an easy way to obtain the list of Topology regions from BigIP. Would be great to have a facts module which could pull that information
We want to automate management of topology regions by syncing the information from external source to BigIP.  
Currently we are able to add new regions with -present option.
But we are unable to remove the regions which dont exists anymore as we cant pull the current list of regions from F5 to compare with new configuration. 

Interim proposed solution was to use REST but having module would be proffered.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
FMFA-320
