### ISSUE TITLE
More info about deprecation

### ISSUE THREAD

**Issue by jmurphyau** [F5Networks/f5-ansible#1451]
I've just run into this warning
```
Specifying 'message-routing' profiles on a 'standard' type is deprecated and will be removed
```
From this code:
https://github.com/F5Networks/f5-ansible/blob/031673abfbbefe5d942e64beda69484dd0c809bb/library/modules/bigip_virtual_server.py#L2562-L2567

I'm just interested in understanding why this will not be supported? SIP profiles are valid on F5 standard virtual server types - it allows the iRule to trigger on SIP messages

**Comment by wojtek0806** [comment]
I would disregard this , as this piece of code is removed in 2.9

**Comment by jmurphyau** [comment]
I actually asked why this was removed - that was the question.. I'm not sure what 'I disagree with that' is referring to?

Given SIP profiles are valid on standard virtual servers, the change/removal didn't make sense and I wanted to know why it was removed even though it's a valid setup

**Comment by wojtek0806** [comment]
like i said nothing will be changed, this was a mistake, VS used to be default fastl4 and that was changed to standard, so to ease the transition this function was introduced:
https://github.com/F5Networks/f5-ansible/blob/031673abfbbefe5d942e64beda69484dd0c809bb/library/modules/bigip_virtual_server.py#L2459

it will be removed in 2.9 so you can still use SIP on standard VS.

**Comment by jmurphyau** [comment]
OH! Sorry - I've mis understood your comment.

Thanks for this feedback!

**Comment by jmurphyau** [comment]
Hi

It seems like this code has made it into the repo

https://github.com/F5Networks/f5-ansible/blob/fdabd68c1c45e4de2bcd981ced0439c1b8facfa0/library/modules/bigip_virtual_server.py#L2766

**Comment by jmurphyau** [comment]
I've manually copied the virtual_server module code into my ansible directory and commented this out - but then I run into further issues. I'm able to create a `standard` virtual server but then when I run the task a second time it thinks I want to change the `type` to `message-routing` and errors

These lines seem responsible:

https://github.com/F5Networks/f5-ansible/blob/fdabd68c1c45e4de2bcd981ced0439c1b8facfa0/library/modules/bigip_virtual_server.py#L1386-L1387
