### ISSUE TITLE
Create module to manipulate device interface settings

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible#1453]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
LLDP

##### SUMMARY
It would be great to have a module that would allow complete configuration of lldp - both global and interface settings.

Following parts of TMOS configuration should be configurable:
```
net lldp-globals
net interface (<ifname> or "all">)  lldp-admin lldp-tlvmap
```

**Comment by wojtek0806** [comment]
this requires 2 new modules:
- a module that allows modifying network interfaces on device, as far as i know you cannot create 'interfaces' on BIGIP so this module would only run updates on existing interfaces
- a network globals module that encompass the following:
  - /mgmt/tm/net/stp-globals
  - /mgmt/tm/net/multicast-globals
  - /mgmt/tm/net/dag-globals
  - /mgmt/tm/net/lldp-globals

**Comment by wojtek0806** [comment]
tracked under FMFA-345
