### ISSUE TITLE
Feature request: SSL Cipher groups

### ISSUE THREAD

**Issue by VeselaHouba** [F5Networks/f5-ansible#1483]
Hi,
Do you think about implementing SSL Cipher groups assignment into client ssl profile? 
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_profile_client_ssl.py

And possibly also definition of the groups via ansible.

I know I should create a pull request with the code, but with my programming skills it would probably end-up with F5 box burning down in flames ;)

//JM

**Comment by wojtek0806** [comment]
the fundamental question is are both of these achievable via REST api?

**Comment by wojtek0806** [comment]
FMFA-410
