### ISSUE TITLE
Create method for modifying ASM settings

### ISSUE THREAD

**Issue by yxeGithub** [F5Networks/f5-ansible#1485]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ASM Configuration Setting

##### ANSIBLE VERSION

```
ansible 2.7.5
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
13.1.0
```

##### ROLE VERSION

```
N/A
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I would like the ability to modify the ASM configuration settings as per https://support.f5.com/csp/article/K10803 . In a CI/CD deploying an F5 with ASM that will be used along with large file uploads need these settings changed.  It would be great to do this via ansible.
##### STEPS TO REPRODUCE

```
Cant reproduce - you need to ssh into the f5 and run the command:
long_request_buffer_size/usr/share/ts/bin/add_del_internal add <system variable name> <value in bytes>
and perhaps other variable changes and then restart ASM daemon
```

##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

```
N/A
```

**Comment by yxeGithub** [comment]
I have found the REST endpoints if that makes it easier:

**To get all the ASM settings:**
`curl --request GET \
  --url https://192.168.3.103/mgmt/tm/asm/advanced-settings \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: 1425f2de-6b7c-4f25-8540-fb893d6f8e84' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache'`

**The settings I am interested in are:**

1.   **Get to the ID for long_request_mem_percentage**
`curl --request GET \
  --url 'https://192.168.3.103/mgmt/tm/asm/advanced-settings?$filter=name+eq+long_request_mem_percentage&$select=id' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: fc8f5a2b-e214-468a-ba5b-6aeab1d32d60' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache`

**Get to get the current value**
curl --request GET \
  --url 'https://192.168.3.103/mgmt/tm/asm/advanced-settings/{{long_rq_mem_id}}?$select=value' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: b2e708d2-35c1-4c0f-a711-57ca80af0c1e' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache'

**Set the value**
`curl --request PATCH \
  --url 'https://192.168.3.103/mgmt/tm/asm/advanced-settings/{{long_rq_mem_id}}' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: c14307e8-6715-4189-8087-5681db4d0432' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache' \
  --data '{\n  "value": "30"\n}'`

2.   **Get the ID for long_request_buffer_size**
`curl --request GET \
  --url 'https://192.168.3.103/mgmt/tm/asm/advanced-settings?$filter=name+eq+long_request_buffer_size&$select=id' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: 5bb6175d-5c8b-4898-9daa-f5516fef0562' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache'`

**Get to get the current value**
`curl --request GET \
  --url 'https://192.168.3.103/mgmt/tm/asm/advanced-settings/{{long_rq_buff_sz}}?$select=value' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: 41dc55f6-6979-4653-a17b-3a1ffe7fd6dc' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache'`

**Set the value**
`curl --request PATCH \
  --url 'https://192.168.3.103/mgmt/tm/asm/advanced-settings/{{long_rq_mem_id}}' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: fdac656c-9781-464b-a8ff-4aaca93d0a50' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache' \
  --data '{\n  "value": "10"\n}'`

3.  **Now we need to restart ASM to get the settings to take**
`curl --request POST \
  --url https://192.168.3.103/mgmt/tm/util/bash \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Postman-Token: dac7248b-ba5f-46e2-8737-e74a9f97285b' \
  --header 'X-F5-Auth-Token: {{atoken_BIGIP_A}}' \
  --header 'cache-control: no-cache' \
  --data '{\n  "command": "run",\n  "utilCmdArgs": "-c '\''bigstart restart asm'\''"\n}'`

**Comment by wojtek0806** [comment]
tracked under FMFA-342
