### ISSUE TITLE
Question regarding official ltm modules

### ISSUE THREAD

**Issue by ishuguru** [F5Networks/f5-ansible#1504]
This is maybe more of a general question regarding ansible. But i can see some fixes that has been done is merged in the ansibel-devel (when i check on the ansible github page) But in ansible 2.8 some module that has been fixed is still the one from 6 month ago  (for example bigip_configsync_action) when are they being merged into the official 2.8?

**Comment by wojtek0806** [comment]
@ishuguru they will be released with ansible 2.9, we do not backport changes unfortunately.

**Comment by ishuguru** [comment]
Thanks for clarify. I wonder how the future will be for this kind of modules, i know that other vendors have stopped updating their offical modules and only pointing to ansible galaxy. Since it takes to long time to get fixes out the offical ansible way. 

I understand this, but i can tell you its much easier to sell automation to higher management when telling them that there is "official support" för certain modules.

**Comment by wojtek0806** [comment]
all of the vendors are moving towards ansible collections, the collections that will have modules and be hosted on the ansible automation hub will be officially supported.

**Comment by ishuguru** [comment]
Really interesting
