### ISSUE TITLE
Please update documentation on clouddocs.f5.com

### ISSUE THREAD

**Issue by rainierpineda2** [F5Networks/f5-ansible#1506]
I opened an F5 case but was referred to this site. The page is missing information for this link: https://clouddocs.f5.com/api/icontrol-soap/System__SystemInfo.html. Other pages within the icontrol-soap folder are ok.

**Comment by wojtek0806** [comment]
SOAP has been removed and is no longer supported, we will fix the doc fragments once the role is actually released @rainierpineda2
