### ISSUE TITLE
bigip_asm_policy_import does not maintain <parent_policy_name> definition on import

### ISSUE THREAD

**Issue by mbystrzak** [F5Networks/f5-ansible#1511]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- bigip_asm_policy_import

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tsaamb0/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```

##### PYTHON VERSION

```
Python 2.7.15+
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.1
  Build       0.0.4
  Edition     Point Release 1
  Date        Tue Sep 17 15:44:32 PDT 2019
```

##### CONFIGURATION

NO CHANGES TO ANSIBLE.CFG

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I'm attempting to use the bigip_asm_policy_import module to create a new ASM policy based on a standard_template.xml file which I use for the majority of new policies. This standard_template.xml file has a <parent_policy_name>/Common/parent</parent_policy_name> in it which defines the parent policy to be used. Additionally there are a bunch of inheritance settings further down in the xml file which define what should or shouldn't be inherited by the child. The goal is to assure that the parent policy is defined for the new policy.
When the playbook completes, which is successful in creating the new file, the asm policy has all of the correct attributes from the template file but does NOT have a parent profile assigned. I exported that policy and examined the XML to find that the <parent_policy_name>/Common/parent</parent_policy_name> did not persist through to the new policy. Similarly, none of the inheritance settings did either. They are all defaulted to NONE.
The parent_policy and retain_inheritance_settings are only available when using the inline mode which I don't really want to use if I don't have to. I believe this is a bug that should be addressed. 

##### STEPS TO REPRODUCE

```
  - name: Create ASM Policy
    bigip_asm_policy_import:
      provider: "{{ provider }}"
      name: MY_NEW_CHILD_POLICY
      source: "./path/to/your/exported_template.xml"
    delegate_to: localhost

```

##### EXPECTED RESULTS

 A new ASM policy "should" be created which is based off of your template file which inherits your parent profile called /Common/parent

##### ACTUAL RESULTS

A new policy is created, but the parent is not assigned and the inheritance settings are not defined. You can see, if you export the MY_NEW_CHILD_POLICY that the xml doesn't have the <parent_policy_name>/Common/parent</parent_policy_name>

```
N/A - I just get the expected play recap stating that the config was "changed"
```

**Comment by wojtek0806** [comment]
unfortunately you need to use inline for parent policy imports this is an api limitation

**Comment by mbystrzak** [comment]
I don't understand. I'm not trying to set the parent profile. I'm trying to import a policy that has the parent of the child defined. Isn't this just uploading the template.xml file that I specify and adding it to the ASM config? I'm confused how the API is removing part of my defined XML that I'm uploading.

**Comment by wojtek0806** [comment]
file import api endpoints do not have capability to define parents use inline imports.
