### ISSUE TITLE
Extend bigip_sys_global module

### ISSUE THREAD

**Issue by techoover** [F5Networks/f5-ansible#1515]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_sys_global
##### ANSIBLE VERSION

```
ansible --version
ansible 2.8.3

```

##### PYTHON VERSION

```
Python 2.7.15+
```

##### BIGIP VERSION

```
14.1.0.2  
```

##### SUMMARY

bigip_sys_global now offers only fraction of what is possible to configure via gui/tmsh
also there is module bigip_hostname but it would make sense to set hostname via bigip_sys_global to copy what tmsh does

on 14.1.2 tmsh can do the following
list sys global-settings
Options:
  all-properties                         non-default-properties                 one-line                               |
Properties:
  aws-access-key                         failsafe-action                        gui-security-banner                    lcd-display                            remote-host
  aws-api-max-concurrency                file-blacklist-path-prefix             gui-security-banner-text               led-locator                            username-prompt
  aws-secret-key                         file-blacklist-read-only-path-prefix   gui-setup                              mgmt-dhcp                              {
  console-inactivity-timeout             file-local-path-prefix                 host-addr-mode                         net-reboot
  custom-addr                            file-whitelist-path-prefix             hostname                               password-prompt
  description                            gui-audit                              hosts-allow-include                    quiet-boot

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by petman** [comment]
Hello, 

I have the same need. 
Can you implement these functions ? 

Regards

**Comment by wojtek0806** [comment]
FMFA-405

**Comment by focrensh** [comment]
@techoover and @petman ,

Of the listed features, do you have specific ones that are the most critical and in use within your environments? We would like to implement those first.

**Comment by techoover** [comment]
For me its:
console-inactivity-timeout         
gui-security-banner         
gui-security-banner-text    
gui-setup               
password-prompt
username-prompt

**Comment by petman** [comment]
For me its: 
global-settings service number

**Comment by jeffl2017** [comment]
For Federal Accounts we need access to:
sys/global-settings/failsafeAction

Also need: cli/global-settings/idleTimeout

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
