### ISSUE TITLE
Trailing comment blocks in iRules are not uploaded

### ISSUE THREAD

**Issue by Sam-Hall** [F5Networks/f5-ansible#1516]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_irule

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = None
  configured module search path = [u'/home/shall/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shall/venv/lib/python2.7/site-packages/ansible
  executable location = /home/shall/venv/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2
  Build       0.0.37
  Edition     Final
  Date        Wed Aug  7 09:56:44 PDT 2019
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
RHEL7.7

##### SUMMARY
If uploading an irule containing lines at the end that are commented out, the irule uploads without the trailing comments. That would be ok with me, except it keeps triggering "changed" state. Moving that block of comments above the last event in the irule is my current workaround.

##### STEPS TO REPRODUCE

```
  bigip_irule:
    provider: "{{ provider }}"
    name: "{{ item }}"
    module: "ltm"
    src: "irules/myrule.tcl"
    state: "present"
  delegate_to: localhost
```
Example irule:
```
when HTTP_REQUEST priority 200 {
    HTTP::respond 200 content {HELLO WORLD} "Content-Type" "text/plain" "Connection" "Close"
}

# Blah
# Blah
# Blah
```

##### EXPECTED RESULTS

I'd expect to see the comments make it up to the F5

##### ACTUAL RESULTS
iRule that appears on the F5...
```
when HTTP_REQUEST priority 200 {
    HTTP::respond 200 content {HELLO WORLD} "Content-Type" "text/plain" "Connection" "Close"
}
```

**Comment by wojtek0806** [comment]
@Sam-Hall 
Have you tried this with content parameter, i would be interested to see if the same thing happens when you specify the iRule content directly rather than loading from file.

**Comment by Sam-Hall** [comment]
Tried using content just now, it also excludes any trailing comments. Tested the content param using lookup from a file, a template and also a block of text. Trailing comment lines never make it to the F5 and status is always "changed" in such a case.

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
