### ISSUE TITLE
Develop Ansible Module to create custom ssl client profile in BigIP LTM

### ISSUE THREAD

**Issue by yk8511** [F5Networks/f5-ansible#152]
ISSUE TYPE
Feature Idea

COMPONENT NAME
Develop Ansible Module to create custom ssl client profile in BigIP LTM 

EXPECTED ATTRIBUTES OF MODULE
It will be nice to have following changeable parameters when creating client ssl profile
Name of the profile
Parent Profile (with clientssl as default value)
Certificate Key Chain (Key and Certificate name as mandatory parameters while Chain, Passphrase and OCSP Stapling as optional fields) 

ANSIBLE VERSION
Version 2.2

PYTHON VERSION
Python 2.7.5

BIGIP VERSION

Sys::Version
Main Package
Product BIG-IP
Version 12.1.0

**Comment by insidepacket** [comment]
we need server ssl profile as well.

**Comment by caphrim007** [comment]
@yk8511 @insidepacket what "passphrase" is being suggested above? I only see a "CA passphrase" in BIG-IP under the "SSL Forward Proxy"

**Comment by insidepacket** [comment]
passphrase to protect the key. please see the attached
![2017-11-05_211652](https://user-images.githubusercontent.com/16912024/32413890-b59ba9d6-c26e-11e7-98b1-8d0902fb388b.png)

**Comment by caphrim007** [comment]
@insidepacket ahh thanks for that reference

**Comment by holmahenkel** [comment]
A `passphrase` module parameter would be highly appreciated :-)

**Comment by caphrim007** [comment]
requires #498

**Comment by caphrim007** [comment]
OCSP stapling is a non-trivial addition to this request.

This is because configuration of OCSP stapling has **significantly** changed from 12.x to 13.x. I'm not sure if it has changed further in 14.x yet.

**Comment by caphrim007** [comment]
this feature (sans the ocsp stapling) should now be complete. I will open another issue for supporting ocsp stapling.

**Comment by caphrim007** [comment]
this is now upstreamed
