### ISSUE TITLE
Feature Request - bigip_software_install

### ISSUE THREAD

**Issue by binbashroot** [F5Networks/f5-ansible#1548]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_software_install
##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3
  Build       0.0.6
  Edition     Final
  Date        Fri Aug  2 20:39:15 PDT 2019
```

##### OS / ENVIRONMENT

RHEL7.7   and BIGIP 13.x

##### SUMMARY

Requesting the ability to copy the config from either the active volume (default) or a different volume to the newly installed software boot location when using the "state" is either activated or installed.  Maybe a "src_volume" flag??   As I'm not sure, but I believe the tmsh command for this would be something along the lines of.  

cpcfg --source=HD1.1 --reboot HD1.4

GUI  configuration would be
System > Software Management > Boot Locations > HD1.x Install configuration (yes) > source volume

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by wojtek0806** [comment]
we might include this in a future role that manages volumes, but this will not be implemented in the module
