### ISSUE TITLE
bigip_device_info ipv6 netmask error

### ISSUE THREAD

**Issue by nitinthewiz** [F5Networks/f5-ansible#1563]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

bigip_device_info

##### ANSIBLE VERSION

```
ansible 2.10.0.dev0
  config file = /root/nitin_ansible.cfg
  configured module search path = ['/root/f5-ansible/library/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

##### PYTHON VERSION

```
Python 3.6.8
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Tue Nov  5 10:09:50 PST 2019
```

##### SUMMARY

The bigip_device_info (bigip_device_facts in ansible 2.8) module fails to gather self IPs if the BIG-IP system has IPv6 self IPs with a netmask larger than /32 (e.g. a /64), and generates nonsense results if a BIG-IP system has IPv6 self IPs with a netmask of /32 or lower.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by nahun** [comment]
Will a fix for this go into 2.9 at some point or only 2.10?
