### ISSUE TITLE
GTM Wide IP Looping Through Adding Members

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1598]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_gtm_wide_ip

##### ANSIBLE VERSION

```
ansible 2.9.2
```

##### BIGIP VERSION

```
14.1.0.3
```

##### SUMMARY

When adding new pool members to the Wide IP, all poll members have to be listed every time. This prevents loops from working as the last member in the loop is the only one that is added. Would be nice if this functioned the same as LTM Pool Members.

**Comment by wojtek0806** [comment]
this sounds like a bug 
FMFA - 414

**Comment by DerrickTJ** [comment]
Oh? Would you like me to provide some more outputs then?

**Comment by wojtek0806** [comment]
i will test to verify no need, if this is not a bug then this could be down to the fact that lists in REST API are replace all with and due idempotency issues we follow the same pattern where we override what is on device with whatever the user gives us. The bigip_pool_member module you mentioned has its own distinct API and is a sub-collection of bigip_pool , whereas the pool in bigip_gtm_wide_ip is an array.

**Comment by wojtek0806** [comment]
@DerrickTJ after looking into this further, I am afraid we will have to decline this request, WideIP pools are not the same as LTM pools, for the reason I have explained above. The pools for wide IP in REST api are arrays (lists) with objects (dictionaries),  the objects contain a number of parameters, this adds to the complexity, adding any kind of logic to support atomic removal of array items will cause idempotency edge cases and is not scalable. All lists in f5 modules are replace-all, that means if there is a difference between what user provided and what is on device, we always favor user's input. I believe bigip_device_info module returns wide-ip pool information for you which you can use to reduce repeating what is on the device already.

**Comment by DerrickTJ** [comment]
:( Understood. Thanks for looking.
