### ISSUE TITLE
Module Template

### ISSUE THREAD

**Issue by buzzsurfr** [F5Networks/f5-ansible#16]
Between different versions of BIG-IP, SOAP/REST, and differing python modules--it's difficult to determine where to start writing a new module.  There's different versions of the module framework present throughout the modules.

There needs to be a template to distinguish how to tie all the components together, and separate some of the logic between the API call and the method used.  Possibly include a guidelines page to determine whether a feature meets the criteria for using one template over another (e.g. a feature in SOAP not in REST, etc.).

**Comment by buzzsurfr** [comment]
Also, I did see [GUIDELINES.md](https://github.com/F5Networks/f5-ansible/blob/master/GUIDELINES.md), but I think we should expand to include the full framework (DOCUMENTATION, EXAMPLES, RETURN, the classes, etc.)

**Comment by caphrim007** [comment]
@buzzsurfr lemme know if these are sufficient

https://f5-ansible.readthedocs.io/en/latest/development/guidelines.html

and

https://f5-ansible.readthedocs.io/en/latest/development/writing-a-module.html

**Comment by buzzsurfr** [comment]
@caphrim007 the latter, specifically.  Thanks!

**Comment by caphrim007** [comment]
I have to add some more steps concerning the testing bits and fix some formatting but I think the meat of it is there
