### ISSUE TITLE
f5networks.f5_modules v1.1.0 won't install

### ISSUE THREAD

**Issue by sbyount** [F5Networks/f5-ansible#1605]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
f5networks.f5_modules

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /Users/zg46503/STRATOS/ansible-testing/ansible.cfg
  configured module search path = ['/Users/zg46503/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/zg46503/STRATOS/ansible-testing/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/zg46503/STRATOS/ansible-testing/venv/bin/ansible
  python version = 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) [Clang 6.0 (clang-600.0.57)]
```

##### PYTHON VERSION

```
Python 3.7.3
```

##### BIGIP VERSION

```
N/A for this issue
```

##### SUMMARY
Collection will not install.  I have v1.0.0 installed and am trying to upgrade to 1.1.0.

##### STEPS TO REPRODUCE
ansible-galaxy collection install -c f5networks.f5_modules:==1.1.0

##### EXPECTED RESULTS
Updated collection

##### ACTUAL RESULTS
ERROR! Cannot meet requirement f5networks.f5_modules:==1.1.0 as it is already installed at version '1.0.0'. Use --force-with-deps to overwrite

**Comment by wojtek0806** [comment]
you need to use the command that the error message is giving you:
```
└─▪ ansible-galaxy collection install -c f5networks.f5_modules --force-with-deps
Process install dependency map
Starting collection install process
Installing 'f5networks.f5_modules:1.1.0' to '/redacted/redacted/Work/collections/ansible_collections/f5networks/f5_modules'
```
