### ISSUE TITLE
Ansible Module required to manage Profiles WebAccelearion

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1606]
##### ISSUE TYPE
 - Feature Idea
##### ANSIBLE VERSION
2.9.2
##### PYTHON VERSION
Python 2.7.5
##### BIGIP VERSION
Version > 13
##### OS / ENVIRONMENT
Rhel7
##### SUMMARY
Request a ansible module to manage webacceleration profiles.
Actually the non-idempotent bigip_command module is used.

##### STEPS TO REPRODUCE
# Example create webacceleration profile
    - name: Create webacceleration
      delegate_to: localhost
      bigip_command:
       provider: "{{ provider }}"
       commands:
         - create ltm profile web-acceleration webacceleration

**Comment by focrensh** [comment]
Tracking with FMFA-451

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
