### ISSUE TITLE
[New Module] like  bigip_ltm_ifile

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1621]
ISSUE TYPE
Feature Idea

COMPONENT NAME
New module like bigip_ltm_ifile.py

ANSIBLE VERSION
ansible 2.9.4

PYTHON VERSION
Python 2.7.5 or +

BIGIP VERSION
13+

SUMMARY
New module like bigip_ltm_ifile.py 

STEPS TO REPRODUCE
I need to create a reference betweek an uploaded ifiles and an irules.

The command provided by F5 in cli is like following : 
list sys file ifile "ifiles_name"

I have found some references on internet here: 

- https://gitmemory.com/issue/F5Networks/f5-ansible/1387/527176965
- https://github.com/erjac77/ansible-module-f5bigip/blob/master/library/f5bigip_ltm_ifile.py

Can you improve this function officially ?

Regards

**Comment by focrensh** [comment]
Created internal ticket to create association after file has been uploaded.

Tracking with FMFA-449.

**Comment by olanystrom** [comment]
I vote for this feature also.

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
