### ISSUE TITLE
[Bug] on bigip_static_route module

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1622]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_static_route

##### ANSIBLE VERSION
2.9.4

##### PYTHON VERSION
2.7
/usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_static_route.py

##### BIGIP VERSION
13+
##### CONFIGURATION
no modification

##### OS / ENVIRONMENT
centos 7.7

##### SUMMARY
The module bigip_static_route return a bad information but the job is done.
 

##### STEPS TO REPRODUCE
Below an example about my role configuration. Without variables usage, the behaviour is the same (like below)
The route is created on the F5 with the same parameters, but ansible return changed=yes. 
```
- name: Verify routes
  bigip_static_route:
    name:            "Default"
    partition:       "Partition_EXAMPLE"
    gateway_address: "1.1.1.x"
    destination:     "0.0.0.0"
    netmask:         "0.0.0.0"
    provider:        "{{ provider }}"
```
The error is provided by gateway_address parameters. When I put in comments it the execution return done without change.

##### EXPECTED RESULTS
I want to have an ok return when there is no change apply on f5.

##### ACTUAL RESULTS
```
changed: [hostname] => {
    "changed": true,
    "gateway_address": "x.x.x.y",
    "invocation": {
        "module_args": {
            "description": null,
            "destination": "0.0.0.0",
            "gateway_address": "x.x.x.y",
            "mtu": null,
            "name": "Default",
            "netmask": "0.0.0.0",
            "partition": "Partition_EXAMPLE",
            "pool": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "x.x.x.x",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "USERNAME",
                "validate_certs": false
            },
            "reject": null,
            "route_domain": null,
            "state": "present",
            "vlan": null
        }
    }
}

```

**Comment by wojtek0806** [comment]
@petman so when you run your example task two times, the second time it runs it also reports changed? is that what you are saying?

**Comment by petman** [comment]
Yes, it is the issue

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version. Re-open if you still face the issue, thanks!
