### ISSUE TITLE
Module for modify sys httpd ssl-certchainfile

### ISSUE THREAD

**Issue by Ezeon** [F5Networks/f5-ansible#1626]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_device_httpd

##### SUMMARY
I'm not currently able to set the ssl-certchainfile using idempotent Ansible modules. Without the certificate chain the Big-IP web gui will give a certificate warning to the user.

This can be modified via the bigip_command module, but that is not idempotent.
- name: Set SSL-CertChainFile
  bigip_command:
    commands:
      - 'modify sys httpd ssl-certchainfile /etc/httpd/conf/ssl.crt/server-chain.crt'

This option could be added to the bigip_device_httpd module.

**Comment by 1080dpi** [comment]
Hello, 
Do you have any news regarding this feature ? 
We need to update WebGUI SSL Cert for 200 devices or more... So this feature should be great for this job !
Regards,

**Comment by trinaths** [comment]
@Ezeon @1080dpi  Suggest use V2 collection for your requirement with AS3. See the AS3 declaration examples. https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html
