### ISSUE TITLE
bigip_monitor_oracle module does not exist

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1632]
ISSUE TYPE
Feature Idea

ANSIBLE VERSION
2.9.2

PYTHON VERSION
Python 2.7.5

BIGIP VERSION
Version > 13

CONFIGURATION
OS / ENVIRONMENT
Rhel7

SUMMARY
Request a ansible module to manage bigip_monitor_oracle.

Could you add this module developpment in the roadmap ? 

Regards

**Comment by focrensh** [comment]
Tracking with FMFA-432

**Comment by focrensh** [comment]
Aiming to be in the daily build of our collection in ~1 month.
