### ISSUE TITLE
bigip_monitor_smtp module does not exist

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1633]
ISSUE TYPE
Feature Idea

ANSIBLE VERSION
2.9.2

PYTHON VERSION
Python 2.7.5

BIGIP VERSION
Version > 13

CONFIGURATION
OS / ENVIRONMENT
Rhel7

SUMMARY
Request a ansible module to manage bigip_monitor_smtp.

Could you add this module developpment in the roadmap ?

Regards

**Comment by focrensh** [comment]
Module already exists:

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_monitor_smtp_module.html#bigip-monitor-smtp-module

**Comment by petman** [comment]
> Module already exists:
> 
> https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_monitor_smtp_module.html#bigip-monitor-smtp-module

Hello, 

Sorry, I see the docs on F5 website. but not on https://docs.ansible.com/

With the command ansible-console I can't see the availability module bigip_monitor_smtp 

only bigip_monitor_snmp_dca.

My ansible is 2.9.4. 

Perhaps the module is not publicated ? 

Regards

**Comment by wojtek0806** [comment]
ansible no longer accepts modules into the core, please read readme file on the main repo page
