### ISSUE TITLE
bigip_monitor_tcp parameter module 

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1639]
ISSUE TYPE
Feature Idea

ANSIBLE VERSION
2.9.2

PYTHON VERSION
Python 2.7.5

BIGIP VERSION
Version > 13

CONFIGURATION
OS / ENVIRONMENT
Rhel7

SUMMARY
Request a ansible paramter for module bigip_monitor_tcp.

The options 'Alias Address' and 'Alias Service Port' is not available.

Could you add these parameters in the roadmap developpment?

Regards

**Comment by focrensh** [comment]
Tracking with FMFA-433

**Comment by focrensh** [comment]
Quick update, this will be in our next release in ~2weeks.

**Comment by focrensh** [comment]
This was released in our 1.2.1 Collection 

https://galaxy.ansible.com/f5networks/f5_modules
