### ISSUE TITLE
New Module Ansible BIG-IP Remote Console

### ISSUE THREAD

**Issue by gitmikex** [F5Networks/f5-ansible#1651]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ansible_big-ip_remote_console

##### ANSIBLE VERSION

```
2.8 and above
```

##### PYTHON VERSION

```
2.7 and above
```

##### BIGIP VERSION

```
13.1 and above
```

##### SUMMARY

Normally for the hardware bootstrap process, including configuring management IP address/subnet and gateway on a brand new box, one has to manually connect to console port and enter commands.

##### STEPS TO REPRODUCE

```
https://github.com/fortinetps/ansible_fortigate_remote_console/blob/master/library/fortigate_remote_console.py
```

##### EXPECTED RESULTS

  | - For physical appliance and VIPRION chassis/blade with serial console port
  | - This module should work for device WITHOUT network connection, but with remote console connection (OOB)
  | - Should be able to work with terminal servers that support SSH, such as "Vertiv Avocent"
  | - Should be able to use this module to assign management IP/Subnet/GW on a brand new BIG-IP
  | - Should be able to use this module to bootstrap brand new BIG-IP
  | - Should be able to use this module to factory reset BIG-IP
  | - Should be able to use this module to perform low level disk operation

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Thank you for opening this issue. Control over remote console servers is not currently in scope for the F5 Modules roadmap as each server would require its own testing. Please check the Pexpect module for handling console server requirements.

https://docs.ansible.com/ansible/latest/modules/expect_module.html
