### ISSUE TITLE
bigip_syslog now fails with requested host () is invalid for host

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-ansible#1652]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_remote_syslog
##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /c/Users/sxw455/Ubuntu/.ansible.cfg
  configured module search path = ['/c/Users/sxw455/Ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /c/Users/sxw455/Ubuntu/.local/lib/python3.8/site-packages/ansible
  executable location = /c/Users/sxw455/Ubuntu/.local/bin/ansible
  python version = 3.8.0 (default, Oct 28 2019, 16:14:01) [GCC 8.3.0]
```

##### PYTHON VERSION

```
Python 3.8.0
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.1
  Build       0.99.4
  Edition     Engineering Hotfix
  Date        Thu Oct 31 04:27:27 PDT 2019

Hotfix List
ID785741-1    ID838297-1  ID806093-1  ID762385

```

##### CONFIGURATION

```
[defaults]
retry_files_enabled = False
roles_path = ~/.ansible/roles
collections_paths = ~/.ansible/collections
inventory = ~/git/Ansible-F5/Inventory/Inventory.yaml
host_key_checking = False
private_key_file = /c/Users/sxw455/Ubuntu/.ssh/Ansible
remote_user = admin
deprecation_warnings=False
display_skipped_hosts = false
bin_ansible_callbacks = True
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

This code used to work with the most recently published Dev branch, but fails on the collection released with 2.9.4 with the following error:  "msg": "01070911:3: The requested host () is invalid for host in /Common/syslog remote_server (/Common/Splunk1)"

##### STEPS TO REPRODUCE

```
https://gist.github.com/C0missar/805d229417d4fce2806971b254d868fb
```

##### EXPECTED RESULTS

```
That two servers would be added as Syslog destinations:

        {
            "name": "Splunk1",
            "remote_host": "10.140.5.182",
            "remote_port": 514
        },
        {
            "name": "Splunk2",
            "remote_host": "10.20.58.168",
            "remote_port": 514
        }
```

##### ACTUAL RESULTS

```
See Gist
```

**Comment by C0missar** [comment]
Found a workaround, but there is a bug in the module.  If you attempt to add a syslog remote host with a different name but the same IP as an existing remote host, it fails.  This works via TMSH.

The module should allow this condition, otherwise the module cannot be used to do adds without a great deal of additional code to read existing values and compare IPs against each item to be added.

The alternative is to delete all existing values, but there is no function for that with the module; they must be enumerated individually.

 For this and most other modules, my playbooks issue a bigip_command with the equivalent TMSH "delete" first, although having done that, it makes the module call fairly pointless, since one could just as easily issue a single tmsh command to replace the module call.

A flag implementing a delete all and/or the equivalent of the TMSH "replace-all-with" function for this and most other bigip modules would help a lot, as would insuring that any valid TMSH value combination would also work via the module call.

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!
