### ISSUE TITLE
bigip_profile_fastl4 parameter module

### ISSUE THREAD

**Issue by petman** [F5Networks/f5-ansible#1657]
ISSUE TYPE
Feature Idea

ANSIBLE VERSION
2.9.2

PYTHON VERSION
Python 2.7.5

BIGIP VERSION
Version > 13

CONFIGURATION
OS / ENVIRONMENT
Rhel7

SUMMARY
Request a ansible paramter for module bigip_profile_fastl4.

I can't find the option 'PVA acceleration'. It seems that it is not available.

Could you add this parameter in the roadmap developpment?

Regards

**Comment by focrensh** [comment]
To make sure we get the exact feature you are looking for please provide the TMSH/API call for the parameter you are looking to toggle.

**Comment by petman** [comment]
You can find the command below :

modify ltm profile fastl4  Profil_fastL4_name  pva-acceleration [dedicated,default-value,full,none,partial]


Regards

**Comment by focrensh** [comment]
Tracking with FMFA-470
