### ISSUE TITLE
Feature Request: APM Policy Sync

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1659]
#### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Access > Profiles/ Policies > Policy Sync
Select the policy and "Sync Policy"
Add device group and description, then sync

##### SUMMARY
We use this on a config-sync only group of vCMPs. As this doesn't automatically sync up, would be nice to add this to the playbooks to sync the policy once it is done.

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
