### ISSUE TITLE
Feature Request - Include snat_pool configuration with Ansible device-info-module

### ISSUE THREAD

**Issue by lmailloux** [F5Networks/f5-ansible#1661]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

https://docs.ansible.com/ansible/latest/modules/bigip_device_info_module.html#bigip-device-info-module

##### ANSIBLE VERSION

```
ansible 2.9.2

  config file = None

  configured module search path = ['/bbnet/home/byu65/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']

  ansible python module location = /bb/netfun/lib/python3.7/site-packages/ansible

  executable location = /bb/netfun/bin/ansible

  python version = 3.7.5 (default, Jan 15 2020, 17:13:57) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

##### PYTHON VERSION

```
Python 3.7.5
```

##### BIGIP VERSION

```
14.1.2.3
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

The module is not pulling in snat_pool configuration on the VIP.  See example below where this VIP does have a snat_pool in the bigip.conf file.  But it does not show up in the Ansible output.

```

```

##### EXPECTED RESULTS

Expect to pull in the snat_pool configuration

##### ACTUAL RESULTS

```
"name": "vs-artifacts.bqnt.inf.bloomberg.com-443",
"nat64_enabled": "no",

"persistence_profile": "/Common/pf_persist_src_addr_artifacts.bqnt.inf.bloomberg.com-443",

"profiles": [

{

"context": "all",

"full_path": "/Common/pf_tcp_artifacts.bqnt.inf.bloomberg.com-443",

"name": "pf_tcp_artifacts.bqnt.inf.bloomberg.com-443"

}

],

"protocol": "tcp",

"rate_limit": -1,

"rate_limit_destination_mask": 0,

"rate_limit_mode": "object",

"rate_limit_source_mask": 0,

"software_syn_cookie_instances": 0,

"source_address": "0.0.0.0/0",

"source_port_behavior": "preserve",

"status_reason": "The children pool member(s) are down",
```

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
