### ISSUE TITLE
Feature Request: Add selective property to bigip_profile_http_compression

### ISSUE THREAD

**Issue by ksbarnt** [F5Networks/f5-ansible#1665]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- bigip_profile_http_compression

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### PYTHON VERSION

```
Python 3.6.8
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.5
  Build       0.0.4
  Edition     Point Release 5
  Date        Wed Apr 24 21:26:13 PDT 2019
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

We have an iRule that we apply to all HTTP(S) virtual servers that injects HTML into the response body in certain situations, which requires calling COMPRESS::disable, which in turn requires an HTTP Compression profile with Selective Compression enabled. This property is available in the iControl API, but isn't exposed in the Ansible modules at this point.

##### STEPS TO REPRODUCE

To create in tmsh:
```
create ltm profile http-compression HTTPCompression-Base-PF selective enabled
```

Proposed ansible equivalent:
```
bigip_profile_http_compression:
  name: HTTPCompression-Base-PF
  selective: enabled
```

`selective` would be an optional string property that accepts the values `enabled` and `disabled` (default)

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
