### ISSUE TITLE
"No JSON object could be decoded" when restoring UCS Configuration (bigip_ucs)

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [F5Networks/f5-ansible#1666]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_ucs

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /home/student1/.ansible.cfg
  configured module search path = [u'/home/student1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

tested on 2.9.3 as well with same issue
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018

```

##### SUMMARY
When backup and restoring the same UCS file to a BIG-IP i get the error "No JSON object could be decoded" even though the restore runs correctly.  

I take a backup then instantly restore it and i get this error, i have also seen it when there is other data on the BIG-IP the restoration works fine the execution of the code however creates this JSON error.

##### STEPS TO REPRODUCE

```
 - name: Download a new UCS
  bigip_ucs_fetch:
    src: Use-Case-00-Backup.ucs
    dest: "/tmp/Use-Case-00-Backup.ucs"
    provider: "{{provider}}"
  delegate_to: localhost

- name: Restore UCS From Backup
  bigip_ucs:
    ucs: "/tmp/Use-Case-00-Backup.ucs"
    state: installed
    no_license: yes
    provider: "{{provider}}"
  delegate_to: localhost
```

##### EXPECTED RESULTS

I expected an OK from this restoration as it was the same file from backup.

##### ACTUAL RESULTS

```
TASK [f5_restore_data : Restore UCS From Backup] *******************************************************************************************************************************************
task path: /home/student1/FAS-ansible-use-cases/00-Backup-Restore-Role/roles/f5_restore_data/tasks/f5_restore_config.yaml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: student1
<localhost> EXEC /bin/sh -c 'echo ~student1 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509 `" && echo ansible-tmp-1582913667.86-110774308874509="` echo /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_ucs.py
<localhost> PUT /home/student1/.ansible/tmp/ansible-local-24495TiUgs2/tmpgcEMFo TO /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509/AnsiballZ_bigip_ucs.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509/ /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509/AnsiballZ_bigip_ucs.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509/AnsiballZ_bigip_ucs.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/student1/.ansible/tmp/ansible-tmp-1582913667.86-110774308874509/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_ucs_payload_l_TfS4/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 711, in main
  File "/tmp/ansible_bigip_ucs_payload_l_TfS4/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 315, in exec_module
  File "/tmp/ansible_bigip_ucs_payload_l_TfS4/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 359, in exec_module
  File "/tmp/ansible_bigip_ucs_payload_l_TfS4/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 372, in present
  File "/tmp/ansible_bigip_ucs_payload_l_TfS4/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 385, in update
  File "/tmp/ansible_bigip_ucs_payload_l_TfS4/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 626, in install_on_device
fatal: [f5 -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      force: false
      include_chassis_level_config: null
      no_license: true
      no_platform_check: null
      passphrase: null
      provider:
        auth_provider: null
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: 172.16.140.107
        server_port: 8443
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: admin
        validate_certs: false
      reset_trust: null
      state: installed
      ucs: /tmp/Use-Case-00-Backup.ucs
  msg: No JSON object could be decoded
```

**Comment by VDI-Tech-Guy** [comment]
just to confirm even though i get the error, the restoration does complete, just the error occurs during the restoration process

**Comment by VDI-Tech-Guy** [comment]
Just an FYI the error did update from the previous to now

ASK [f5_restore_data : Restore UCS From Backup] ***********************************************************************************************************************************************************
task path: /home/student1/ansible-provisioner-usecases/00-Backup-Restore-Role/roles/f5_restore_data/tasks/f5_restore_config.yaml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: student1
<localhost> EXEC /bin/sh -c 'echo ~student1 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/student1/.ansible/tmp `"&& mkdir /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760 && echo ansible-tmp-1591031892.202336-24278-209141155273760="` echo /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_ucs.py
<localhost> PUT /home/student1/.ansible/tmp/ansible-local-24249qts7mmbw/tmpjmx9zzim TO /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760/AnsiballZ_bigip_ucs.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760/ /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760/AnsiballZ_bigip_ucs.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760/AnsiballZ_bigip_ucs.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/student1/.ansible/tmp/ansible-tmp-1591031892.202336-24278-209141155273760/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_bigip_ucs_payload_0q_f5m3i/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 711, in main
  File "/tmp/ansible_bigip_ucs_payload_0q_f5m3i/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 315, in exec_module
  File "/tmp/ansible_bigip_ucs_payload_0q_f5m3i/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 359, in exec_module
  File "/tmp/ansible_bigip_ucs_payload_0q_f5m3i/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 372, in present
  File "/tmp/ansible_bigip_ucs_payload_0q_f5m3i/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 385, in update
  File "/tmp/ansible_bigip_ucs_payload_0q_f5m3i/ansible_bigip_ucs_payload.zip/ansible/modules/network/f5/bigip_ucs.py", line 626, in install_on_device
fatal: [f5 -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      force: false
      include_chassis_level_config: null
      no_license: true
      no_platform_check: null
      passphrase: null
      provider:
        auth_provider: null
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: 172.16.54.85
        server_port: 8443
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: admin
        validate_certs: false
      reset_trust: null
      state: installed
      ucs: /tmp/UseCase-00-backup.ucs
  msg: 'Expecting value: line 1 column 1 (char 0)'
...ignoring
Read vars_file 'vars/f5_vars.yml'

Still does the restoration but the error occurring

**Comment by focrensh** [comment]
Are you defining your python interpreter for localhost? I see that you have python2.7 but are getting a python 3 error.

Just ran a test and did not hit an issue on 14.1. Can you try updating to the newest collection and ensuring that you are pointing to your python3 interpreter by default (supported) (which python3).

**Comment by focrensh** [comment]
I was able to reproduce on 13.1 myself. Tracking internally based on the ticket above.

**Comment by nitinthewiz** [comment]
After discussions and a thorough search for a solution, we've come to a conclusion that this is a known bug in BIG-IP v13.1 and below, as seen here.

The solution, for any other customers, if to add ignore_errors to their ansible playbook for the bigip_ucs task as follows - 
```
- name: Restore UCS From Backup
  bigip_ucs:
    ucs: "/path/to/file.ucs"
    state: installed
  ignore_errors: yes
```

Further, if a user wants to make this specific to versions of the BIG-IP lower than 13.1, they can do so as follows - 
```
- name: Collect BIG-IP facts
  bigip_device_info:
    include: system-info
  register: sysinfo

- name: Restore UCS From Backup and ignore errors
  bigip_ucs:
    ucs: "/path/to/file.ucs"
    state: installed
  ignore_errors: yes
  when: sysinfo.system_info.product_version <= "13.1.0"

- name: Restore UCS From Backup and don't ignore errors
  bigip_ucs:
    ucs: "/path/to/file.ucs"
    state: installed
  when: sysinfo.system_info.product_version > "13.1.0"
```
