### ISSUE TITLE
bigip_virtual_server Not Erroring On Duplicate Profiles

### ISSUE THREAD

**Issue by bradstapleton94** [F5Networks/f5-ansible#1670]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /srv/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.6/site-packages/ansible
  executable location = /root/.local/bin/ansible
  python version = 3.6.8 (default, Nov 10 2019, 15:33:49) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4.0.1)]
```

##### PYTHON VERSION

```
Python 3.6.8
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.1
  Build       0.0.4
  Edition     Point Release 1
  Date        Tue Sep 17 15:44:32 PDT 2019
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.1 (Ootpa)

##### SUMMARY

When creating a virtual server using the bigip_virtual_server module, the virtual server will show as created in the ansible output, but unable to be found via both the BigIP API and WebUI.  We found that when a profile is used for both the client-side and server-side context, the WebUI will error but Ansible will proceed with the creation.  If a duplicate profile name is used, any errors following such as an irule with a missing pool are ignored.

##### STEPS TO REPRODUCE

```
bigip_virtual_server
  state: present
  partition: "{{ partition }}"
  name: "{{ item.name }}"
  port: "{{ item.port }}"
  destination: "{{ item.destination }}"
  profiles:
     - name: tenminutetimeout
       context: client-side
     - name: tenminutetimeout
       content: server-side
     - xforwardedfor
provider:
      server:         "{{ server }}"
      user:           "{{ username }}"
      password:       "{{ password }}"
      validate_certs: "{{ validate_certs }}"
  with_items:
    - { name: "vs1",
          port: 80,
          destination: xx.xx.xx.xx
      }
```

##### EXPECTED RESULTS

The above should return an error stating that the profile cannot be used in both the server-side and client-side.

##### ACTUAL RESULTS

The raw JSON from the F5 API is returned showing it was changed.  The WebUI and API do not show a record of it.

**Comment by wojtek0806** [comment]
i have made some changes to the module, see if you get the API error now, it should propagate properly

@bradstapleton94

**Comment by wojtek0806** [comment]
please retest and we will revisit if this is still an issue
