### ISSUE TITLE
get_device_facts module in ansible 2.8 crashed when querying 3300 vips

### ISSUE THREAD

**Issue by carldubois** [F5Networks/f5-ansible#1687]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
2.8

##### PYTHON VERSION
2.7.5

##### BIGIP VERSION
13.1.1.5

##### CONFIGURATION
HA - 1xactive * 1xstandby

##### SUMMARY
Running a get_facts against ltm w/ 3339 virtual servers all live in /Common partition crashes.

##### STEPS TO REPRODUCE
Is there a know scale issue with get_facts that may be addressed in get_info module for 2.9?

Ansible module trace response:
may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 15468, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 15214, in exec_module
    result = self.execute_managers(managers)
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 15293, in execute_managers
    result = manager.exec_module()
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 14891, in exec_module
    facts = self._exec_module()
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 14897, in _exec_module
    facts = self.read_facts()
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 14906, in read_facts
    collection = self.read_collection_from_device()
  File "/tmp/ansible_bigip_device_facts_payload_tgXJKA/__main__.py", line 14926, in read_collection_from_device
    raise F5ModuleError(response['message'])

200 virtual ltm seems to work fine.

##### EXPECTED RESULTS
To render device facts for virtuals, pools, monitors, profiles. 

##### ACTUAL RESULTS
Crashed, stack trace above.

**Comment by carldubois** [comment]
Maybe a way to parse out based on "vip name"? or allow user to return only # at a time?

**Comment by carldubois** [comment]
**Isolated this into two areas.**  
Getting ltm-pools and virtual-server information fails, with two separate errors against our larger LTM.
 Here is the appropriate output that F5 may need. 
#### Server information  #####
SOMEUNIXPROMPT $ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
SOMEUNIXPROMPT $ ansible  --version
ansible 2.9.4
  config file = None
  configured module search path = ['/net/psn02hom/home/b/bo617a/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
SOMEUNIXPROMPT $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:50:56:a3:72:f9 brd ff:ff:ff:ff:ff:ff
    inet 172.21.37.126/21 brd 172.21.39.255 scope global ens192
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:d9:71:72:f5 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: br-1058913e1472: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:90:00:c6:96 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global br-1058913e1472
       valid_lft forever preferred_lft forever
SOMEUNIXPROMPT $
 
#### Ansible playbook ####
---
- name: Getting F5 facts
  hosts: "{{device}}"
  connection: local
  gather_facts: false
  become: false
  vars:
    f5_provider:
      server: "{{ inventory_hostname }}"
      user: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      validate_certs: False
      timeout: 1800
 
  tasks:
    - name: Collect BIG-IP ltm-pools
      bigip_device_info:
        gather_subset:
          - ltm-pools
        provider: "{{ f5_provider }}"
      register: ltm_pools
 
    - name: Collect BIG-IP virtual-servers
      bigip_device_info:
        gather_subset:
          - virtual-servers
        provider: "{{ f5_provider }}"
      register: virtual_servers
 
#### Ansible playbook works fine with BOTH tasks on small LAB deployment ####
####   also know that pulling info from LTM devices with a little over 1000 VIP's works! ####

SOMEUNIXPROMPT $ ansible-playbook -i ../inventory/hosts gdi_test.yml -e device=ib33-03y6.ns.cs.customer.com
 
PLAY [Getting F5 facts] ************************************************************************************************
 
TASK [Collect BIG-IP ltm-pools] ****************************************************************************************
ok: [ib33-03y6.ns.cs.customer.com]
 
TASK [Collect BIG-IP virtual-servers] **********************************************************************************
ok: [ib33-03y6.ns.cs.customer.com]
 
PLAY RECAP *************************************************************************************************************
ib33-03y6.ns.cs.customer.com : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
 
SOMEUNIXPROMPT $
 
 
#### Ansible playbook failure with an LTM of over 3000 VIPs ####
SOMEUNIXPROMPT $ ansible-playbook -vvv -i ../inventory/hosts gdi_test.yml -e device=ds50-115-b.ns.cs.customer.com
ansible-playbook 2.9.4
  config file = None
  configured module search path = ['/net/psn02hom/home/b/bo617a/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
No config file found; using defaults
host_list declined parsing /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts as it did not pass its verify_file() method
script declined parsing /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts as it did not pass its verify_file() method
Parsed /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts inventory source with yaml plugin
 
PLAYBOOK: gdi_test.yml *************************************************************************************************
1 plays in gdi_test.yml
 
PLAY [Getting F5 facts] ************************************************************************************************
META: ran handlers
 
TASK [Collect BIG-IP ltm-pools] ****************************************************************************************
task path: /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/experiments/gdi_test.yml:41
<ds50-115-b.ns.cs.customer.com> ESTABLISH LOCAL CONNECTION FOR USER: bo617a
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'echo ~bo617a && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859 `" && echo ansible-tmp-1584367750.2764268-7161135715859="` echo /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859 `" ) && sleep 0'
<ds50-115-b.ns.cs.customer.com> Attempting python interpreter discovery
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_device_info.py
<ds50-115-b.ns.cs.customer.com> PUT /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-local-63113_8u92ed/tmpgqamk5x3 TO /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'chmod u+x /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/ /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c '/usr/bin/python /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'rm -f -r /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py", line 102, in <module>
    _ansiballz_main()
  File "/net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16266, in <module>
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16259, in main
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15999, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16078, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 11635, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 11641, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 11655, in read_facts
  File "/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 11729, in read_stats_from_device
TypeError: 'NoneType' object has no attribute '__getitem__'
 
fatal: [ds50-115-b.ns.cs.customer.com]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584367750.2764268-7161135715859/AnsiballZ_bigip_device_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.f5.bigip_device_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16266, in <module>\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16259, in main\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 15999, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 16078, in execute_managers\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 11635, in exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 11641, in _exec_module\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 11655, in read_facts\n  File \"/tmp/ansible_bigip_device_info_payload_2cvhDq/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py\", line 11729, in read_stats_from_device\nTypeError: 'NoneType' object has no attribute '__getitem__'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
 
PLAY RECAP *************************************************************************************************************
ds50-115-b.ns.cs.customer.com : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
 
SOMEUNIXPROMPT $
 
#### Second problem with the module!!!  ####
#### Error with running ONLY the 2nd task of getting virtual-servers ####
 
SOMEUNIXPROMPT $ ansible-playbook -vvv -i ../inventory/hosts gdi_test.yml -e device=ds50-115-b.ns.cs.customer.com

ansible-playbook 2.9.4
  config file = None
  configured module search path = ['/net/psn02hom/home/b/bo617a/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
No config file found; using defaults
host_list declined parsing /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts as it did not pass its verify_file() method
script declined parsing /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts as it did not pass its verify_file() method
Parsed /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/inventory/hosts inventory source with yaml plugin
 
PLAYBOOK: gdi_test.yml *************************************************************************************************
1 plays in gdi_test.yml
 
PLAY [Getting F5 facts] ************************************************************************************************
META: ran handlers
 
TASK [Collect BIG-IP virtual-servers] **********************************************************************************
task path: /net/psn02hom/home/b/bo617a/repos/load-balancing-playbooks/experiments/gdi_test.yml:26
<ds50-115-b.ns.cs.customer.com> ESTABLISH LOCAL CONNECTION FOR USER: bo617a
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'echo ~bo617a && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553 `" && echo ansible-tmp-1584370879.149695-272657265712553="` echo /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553 `" ) && sleep 0'
<ds50-115-b.ns.cs.customer.com> Attempting python interpreter discovery
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_device_info.py
<ds50-115-b.ns.cs.customer.com> PUT /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-local-9224rtnj86pf/tmpzs1iswc8 TO /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553/AnsiballZ_bigip_device_info.py
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'chmod u+x /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553/ /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553/AnsiballZ_bigip_device_info.py && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c '/usr/bin/python /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553/AnsiballZ_bigip_device_info.py && sleep 0'
<ds50-115-b.ns.cs.customer.com> EXEC /bin/sh -c 'rm -f -r /net/psn02hom/home/b/bo617a/.ansible/tmp/ansible-tmp-1584370879.149695-272657265712553/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16259, in main
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15999, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 16078, in execute_managers
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15674, in exec_module
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15680, in _exec_module
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15689, in read_facts
  File "/tmp/ansible_bigip_device_info_payload_1bg0cp/ansible_bigip_device_info_payload.zip/ansible/modules/network/f5/bigip_device_info.py", line 15709, in read_collection_from_device
 
fatal: [ds50-115-b.ns.cs.customer.com]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "virtual-servers"
            ],
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "ds50-115-b.ns.cs.customer.com",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": 1800,
                "transport": "rest",
                "user": "SVCansible",
                "validate_certs": false
            }
        }
    },
    "msg": "remoteSender:172.21.37.126, method:GET "
}
 
PLAY RECAP *************************************************************************************************************
ds50-115-b.ns.cs.customer.com : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
 
SOMEUNIXPROMPT $

**Comment by focrensh** [comment]
Tracking with FMFA-447
