### ISSUE TITLE
Check for missing commits vs devel vs migration process

### ISSUE THREAD

**Issue by gundalow** [F5Networks/f5-ansible#1688]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created. Also to see if there are any parts of the migration.py rewrite to existing code that need applying to this repo

Please check the contents of https://github.com/ansible-collection-migration/f5networks.f5_modules against this repo

In particular:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

##### ISSUE TYPE
- Bug Report

**Comment by wojtek0806** [comment]
i have already closed previous issue, please refrain from opening the same thing again, we are well aware of what needs to be done thank you!

**Comment by gundalow** [comment]
Sorry, this was my mistake as I hadn't archived the original repo.

**Comment by wojtek0806** [comment]
no problem i have forked it for reference as we will use it as a  reference to tidy up the remaining code close to 2.10 launch.
