### ISSUE TITLE
bigip_user does not preserve shell setting

### ISSUE THREAD

**Issue by jesmith18** [F5Networks/f5-ansible#1695]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME
bigip_user

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jsmith18/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When the bigip_user module is invoked without specifying the "shell" parameter, the current setting of the shell in the user is not preserved.

It doesn't appear that the module is making a distinction between "shell: none" (set the user's access to none) and when the shell parameter is not present (preserve the existing shell setting of the user).

##### STEPS TO REPRODUCE

```
- name: Update User Password
  bigip_user:
    provider: "{{ creds }}"
    username_credential: "{{ targetUsername }}"
    password_credential: "{{ targetPassword }}"
  register: output
  notify: Save Config
  delegate_to: localhost
```

##### EXPECTED RESULTS

changed: [192.168.71.129 -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "full_name": null, 
            "partition": "Common", 
            "partition_access": null, 
            "password_credential": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.71.129", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": false
            }, 
            "shell": "bash", 
            "state": "present", 
            "update_password": "always", 
            "username_credential": "joel"
        }
    }, 
    "password_credential": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
    "shell": "none"
}
##### ACTUAL RESULTS

```
changed: [192.168.71.129 -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "full_name": null, 
            "partition": "Common", 
            "partition_access": null, 
            "password_credential": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.71.129", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": false
            }, 
            "shell": null, 
            "state": "present", 
            "update_password": "always", 
            "username_credential": "joel"
        }
    }, 
    "password_credential": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
    "shell": "none"
}
```

**Comment by focrensh** [comment]
Tracking with FMFA-472
