### ISSUE TITLE
JSON Formatted Playbook

### ISSUE THREAD

**Issue by jcshelby** [F5Networks/f5-ansible#17]
Hi - I'm working a way to generate our playbooks dynamically and am wanting to format them in JSON instead of YAML. I've pretty much figured out how to do this, but am running into issues when I try to include the parameters specified in the module (ex. server, user, etc.) as a list value to a dictionary key (specifically I'm told that the parameter doesn't support a list). Do you have any insight on how these parameters are formatted so that I can translate them to Python and subsequently into JSON? I'm testing with the bigip_node module but would eventually need to use all module parameters. It looked like the YAML was a list containing a dictionary containing a list but when I try to emulate that in Python I get the error mentioned above. Thanks!

**Comment by caphrim007** [comment]
@jcshelby which error were you receiving?

Here's an example of what the code looks like in YAML

```yaml
bigip_node:
    server: "bigip.example.com"
    user: "admin"
    password: "secret"
    state: "present"
    partition: "Common"
    host: "10.10.10.10"
    name: "foo.host.org"
```

The parameters to the module, as you were told, do not support a list. For this module, the parameters are just key=val entries.

**Comment by jcshelby** [comment]
Tim:
Thank you for your response. I was actually able to figure out part of my issue using a dictionary containing multiple key-value pairs rather than an array (list), which is what it looked like when I initially reviewed the YAML. With that done the JSON now looks to be correctly formatted for the playbook, but I'm now getting an error where it's saying "the field hosts is required but was not set", even though there's clearly a value in that field. I've included a portion of my JSON formatted playbook here to illustrate what I'm talking about. Thanks for the assistance with this - I'm still new to Ansible so help is very much appreciated. 

[{"connection" : "local", "hosts" : "10.0.32.120", "name" : "Create a node in my BIG-IP"}

**Comment by caphrim007** [comment]
@jcshelby try this

```
[
  {
    "name": "Test the bigip_node module",
    "hosts": "f5-test",
    "connection": "local",
    "tasks": [
      {
        "name": "Create a node",
        "bigip_node": {
          "server": "bigip.example.com",
          "user": "admin",
          "password": "secret",
          "state": "present",
          "partition": "Common",
          "host": "10.10.10.10",
          "name": "foo.host.org"
        }
      }
    ]
  }
]
```

It worked for me on my test box

**Comment by jcshelby** [comment]
Thanks! That worked perfectly. Would you have a guideline for how the YAML formatting in your playbook examples would convert to JSON? I attempted to use an online YAML to JSON converter but there were some formatting issues that it couldn't parse. I apologize if these questions are overly simplistic; I'm still very new to YAML and programming in general. Also, would there be a better way to ask questions about the F5 modules in Ansible rather than opening an issue? I don't want to unnecessarily clog up your queues :)

**Comment by caphrim007** [comment]
Can you elaborate on what couldn't be parsed? It might be a syntax error on my part.

Generally we ask that folks use the Ansible mailing list for questions about F5 modules that *ship* with Ansible, and use this forum for modules that *do not ship* with Ansible.

**Comment by jcshelby** [comment]
Honestly I only copied and pasted the YAML from the website to an online conversion tool to try and understand what the underlying JSON structure was so I could convert this into my script. As a result of this I didn't get more information than the YAML wasn't correctly formatted. I'm sure this was most likely a cut and paste issue on my part given that YAML is sensitive to indentation. 

So since this is an extras module this would be the preferred method of communication with yourself and your team for any questions that I have?

Also, I noticed in some of your examples you have an option for "local_action" and others you don't. I was curious what this option is as I didn't see any documentation on it, though I could have missed it. I was also curious if you have any guidelines suggesting how to convert YAML as used in playbooks to JSON, similar to the suggestion you provided earlier to resolve my issue? In other words, what structures in YAML correlate to what structures in JSON? Again my apologies if this question is overly simplistic as I'm still learning both formats.

**Comment by caphrim007** [comment]
Yeah, for now you can communicate over this channel if a specific module does not exist. We also hangout on the ansible mailing list, so we'll usually see something if you mention "F5" in the subject.

Over time these modules will begin to go into the Ansible core product, so more of the ansible mailing list will be able to assist, but we'll probably continue to remain the foremost authorities on the F5 modules.

`local_action` is a way in ansible to short-cut having to specify a delegate for a task that you want to run locally.

Normally you have the choice of using `local_action`, `delegate_to` or, if your `hosts:` line is set to `localhost` using neither.

I (personally) do not like using `local_action`. If you see it in the examples, it's likely a remnant from the community putting it in there. All of the examples that I create use the `delegate_to` form.

For converting from YAML to JSON, just think of YAML as a different dialect of JSON. The syntax is the key differentiator because JSON is more verbose in the quotes, commas, etc.

That said, most tools that consume JSON will also consume YAML. This gives you the ability to read in one format and spit out another.

Here's a snippet using [pyyaml](http://pyyaml.org/wiki/PyYAMLDocumentation) and json

```
import json
import yaml

fh = open('tests/bigip_gtm_datacenter.yaml')
y = fh.read()
yam = yaml.load(y)
print json.dumps(yam)
```

hope that helps.

**Comment by jcshelby** [comment]
Tim:

That sounds good. That makes sense; thanks for taking the time to explain that to me with regards to the action types. Is there some documentation on those and their use cases?

That also makes sense about YAML and JSON; I had been using the JSON library to create the JSON-formatted playbook but I didn’t think about using it to translate between the two. One other question I had – why in some of the examples are key-value pairs using a = rather than a :?

Thanks again for your help and taking the time to explain all of this to me. It’s very much appreciated and helping me move along much faster in my project.

Respectfully,

Joseph Shelby

Network Services Engineer II, IT Voice and Data Networks
joseph.shelby@asurion.com<mailto:joseph.shelby@asurion.com>
voice 615.445.1240 | mobile 615.210.6139
Asurion I 648 Grassmere Park, Nashville, TN 37211
www.asurion.com<http://www.asurion.com/> I Twitter<https://twitter.com/Asurion> I Facebook<https://www.facebook.com/Asurion>

**Comment by caphrim007** [comment]
Sure. It's described in more detail in the Ansible documentation on delegation here.

http://docs.ansible.com/ansible/playbooks_delegation.html

The reason for the difference in examples is entirely due to the different contributors that provided samples before I stepped in and took over much of the development. Until that time, there were no coding conventions to reference when developing modules. Now, there are.

The decision whether to use k/v or complex args is a little bit personal and a little bit technical. They are both valid YAML. More about it can be found here

http://www.jeffgeerling.com/blog/yaml-best-practices-ansible-playbooks-tasks

The reason I use complex args is that it is more readable and because I have encountered cases when setting a value in YAML simply does not work with the simple k/v form.

**Comment by jcshelby** [comment]
Tim:

Excellent – thank you for providing that documentation. It’s very helpful in understanding this.

That makes sense regarding the consistency. I’m glad that seems to have been addressed. The information about key/value pairs vs complex arguments is also very helpful. I very much appreciate you taking the time to send all of that over.

I think that’s all of my questions for now but I’ll definitely reach out if I come up with any more. Thanks again!

Respectfully,

Joseph Shelby

Network Services Engineer II, IT Voice and Data Networks
joseph.shelby@asurion.com<mailto:joseph.shelby@asurion.com>
voice 615.445.1240 | mobile 615.210.6139
Asurion I 648 Grassmere Park, Nashville, TN 37211
www.asurion.com<http://www.asurion.com/> I Twitter<https://twitter.com/Asurion> I Facebook<https://www.facebook.com/Asurion>

**Comment by jcshelby** [comment]
Another question for you if you don't mind. How can I add multiple hosts (distinct server IP addresses) as an argument in a JSON formatted playbook? The use case would be creating a pool with multiple servers available rather than just a single member. I tried using a list of IP address as value for the host key, but this didn't work.  Example below. Thanks in advance for your assistance.

"bigip_node": {
       "hosts" : ["host 0", "host 1", "host 3"]
    }

**Comment by caphrim007** [comment]
@jcshelby hosts are specified as a string which is colon separated. So simply,

`"hosts": "vms-bigip:vms-bigiq"`

hope that helps

**Comment by jcshelby** [comment]
Tim:

Apologies for the long reply – I’ve had to focus on a couple other things as a priority and am now able to focus back on this. I tried the syntax suggested below but received an error stating:


1.     The requested object name (10.0.38.80:10.3.100.73) is invalid

2.     The syntax for my JSON playbook is:

a.      “host” : “10.0.38.80:10.3.100.73”, (with a comma preceding the argument)

Respectfully,

Joseph Shelby

Network Services Engineer II, IT Voice and Data Networks
joseph.shelby@asurion.com<mailto:oseph.shelby@asurion.com>
voice 615.445.1240 | mobile 615.210.6139
Asurion I 648 Grassmere Park, Nashville, TN 37211
www.asurion.com<http://www.asurion.com/> I Twitter<https://twitter.com/Asurion> I Facebook<https://www.facebook.com/Asurion>

**Comment by caphrim007** [comment]
@jcshelby what module are you trying to use?

**Comment by jcshelby** [comment]
Tim: 

I'm using bigip_pool. I'm running Ansible v2.2.0 (devel 4cc4dc6793) from source and last updated on 2016-07-19

**Comment by caphrim007** [comment]
can you post the content of the playbook itself?

**Comment by jcshelby** [comment]
Tim:

Playbook contents are below. I've added a few empty strings where some internal data was, but otherwise this is exactly what I'm trying to run. 

{"connection": "local", "tasks": [{"bigip_pool": {"port": "80", "state": "present", "partition": "Common", "user": "admin", "name": "", "lb_method": "round_robin", "password": "", "validate_certs": "no", "host": "10.0.38.80:10.3.100.73", "server": ""}, "name": "Create a node"}], "hosts": "F5", "name": "Create a pool"}]

**Comment by jcshelby** [comment]
For what it's worth, I did confirm that this is valid JSON

**Comment by caphrim007** [comment]
Your problem is that you're specifying multiple IP addresses in a task argument (field) that expects only a single IP address.

What you want to use in Ansible is an iterator that includes all of the IP addresses of the hosts that you want in the pool.

Here is an example of the JSON to do that.

```
[
  {
    "name": "Pool and Pool members",
    "hosts": "f5-test",
    "connection": "local",
    "tasks": [
      {
        "name": "Create a pool",
        "bigip_pool": {
          "lb_method": "round_robin",
          "name": "my_pool",
          "password": "secret",
          "server": "lb.mydomain.com",
          "state": "present",
          "user": "admin",
          "validate_certs": "no"
        }
      },
      {
        "name": "Add pool members",
        "bigip_pool_member": {
          "host": "{{ item }}",
          "password": "secret",
          "server": "lb.mydomain.com",
          "state": "present",
          "pool": "my-pool",
          "port": 80,
          "user": "admin"
        },
        "with_items": [
          "10.0.38.80",
          "10.3.100.73"
        ]
      }
    ]
  }
]
```

And here is YAML

```
---

- name: Pool and Pool members
  hosts: f5-test
  connection: local

  tasks:
      - name: Create a pool
        bigip_pool:
            lb_method: "round_robin"
            name: "my_pool"
            password: "secret"
            server: "lb.mydomain.com"
            state: "present"
            user: "admin"
            validate_certs: "no"

      - name: Add pool members
        bigip_pool_member:
            host: "{{ item }}"
            password: "secret"
            server: "lb.mydomain.com"
            state: "present"
            pool: "my-pool"
            port: 80
            user: "admin"
        with_items:
            - 10.0.38.80
            - 10.3.100.73
```

**Comment by jcshelby** [comment]
Tim:

That worked perfectly. I did make one change and that was to use the hosts key in the bigip_pool playbook to consolidate that work into a single playbook. Otherwise I use everything exactly as specified and it worked out great. As always thank you for the assistance with this. One question - do you have a preferred resource (aside from their documentation) for learning about Ansible? I'd like to increase my knowledge of this tool in preparation for some internal efforts we're starting up. Thanks again for the assistance

**Comment by caphrim007** [comment]
I learned most of it just by having a problem and then asking questions. Their documentation is decent imho. I reference the module index frequently, but other than that, for me the best way has been the proverbial googling "ansible ...." and sifting through the results. Their mailing list is also a good source of information.

**Comment by jcshelby** [comment]
Tim:

Agreed and that makes sense. I've been doing that as well but am always on the lookout for anything else that might be helpful. As of now I think I'm good. I really appreciate all of the help and will reach back out if I run into anything else. Thanks again for everything!

**Comment by caphrim007** [comment]
Sure thing. I'm going to close the issue for now, but feel free to open other issues if you have questions in the future. Otherwise, the ansible mailing list is usually knowledgable and friendly.
