### ISSUE TITLE
Enhance bigip_device_info with security_log_profiles gather_subset

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#1705]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_device_info
##### ANSIBLE VERSION

```
ansible 2.9.6
```

##### PYTHON VERSION

```
python version = 2.7.17
```

##### BIGIP VERSION

```
14.1.2.3
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Add the gather_subset element 

> security_log_profiles

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```
At this time, I have to gather all, and it takes quite some minutes to complete.
```

**Comment by focrensh** [comment]
Are you looking for a list of the log_profiles and their settings, or a list of log profiles associated with a virtual?

Do you have an example of what you are looking for?

**Comment by amolari** [comment]
I can already gather a list of log profiles associated with a virtual with the gather_subset=virtual-server. I'm looking for a list of the log_profiles and their settings

**Comment by amolari** [comment]
was my last comment not sufficient?

**Comment by focrensh** [comment]
Are you looking for the output of the firewall_log_profile module or is this ASM security log profiles that do not currently have a module for creation?

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_firewall_log_profile_module.html

**Comment by amolari** [comment]
I'm looking for an ASM security log profile module (creation)

**Comment by focrensh** [comment]
Thanks, so this would be for security log profile module, and then adding that data to device_info.

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!

**Comment by amolari** [comment]
@KrithikaChidambaram why is it marked as completed? I do not see any PR associated. Please reopen
