### ISSUE TITLE
bigip_device_info - extremely slow - takes 29 minutes to retrieve just ltm-pools

### ISSUE THREAD

**Issue by MTWiley** [F5Networks/f5-ansible#1735]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_info

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 26 2019, 16:55:40) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### PYTHON VERSION

```
[username@servername~]$ python -V
Python 2.7.5
```

```
[username@servername~]$ python3 --version
Python 3.6.8
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Tue Nov  5 10:09:50 PST 2019
```

##### CONFIGURATION
[defaults]
vault_password_file = /opt/ansible/private_key.pem
host_key_checking = false
inventory = inventory/inventory
retry_files_enabled = false
callback_whitelist = splunk, timer
display_skipped_hosts = no

[callback_splunk]
url = https://splunkhec.something.com:10515/services/collector
authtoken = 00000000-0000-0000-0000-00000000000

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### SUMMARY
Incredibly slow to gather information, takes upwards of 5 minutes to gather even just the ltm-pools

##### STEPS TO REPRODUCE
Inventory:
[f5_group_name]
x.x.x.x
x.x.x.y

Command:
ansible-playbook playbooks/get_f5_facts.yml -e "f5_group=f5_group_name"
...
TASK [Debugging Empty ltm-pools] *********************************************************************************************************************************************************************
ok: [x.x.x.x] => {
    "dead_pools": [
        "_pool",
        "anotherrandompool.mywebsite.com_pool",
        "someotherrandompool.svc.mywebsite.lan",
        "somerandompool",
        "sslpool.mywebsite.com_pool",
        "test_pool"
    ]
}

PLAY RECAP *******************************************************************************************************************************************************************************************
10.128.1.13                : ok=6620 changed=0    unreachable=0    failed=0    skipped=0    rescued=10   ignored=0   
10.128.1.14                : ok=6620 changed=0    unreachable=0    failed=0    skipped=0    rescued=10   ignored=0   

Playbook run took 0 days, 0 hours, 29 minutes, 9 seconds

get_active_pool_member_count.yml contents:
```
- name: Block & Rescue
  block: 
  - name: POOL MEMBER COUNTS
    debug:
      msg:
        - "Pool Name: {{ pool['name'] }}"
        - "Pool Status: {{ pool['availability_status'] }}"
        - "Members: {{ pool['members'] }}"
        - "Online Members: {{ pool['members'] | selectattr('real_state', 'equalto', 'up') | list | count }}"
        - "Total Members: {{ pool['members'] | count }}"
  rescue:
  - name: Pool has no members
    debug:
      msg: "{{ pool['name'] }} HAS NO MEMBERS, PROBABLY NEEDS TO BE RECLAIMED"

  - name: Add Dead Pools to list
    set_fact:
      dead_pools: "{{ dead_pools + [pool['name']] }}"
```

Example Playbook:

```
---
  # Interrogate F5 for Information
  - name: Get Facts from F5s
    hosts: "{{ f5_group }}"
    gather_facts: no
    
    tasks:
    - name: Get Active/Standby Status
      bigip_command:
        provider: "{{ provider }}"
        commands: show cm failover-status | grep 'Status' | grep -v Failover
      delegate_to: localhost
      register: active_standby

    - name: Show Active/Standby Results
      debug:
        msg: "{{ active_standby }}"

    - name: Get BIG-IP pool facts
      bigip_device_info:
        provider: "{{ provider }}"
        gather_subset: 
          - ltm-pools
      delegate_to: localhost
      register: bigip_device_info
      when: active_standby is search("ACTIVE")

    - name: Add Dead Pools to list
      set_fact:
        dead_pools: []
      when: active_standby is search("ACTIVE")      
    

    - name: Check each pool for member counts
      include_tasks: get_active_pool_member_count.yml
      loop: "{{ bigip_device_info['ltm_pools'] }}"
      loop_control:
        loop_var: pool

    - name: Debugging Empty ltm-pools
      debug:
        var: dead_pools
```

##### EXPECTED RESULTS
I expected with 6000 pools for it to take a while, but not 29 minutes to run, that seems like an insanely long time to run to retrieve that data.

##### ACTUAL RESULTS
Timer callback plugin reports that it took 0 days, 0 hours, 29 minutes, 9 seconds to run the playbook.

**Comment by NicCage1337** [comment]
We are having same issue with huge Configurations when the Remote Device is away from the ansible_host. For me it worked like a charm when i removed delegate_to: localhost and changed the server in the provider dict to localhost.

In that case the Ansible Host is using an SSH Connection to the BigIP and queries the REST Api with localhost only. this was 500% faster.

Another remark: You can get Active / Standby state from within the bigip_device_info Module.
You have to search for item.self = yes and in this element the Failover State is stored as failover_state.

**Comment by MTWiley** [comment]
@NicCage1337 

Did you have to install any dependencies on the f5s themselves?   For some reason I was thinking big_suds or some other sdk was required to run the modules or do those automatically get copied over when it's executing

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
