### ISSUE TITLE
bigip_software_image image http mirror

### ISSUE THREAD

**Issue by vmpr** [F5Networks/f5-ansible#1741]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_software_image

##### ANSIBLE VERSION
```
all supported versions
```

##### PYTHON VERSION
```
all supported versions
```

##### BIGIP VERSION
```
all supported versions
```

##### SUMMARY
the module should be able to copy the firmware image from somewhere else than the mounted filesystem, like an HTTP-mirror (example path: http://local.http.repo/f5_images/BIGIP-14.1.2.3-0.0.5.iso )

**Comment by wojtek0806** [comment]
if you want to copy files from external sources to ansible controller then use built in modules from ansible core. in terms of direct bigip downloads we will never implement file download directly on bigip.
