### ISSUE TITLE
Ansible Module Missing for SSL Persistence Profile

### ISSUE THREAD

**Issue by fredchag** [F5Networks/f5-ansible#1750]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_profile_persistence_ssl

##### ANSIBLE VERSION

```
ansible 2.9.4
```

##### PYTHON VERSION

```
Python 3.8.0
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.73.2
  Edition     Engineering Hotfix
  Date        Wed Nov 14 21:56:00 PST 2018

Hotfix List
ID738945-1
```

##### OS / ENVIRONMENT

Linux Ubuntu

##### SUMMARY

I can't create SSL Persistence Profile with a dedicated module of Ansible, I need to use the command module which is not idempotent.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking with FMFA-526

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
