### ISSUE TITLE
configure tcp remote logs in bigip_remote_syslog

### ISSUE THREAD

**Issue by vchepkov** [F5Networks/f5-ansible#1765]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_remote_syslog

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = None
  configured module search path = ['/Users/vc7733/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### PYTHON VERSION

```
Python 3.7.7
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.3
  Build       0.0.5
  Edition     Point Release 3
  Date        Tue Dec 17 19:48:55 PST 2019

```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

To guarantee logs delivery to remote destination it's better to use TCP instead of UDP for remote destination logs.  https://support.f5.com/csp/article/K13080 provides commands to configure tcp remote logging. Could you consider adding this option to bigip_remote_syslog module, please?

**Comment by focrensh** [comment]
Tracking with FMFA-563

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
