### ISSUE TITLE
Can't create gateway failsafe  device via Ansible

### ISSUE THREAD

**Issue by rnautiyal** [F5Networks/f5-ansible#1766]
##### ISSUE TYPE

 
 - Feature Idea

##### ANSIBLE VERSION

ansible 2.9.2 

##### PYTHON VERSION

```
Python 2.7.5 

```

##### BIGIP VERSION

```
14.x

```

##### SUMMARY

I am trying to set up Gateway failsafe. There is no corresponding Ansible command to do so. I do not see any option in bigip_pool for Gateway failsafe.

Ansible -https://docs.ansible.com/ansible/latest/modules/bigip_pool_module.html

tmsh create /ltm pool GW1 { Gateway-failsafe-device xyz.com members add { ....

https://support.f5.com/csp/article/K15367
modify /ltm pool <gateway pool name> min-up-members <n> min-up-members-action <failover | reboot | restart-all>
##### STEPS TO REPRODUCE

```
No ANsible command
```

##### EXPECTED RESULTS

Trying to create the following ltm pool for  Gateway failsafe 

tmsh create /ltm pool GW1 { Gateway-failsafe-device xyz.com members add { 

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking via FMFA-559

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
