### ISSUE TITLE
bigip_device_info does not return remote Syslog configuration // feature idea/request

### ISSUE THREAD

**Issue by iamroddo** [F5Networks/f5-ansible#1777]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_device_info

##### ANSIBLE VERSION
n/a

##### PYTHON VERSION
n/a

##### BIGIP VERSION
n/a

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
bigip_device_info (from collection version 1.4) does not return remote Syslog configuration. Currently in order to get this information it is necessary to run bigip_command

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
n/a

##### ACTUAL RESULTS
n/a

**Comment by focrensh** [comment]
Tracking via FMFA-560
