### ISSUE TITLE
[SECURITY REQ] remove sensitive files from /var/config/rest/

### ISSUE THREAD

**Issue by pcloup** [F5Networks/f5-ansible#1786]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_ssl_key, bigip_ssl_certificate (and probably others)

##### ANSIBLE VERSION
2.9.10 (but should be in previous versions)

##### PYTHON VERSION
2.7.16

##### BIGIP VERSION
15.1.0.3

##### CONFIGURATION
nothing specific compared to what is documented in clouddocs

##### OS / ENVIRONMENT
ubuntu 18.04 LTS (Bionic)

##### SUMMARY
I have just created an ANSIBLE playbook to troubleshoot a customer issue and found out that the files used with certificate/key when pushing/updating certificates on BIG-IP, are stored in /var/config/rest/.
IF that makes sense as it is then used by our REST API to retrieve locally the files inside the device, for security resons, those files should be removed from this directory, as when they are in the BIG-IP cert store, we have ways to secure them as "files" (with passphrases and securevault), but not on this /var/config/rest/ folder.

##### STEPS TO REPRODUCE
  - name: push SSL cert
    bigip_ssl_certificate:
      name: pipomolo
      state: present
      content: "{{ lookup('file', './cert.pem') }}"
      provider:
        server: bigip1.internal
        user: admin
        password: xxxxxxxxx
        validate_certs: no
    delegate_to: localhost
  - name: modify SSL Priv key
    bigip_ssl_key:
      name: pipomolo
      state: present
      content: "{{ lookup('file', './privkey.pem') }}"
      provider:
        server: bigip1.internal
        user: admin
        password: xxxxxxxxx
        validate_certs: no
    delegate_to: localhost

##### EXPECTED RESULTS
solution works, it is not a bug. But for security reasons, those files had to be removed from this directory.

##### ACTUAL RESULTS
When the Cert and Priv key are processed (with a positive or negative outcome), the files had to be wiped from this directory.

**Comment by focrensh** [comment]
Tracking with FMFA-547

**Comment by amolari** [comment]
Is there any workaround? I've tried to POST an empty json body with Content-Range: 0, the result is OK => file deleted, but I get a 400 Bad Request.

**Comment by wojtek0806** [comment]
doable by adding remove files logic at the end of successful module run, if there is an exception during the module execution then these files would have to be removed manually,
