### ISSUE TITLE
add support for log-profile in bigip_profile_dns

### ISSUE THREAD

**Issue by vchepkov** [F5Networks/f5-ansible#1793]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_profile_dns

##### ANSIBLE VERSION

```
ansible 2.9.10
  ansible python module location = /opt/ansible/lib/python3.8/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.8.3 (default, Jul  8 2020, 14:27:55) [Clang 11.0.3 (clang-1103.0.32.62)]

```

##### PYTHON VERSION

```
Python 3.8.3
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.6
  Build       0.0.2
  Edition     Point Release 6
  Date        Fri Jun  5 11:36:46 PDT 2020

```

##### CONFIGURATION

ANSIBLE_COLLECTIONS_PATHS=/opt/ansible

##### OS / ENVIRONMENT

macOS

##### SUMMARY
Currently, there is no option to configure log-profile in dns profile

Here is an example of a working configuration with dns logging enabled

```
ltm profile dns /Common/custom {
    app-service none
    avr-dnsstat-sample-rate 1
    defaults-from /Common/dns
    enable-dns-express no
    enable-dnssec no
    enable-logging yes
    log-profile /Common/splunk
}
ltm profile dns-logging /Common/splunk {
    enable-response-logging yes
    include-timestamp no
    include-view no
    log-publisher /Common/splunk
}

```

I can configure destinations, publisher, but not these two last components - dns-logging profile and log-profile attribute on dns profile

**Comment by focrensh** [comment]
Tracking via FMFA-564

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!

**Comment by vchepkov** [comment]
I am not sure why this was closed. Provisioning new DNS servers and having the same issue again.

**Comment by pgouband** [comment]
Hi @vchepkov,

Have you tried to configure dns profile with log profile using AS3?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#dns-profile

And the AS3 module from the declarative collection:
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2
