### ISSUE TITLE
RFE - renew license option in bigip_device_license

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1810]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_device_license

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = None
  configured module search path = ['/Users/ganti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]

```

##### PYTHON VERSION

```
3.7.4

```

##### BIGIP VERSION

```
Applies to all versions

```

##### OS / ENVIRONMENT

Not platform specific

##### SUMMARY

Need relicensing (renew license) feature (currently not supported)

##### STEPS TO REPRODUCE

Add a relicense option (flag). 

Alternatively, the current module can also be modified to run the licensing again when the service check date is different on the big-ip. Currently it is only available for licensing the first time.

**Comment by focrensh** [comment]
Tracking with FMFA-575

**Comment by focrensh** [comment]
This was added in Collection 1.6 using the "latest" flag on state.

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_device_license_module.html#bigip-device-license-module
