### ISSUE TITLE
Create a hash based peristence profile module

### ISSUE THREAD

**Issue by Virenta** [F5Networks/f5-ansible#1817]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_profile_persistence_hash

##### ANSIBLE VERSION

```
Non-relevant
```

##### PYTHON VERSION

```
Non-relevant
```

##### BIGIP VERSION

```
Non-relevant
```

##### SUMMARY

There is no module to create a hash based persistence profile, please create one

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Do you have the equivalent TMSh/REST calls you are using to make sure we cover the scope of exactly what you are looking for?

**Comment by Virenta** [comment]
Yes, it's this one - https://clouddocs.f5.com/api/icontrol-rest/APIRef_tm_ltm_persistence_hash.html

**Comment by focrensh** [comment]
Tracking via FMFA-591

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
