### ISSUE TITLE
RFE - support add on keys with license

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1826]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_device_license

##### ANSIBLE VERSION

```
2.9.2
```

##### PYTHON VERSION

```
3.7
```

##### BIGIP VERSION

```
all versions
```

##### SUMMARY

Licensing does not support addon keys at the moment. Add on keys should be an option in the "bigip_device_license" module. The addon keys feature also needs to be supported in re-licensing (https://github.com/F5Networks/f5-ansible/issues/1810). The information should also be available using bigip_device_info.

**Comment by focrensh** [comment]
Tracking via FMFA-589.

**Comment by focrensh** [comment]
Addon keys have a parameter in 1.2:
https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_device_license_module.html#bigip-device-license-module

If issues are found using this, please open a new issue.
