### ISSUE TITLE
Manipulate data output - bigip-device-info-module

### ISSUE THREAD

**Issue by vinealvees** [F5Networks/f5-ansible#1829]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

[Big IP Device Info](https://docs.ansible.com/ansible/latest/modules/bigip_device_info_module.html#bigip-device-info-module)

##### ANSIBLE VERSION

```
ansible --version
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible 2.9.6
  config file = /home/viniciusas/.ansible.cfg
  configured module search path = ['/home/viniciusas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### PYTHON VERSION

```
python -V
Python 2.7.18rc1

```

##### BIGIP VERSION

```
tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.6
  Build       0.0.2
  Edition     Point Release 6
  Date        Fri Jun  5 11:36:46 PDT 2020


```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

##### SUMMARY

When you need making filters on output of bigip_device_info, you do not get just the fields that you want, like "sections".
For example: I am running bigip_device_info and I want to list ltm-pools and select just one field, like a 'section' such as 'name'. Always when I need to get the name off all pools, I need run ltm-pools and after make some output filter.
The ideia is create sections and we can be use like: ltm.name and list just the pools name. Currently I need ran ltm-pools, register it in a variable and make a output filter to just show the names.
I think that with theese "sections" its easly to work and manipulate it.

Sorry about redundancy in the text.

##### STEPS TO REPRODUCE

```
N/A

```

##### EXPECTED RESULTS

Today we need a register the output of ltm-pools in an variable and make filters with it

##### ACTUAL RESULTS

Create section in ltm-pools and in the other options available to facilitate data manipulation.

```
NA

```

**Comment by wojtek0806** [comment]
whats wrong with using jq or jinja filter to achive your goal?

**Comment by wojtek0806** [comment]
Also in the case where you need to have something tailored to your needs you can write your own lookup plugin to take care of the data formatting for you.

**Comment by vinealvees** [comment]
Let me try explain my situation:

Currently, I am runnning bigip-device-info and I need to get the field "name" (ltm_pools.name in the output). The problem is that my load balancer has a lot of pools and this delay something like 15 minutes to conclude and after it I do the filter.

I think that with bigip-device-info divided in sub-section when it run, for example in the module, if I could run "ltm_pools.name" instead of just ltm-pools and get all information that ltm_pools give me, the time of processing will be a lot of smaller, if I could select some field inside ltm_pools.

Could you understand me?

**Comment by wojtek0806** [comment]
we do not filter for specific parameters, we will introduce maybe splitting data per partition so you can for example specify ltm-pools for partition Common to make this less of a burden if there are multiple partitions. Other than that we won't implement it like you said above.
