### ISSUE TITLE
bigip_configsync_action_module seems to miss documented functionality

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible#1830]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
`bigip_configsync_action_module`

##### ANSIBLE VERSION
```
latest
```

##### PYTHON VERSION
```
3.6/3.7/3.8
```

##### BIGIP VERSION
```
13.x/14.x
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The [documentation](https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_configsync_action_module.html) refers to `sync_most_recent_to_device`. Checking the current [`devel`](https://github.com/F5Networks/f5-ansible/blob/4fda13494716c34a36ac9b2719a516714c1b1e57/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_configsync_action.py) branch there seems to be no implementation of the functionality.

Also `sync_group_to_device` is not documented itself, it is referred to by `sync_device_to_group`.
`sync_group_to_device` does still have some implementation "fragments":
https://github.com/F5Networks/f5-ansible/blob/4fda13494716c34a36ac9b2719a516714c1b1e57/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_configsync_action.py#L135-L138
https://github.com/F5Networks/f5-ansible/blob/4fda13494716c34a36ac9b2719a516714c1b1e57/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_configsync_action.py#L227-L231

##### EXPECTED RESULTS

Functional implementation and documentation for `sync_group_to_device` and `sync_most_recent_to_device`

**Comment by focrensh** [comment]
Tracking via FMFA-587

**Comment by wojtek0806** [comment]
the confusion here was the incorrect parameter name, as the rest of the code is there, i have fixed that now
