### ISSUE TITLE
bigip_firewall_rule does not support associating a service policy, send to virtual, Protocol Inspection Profile or Classification Policy

### ISSUE THREAD

**Issue by DonPrice** [F5Networks/f5-ansible#1839]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_firewall_rule
##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/donovanp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### PYTHON VERSION

```
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### BIGIP VERSION

```
15.1.0.4
```

##### SUMMARY

There is not option to pass a service policy to a firewall rule. Methods exist to create timer polices and service policies but the service policies can not be associated with a firewall rule during creation the Send To Virtual, Protocol Inspection Profile and Classification Policy are also not available.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking via FMFA-642

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
