### ISSUE TITLE
[RFE ] Feature request to add an Ansible F5 module for Inband monitor

### ISSUE THREAD

**Issue by SWADESNA** [F5Networks/f5-ansible#1841]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME

- F5 Module

##### ANSIBLE VERSION

```
 All versions
```

##### BIGIP VERSION

```
All versions
```

##### OS / ENVIRONMENT

NA

##### SUMMARY

Customer requires an F5 module for Inband monitor.

##### STEPS TO REPRODUCE
 This is a feature request. So, no reproduction steps required.

**Comment by stephenpaynter** [comment]
Identity added: /tmp/awx_1257_0_wnqoli/artifacts/1257/ssh_key_data (/tmp/awx_1257_0_wnqoli/artifacts/1257/ssh_key_data)
PLAY [Test F5 Create Health Monitors] **************************************
TASK [Gathering Facts] *********************************************************
ok: [bigip1]
TASK [ansible-role-F5-create-monitors : Create Test F5 Create Health Monitors] ***
[WARNING]: Using "write" commands is not idempotent. You should use a module
that is specifically made for that. If such a module does not exist, then
please file a bug. The command in question is "create ltm monitor inband TEST-
R_inband-r..."
changed: [bigip1 -> localhost]
PLAY RECAP *********************************************************************
bigip1                     : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by pgouband** [comment]
Hi @SWADESNA,
Have you tried using AS3?
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
