### ISSUE TITLE
bigip_gtm_wide_ip support for description and prefer_client_subnet (topologyPreferEdns0ClientSubnet)

### ISSUE THREAD

**Issue by dmahler** [F5Networks/f5-ansible#1842]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`bigip_gtm_wide_ip`

##### SUMMARY
Please add support in `bigip_gtm_wide_ip` for `description` and `topologyPreferEdns0ClientSubnet` (friendly name: `prefer_client_subnet`).

`prefer_client_subnet=dict(type='bool')`
`description=dict(type='str')`

I've done this locally but saw that PRs are not accepted, it is just a few lines of code to update the existing `Parameters` class and a `prefer_client_subnet` property like the `persistence` one

**Comment by focrensh** [comment]
tracking with FMFA-618

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
