### ISSUE TITLE
playbook not working to create partition on f5 via ansible 

### ISSUE THREAD

**Issue by rohit1881** [F5Networks/f5-ansible#1845]
Hi ,

I am trying to create a new partition on our F5 box via ansible installed on ubuntu :
using below ansible version and python version :
-virtual-machine:/etc/ansible# ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
!
bigip module is installed successfull 
 ansible-doc -l | grep bigip
bigip_apm_acl                                                 Manage user-defined APM ACLs
bigip_apm_network_access                                      Manage APM Network Access resource
bigip_apm_policy_fetch                                        Exports the APM policy or APM access profile from remote nodes
bigip_apm_policy_import                     
!
this is a playbook which I have created on ansible server machine 👍 

---

- name: An example partition playbook
  hosts: 192.168.1.32
  connection: local

  vars:
    validate_certs: no
    username: admin
    password: admin

  tasks:
    - name: Create partition
      bigip_partition:
        name: my-partition
        password: "{{ password }}"
        server: 192.168.1.32
        validate_certs: "{{ validate_certs }}"
        user: "{{ username }}"
!
ping via ansible working fine:
nsible 192.168.132 -m ping
192.168.1.32 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "ping": "pong"
}
while running a playbook getting error message:
nsible-playbook test.yml

PLAY [An example partition playbook] ***********************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [192.168.1.32]

TASK [Create partition] ************************************************************************************************************************************************
fatal: [192.168.1.32]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (bigip_partition) module: password, server, user, validate_certs Supported parameters include: description, name, provider, route_domain, state"}

PLAY RECAP *************************************************************************************************************************************************************
192.168.1.32                 : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Please check and let me know how to fix this

**Comment by nmenant** [comment]
You should put all the data related to your connection into a provider section. Like this: 

```
    - bigip_partition: 
        name: my-partition
        provider:
          server: 192.168.143.153
          user: admin
          password: xxx
          validate_certs: no
      delegate_to: localhost 
``` 

I did a quick test and the partition is properly created

![image](https://user-images.githubusercontent.com/13098758/93094131-cd22d100-f6a1-11ea-89a1-8cc16e154797.png)


https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_partition_module.html#bigip-partition-module
