### ISSUE TITLE
unable to run bash commands using bigip_command module

### ISSUE THREAD

**Issue by narasims** [F5Networks/f5-ansible#1846]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

 - Bug Report

##### COMPONENT NAME

bigip_command
##### ANSIBLE VERSION

```
ansible 2.9.12
  config file = /home/narasims/.virtenv/Python36_Ansible29_NET/ansible.cfg
  configured module search path = ['/home/narasims/NET/library']
  ansible python module location = /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible
  executable location = /home/narasims/.virtenv/Python36_Ansible29_NET/bin/ansible
  python version = 3.6.9 (default, Sep 11 2019, 16:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### PYTHON VERSION

```
Python 3.6.9
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.5
  Build       0.0.3
  Edition     Point Release 5
  Date        Sat May  9 09:31:20 PDT 2020
```

##### CONFIGURATION

'''
[defaults]

library        = /home/narasims/NET/library
roles_path    = /home/narasims/NET/roles
collections_paths = /home/narasims/.virtenv/Python36_Ansible29_NET/share/ansible/collections
vault_identity_list = /home/narasims/NET/.vault_pass
callback_plugins   = /home/narasims/NET/plugins/callback_plugins
playbook_dir = /home/narasims/NET/playbooks'
forks          = 200
transport = smart
remote_user = narasims
remote_tmp     = /tmp/$USER/.ansible
gather_subset = !ohai,!facter
host_key_checking = False
timeout = 120
verbosity = 1
module_name = shell
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M by narasims on {host}
system_warnings = True
deprecation_warnings = True
command_warnings = False

callback_whitelist = timer
stdout_callback = debug
retry_files_enabled = False
var_compression_level = 9
jinja2_extensions = jinja2.ext.do

[privilege_escalation]
become_ask_pass=False
become_method=sudo
become_flags="-iS"

[ssh_connection]

ssh_args = -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=4h
control_path = /tmp/ansible-narasims-%%h
pipelining = True
transfer_method = smart

[persistent_connection]

connect_timeout = 30
connect_retries = 30
connect_interval = 1
'''
##### OS / ENVIRONMENT

'''
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Red Hat Enterprise Linux Server release 7.7 (Maipo)
'''
##### SUMMARY

Unable to run the cpcfg command for copying the config to the new boot location and rebooting the boot location.
'''
}
<localhost> connection transport is cli
<csdc-viprgst-test.core.oclc.org> using connection plugin network_cli
<csdc-viprgst-test.core.oclc.org> starting connection from persistent connection plugin
<csdc-viprgst-test.core.oclc.org> local domain socket does not exist, starting it
<csdc-viprgst-test.core.oclc.org> control socket path is /home/narasims/.ansible/pc/87eb7de594
<csdc-viprgst-test.core.oclc.org> local domain socket listeners started successfully
<csdc-viprgst-test.core.oclc.org> unable to load cliconf for network_os bigip
<csdc-viprgst-test.core.oclc.org> 
<csdc-viprgst-test.core.oclc.org> local domain socket path is /home/narasims/.ansible/pc/87eb7de594
<csdc-viprgst-test.core.oclc.org> socket_path: /home/narasims/.ansible/pc/87eb7de594
Using module file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_command.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: narasims
<localhost> EXEC /bin/sh -c '/home/narasims/.virtenv/Python36_Ansible29_NET/bin/python3 && sleep 0'
The full traceback is:
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 719, in main
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 659, in exec_module
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 437, in exec_module
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 599, in execute
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 508, in execute
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 582, in _execute
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 602, in execute_on_device
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/module_utils/network/f5/common.py", line 168, in run_commands
    raise F5ModuleError(to_text(err, errors='surrogate_then_replace'))
fatal: [csdc-viprgst-test.core.oclc.org]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "chdir": null,
            "commands": [
                "bash",
                "cpcfg --source=HD1.3 --reboot HD1.1"
            ],
            "interval": 1,
            "match": "all",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "csdc-viprgst-test.core.oclc.org",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "user": "root",
                "validate_certs": false
            },
            "retries": 10,
            "transport": "rest",
            "wait_for": null,
            "warn": true
        }
    }
}

MSG:

tmsh -c "cpcfg --source=HD1.3 --reboot HD1.1"
Syntax Error: unexpected argument "cpcfg"
[root@csdc-viprgst-test:/S1-green-P::ForcedOffline:In Sync] config # 
META: ran handlers
META: ran handlers
'''
##### STEPS TO REPRODUCE

```
           - name: Ensure an existing image is activated in specified volume
             bigip_command:
               commands:
                 - "cpcfg --source={{ used_HD }} --reboot {{ unused_HD }}"
               provider:
                 server: "{{ bigip_ltm_standby_loadbalancer }}"
                 user: root
                 password: "{{ f5_root_password }}"
                 validate_certs: no
                 transport: cli
             delegate_to: localhost
```

##### EXPECTED RESULTS

'''
should copy the config to the new boot and reboot it.
##### ACTUAL RESULTS

```
TASK [Ensure an existing image is activated in specified volume] ************************************************************************************************************************************************************************
task path: /home/narasims/NET/playbooks/f5-upgrade_HA-pair.yml:84
skipping: [dsdc-viprgst-test.core.oclc.org] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
<localhost> connection transport is cli
<csdc-viprgst-test.core.oclc.org> using connection plugin network_cli
<csdc-viprgst-test.core.oclc.org> starting connection from persistent connection plugin
<csdc-viprgst-test.core.oclc.org> local domain socket does not exist, starting it
<csdc-viprgst-test.core.oclc.org> control socket path is /home/narasims/.ansible/pc/87eb7de594
<csdc-viprgst-test.core.oclc.org> local domain socket listeners started successfully
<csdc-viprgst-test.core.oclc.org> unable to load cliconf for network_os bigip
<csdc-viprgst-test.core.oclc.org> 
<csdc-viprgst-test.core.oclc.org> local domain socket path is /home/narasims/.ansible/pc/87eb7de594
<csdc-viprgst-test.core.oclc.org> socket_path: /home/narasims/.ansible/pc/87eb7de594
Using module file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_command.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: narasims
<localhost> EXEC /bin/sh -c '/home/narasims/.virtenv/Python36_Ansible29_NET/bin/python3 && sleep 0'
The full traceback is:
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 719, in main
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 659, in exec_module
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 437, in exec_module
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 599, in execute
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 508, in execute
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 582, in _execute
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 602, in execute_on_device
  File "/tmp/ansible_bigip_command_payload_3rcclbxu/ansible_bigip_command_payload.zip/ansible/module_utils/network/f5/common.py", line 168, in run_commands
    raise F5ModuleError(to_text(err, errors='surrogate_then_replace'))
fatal: [csdc-viprgst-test.core.oclc.org]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "chdir": null,
            "commands": [
                "bash",
                "cpcfg --source=HD1.3 --reboot HD1.1"
            ],
            "interval": 1,
            "match": "all",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "csdc-viprgst-test.core.oclc.org",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "user": "root",
                "validate_certs": false
            },
            "retries": 10,
            "transport": "rest",
            "wait_for": null,
            "warn": true
        }
    }
}

MSG:

tmsh -c "cpcfg --source=HD1.3 --reboot HD1.1"
Syntax Error: unexpected argument "cpcfg"
[root@csdc-viprgst-test:/S1-green-P::ForcedOffline:In Sync] config # 
META: ran handlers
META: ran handlers

```

**Comment by nmenant** [comment]
bigip_command will try to run TMSH command by default. cpcfg is to be triggered from bash. 

instead of doing: 

```
bigip_command:
  commands:
    - "cpcfg --source={{ used_HD }} --reboot {{ unused_HD }}"
```

Try something like: 
``` 
bigip_command:
  commands:
    - run /util bash -c "cpcfg --source={{ used_HD }} --reboot {{ unused_HD }}"
``` 

Let us know how it goes

**Comment by narasims** [comment]
Thank you will try that and give you an update.

**Comment by narasims** [comment]
Unfortunately when I ran that. it's giving me the result of the help

'''
TASK [Ensure an existing image is activated in specified volume] ************************************************************************************************************************************************************************
task path: /home/narasims/NET/playbooks/f5-upgrade_HA-pair.yml:84
skipping: [dsdc-viprgst-test.core.oclc.org] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
<localhost> connection transport is cli
<csdc-viprgst-test.core.oclc.org> using connection plugin network_cli
<csdc-viprgst-test.core.oclc.org> starting connection from persistent connection plugin
<csdc-viprgst-test.core.oclc.org> local domain socket does not exist, starting it
<csdc-viprgst-test.core.oclc.org> control socket path is /home/narasims/.ansible/pc/b5ded23820
<csdc-viprgst-test.core.oclc.org> local domain socket listeners started successfully
<csdc-viprgst-test.core.oclc.org> unable to load cliconf for network_os bigip
<csdc-viprgst-test.core.oclc.org> 
<csdc-viprgst-test.core.oclc.org> local domain socket path is /home/narasims/.ansible/pc/b5ded23820
<csdc-viprgst-test.core.oclc.org> socket_path: /home/narasims/.ansible/pc/b5ded23820
Using module file /home/narasims/.virtenv/Python36_Ansible29_NET/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_command.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: narasims
<localhost> EXEC /bin/sh -c '/home/narasims/.virtenv/Python36_Ansible29_NET/bin/python3 && sleep 0'
[WARNING]: Using "write" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not exist, then please file a bug. The command in question is "run /util bash -c cpcfg
--source=HD1.1 -..."
ok: [csdc-viprgst-test.core.oclc.org] => {
    "changed": false,
    "executed_commands": [
        "tmsh -c \"run /util bash -c cpcfg --source=HD1.1 --reboot HD1.3\""
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "commands": [
                "run /util bash -c cpcfg --source=HD1.1 --reboot HD1.3"
            ],
            "interval": 1,
            "match": "all",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "csdc-viprgst-test.core.oclc.org",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "cli",
                "user": "root",
                "validate_certs": false
            },
            "retries": 10,
            "transport": "rest",
            "wait_for": null,
            "warn": true
        }
    }
}

STDOUT:

['info: No source location specified; using active location (HD1.1) by default \nUsage: /sbin/cpcfg [options] <destination image location>\n  Options:\n    --source=SLOT : Get configuration from specified slot (eg: HD1.1)\n    --verbose     : Increase verbose level (cumulative)\n    --reboot      : Immediately switch to target location after transferring configuration.']
META: ran handlers
META: ran handlers
'''
I ran the same command manually from the command line

'''
[root@csdc-viprgst-test:/S1-green-P::ForcedOffline:Disconnected] config # tmsh
root@(csdc-viprgst-test)(cfg-sync Disconnected)(/S1-green-P::ForcedOffline)(/Common)(tmos)# run /util bash -c cpcfg --source=HD1.1 --reboot HD1.3
info: No source location specified; using active location (HD1.1) by default 
Usage: /sbin/cpcfg [options] <destination image location>
  Options:
    --source=SLOT : Get configuration from specified slot (eg: HD1.1)
    --verbose     : Increase verbose level (cumulative)
    --reboot      : Immediately switch to target location after transferring configuration.

root@(csdc-viprgst-test)(cfg-sync Disconnected)(/S1-green-P::ForcedOffline)(/Common)(tmos)# run /util bash -c cpcfg --help
info: No source location specified; using active location (HD1.1) by default 
Usage: /sbin/cpcfg [options] <destination image location>
  Options:
    --source=SLOT : Get configuration from specified slot (eg: HD1.1)
    --verbose     : Increase verbose level (cumulative)
    --reboot      : Immediately switch to target location after transferring configuration.
'''

**Comment by darkrain42** [comment]
@narasims, I believe you need to include the double-quotes around the `cpcfg ...` invocation.  Bash's -c argument expects a single next argument to be a command_string (which is what's run), but without the quotes, that next argument is _just_ the 'cpcfg' command itself, and none of its arguments.

```
root@(bigip1)(cfg-sync Standalone)(Active)(/Common)(tmos)# run util bash -c echo hi

root@(bigip1)(cfg-sync Standalone)(Active)(/Common)(tmos)# run util bash -c "echo hi"
hi
root@(bigip1)(cfg-sync Standalone)(Active)(/Common)(tmos)# run util bash -c cpcfg HD1.2
info: No source location specified; using active location (HD1.1) by default
Usage: /usr/sbin/cpcfg [options] <destination image location>
  Options:
    --source=SLOT : Get configuration from specified slot (eg: HD1.1)
    --verbose     : Increase verbose level (cumulative)
    --reboot      : Immediately switch to target location after transferring configuration.

root@(bigip1)(cfg-sync Standalone)(Active)(/Common)(tmos)# run util bash -c "cpcfg HD1.2"
info: No source location specified; using active location (HD1.1) by default
error: tm_install::VolumeSet::VolumeSet_open -- No volumes exist for sda.2 volume set
Could not access configuration destination; sda, 2 .
root@(bigip1)(cfg-sync Standalone)(Active)(/Common)(tmos)#
```

**Comment by pgouband** [comment]
Hi @narasims,
Have you tried the solution provided by @darkrain42?

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
