### ISSUE TITLE
RFE: big_ip license to support BIG-IQ license manager

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#1857]
### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_license

##### SUMMARY

The module is one legged without this capability. This module should support all licensing options.

**Comment by wojtek0806** [comment]
this module is for bigip only not bigiq, have a look at bigiq modules in collection  there is a bunch to manage licenses
