### ISSUE TITLE
tag commits released to Ansible Galaxy with version

### ISSUE THREAD

**Issue by ajsq** [F5Networks/f5-ansible#1858]
##### ISSUE TYPE
 - Documentation Report

##### SUMMARY
There's no way to associate a version of the f5_modules collection on Ansible Galaxy to a commit on github, which complicates determining if issues can be fixed through upgrading and understanding what version fixes are included in.

**Comment by wojtek0806** [comment]
this is because this repository is not 1:1 with galaxy, if you are internal F5 staff ping me on Teams ill direct you to internal repository
