### ISSUE TITLE
Force connection termination

### ISSUE THREAD

**Issue by devnullNZ** [F5Networks/f5-ansible#186]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = 
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
11.6.1
```

##### SUMMARY

To be able to collect a list of current connections and forcibly terminate them
i.e. collect output from bigip.System.Connections.get_list()
and pass the list to bigip.System.Connections.delete_active_connection()

**Comment by wojtek0806** [comment]
@devnullNZ 

I am assuming you mean the connections to a single virtual server? Even with narrowing this down to a single VS, this should be used with caution, as querying connection table on busier systems will lead to instability including CPU at 100% etc.

Are you just terminating connections before you want to put the VS offline?  If not what would be a a reason for clearing all of the connections?

If you need to terminate some clients, then a better approach would be to have a feature to delete VS connections for a given range of Client IPs.

**Comment by devnullNZ** [comment]
@wojtek0806

Clearing the existing connections is part of forcing a failover between data centres. Currently, a script gathers up the server side & client side connections, disables the active pool member, then terminates the existing connections.
In this case, the F5 is being used to front end postgres databases (not my design). So a small number of long lived connections need to be closed in order to get predictable failover.
So having a module that'll give connection info for pools & VIP's & to be able to close those connections would be a very nice addition.

**Comment by devnullNZ** [comment]
I've been looking through the SDK docs, but can't see where I can extract connection info.
I don't see anything similar to Systems.Connections.get_list()
Am I missing something, or is there something more elegant than that now?

**Comment by delgadillo22** [comment]
Looks like more information is needed to understand the requirement and prioritize.

**Comment by devnullNZ** [comment]
@delgadillo22 what would you like? I described the scenario further back in this thread, but basically what I'm wanting to do is identify long lived connections and force a close when a manual failover is required.
The current solution uses custom scripts to collect current serverside & clientside connections for a given VIP, then walk through the list and delete the active connection.
Grabbing this information and then walking a list to close the connections would probably be well suited to a new module

**Comment by caphrim007** [comment]
the suggested way for doing this would be to use the bigip_command module.
