### ISSUE TITLE
[DOC] bigip_device_license document connectivity requirements

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#1863]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
bigip_device_license

##### SUMMARY
Please document connectivity requirements to activate.f5.com of ansible and BIG-IP device . 

It is important to remark in the doc that this module can be used from bastion hosts where the BIG-IP device doesn't have Internet access but the bastion host does. This is a common arrangement.

Also, please remove the legacy bigip_license doc from clouddocs.

Thanks

**Comment by focrensh** [comment]
Thanks, tracking doc update with FMFA-614.

Which doc page are you referring to for removal? I do not see the legacy module listed on our current clouddocs page index:

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/module_index.html

**Comment by alonsocamaro** [comment]
Thanks Forest, this is the doc of the previous module still available https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_license_module.html

**Comment by wojtek0806** [comment]
we will remove that, in the meantime here is proper link to the module you should be using:

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_device_license_module.html#bigip-device-license-module
