### ISSUE TITLE
BIG-IP license removal fails

### ISSUE THREAD

**Issue by vakhanna** [F5Networks/f5-ansible#1866]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_license

##### ANSIBLE VERSION
```
ansible 2.9.10
```

##### PYTHON VERSION

```
Python 3.6.8
```

##### BIGIP VERSION

```
Version     15.1.0.4
```

##### SUMMARY
BIG-IP license removal fails with 'command not found' error

##### STEPS TO REPRODUCE
Running the playbook task for for license removal using  bigip_device_license module.

```
- name: Remove the license from the system
  bigip_device_license:
    state: "absent"
    provider:
      server: "192.168.15.75"
      user: "admin"
      password: "xxxxx"
      validate_certs: no
      server_port: 443
  delegate_to: localhost
  tags: remove_lic
```

##### EXPECTED RESULTS
license removed

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_bigip_device_license_payload_5wge4o2i/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 882, in main
  File "/tmp/ansible_bigip_device_license_payload_5wge4o2i/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 388, in exec_module
  File "/tmp/ansible_bigip_device_license_payload_5wge4o2i/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 574, in absent
  File "/tmp/ansible_bigip_device_license_payload_5wge4o2i/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 416, in remove
  File "/tmp/ansible_bigip_device_license_payload_5wge4o2i/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 771, in remove_from_device
  File "/tmp/ansible_bigip_device_license_payload_5wge4o2i/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 813, in remove_license_from_device
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_eula": false,
            "license_key": null,
            "license_server": "activate.f5.com",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.15.75",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "state": "absent"
        }
    },
    "msg": "/config/bigip.license: line 2: Auth: command not found\n/config/bigip.license: line 16: Usage: command not found\n/config/bigip.license: line 21: Vendor: command not found\n/config/bigip.license: line 25: syntax error near unexpected token `('\n/config/bigip.license: line 25: `active module :               AFM, High Performance VE, 4 vCPUs|ESCRUTZ-SNWQKNA|Routing Bundle, VE|VE, Carrier Grade NAT (AFM ONLY)|PSM, VE'\n"
```

**Comment by wojtek0806** [comment]
please retry by installing latest version of collection

**Comment by alonsocamaro** [comment]
I have installed the dev version of the collection (before I removed my $HOME/.ansible/collections directory) and I experience the same issue:

```
[ucamaro@minikube bigip_device_license]$ ansible-playbook -vvv test1bis-revoke.yaml 
ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ucamaro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAYBOOK: test1bis-revoke.yaml ********************************************************************************************************************************
1 plays in test1bis-revoke.yaml

PLAY [test1] **************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************
task path: /home/ucamaro/bigip_device_license/test1bis-revoke.yaml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ucamaro
<127.0.0.1> EXEC /bin/sh -c 'echo ~ucamaro && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ucamaro/.ansible/tmp `"&& mkdir "` echo /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046 `" && echo ansible-tmp-1601542790.8751197-122954-48642384428046="` echo /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /home/ucamaro/.ansible/tmp/ansible-local-122947b9y8tl0m/tmpa0lbkajp TO /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046/ /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.6 /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ucamaro/.ansible/tmp/ansible-tmp-1601542790.8751197-122954-48642384428046/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [License BIG-IP using a key] *****************************************************************************************************************************
task path: /home/ucamaro/bigip_device_license/test1bis-revoke.yaml:10
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ucamaro
<localhost> EXEC /bin/sh -c 'echo ~ucamaro && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ucamaro/.ansible/tmp `"&& mkdir "` echo /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459 `" && echo ansible-tmp-1601542792.3330855-123030-92739883370459="` echo /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/f5.disabled/bigip_device_license.py
<localhost> PUT /home/ucamaro/.ansible/tmp/ansible-local-122947b9y8tl0m/tmpdkmxk9np TO /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459/AnsiballZ_bigip_device_license.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459/ /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459/AnsiballZ_bigip_device_license.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459/AnsiballZ_bigip_device_license.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ucamaro/.ansible/tmp/ansible-tmp-1601542792.3330855-123030-92739883370459/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_bigip_device_license_payload_sfacu2sr/ansible_bigip_device_license_payload.zip/ansible/modules/bigip_device_license.py", line 882, in main
  File "/tmp/ansible_bigip_device_license_payload_sfacu2sr/ansible_bigip_device_license_payload.zip/ansible/modules/bigip_device_license.py", line 388, in exec_module
  File "/tmp/ansible_bigip_device_license_payload_sfacu2sr/ansible_bigip_device_license_payload.zip/ansible/modules/bigip_device_license.py", line 574, in absent
  File "/tmp/ansible_bigip_device_license_payload_sfacu2sr/ansible_bigip_device_license_payload.zip/ansible/modules/bigip_device_license.py", line 416, in remove
  File "/tmp/ansible_bigip_device_license_payload_sfacu2sr/ansible_bigip_device_license_payload.zip/ansible/modules/bigip_device_license.py", line 771, in remove_from_device
  File "/tmp/ansible_bigip_device_license_payload_sfacu2sr/ansible_bigip_device_license_payload.zip/ansible/modules/bigip_device_license.py", line 813, in remove_license_from_device
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_eula": true,
            "license_key": "XWPBD-MKMTO-NWTAG-FOEST-NRKFYCD",
            "license_server": "activate.f5.com",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.20.12",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "state": "absent"
        }
    },
    "msg": "/config/bigip.license: line 2: Auth: command not found\n/config/bigip.license: line 16: Usage: command not found\n/config/bigip.license: line 21: Vendor: command not found\n/config/bigip.license: line 25: syntax error near unexpected token `('\n/config/bigip.license: line 25: `active module :                    APM, Base, VE GBB (500 CCU, 2500 Access Sessions)|WWAABPT-PAOXAXY|Anti-Virus Checks|Base Endpoint Security Checks|Firewall Checks|Network Access|Secure Virtual Keyboard|APM, Web Application|Machine Certificate Checks|Protected Workspace|Remote Desktop|App Tunnel'\n"
}

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

You can find the playbook next:

```
[ucamaro@minikube bigip_device_license]$ cat test1bis-revoke.yaml 
---

- name: test1
  hosts: localhost
  connection: local
  collections:
  - f5networks.f5_module

  tasks:
    - name: License BIG-IP using a key
      bigip_device_license:
        license_key: "XWPBD-MKMTO-NWTAG-FOEST-NRKFYCD"
        accept_eula: yes
        state: absent
        provider:
          server: "192.168.20.12"
          user: "admin"
          password: "swanlabs1"
          validate_certs: no
          server_port: 443
      delegate_to: localhost

` ``

**Comment by alonsocamaro** [comment]
Using "revoked" works fine.

**Comment by alonsocamaro** [comment]
I'm afraid I'm not using the expected module, how can I know from the cli which file is ansible using as module?

**Comment by penghon** [comment]
-vvv to see the path to module file?

**Comment by bwearp** [comment]
I get the same error when trying to remove the license using 'state:absent'.
I have installed the latest collection....
Basically I am trying to relicense a device without resetting it to defaults first - is that possible?

**Comment by focrensh** [comment]
@bwearp , have you tried using "revoked" as mentioned above?

**Comment by bwearp** [comment]
Hi. I did. Worked great. Thanks


Kind regards,
Ben Wyatt | Professional Services Consultant
M: +971 (0) 5653 67791
[Absence: 20-31 Dec]
________________________________

**Comment by bwearp** [comment]
Hi - "revoked" seems to have stopped working...

The below task fails with "msg": "Failed to generate license from F5 activation servers."

          - name: Revoke the license from the system
            bigip_device_license:
              state: revoked
              license_key: "{{ bigip_existing_reg_key.stdout }}"
              license_server: "{{ bigip_license_server }}"
              accept_eula: yes
              provider: "{{ provider }}"
            delegate_to: localhost

Whereas using the exact same commands as above but changing it to "present" succeeds.

TASK [Revoke the license from the system] ****************************************************************************************************************************************************************************************************************************************************************
task path: /Users/ben/Dropbox/Ansible/F5 Ansible Automation/xls-to-facts/relicense.yml:28
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ben
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible-${USER}/tmp `"&& mkdir /tmp/.ansible-${USER}/tmp/ansible-tmp-1610350163.969155-96565-251704018994352 && echo ansible-tmp-1610350163.969155-96565-251704018994352="` echo /tmp/.ansible-${USER}/tmp/ansible-tmp-1610350163.969155-96565-251704018994352 `" ) && sleep 0'
Using module file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/modules/network/f5/bigip_device_license.py
<localhost> PUT /Users/ben/.ansible/tmp/ansible-local-96543lldllc_y/tmpx2pbrqfi TO /private/tmp/.ansible-ben/tmp/ansible-tmp-1610350163.969155-96565-251704018994352/AnsiballZ_bigip_device_license.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/.ansible-ben/tmp/ansible-tmp-1610350163.969155-96565-251704018994352/ /tmp/.ansible-ben/tmp/ansible-tmp-1610350163.969155-96565-251704018994352/AnsiballZ_bigip_device_license.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /tmp/.ansible-ben/tmp/ansible-tmp-1610350163.969155-96565-251704018994352/AnsiballZ_bigip_device_license.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/.ansible-ben/tmp/ansible-tmp-1610350163.969155-96565-251704018994352/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/lq/hp2d_r012gxbprtfs0_xglqm0000gn/T/ansible_bigip_device_license_payload_0x0413y4/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 882, in main
  File "/var/folders/lq/hp2d_r012gxbprtfs0_xglqm0000gn/T/ansible_bigip_device_license_payload_0x0413y4/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 390, in exec_module
  File "/var/folders/lq/hp2d_r012gxbprtfs0_xglqm0000gn/T/ansible_bigip_device_license_payload_0x0413y4/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 434, in revoke
  File "/var/folders/lq/hp2d_r012gxbprtfs0_xglqm0000gn/T/ansible_bigip_device_license_payload_0x0413y4/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 564, in create
  File "/var/folders/lq/hp2d_r012gxbprtfs0_xglqm0000gn/T/ansible_bigip_device_license_payload_0x0413y4/ansible_bigip_device_license_payload.zip/ansible/modules/network/f5/bigip_device_license.py", line 678, in create_on_device
fatal: [192.168.1.236 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_eula": true,
            "license_key": "Y7573-95439-17649-48519-4241651",
            "license_server": "authem.f5net.com",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.1.236",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "state": "revoked"
        }
    },
    "msg": "Failed to generate license from F5 activation servers."
}
...ignoring

TASK [License BIG-IP using a key] ************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/ben/Dropbox/Ansible/F5 Ansible Automation/xls-to-facts/relicense.yml:38
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ben
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible-${USER}/tmp `"&& mkdir /tmp/.ansible-${USER}/tmp/ansible-tmp-1610350197.628779-96652-261366441529163 && echo ansible-tmp-1610350197.628779-96652-261366441529163="` echo /tmp/.ansible-${USER}/tmp/ansible-tmp-1610350197.628779-96652-261366441529163 `" ) && sleep 0'
Using module file /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible/modules/network/f5/bigip_device_license.py
<localhost> PUT /Users/ben/.ansible/tmp/ansible-local-96543lldllc_y/tmp42un38kt TO /private/tmp/.ansible-ben/tmp/ansible-tmp-1610350197.628779-96652-261366441529163/AnsiballZ_bigip_device_license.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/.ansible-ben/tmp/ansible-tmp-1610350197.628779-96652-261366441529163/ /tmp/.ansible-ben/tmp/ansible-tmp-1610350197.628779-96652-261366441529163/AnsiballZ_bigip_device_license.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /tmp/.ansible-ben/tmp/ansible-tmp-1610350197.628779-96652-261366441529163/AnsiballZ_bigip_device_license.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/.ansible-ben/tmp/ansible-tmp-1610350197.628779-96652-261366441529163/ > /dev/null 2>&1 && sleep 0'
ok: [192.168.1.236 -> localhost] => {
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_eula": true,
            "license_key": "Y7573-95439-17649-48519-4241651",
            "license_server": "authem.f5net.com",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.1.236",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "state": "present"
        }
    }
}
