### ISSUE TITLE
bigip_policy_rule: add action type "remove"

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#1867]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_policy_rule

##### ANSIBLE VERSION

```
ansible 2.9.9
```

##### PYTHON VERSION

```
python version = 3.6.8 
```

##### BIGIP VERSION

```
14.1.2.6
```

#### OS / ENVIRONMENT

N/A
##### SUMMARY

Please add the action type "remove"
Goal: be able to configure a rule such as:

```
rules {
        default {
            actions {
                0 {
                    http-header
                    response
                    remove
                    name test-header
                }
            }
            description default
        }
    }
```
An implementation of the following scenarios would be appreciated:
- Remove HTTP-Header <named> at Request
- Remove HTTP-Header <named> at Response
- Remove HTTP-Cookie <named> at Request
- Remove HTTP-Set-Cookie <named> at Response
- Remove HTTP-Referer <named> at Request

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking via FMFA-640

**Comment by amolari** [comment]
Tested this new feature and found this issue (BIGIP v14.1.3.1):

f I'm in the following situation:

1) on my bigip I have this LTM policy/rule configure:

)# list ltm policy mainHTTPS_policy rules { default }
ltm policy mainHTTPS_policy {
    rules {
        default {
            actions {
                0 {
                    tcl
                    request
                    set-variable
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression 1
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name ltm_policy_default_rule_matched
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
                1 {
                    http-header
                    response
                    remove
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression none
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name X-Pingback
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
            }
            app-service none
            description default
            ordinal 0
            conditions none
        }
    }
}



Then I run my playbook but it contains only the action "set-variable" (so, what is rule 0):
Here the invocation

{
    "actions": [
        {
            "type": "ignore"
        }
    ],
    "conditions": [
        {
            "type": "all_traffic"
        }
    ],
    "changed": false,
    "invocation": {
        "module_args": {
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "3.250.235.136",
                "user": "my-admin",
                "validate_certs": false,
                "server_port": 8443,
                "no_f5_teem": true,
                "transport": "rest",
                "timeout": null,
                "auth_provider": null
            },
            "name": "default",
            "description": "default",
            "policy": "mainHTTPS_policy",
            "partition": "Common",
            "conditions": [
                {
                    "type": "all_traffic",
                    "path_begins_with_any": null,
                    "host_begins_with_any": null,
                    "host_ends_with_any": null,
                    "host_is_any": null,
                    "host_is_not_any": null,
                    "server_name_is_any": null,
                    "event": null
                }
            ],
            "actions": [
                {
                    "type": "set_variable",
                    "variable_name": "ltm_policy_default_rule_matched",
                    "expression": "1",
                    "event": "request",
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "http_header": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                }
            ],
            "state": "present"
        }
    },
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {}
}


As you see, no change is detected => result is that my rule is not changed.


The same, if I have this default policy configured on my bigip:

ltm policy mainHTTPS_policy {
    rules {
        default {
            actions {
                0 {
                    tcl
                    request
                    set-variable
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression 1
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name ltm_policy_default_rule_matched
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
                1 {
                    http-header
                    response
                    remove
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression none
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name X-Pingback
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
                2 {
                    http-header
                    response
                    remove
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression none
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name X-Generator
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
                3 {
                    http-header
                    response
                    remove
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression none
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name X-Drupal-Cache
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
            }
            app-service none
            description default
            ordinal 0
            conditions none
        }
    }
}


and then I run my playbook without what is rule 3:

{
    "actions": [
        {
            "type": "ignore"
        }
    ],
    "conditions": [
        {
            "type": "all_traffic"
        }
    ],
    "changed": false,
    "invocation": {
        "module_args": {
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "3.250.235.136",
                "user": "my-admin",
                "validate_certs": false,
                "server_port": 8443,
                "no_f5_teem": true,
                "transport": "rest",
                "timeout": null,
                "auth_provider": null
            },
            "name": "default",
            "description": "default",
            "policy": "mainHTTPS_policy",
            "partition": "Common",
            "conditions": [
                {
                    "type": "all_traffic",
                    "path_begins_with_any": null,
                    "host_begins_with_any": null,
                    "host_ends_with_any": null,
                    "host_is_any": null,
                    "host_is_not_any": null,
                    "server_name_is_any": null,
                    "event": null
                }
            ],
            "actions": [
                {
                    "type": "set_variable",
                    "variable_name": "ltm_policy_default_rule_matched",
                    "expression": "1",
                    "event": "request",
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "http_header": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                },
                {
                    "type": "remove",
                    "http_header": {
                        "name": "X-Pingback",
                        "event": "response",
                        "value": null
                    },
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "event": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "expression": null,
                    "variable_name": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                },
                {
                    "type": "remove",
                    "http_header": {
                        "name": "X-Generator",
                        "event": "response",
                        "value": null
                    },
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "event": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "expression": null,
                    "variable_name": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                }
            ],
            "state": "present"
        }
    },
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {}
}

As you see, no change is detected => result is that my rule is not changed.


On the other hand, if I change the http_header names in my playbook and run it:

{
    "actions": [
        {
            "type": "ignore"
        }
    ],
    "conditions": [
        {
            "type": "all_traffic"
        }
    ],
    "changed": true,
    "invocation": {
        "module_args": {
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "3.250.235.136",
                "user": "my-admin",
                "validate_certs": false,
                "server_port": 8443,
                "no_f5_teem": true,
                "transport": "rest",
                "timeout": null,
                "auth_provider": null
            },
            "name": "default",
            "description": "default",
            "policy": "mainHTTPS_policy",
            "partition": "Common",
            "conditions": [
                {
                    "type": "all_traffic",
                    "path_begins_with_any": null,
                    "host_begins_with_any": null,
                    "host_ends_with_any": null,
                    "host_is_any": null,
                    "host_is_not_any": null,
                    "server_name_is_any": null,
                    "event": null
                }
            ],
            "actions": [
                {
                    "type": "set_variable",
                    "variable_name": "ltm_policy_default_rule_matched",
                    "expression": "1",
                    "event": "request",
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "http_header": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                },
                {
                    "type": "remove",
                    "http_header": {
                        "name": "X-PingbackNEW",
                        "event": "response",
                        "value": null
                    },
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "event": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "expression": null,
                    "variable_name": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                },
                {
                    "type": "remove",
                    "http_header": {
                        "name": "X-GeneratorNEW",
                        "event": "response",
                        "value": null
                    },
                    "pool": null,
                    "node": null,
                    "asm_policy": null,
                    "virtual": null,
                    "location": null,
                    "event": null,
                    "cookie_insert": null,
                    "cookie_expiry": null,
                    "expression": null,
                    "variable_name": null,
                    "http_referer": null,
                    "http_set_cookie": null,
                    "http_cookie": null
                }
            ],
            "state": "present"
        }
    },
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {}
}

This change is detected => result is that my rule is changed on the bigip:


ltm policy mainHTTPS_policy {
    rules {
        default {
            actions {
                0 {
                    tcl
                    request
                    set-variable
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression 1
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name ltm_policy_default_rule_matched
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
                1 {
                    http-header
                    response
                    remove
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression none
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name X-PingbackNEW
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
                2 {
                    http-header
                    response
                    remove
                    app-service none
                    application none
                    category none
                    clone-pool none
                    code 0
                    content none
                    domain none
                    expiry none
                    expiry-secs 0
                    expression none
                    extension none
                    facility none
                    from-profile none
                    host none
                    ifile none
                    internal-virtual none
                    ip-address none
                    key none
                    length 0
                    location none
                    member none
                    message none
                    name X-GeneratorNEW
                    netmask none
                    nexthop none
                    node none
                    offset 0
                    path none
                    policy none
                    pool none
                    port 0
                    priority none
                    profile none
                    protocol none
                    query-string none
                    rateclass none
                    scheme none
                    script none
                    snat none
                    snatpool none
                    status 0
                    text none
                    timeout 0
                    value none
                    virtual none
                    vlan none
                    vlan-id 0
                }
            }
            app-service none
            description default
            ordinal 0
            conditions none
        }
    }
}
