### ISSUE TITLE
bigip_profile_http header_erase should not require a header key:value pair

### ISSUE THREAD

**Issue by andybotting** [F5Networks/f5-ansible#1869]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
bigip_profile_http

##### ANSIBLE VERSION
```
ansible 2.9.12
  config file = /home/andy/usr/nectar/source/nectar-ansible/ansible.cfg
  configured module search path = ['/home/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andy/usr/nectar/source/nectar-ansible/.tox/testenv/lib/python3.8/site-packages/ansible
  executable location = .tox/testenv/bin/ansible
  python version = 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]

```

##### PYTHON VERSION
```
Python 3.8.5
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.5
  Build       0.0.8
  Edition     Point Release 5
  Date        Mon Aug 24 01:16:01 PDT 2020

```

##### CONFIGURATION
```
        bigip_profile_http:
          name: https
          provider: "{{ provider }}"
          header_erase: X-Forwarded-Proto
          header_insert: 'X-Forwarded-Proto: https'
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When trying to configure a http profile with the `Request Header Erase` option, it fails with the `Invalid header format` error if the given value is not a key: value pair. 

This restriction may be valid for `Request Header Insert`, but in the case of erasing a header, you may want to just specify the key to erase the header with any given value.

In our specific case, we want to specify:
```
Request Header Erase = X-Forwarded-Proto
Request Header Insert = X-Forwarded-Proto: https
```
so that any X-Forwarded-Proto headers are stripped before we add our own.

##### STEPS TO REPRODUCE
See the config above.

##### EXPECTED RESULTS
Key without a specific value is accepted (which is fine when configured on the device directly)

##### ACTUAL RESULTS
```
FAILED! => {"changed": false, "msg": "Invalid header format: X-Forwarded-Proto"}
```

**Comment by andybotting** [comment]
Commenting out the line:
```
 984         check_header_validity(header_erase)
```
in `bigip_profile_http.py` seems to resolve my issue.

**Comment by focrensh** [comment]
Tracking via FMFA-638

**Comment by wojtek0806** [comment]
i believe you were working on wrong version of collection, this issue was fixed last year: https://github.com/F5Networks/f5-ansible/pull/1533
