### ISSUE TITLE
bigip_remote_syslog gives SNMP error

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#187]
Trying the following:

```
- name: Syslog servers on BIG-IP
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Add Syslog
    bigip_remote_syslog:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      remote_host: "{{item.host}}"
      remote_port: "{{item.port}}"
    with_items:
     - { host: "144.20.92.35", port: "514" }
     - { host: "40.84.158.3", port: "514" }
     - { host: "10.243.127.163", port: "514" }
    delegate_to: localhost

Error that it is giving is on SNMP:
failed: [10.192.73.218 -> localhost] (item={u'host': u'144.20.92.35', u'port': u'514'}) => {"failed": true, "item": {"host": "144.20.92.35", "port": "514"}, "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/sys/snmp/\nText: u'{\"code\":400,\"message\":\"one or more properties must be specified\",\"errorStack\":[],\"apiError\":26214401}'"}

**Comment by mcgonagle** [comment]
https://github.com/mcgonagle/ansible_f5/issues/11

**Comment by caphrim007** [comment]
@payalsin this should no longer be an issue

**Comment by adonerok** [comment]
This module does not work. Getting the same error as above.
fatal: [f5ltm01.domain.com -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "local_ip": "172.16.10.21",
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "remote_host": "1.1.1.1",
            "remote_port": "514",
            "server": "f5ltm01.domain.com",
            "server_port": 443,
            "state": "present",
            "user": "admin",
            "validate_certs": false

**Comment by caphrim007** [comment]
@adonerok do not comment on closed issues. Please file a new issue if there is a problem
