### ISSUE TITLE
APM automation

### ISSUE THREAD

**Issue by xbill42** [F5Networks/f5-ansible#1870]
##### ISSUE TYPE
 - question about features

##### COMPONENT NAME
APM

##### SUMMARY
I would like to know what would be possible to do with ansible regarding APM automation ?
I know that it is also limited by the fact that the creation of a complete policy on a bigip is done using the VPM and not using tmsh commands.

Maybe would it be just possible to attach a manually created APM policy to a VS using ansible ?

**Comment by focrensh** [comment]
There are no short term goals for adding APM through the virtualserver module. One current way to accomplish this would be by uploading the APM policy either through Ansible or AS3, and then referencing it within an AS3 declaration.
