### ISSUE TITLE
SNMP v3 Trap support is needed to use secure protocols

### ISSUE THREAD

**Issue by KernelPicnic** [F5Networks/f5-ansible#1879]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_snmp_trap
##### ANSIBLE VERSION

```
ansible 2.9.10

```

##### PYTHON VERSION

```
python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### BIGIP VERSION

```
14.1.2.8
```

##### OS / ENVIRONMENT

Ubuntu 20 Server 5.4.0-47-generic #51-Ubuntu 
##### SUMMARY

Only supports v1 and v2c. 
v3 support is needed to run secure protocols.
##### STEPS TO REPRODUCE

```
snmp_versionstring, Choices:1,2c
----



```

##### EXPECTED RESULTS

v3 support and documentation for it.

##### ACTUAL RESULTS

```

```

**Comment by nmenant** [comment]
Thanks for your feedback, it has been added to our backlog. Tracking internally with ID FMFA-643

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version, it should work. If not, please reach out, thanks!
