### ISSUE TITLE
Unsupported parameters - ssh_keyfile being added by f5 module

### ISSUE THREAD

**Issue by BDworak** [F5Networks/f5-ansible#1882]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_user

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sc-dc365/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
user@(network-device)(cfg-sync Standalone)(Active)(/Common)(tmos)# show sys version

Sys::Version
Main Package
Product BIG-IP
Version 12.1.3.4
Build 0.124.2
Edition Engineering Hotfix
Date Sat Jul 11 17:55:56 PDT 2020



Hotfix List
ID597899-1 ID905905-5 ID678103-2 ID895525-6 ID895993-6 ID723794
ID631334-4 ID598204-3 ID895981-6 ID681184-1 ID895881-5 ID705112-1
ID499404-7
```

##### CONFIGURATION

We are invoking an f5 module with no additional configuration changes. Specific to this issue, we checked ansible.cfg for an ssh_keyfile being set and it is not present. 

##### OS / ENVIRONMENT

This is being run on RHEL 7.7 and executed from Ansible Tower 3.4.3. 

##### SUMMARY

When running the bigip_user module, the module says that ssh_keyfile parameter was passed but is not supported. In our tests ssh_keyfile is not being passed in by us, we don't have it configured anywhere, and additionally it is set to "null". We created a test playbook where we explicitly set provider(example below) and omit setting the ssh_keyfile, yet somehow in the execution pipeline the bigip_user module is invoked with a ssh_keyfile parameter causing this error to occur. 

Here is the error the module is throwing: "msg": "Unsupported parameters for (f5networks.f5_modules.bigip_user) module: ssh_keyfile found in provider. Supported parameters include: auth_provider, password, server, server_port, timeout, transport, user, validate_certs",

##### STEPS TO REPRODUCE

Create a playbook with the below task, referencing the f5 module bigip_users and pass in providers manually, omitting an ssh_keyfile parameter then (if possible) run the playbook in Ansible Tower. 

```
- name: change admin password
  f5networks.f5_modules.bigip_user:
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ cli_username }}"
      password: "{{ cli_password }}"
      transport: rest
      validate_certs: no
      timeout: 50
    state: present
    username_credential: admin
    password_credential: "{{ enable_pass }}"
    register: applied_lines_admin
```

##### EXPECTED RESULTS

The ssh_keyfile is being added somehow by ansible and we cannot figure out where. Wondering if maybe the f5 module is somehow adding it to the provider and creating this error. As you can see from the example provided above we are not passing in an ssh_keyfile, but when it executes the module shows a "ssh_keyfile: null" was passed in.

##### ACTUAL RESULTS

```
{
    "invocation": {
        "module_args": {
            "update_password": "always",
            "shell": null,
            "password_credential": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "partition_access": null,
            "partition": "Common",
            "state": "present",
            "full_name": null,
            "provider": {
                "ssh_keyfile": null,
                "timeout": 50,
                "auth_provider": null,
                "server": "network_device",
                "user": "f5user",
                "server_port": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false,
                "transport": "rest"
            },
            "username_credential": "admin"
        }
    },
    "msg": "Unsupported parameters for (f5networks.f5_modules.bigip_user) module: ssh_keyfile found in provider. Supported parameters include: auth_provider, password, server, server_port, timeout, transport, user, validate_certs",
    "changed": false,
    "_ansible_no_log": false,
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }
}
```

```
"msg": "Unsupported parameters for (f5networks.f5_modules.bigip_user) module: ssh_keyfile found in provider. Supported parameters include: auth_provider, password, server, server_port, timeout, transport, user, validate_certs",
```

**Comment by wojtek0806** [comment]
already answered here: https://github.com/F5Networks/f5-ansible/issues/1804
