### ISSUE TITLE
bigip_policy_rule: Additional Conditions and Actions

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1883]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_policy_rule

##### SUMMARY
Please add the following conditions: "path is" when selecting http_uri as type and "host is" when selecting http_host as type.

Please add action "Replace" to the list of actions.

**Comment by focrensh** [comment]
Tracking via FMFA-665

**Comment by VeselaHouba** [comment]
+1 , especially the `path_is` in addition to already implemented `path_begins_with_any` is crucial, as we need to use policy for redirecting 
```
/login
```
to
``` 
/login/
```
which would result in loop using `path_begins_with_any`

thanks in advance!
