### ISSUE TITLE
Add connection-limit to bigip_virtual_server module

### ISSUE THREAD

**Issue by jeffl2017** [F5Networks/f5-ansible#1892]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION
```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/testuser/.ansible/plugins/modules', u                                                                             '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]

```

##### PYTHON VERSION

```
Python 2.7.17
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3.4
  Build       0.0.5
  Edition     Point Release 4
  Date        Tue Jun 16 14:26:18 PDT 2020

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Need to add an option to be able to set the connection-limit on BIG-IP Virtual Servers.  There are settings exposed for the rate-limit but not the connection-limit.  This is required by Federal Customers.

##### STEPS TO REPRODUCE

ltm virtual /Logging/GEF_Encrypted_Syslog_Lab1214A_vs {
    connection-limit 500
    destination 172.16.50.2:514
    ip-protocol tcp
    mask 255.255.255.255
    partition Logging
    pool /Logging/GEF_Encrypted_Syslog_pool
    profiles {
        STIG_f5-tcp-progressive { }
    }
    rate-limit 500
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
    vlans {
        GEF_securelog_private_vlan
    }
    vlans-enabled
    vs-index 3
}

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking via FMFA-662

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
