### ISSUE TITLE
Add remaining parameters for HTTP Analytics Profile

### ISSUE THREAD

**Issue by jeffl2017** [F5Networks/f5-ansible#1893]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_profile_analytics

##### ANSIBLE VERSION

```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/testuser/.ansible/plugins/modules', u                                                                             '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]

```

##### PYTHON VERSION
```
Python 2.7.17

```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3.4
  Build       0.0.5
  Edition     Point Release 4
  Date        Tue Jun 16 14:26:18 PDT 2020

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
bigip_profile_analytics does have all the settings available.  Need to add the remaining settings:

"collectHttpTimingMetrics": "enabled",
"collectMethods": "enabled",
"collectOsAndBrowser": "enabled",
"collectResponseCodes": "enabled",
"sampling": "enabled",
"sessionTimeoutMinutes": "##"

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
Tracking via FMFA-661

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
