### ISSUE TITLE
bigip_vlan

### ISSUE THREAD

**Issue by hemskgren** [F5Networks/f5-ansible#19]
Hi

I installed latest f5-ansible and f5-common-python today and get this.  
An other older installation works.

Regards
Christer
>>>

ansible-playbook -vvv f5-make.yml
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: f5-make.yml **********************************************************
3 plays in f5-make.yml

PLAY [Deploy customer in loadbalancer] *****************************************

PLAY [Create VLAN in I LB] ***************************************************

TASK [Add vlan on pod LB trunk (vPC37)] ****************************************
task path: /home/xx/dev/f5-make.yml:25
<i-p0-lb01> ESTABLISH LOCAL CONNECTION FOR USER: xx
<i-p0-lb01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466715236.73-198574109131084 `" && echo ansible-tmp-1466715236.73-198574109131084="` echo $HOME/.ansible/tmp/ansible-tmp-1466715236.73-198574109131084 `" ) && sleep 0'
<i-p0-lb01> PUT /tmp/tmpT16MCc TO /home/xx/.ansible/tmp/ansible-tmp-1466715236.73-198574109131084/bigip_vlan
<i-p0-lb01> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /home/xx/.ansible/tmp/ansible-tmp-1466715236.73-198574109131084/bigip_vlan; rm -rf "/home/xx/.ansible/tmp/ansible-tmp-1466715236.73-198574109131084/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_lkoqBq/ansible_module_bigip_vlan.py", line 210, in <module>
    main()
  File "/tmp/ansible_lkoqBq/ansible_module_bigip_vlan.py", line 199, in main
    obj = BigIpVlan(**module.params)
  File "/tmp/ansible_lkoqBq/ansible_module_bigip_vlan.py", line 120, in __init__
    port=kwargs['server_port'])
KeyError: 'server_port'

fatal: [i-p0-lb01]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "bigip_vlan"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lkoqBq/ansible_module_bigip_vlan.py\", line 210, in <module>\n    main()\n  File \"/tmp/ansible_lkoqBq/ansible_module_bigip_vlan.py\", line 199, in main\n    obj = BigIpVlan(**module.params)\n  File \"/tmp/ansible_lkoqBq/ansible_module_bigip_vlan.py\", line 120, in __init__\n    port=kwargs['server_port'])\nKeyError: 'server_port'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by caphrim007** [comment]
which version of ansible? we're building modules off of the 2.x branch of
code

**Comment by hemskgren** [comment]
ansible 2.1.0.0

**Comment by caphrim007** [comment]
hmm, seems to be that the vlan module is incomplete. I should have an updated version by friday that should work

**Comment by caphrim007** [comment]
can you check to see what the contents of your f5.py module is in your ansible module_utils/network/ directory? It should include verbiage for server_port.

**Comment by hemskgren** [comment]
correct, server_port was missing.

**Comment by caphrim007** [comment]
That might have come in one of the recent roll-up releases? Or maybe it's
slated for 2.2

**Comment by caphrim007** [comment]
@hemskgren I pushed an updated version of the bigip_vlan where I suspect that all functionality is now there. Can you check?

**Comment by hemskgren** [comment]
Hi

The module works now, 
But I do not understand how to  add a vlan as taged to a interface or trunk!!?

Christer

**Comment by caphrim007** [comment]
@hemskgren is this what you were looking for? https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_vlan.py#L32
