### ISSUE TITLE
Undocumented requirement (ansible.netcommon)

### ISSUE THREAD

**Issue by inversecow** [F5Networks/f5-ansible#1904]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

N/A
##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user_a/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
N/A
```

##### CONFIGURATION

Stock.
##### OS / ENVIRONMENT

"N/A"

##### SUMMARY

We are attempting to source & install the `f5networks.f5_modules` collection into an "air-gapped" environment (*Ansible Tower: Isolation nodes*), which do not have internet access.
In the process of sourcing & installing, an undocumented dependency was noted (for `ansible.netcommon`).

##### STEPS TO REPRODUCE

```
sudo ansible-galaxy collection install -vvvv /home/"$USER"/staging/f5networks-f5_modules-1.6.0.tar.gz -p /usr/share/ansible/collections/;
```

##### EXPECTED RESULTS

```
Installing 'f5networks.f5_modules:1.6.0' to '/usr/share/ansible/collections/ansible_collections/f5networks/f5_modules'
```

##### ACTUAL RESULTS

Initial results posted, obtained / installed `ansible.netcommon` collection, re-ran again (results also below).

Before installing `ansible.netcommon` manually.
```
[10:23:21:user_a@isolated_node:~]
$ sudo ansible-galaxy collection install -vvvv /home/"$USER"/staging/f5networks-f5_modules-1.6.0.tar.gz -p /usr/share/ansible/collections/;
ansible-galaxy 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-galaxy
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Found installed collection netapp.ontap:20.10.0 at '/usr/share/ansible/collections/ansible_collections/netapp/ontap'
Process install dependency map
Processing requirement collection '/home/user_a/staging/f5networks-f5_modules-1.6.0.tar.gz'
Collection requirement '/home/user_a/staging/f5networks-f5_modules-1.6.0.tar.gz' is a tar artifact
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /root/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'ansible.netcommon' - as dependency of f5networks.f5_modules
Collection requirement 'ansible.netcommon' is the name of a collection
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 97] Address family not supported by protocol>
```

After installing `ansible.netcommon` manually (from the [Galaxy repo](https://galaxy.ansible.com/ansible/netcommon)).
```
[10:45:25:user_a@isolated_node:~]
$ sudo ansible-galaxy collection install -vvvv /home/"$USER"/pip/staging/f5networks-f5_modules-1.6.0.tar.gz -p /usr/share/ansible/collections/;
ansible-galaxy 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-galaxy
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Found installed collection ansible.netcommon:1.4.2-dev1 at '/usr/share/ansible/collections/ansible_collections/ansible/netcommon'
Found installed collection netapp.ontap:20.10.0 at '/usr/share/ansible/collections/ansible_collections/netapp/ontap'
Process install dependency map
Processing requirement collection '/home/user_a/staging/f5networks-f5_modules-1.6.0.tar.gz'
Collection requirement '/home/user_a/staging/f5networks-f5_modules-1.6.0.tar.gz' is a tar artifact
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /root/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'ansible.netcommon' - as dependency of f5networks.f5_modules
Collection requirement 'ansible.netcommon' is the name of a collection
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 97] Address family not supported by protocol>
```

**Comment by focrensh** [comment]
There is a supported method using galaxy to download a collection and its dependencies together. You do not need to perform the steps individually as above.

https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#downloading-collections

- ``ansible-galaxy collection download f5networks.f5_modules -p ./collections``
  - This will download the f5 collection along netcommon and create a requirements.yml file within a relative collections folder
```
.
└── collections
    ├── ansible-netcommon-1.4.1.tar.gz
    ├── f5networks-f5_modules-1.6.0.tar.gz
    └── requirements.yml
```

- You can then install the f5 collection along with dependencies using: ``ansible-galaxy collection install -r requirements.yml
``

**Comment by inversecow** [comment]
> There is a supported method using galaxy to download a collection and its dependencies together. You do not need to perform the steps individually as above.
> 
> https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#downloading-collections
> 
> * `ansible-galaxy collection download f5networks.f5_modules -p ./collections`
>   
>   * This will download the f5 collection along netcommon and create a requirements.yml file within a relative collections folder
> 
> ```
> .
> └── collections
>     ├── ansible-netcommon-1.4.1.tar.gz
>     ├── f5networks-f5_modules-1.6.0.tar.gz
>     └── requirements.yml
> ```
> 
> * You can then install the f5 collection along with dependencies using: `ansible-galaxy collection install -r requirements.yml `

Thank you for the prompt reply.

Indeed, I had investigated this option also, however it is currently ill-suited for my present scenario.
Specifically, it requires `ansible-2.10.x` (when galaxy gets the `download` option), where I only have access up to `ansible-2.9.14` in my company EPEL repo.

That said, would sourcing `ansible-netcommon-1.4.1` (instead of 1.4.2 which is "current" in the Galaxy collection) better serve the dependency mapping for the F5 bits?

**Comment by focrensh** [comment]
That should work. If you download the netcommon gz file from galaxy, it actually pulls the dev build currently. The galaxy command downloads the latest stable which is 1.4.1 as you mentioned.

**Comment by inversecow** [comment]
> That should work. If you download the netcommon gz file from galaxy, it actually pulls the dev build currently. The galaxy command downloads the latest stable which is 1.4.1 as you mentioned.

Indeed, when I looked closer I saw the DEV tag in the filename.

To that end, I just sourced in the "latest" stable release (1.4.1), by way of grabbing the tarball from the Galaxy collections page.
I then shipped it into my air-gapped ENV, removed the DEV 1.4.2 install (`sudo rm -rf /usr/share/ansible/collections/ansible_collections/ansible/netcommon/`), and layered the 1.4.1 stable release.

```
[15:36:11:user_a@isolation_node:~]
$ sudo ansible-galaxy collection install /home/"$USER"/pip/staging/ansible-netcommon-1.4.1.tar.gz -p /usr/share/ansible/collections/;
Process install dependency map
Starting collection install process
Installing 'ansible.netcommon:1.4.1' to '/usr/share/ansible/collections/ansible_collections/ansible/netcommon'
```

However, upon re-attempting to install the F5 collection, it "sees" the `ansible.netcommon` collection, but still is unsatisfied on requirements.
Very odd I should think!

```
[15:36:21:user_a@isolation_node:~]
$ sudo ansible-galaxy collection install -vvvv /home/"$USER"/pip/staging/f5networks-f5_modules-1.6.0.tar.gz -p /usr/share/ansible/collections/;
ansible-galaxy 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-galaxy
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Found installed collection ansible.netcommon:1.4.1 at '/usr/share/ansible/collections/ansible_collections/ansible/netcommon'
Found installed collection netapp.ontap:20.10.0 at '/usr/share/ansible/collections/ansible_collections/netapp/ontap'
Process install dependency map
Processing requirement collection '/home/user_a/staging/f5networks-f5_modules-1.6.0.tar.gz'
Collection requirement '/home/user_a/staging/f5networks-f5_modules-1.6.0.tar.gz' is a tar artifact
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /root/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Processing requirement collection 'ansible.netcommon' - as dependency of f5networks.f5_modules
Collection requirement 'ansible.netcommon' is the name of a collection
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 97] Address family not supported by protocol>
```

**Comment by focrensh** [comment]
Please try using the ``--no-deps`` argument when installing. If the correct netcommon version is already installed, then this will tell ansible-galaxy to not check the remote repo for dependencies. I tested this without internet.

```
ansible-galaxy collection install f5networks-f5_modules-1.6.0.tar.gz -p ./collections/ --no-deps
```

**Comment by inversecow** [comment]
Thank you, and confirmed this now works as intended (with the addition of `--no-deps` to command string).
RESOLVED! 👍
