### ISSUE TITLE
bigip_profile_fastl4 parameter module syn-cookie-enable

### ISSUE THREAD

**Issue by gitnetofr** [F5Networks/f5-ansible#1912]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
```
bigip_profile_fastl4
```
##### ANSIBLE VERSION
```
ansible 2.10.1 
collection 1.6.0
```
##### PYTHON VERSION
```
3.8
```

##### BIGIP VERSION
```
Version     15.1.0.5
Build       0.0.8
BIG-IP VE
```
##### CONFIGURATION
```
# default values
[defaults]
inventory                     = ./inventory/
roles_path                    = ./roles/
callback_whitelist            = timer
host_key_checking             = False
force_color                   = 1
ansible_python_interpreter    =/usr/bin/python3
[ssh_connection]
ssh_args = -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no 
```

##### OS / ENVIRONMENT

```
Ubuntu 20.04
```

##### SUMMARY
Request a ansible paramter for module bigip_profile_fastl4.
I can't find the option 'SYN Challenge Handling'. It seems that it is not available.
The tmsh call for the parameter is "tmsh modify ltm profile fastl4 profile-fastL4-name syn-cookie-enable disabled"
Could you add this parameter in the roadmap developpment?

##### STEPS TO REPRODUCE
I want to write a playbook which creates a fastL4 profile configured like that:
tmsh create ltm profile fastl4 profile-fastL4-name defaults-from fastL4 reset-on-timeout enabled loose-close enabled loose-initialization enabled syn-cookie-enable disabled
My playbook is blocked because the parameter syn-cookie-enable is not available.

##### EXPECTED RESULTS
```
root@(opntrrpv-s5014)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm profile fastl4 profile-fastL4-name                                                                         ltm profile fastl4 profile-fastL4-name {
    app-service none
    defaults-from fastL4
    loose-close enabled
    loose-initialization enabled
    reset-on-timeout enabled
    syn-cookie-enable disabled
}
```

**Comment by onurbrc** [comment]
Hi, 

I'm also need this option. Any news? 

Thanks in advance.

**Comment by focrensh** [comment]
Tracking via INFRAANO-40

**Comment by onurbrc** [comment]
Hi, 

Any news about this parameter? 

Thanks.

**Comment by focrensh** [comment]
Currently no update at this time.

**Comment by onurbrc** [comment]
approximate visibility possible? ☺️

**Comment by focrensh** [comment]
Estimate would be within the next 2 releases of the collection.

**Comment by seohs7** [comment]
Hi all, 

I'm also waiting for this evol.

**Comment by onurbrc** [comment]
@focrensh 

Any news about this case? 
In which release did you say that the feature would be available?
#nicetohave 👍

**Comment by focrensh** [comment]
This is possible through our preview collection using AS3 currently at https://galaxy.ansible.com/f5networks/f5_bigip . There is no definitive date still on this collections addition of the parameter. I will update here once there is an update.

**Comment by onurbrc** [comment]
HI @papineni87 , 

I've tested the new version `1.11.0` which has the `syn_cookie_enable`  as new option. 

Before running the Ansible task, I sent a `bigip_device_info`  request  to retrieve the current state of my fastL4 profile. In the results, I got: 

~~~json
 {
            "client_timeout": 30,
            "dont_fragment_flag": "preserve",
            "explicit_flow_migration": "no",
            "full_path": "/internet/fastL4-forwarding",
            "generate_init_seq_number": "no",
            "hardware_syn_cookie": "no",
            "idle_timeout": 300,
            "ip_tos_to_client": "pass-through",
            "ip_tos_to_server": "pass-through",
            "keep_alive_interval": 0,
            "late_binding": "no",
            "link_qos_to_client": "pass-through",
            "link_qos_to_server": "pass-through",
            "loose_close": "yes",
            "loose_init": "yes",
            "mss_override": 0,
            "name": "fastL4-forwarding",
            "parent": "/Common/fastL4",
            "priority_to_client": "pass-through",
            "priority_to_server": "pass-through",
            "pva_acceleration": "full",
            "pva_dynamic_client_packets": 1,
            "pva_dynamic_server_packets": 0,
            "pva_flow_aging": "yes",
            "pva_flow_evict": "yes",
            "pva_offload_dynamic": "yes",
            "pva_offload_state": "embryonic",
            "reassemble_fragments": "no",
            "receive_window": 0,
            "reset_on_timeout": "no",
            "rtt_from_client": "no",
            "rtt_from_server": "no",
            "server_sack": "no",
            "server_timestamp": "no",
            "software_syn_cookie": "no",
            "strip_sack": "no",
            "syn_cookie_enabled": "yes",
            "syn_cookie_mss": 0,
            "syn_cookie_whitelist": "no",
            "tcp_close_timeout": 5,
            "tcp_handshake_timeout": 5,
            "tcp_time_wait_timeout": 0,
            "tcp_timestamp_mode": "preserve",
            "tcp_window_scale_mode": "preserve",
            "timeout_recovery": "disconnect",
            "ttl_mode": "decrement",
            "ttl_v4": 255,
            "ttl_v6": 64
        }
~~~

It tells that by default the option `syn_cookie_enabled` is `yes` already. 
When a list the profile using TMSH, I got: 
```
# list ltm profile fastl4 /internet/fastL4-forwarding    
ltm profile fastl4 /internet/fastL4-forwarding {
    app-service none
    defaults-from fastL4
    loose-close enabled
    loose-initialization enabled
    reset-on-timeout disabled
}
```

The option `syn-cookie-enable` is not visible. 

I'm trying to send the following task below to force the `syn_cookie_enable` become `disable`: 

~~~yaml
- name: "Manage fastL4 profile"
  bigip_profile_fastl4:
    name: "{{ item.name }}"
    syn_cookie_enable: no
    loose_initialization: "{{ item.loose_initialization }}"
    loose_close: "{{ item.loose_close }}"
    reset_on_timeout: "{{ item.reset_on_timeout }}"
    parent: "{{ item.parent | default('/Common/fastL4') }}"
    partition: "{{ item.partition | default('Common') }}"
    provider: "{{ connectionParams }}"
    state: present
 delegate_to: localhost
~~~

However, the current state does not change. The `bigip_device_info` informs that the  `syn_cookie_enable` still is `yes` and the TMSH requests does not show me 
`syn-cookie-enable disabled`. 

Could you help with this? 

# Expected results

```
ltm profile fastl4 /internet/fastL4-forwarding {
    app-service none
    defaults-from fastL4
    loose-close enabled
    loose-initialization enabled
    reset-on-timeout disabled
    syn-cookie-enable enabled
}
```
# Additional question

I'm also wondering if there is a way to change `SYN Challenge Handling` to `Disable Challenges` via this module. Is it possible to do that? Shoud I open a new issue for this? 

Thank you. 
Best regards.

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version, it should work. If not, please reach out, thanks!
