### ISSUE TITLE
Add PKCS 12 support to bigip_ssl_key_cert

### ISSUE THREAD

**Issue by zjpeterson** [F5Networks/f5-ansible#1914]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_ssl_key_cert

##### SUMMARY

The bigip_ssl_key_cert module only accepts PEM-formatted data. Key/certificate combination is a common use case for PKCS 12. Adding this support should be possible, as iControl REST has [an endpoint for registering PKCS #12 key/certificate data](https://clouddocs.f5.com/api/icontrol-rest/APIRef_tm_sys_crypto_pkcs12.html). There is currently no way to use this format with a module in this collection.

**Comment by focrensh** [comment]
Thank you, tracking RFE via INFRAANO-14

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version, it should work. If not, please reach out, thanks!
