### ISSUE TITLE
Connection error with modules from collection and not with builtin F5 module when using no_proxy env variable

### ISSUE THREAD

**Issue by xbill42** [F5Networks/f5-ansible#1924]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
for example bigip_monitor_tcp

##### ANSIBLE VERSION

```
Ansible 2.9.11
AWX 13
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.8
  Build       0.0.7
  Edition     Point Release 8
  Date        Thu Sep 17 22:51:30 PDT 2020
```

##### SUMMARY

Connection error with modules from collection and not with builtin F5 module when using no_proxy environnement variable.

We have a proxy configured in AWX. We use the environment:  no_proxy: "X.X.X.X" to bypass proxy for accessing the F5 at the beginning of the playbook.

The no_proxy works when we use the builtin F5 modules of ansible.
But when using the collection the no_proxy does not work and we get timeouts in the logs.
Also note that the bigip_device_info module works with collection and the no_proxy.

In the logs we can see : socket.timeout: timed out or urllib.error.URLError: <urlopen error timed out>

Complete error logs : https://gist.github.com/xbill42/a7df940be5a245794587d4a798139039

{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1318, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/usr/lib64/python3.6/http/client.py\", line 1254, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1300, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1249, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1036, in _send_output\n    self.send(msg)\n  File \"/usr/lib64/python3.6/http/client.py\", line 974, in send\n    self.connect()\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 417, in connect\n  File \"/usr/lib64/python3.6/socket.py\", line 724, in create_connection\n    raise err\n  File \"/usr/lib64/python3.6/socket.py\", line 713, in create_connection\n    sock.connect(sa)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1606422308.7238119-77-112493145926568/AnsiballZ_bigip_monitor_tcp.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1606422308.7238119-77-112493145926568/AnsiballZ_bigip_monitor_tcp.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1606422308.7238119-77-112493145926568/AnsiballZ_bigip_monitor_tcp.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_monitor_tcp', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_tcp.py\", line 682, in <module>\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_tcp.py\", line 675, in main\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_tcp.py\", line 486, in exec_module\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 99, in send_teem\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 70, in send\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 1390, in open_url\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 448, in https_open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1320, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error timed out>\nException ignored in: <bound method iControlRestSession.__del__ of <ansible_collections.f5networks.f5_modules.plugins.module_utils.icontrol.iControlRestSession object at 0x7f9c180b6860>>\nTraceback (most recent call last):\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 255, in __del__\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 230, in delete\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 194, in send\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 1206, in open\n  File \"/usr/lib64/python3.6/netrc.py\", line 32, in __init__\nNameError: name 'open' is not defined\n",
    "exception": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1318, in do_open\n    encode_chunked=req.has_header('Transfer-encoding'))\n  File \"/usr/lib64/python3.6/http/client.py\", line 1254, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1300, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1249, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1036, in _send_output\n    self.send(msg)\n  File \"/usr/lib64/python3.6/http/client.py\", line 974, in send\n    self.connect()\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 417, in connect\n  File \"/usr/lib64/python3.6/socket.py\", line 724, in create_connection\n    raise err\n  File \"/usr/lib64/python3.6/socket.py\", line 713, in create_connection\n    sock.connect(sa)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1606422308.7238119-77-112493145926568/AnsiballZ_bigip_monitor_tcp.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1606422308.7238119-77-112493145926568/AnsiballZ_bigip_monitor_tcp.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1606422308.7238119-77-112493145926568/AnsiballZ_bigip_monitor_tcp.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_monitor_tcp', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_tcp.py\", line 682, in <module>\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_tcp.py\", line 675, in main\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_tcp.py\", line 486, in exec_module\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 99, in send_teem\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 70, in send\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 1390, in open_url\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 1294, in open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 223, in urlopen\n    return opener.open(url, data, timeout)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 526, in open\n    response = self._open(req, data)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 544, in _open\n    '_open', req)\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 504, in _call_chain\n    result = func(*args)\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 448, in https_open\n  File \"/usr/lib64/python3.6/urllib/request.py\", line 1320, in do_open\n    raise URLError(err)\nurllib.error.URLError: <urlopen error timed out>\nException ignored in: <bound method iControlRestSession.__del__ of <ansible_collections.f5networks.f5_modules.plugins.module_utils.icontrol.iControlRestSession object at 0x7f9c180b6860>>\nTraceback (most recent call last):\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 255, in __del__\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 230, in delete\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 194, in send\n  File \"/tmp/ansible_bigip_monitor_tcp_payload_07drprd6/ansible_bigip_monitor_tcp_payload.zip/ansible/module_utils/urls.py\", line 1206, in open\n  File \"/usr/lib64/python3.6/netrc.py\", line 32, in __init__\nNameError: name 'open' is not defined\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}

When not using F5 collection it works: (removed  the   collections: -  f5networks.f5_modules from the playbook)

TASK [Create TCP Monitor] ******************************************************
task path: /tmp/awx_1235_2imjwn51/project/test_connection.yml:35
<127.0.0.1> connection transport is rest
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756 && echo ansible-tmp-1606411252.4506316-43-64299278935756="` echo /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/f5/bigip_monitor_tcp.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-2_58bt_uc/tmp7us1z0fe TO /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756/AnsiballZ_bigip_monitor_tcp.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756/ /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756/AnsiballZ_bigip_monitor_tcp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'no_proxy=10.10.1.1 /usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756/AnsiballZ_bigip_monitor_tcp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1606411252.4506316-43-64299278935756/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "description": null,
            "interval": null,
            "ip": "*",
            "name": "test-monitor-test",
            "parent": "/Common/tcp",
            "partition": "PROD-INFRA",
            "port": "*",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "10.10.1.1",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "receive": null,…

Also F5 collection works with bigip_device_info and collection

TASK [vip : Collect BIG-IP infos] **********************************************
task path: /tmp/awx_1239_win7ut0u/project/roles/vip/tasks/validate_input.yml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447 && echo ansible-tmp-1606422297.847229-53-174765997731447="` echo /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447 `" ) && sleep 0'
Using module file /tmp/awx_1239_win7ut0u/project/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-2g71hvgrk/tmpasfckqrf TO /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447/AnsiballZ_bigip_device_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447/ /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447/AnsiballZ_bigip_device_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'no_proxy='"'"'10.10.1.1, localhost, 127.0.0.1'"'"' /usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447/AnsiballZ_bigip_device_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1606422297.847229-53-174765997731447/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {

##### STEPS TO REPRODUCE

```

in role meta/main.yml
collections:
  - f5networks.f5_modules

In playbook 
- hosts: localhost
  gather_facts: false
  connection: local

   environment:
     no_proxy: "10.143.177.129"


# this does not work:

- name: Create TCP Monitor
 bigip_monitor_tcp:
   name: "hc_tcp"
   port: "*"
   ip: "*"
   provider: "{{ provider }}"
   state: present


# this works with no proxy

- name: Check that you can connect (GET) to a page
  uri:
    url: https://{{ host }}/
    validate_certs: no
    return_content: yes

- name: Collect BIG-IP infos
  bigip_device_info:
    gather_subset:
      - partitions
      - vlans
      - virtual-servers
      - virtual-addresses
    provider: "{{ provider }}"
  register: bigip_facts

```

##### EXPECTED RESULTS
Collection works as builtin modules when using no_proxy in awx

##### ACTUAL RESULTS

```
Timeouts when modules tries to connect to F5 because it looks like the no_proxy is not taken into account
```

**Comment by wojtek0806** [comment]
i have a fairly good idea where the issue is to verify this please specify this env variable: `F5_TEEM=yes` and see if the problem goes away and report back

**Comment by wojtek0806** [comment]
alternatively you can define `no_f5_teem: yes` in your provider

**Comment by wojtek0806** [comment]
I also noticed the playbook has error (was it a typo) ?

```- name: Create TCP Monitor
 bigip_monitor_tcp:
   name: "hc_tcp"
    port: "{{ extra_pool_service_port }}" <-- duplicate and misaligned parameter
   port: "*"
   ip: "*"
   provider: "{{ provider }}"
   state: present```

**Comment by xbill42** [comment]
Hi,

The problem was the f5_teem.
no_f5_teem: yes   fixed the problem.

But this means it tries to send stuff to f5 by default ?

Thanks for the help.
