### ISSUE TITLE
RFE: modul for building "HTTP Security Profiles" is missing

### ISSUE THREAD

**Issue by david-sieg** [F5Networks/f5-ansible#1926]
##### ISSUE TYPE

  - Feature Idea
 
##### COMPONENT NAME

https://clouddocs.f5.com/training/community/firewall/html/class1/module1/lab6.html

##### ANSIBLE VERSION

```
not necessary
```

##### PYTHON VERSION

```
not necessary
```

##### BIGIP VERSION

```
15.1.1-0.0.6
```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

It would be fine to build http security prfiles with ansible. 

##### ACTUAL RESULTS

```
No module is present which is supporting such topic. 
```

**Comment by pgouband** [comment]
Security profiles feature has been implemented.
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_security_http_profile_module.html#bigip-security-http-profile-module-2
