### ISSUE TITLE
Module to Configure Postgres SQL Monitors

### ISSUE THREAD

**Issue by strain17** [F5Networks/f5-ansible#1930]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

There is a module to configure MySQL monitors ([bigip_monitor_mysql](https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_monitor_mysql.py)). Could we add a module to support Postgres SQL? It is currently supported by REST - https://clouddocs.f5.com/api/icontrol-rest/APIRef_tm_ltm_monitor_postgresql.html - could be just a matter of changing the REST call?

**Comment by focrensh** [comment]
Tracking via FMFA-694

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
