### ISSUE TITLE
Add "up_interval" parameter to bigip_monitor_http

### ISSUE THREAD

**Issue by strain17** [F5Networks/f5-ansible#1932]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_monitor_http

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.2
  config file = /xxx/ansible.cfg
  configured module search path = ['/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /xxx/ansible-2.9.2/lib/python3.7/site-packages/ansible
  executable location = /xxx/ansible-2.9.2/bin/ansible
```

##### PYTHON VERSION

```
python version = 3.7.1 (default, Dec 14 2018, 13:28:58) [Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### BIGIP VERSION

```
14.1.x
```

##### SUMMARY

bigip_monitor_http does NOT support the "up_interval" parameter. Would it be possible to add this parameter similar to what is found for the HTTPS monitor [bigip_monitor_https](https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_monitor_https_module.html#bigip-monitor-https-module)

**Comment by focrensh** [comment]
Tracking via FMFA-693

**Comment by rhavenn** [comment]
Yeah, 2nd this. Any progress?
