### ISSUE TITLE
bigiq_device_discovery unhandled exception in _wait_for_task

### ISSUE THREAD

**Issue by dareste** [F5Networks/f5-ansible#1969]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigiq_device_discovery.py

##### ANSIBLE VERSION
ansible 2.10.5

##### PYTHON VERSION
Python 3.9.1

##### BIGIP VERSION
Big-IQ 7.1.0

##### CONFIGURATION

[task_monitor.pcap.zip](https://github.com/F5Networks/f5-ansible/files/6009598/task_monitor.pcap.zip)

##### SUMMARY

In bigiq_device_discovery, the _wait_for_task function is called from import_modules_on_device in order to monitor the status of a "cm/global/task/device-import/<uuid>" task:

https://github.com/F5Networks/f5-ansible/blob/6bdb902a5d8aabd6459b81daa4b11654a8ae7f1f/library/modules/bigiq_device_discovery.py#L813

We poll the status every second until the 'status' key in the JSON response is in a final state (FINISHED, FAILED or CANCELLED).

This polling is using a token-based auth, as everything else in Big-IQ. If the task takes longer to complete than the token lifetime, we end up making requests with an invalid token, which will be responded by the Big-IQ with a 401 Unauthorized. This response does not contain any 'status' key, and as a consequence, an unhandled exception is raised (KeyError: 'status').

Find attached a traffic capture that exemplifies the behavior. One request works, and the next one after one second is unauthorized.

##### STEPS TO REPRODUCE

- Prepare a Big-IQ that manages a Big-IP with a huge number of objects, to make sure the 
- Use a playbook similar to the one below to rediscover the managed devices.

---
- name: get all managed devices
  f5networks.f5_modules.bigiq_device_info:
    gather_subset: managed-devices
    provider: "{{ f5_bigiq_provider }}"
  register: bigiq_result

- name: discover devices
  f5networks.f5_modules.bigiq_device_discovery:
    device_address: "{{ item.address }}"
    force: yes
    modules:
      - ltm
    provider: "{{ f5_bigiq_provider }}"
  loop: "{{ bigiq_result.managed_devices }}"

##### EXPECTED RESULTS

The discover task completes successfully.

##### ACTUAL RESULTS

The discover task fails with a KeyError: 'status' unhandled exception:

    "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1613095312.734601-30-116369024247949/AnsiballZ_bigiq_device_discovery.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1613095312.734601-30-116369024247949/AnsiballZ_bigiq_device_discovery.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1613095312.734601-30-116369024247949/AnsiballZ_bigiq_device_discovery.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigiq_device_discovery', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 1234, in <module>\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 1227, in main\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 671, in exec_module\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 685, in present\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 709, in update\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 947, in import_modules_on_device\\n  File \\"/tmp/ansible_f5networks.f5_modules.bigiq_device_discovery_payload_lgs0y68g/ansible_f5networks.f5_modules.bigiq_device_discovery_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigiq_device_discovery.py\\", line 821, in _wait_for_task\\nKeyError: 'status'\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1

**Comment by nmenant** [comment]
Thanks for the feedback, we'll look into it with INFRAANO-220.
