### ISSUE TITLE
Feature-request: net packet-filter

### ISSUE THREAD

**Issue by KhangT96** [F5Networks/f5-ansible#1972]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Hi, I was looking around to find any module that can automate the process of creating a net packet-filter, so far I don’t have any luck. I wonder if there exist a module for such creation, or if not, is there a possibility that it can be added?

the tmsh command is following:
```
tmsh create net packet-filter
```

This of course should include all create/modify/delete functions.

**Comment by nmenant** [comment]
Hi,
We've created INFRAANO-240 to track this feature request internally

thanks for your feedback

**Comment by KhangT96** [comment]
> Hi,
> We've created INFRAANO-240 to track this feature request internally
> 
> thanks for your feedback

Thanks, for you response.

**Comment by pgouband** [comment]
Hi @KhangT96,
Have you tried to use command module?
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_command_module.html#bigip-command-module-2

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
