### ISSUE TITLE
[RFE ] Feature request to add an Ansible F5 module for iRule LX for F5networks

### ISSUE THREAD

**Issue by SWADESNA** [F5Networks/f5-ansible#1983]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- F5 Module

##### ANSIBLE VERSION

```
 All versions

```

##### BIGIP VERSION

```
 All versions

```

##### OS / ENVIRONMENT
 
N/A

##### SUMMARY

Customer requires an Ansible module for iRule LX for F5networks
##### STEPS TO REPRODUCE

This is a feature request. So, no reproduction steps required.

**Comment by jmcalalang** [comment]
Might need a bit more explanation when it gets to Product Management, there is already an LX module in v1

https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_lx_package_module.html#bigip-lx-package-module

**Comment by nmenant** [comment]
We'll track this request internally with INFRAANO-245

**Comment by stephenpaynter** [comment]
Nicholas do we have any updates?

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
