### ISSUE TITLE
bigip_policy_rule: Add targets to the disable action 

### ISSUE THREAD

**Issue by BapRx** [F5Networks/f5-ansible#1993]
### Is your feature request related to a problem? Please describe.
I need to disable the persistence for specific policy rules but as of today, only _server SSL_ can be disable with ansible.
### Describe the solution you'd like
It would be great to implement all possible targets for the disable action. 
If that is too much work, I currently only need to disable persistence.

### Additional context
`msg: 'value of disable_target must be one of: server_ssl, got: persist found in actions'`

**Comment by nmenant** [comment]
Hi,

Thanks for your request. Tracking with INFRAANO-308. We will focus first on being able to disable persistence based on your need. We will look into other objects in the future based on feedback
