### ISSUE TITLE
bigip_policy_rule: Rule order

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1998]
### Feature Request:
When adding rules to a policy, it doesn't appear to have any sort of order to them. The GUI adds the new rules to the bottom of the list of rules. Could we get the same applied to the Ansible module? Right now, it looks like it is just throwing them in any spot. Originally I thought it was adding the rules always at the top, but that wasn't the case as I started adding more rules.

This could potentially cause issues always adding to the top or not even allowing us to select a rule ID number in the long run since these are auto deployed and not saved in a draft for GUI review. 

### Possible Solutions:
I propose one of three options:
1. Always save rules at the bottom of the list. Requires GUI review to reorder but prevents any issues that may make processing things in order an issue.
2. Provide us an option to use rule number IDs
~~3. Allow rules to be saved as a draft for GUI review and reordered. ie: state: draft and state: published~~ This is already implemented on bigip_policy

### Additional context
We have a few cases where the order of operations is critical and without control over how rules are assigned, this could cause outages.

**Comment by DerrickTJ** [comment]
Turns out, if you read the documentation for all parts involved here, this is already implemented. You have to use bigip_policy module to actually create the draft first.

Keeping this open for maybe the option to add rule ID to the bigip_policy_rule

**Comment by wojtek0806** [comment]
@DerrickTJ when you create rules via the REST API without giving the `ordinal` parameter the system will assume the number to be 0, and if that is the case then the GUI uses name as tie-breaker to determine order. I will add rule_order parameter so you can specify the number, you need to remember however if you provide the same number which already exists on another rule the name will be used to determine the order

**Comment by wojtek0806** [comment]
here is output from POSTMAN to illustrate this:

```{
    "kind": "tm:ltm:policy:rules:rulescollectionstate",
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules?ver=15.1.2",
    "items": [
        {
            "kind": "tm:ltm:policy:rules:rulesstate",
            "name": "pastman",
            "fullPath": "pastman",
            "generation": 8133,
            "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules/pastman?ver=15.1.2",
            "ordinal": 0,
            "actionsReference": {
                "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules/pastman/actions?ver=15.1.2",
                "isSubcollection": true
            },
            "conditionsReference": {
                "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules/pastman/conditions?ver=15.1.2",
                "isSubcollection": true
            }
        },
        {
            "kind": "tm:ltm:policy:rules:rulesstate",
            "name": "postman",
            "fullPath": "postman",
            "generation": 8132,
            "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules/postman?ver=15.1.2",
            "ordinal": 0,
            "actionsReference": {
                "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules/postman/actions?ver=15.1.2",
                "isSubcollection": true
            },
            "conditionsReference": {
                "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~test/rules/postman/conditions?ver=15.1.2",
                "isSubcollection": true
            }
        }
    ]
}```

**Comment by wojtek0806** [comment]
Tracked with: INFRAANO-329

**Comment by DerrickTJ** [comment]
Thank you @wojtek0806 !
