### ISSUE TITLE
provide capability to configure active directory authentication

### ISSUE THREAD

**Issue by vchepkov** [F5Networks/f5-ansible#2001]
Currently bigip_device_auth_ldap module doesn't provide an option to specify active directory as a source type

If source type was configured using bigip_command `modify auth source { type active-directory }`  it is reversed back to `ldap` by the module. It would preferred to have playbook idempotent, instead of modifying configuration twice each playbook run

I am using f5networks.f5_modules v 1.8.1

**Comment by nmenant** [comment]
Thanks for sharing this issue, tracking this with INFRAANO-309

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version, it should work. If not, please reach out, thanks!
