### ISSUE TITLE
bigip_policy_rule: condition tcp address_matches_with_datagroup supports only internal datagroups

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#2002]
### Is your feature request related to a problem? Please describe.
The condition tcp address_matches_with_datagroup supports only internal datagroups, as shown here:
https://github.com/F5Networks/f5-ansible/blob/07688fb965304757059dca61c75ab8d09d5a7b06/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py#L984

However, it seems the "best" (default) choice should be using external datagroup, as your documentation suggests here:

> The type of this data group.
> You should only consider setting this value in cases where you know exactly what you are doing, or, you are working with a pre-existing internal data group.

(Ref: https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_data_group_module.html?highlight=bigip_data_group)

### Describe the solution you'd like
Support (default) external data groups in condition tcp address_matches_with_datagroup

**Comment by nmenant** [comment]
This is not expected that external datagroup are not supported. This will be addressed as bug and tracked with INFRAANO-304
