### ISSUE TITLE
ansible.netcommon >= 2

### ISSUE THREAD

**Issue by gundalow** [F5Networks/f5-ansible#2003]
The Ansible-4.0.0 package will be including `ansible.netcommon-2.x`.  The f5_modules collection does not presently support ansible.netcommon >= 2.  This will need to be resolved by porting the code and updating the requirements for f5_modules to continue working with the packageset in ansible-4.0.0.

Parent tracking bug https://github.com/ansible-community/antsibull/issues/268

cc @abadger

**Comment by wojtek0806** [comment]
already aware fixed by this PR: https://github.com/F5Networks/f5-ansible/pull/2004
and in next release: 1.9.0

**Comment by gundalow** [comment]
Brilliant, Thank you for the quick fix.
