### ISSUE TITLE
bigip_routedomain enforced/staged firewall policy

### ISSUE THREAD

**Issue by horol** [F5Networks/f5-ansible#2010]
### Problem description
**problem1 (major):** Module 'bigip_routedomain' can attach AFM policy to the routing domain (parameter fw_enforced_policy), but it's not possible to remove/detach it.
**problem2 (minor):** AFM policy can be attached to routing domain in 'enforcement mode', but not in 'staging mode'.

### Requested solution
**problem1:** Add possibility to detach AFM policy from routing domain or describe how is it possible to do in current version.
**problem2:** Add possibility attach (and detach) AFM policy also in 'staging mode'.

### Versions
- ansible: 2.9 or 2.10 (latest)
- f5 collection: 1.8.x or 1.9.0 (latest)

**Comment by nmenant** [comment]
Hi, 

I have reproduced the issue and couldn't find a way to remove the AFM policy (in enforcement mode as mentioned). We'll review this. Tracking this internally with INFRAANO-311
