### ISSUE TITLE
bigip_device_info module does not provide Partition information when running gather subset, - virtual-servers, -ltm_pools, and - nodes

### ISSUE THREAD

**Issue by bpmarkovich** [F5Networks/f5-ansible#2016]
### Is your feature request related to a problem? Please describe.
The bigip_device_info / gather_subset  -virtual-Servers, - ltm_pools, and - nodes does not contain a ansible fact for the partition the F5 property is located in. It does contain full_path, however, that limits you to having to utilize the bigip_command module to make changes, and does not allow for use of other modules with leveraging Ansible_facts to make changes. 

### Describe the solution you'd like
Partition is including in the Ansible facts for each one of the commands in the bigip_device_info module. 

### Describe alternatives you've considered
The only alternative is to leverage the bigip_command module to run commands gathered from Ansible_facts from the bigip_device_info module. 

### Additional context
Here is a basic example where I am forced to use the bigip_command module due to the missing partition information. 
  tasks:
```
  - name: Get Virtual Server configuration
    bigip_device_info:
        gather_subset:
          - virtual-servers
        provider: "{{ vcmp_host_creds }}"
    register: virtual

 - debug: msg="{{virtual}}"

  - name: Collect Connection Table for the Virtual Server
    bigip_command:
      commands:
        - tmsh show /sys conn cs-server-addr {{item.destination_address}}
      provider: "{{ vcmp_host_creds }}"
    with_items: "{{virtual.virtual_servers}}"
    register: connection_result

- debug: msg="{{connection_result}}"
```

**Comment by wojtek0806** [comment]
@bpmarkovich while we consider this, i would suggest looking at the filters you use in your playbooks to get that data: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#manipulating-text
there is no need for bigip_command module here.

**Comment by trinaths** [comment]
@bpmarkovich  Tried suggestion from @wojtek0806 ? Please share your feedback.

**Comment by bpmarkovich** [comment]
@wojtek0806 I appreciate the feedback. I agree I can leverage filters to obtain the partition information of the object, from the "Full Path". However, why would I want to use advanced filters when the F5 Module can be modified to provide the Partition of the Object as its own variable, removing the requirement to leverage a filter to obtain basic, required, F5 information. Also, this will reduce the amount of code required to make changes leveraging the F5 ansible playbook. Cisco NSO also had the same problem with Partitions, and I believe Partitions continue to get overlooked as required variable when attempting to automate anything F5. Thanks again for your feedback, as I will work to apply filters to our F5 Ansible Playbooks. Please consider adding the Partition as a variable to any further updates made to the F5 Ansible Module.

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
