### ISSUE TITLE
RFE: ciphers groups / ciphers rules modules

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#2039]
### Is your feature request related to a problem? Please describe.
Enabling TLS1.3 in a SSL profile requires that the ciphers are configured in a LTM Cipher group, and not directly in the SSL profile anymore.
Today, the module `bigip_profile_client_ssl` supports an attribute `cipher_group`. However we are not able to create an own/customized cipher group (based on customized cipher rule).
Note: today the module `bigip_profile_server_ssl` does not supports the attribute `cipher_group`.
 
### Describe the solution you'd like
Add the following modules to support the solution:
- LTM ciphers rules
- LTM ciphers groups

**Comment by trinaths** [comment]
Created INFRAANO-396 for internal PM tracking.

**Comment by gitnetofr** [comment]
I'm also interested in this feature idea.

**Comment by trinaths** [comment]
@amolari @gitnetofr  - this can be achieved with [F5 Ansible collections V2](https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/install_f5_bigip.html). 

For Cipher groups and Cipher support see the [AS3 declaration](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#using-tls-1-3-and-cipher-rules-and-groups-in-a-declaration) and use ansible playbook to apply. 

Hope this helps. 

This RFE is not valid for Collections V1.

**Comment by amolari** [comment]
@trinaths Moving to AS3 declaration is not possible for us at this time due to the lack of some features (and time to implement it).
Please reconsider your decision and if you decide "won't implement", may I ask you to close the issue?

**Comment by KrithikaChidambaram** [comment]
This can be achieved with [F5 Ansible collections V2](https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/install_f5_bigip.html).
For Cipher groups and Cipher support see the [AS3 declaration](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#using-tls-1-3-and-cipher-rules-and-groups-in-a-declaration) and use ansible playbook to apply.
