### ISSUE TITLE
bigip_data_group: INFRAANO-207 not correctly fixed

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#2046]
##### COMPONENT NAME

bigip_data_group
collection is devel-1.9.2
##### ANSIBLE VERSION

```
2.9.17
```
##### BIGIP VERSION

```
3.6.9
```
##### STEPS TO REPRODUCE

```
tasks:
- name: Create a data group datagroup001 of IP addresses from (tmp) file
  bigip_data_group :
    provider: "{{ provider }}"
    name: "datagroup100"
    records_src: "./new.dg"
    type: address
  delegate_to: localhost
```

file `new.dg`:
```
network 10.100.1.0/24,
network 10.100.1.0/24,
network 10.100.2.23/32,
host 1.1.1.1,
```

external datagroup is correctly configured on the BIGIP.
Then by some other (external, such as tmsh or UI) means the data group gets modified on the BIGIP. When I rerun the
playbook, the data group is not changed.

##### EXPECTED RESULTS

When I re-run the playbook, the data group on the BIGIP results to be the same as the content pushed by my playbook.
My playbook is the source of truth.

##### ACTUAL RESULTS

external datagroup is correctly configured on the BIGIP.
If then, by some other (external, such as tmsh or UI) means, the data group is modified on the BIGIP,  re-running the
playbook doesn't change (back) the content.

```

```

**Comment by wojtek0806** [comment]
Do not modify ansible created data groups outside of ansible, the documentation states this clearly:
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py#L150

**Comment by Klipope** [comment]
I think what we are expecting is that even if the datagroup is modified outside of ansible then the next push should overwrite the changes to comply with the source of truth concept. from your comment, we understand this is not the way you see how this shoudl be implemented. coudl you then pease explain us the reason? and give us some context? Thanks

**Comment by wojtek0806** [comment]
This comment in the code clarifies this:
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py#L879

**Comment by wojtek0806** [comment]
The only thing i could offer here is we add `force` , with default to 'no' option which will force the update with whatever the user provides, this way you could override external data groups.

**Comment by amolari** [comment]
@wojtek0806 that option would match what had been asked in the Support case ("I'm expecting to control the content of the file from Ansible, but no "force" option is available in the module.") but unfortunately it seems it hadn't been communicated in the escalation process. Please add that `force `option to the module.

**Comment by trinaths** [comment]
@wojtek0806  The checksum comparison is failing in this case ? I dont think, `force` will help unless checksum is verified correctly. thoughts ?

**Comment by amolari** [comment]
Probably another bug in TMOS: the checksum value is not changed if the datagroup is modified through the UI. All other values (generation,lastUpdateTime,revision,size) are but not checksum.

**Comment by amolari** [comment]
@wojtek0806 @trinaths 
A fix (available with ENGHF) has been released now for Bug ID948601 and I've successfully tested it (checksum gets updated when change in DG content made through GUI). The module behaves as expected. Therefore, I'm closing this issue.
