### ISSUE TITLE
bigip_policy_rule - remaining conditions for host and path

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#2052]
Can we get the remaining conditionals added to bigip_policy_rule? This will fill in the remaining conditionals that are missing for HTTP Host and HTTP URI.

host_is_not
host_does_not_begin_with
host_does_not_end_with
host_contains

path_is_not
path_does_not_begin_with
path_ends_with
path_does_not_end_with
path_does_not_contain

**Comment by trinaths** [comment]
Created INFRAANO-392 for internal PM tracking.

**Comment by binlan** [comment]
#2091 adressing host_does_not_begin_with condition

**Comment by quaffles** [comment]
Is this commited/pushed to the devel branch?

I'm trying to manage some policies and the conditions I need don't exist in the stable release or devel that I downloaded.

**Comment by binlan** [comment]
@wojtek0806 just closed the pull request without merging it. i dont know why. feel free to reopen a PR as fork of my branch.

**Comment by binlan** [comment]
@quaffles i created a new PR. we will see, if it will be accepted. https://github.com/F5Networks/f5-ansible/pull/2240
