### ISSUE TITLE
bigip_command modules (transport: cli) not working with collections 1.10

### ISSUE THREAD

**Issue by SoumenAbhishek** [F5Networks/f5-ansible#2063]
##### COMPONENT NAME

bigip_command

### Environment
collection 1.10
##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules', '/Users/soumenabhishek/.ansible/collections/ansible_collections/f5networks/f5_modules/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.7/bin/ansible
  python version = 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) [Clang 6.0 (clang-600.0.57)]


```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.3
  Build       0.0.11
  Edition     Final
  Date        Thu Apr  8 01:36:32 PDT 2021

```
##### OS / ENVIRONMENT

MAC OS 
##### SUMMARY

When i tried with collections its showing error as shown below but same works fine if using f5 default modules 
##### STEPS TO REPRODUCE

```
---
- name: Generate Device Certificate for BIG IP Device
  hosts: f5
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  tasks:
    - name: restart httpd sevice
      bigip_command:
        commands: run util bash -c 'bigstart restart httpd'
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_ssh}}"
          password: "{{ansible_password}}"
          transport: cli
      delegate_to: localhost

```

##### EXPECTED RESULTS

ok: [f5 -> localhost] => {
    "changed": false,
    "executed_commands": [
        "tmsh -c \"run util bash -c 'bigstart restart httpd'\""
    ],
    "invocation": {
        "module_args": {
            "chdir": null,
            "commands": "run util bash -c 'bigstart restart httpd'",
            "interval": 1,
            "match": "all",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "x.x.x.x",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "user": "root",
                "validate_certs": null
            },
            "retries": 10,
            "transport": "rest",
            "wait_for": null,
            "warn": true
        }
    },
    "stdout": [
        "Stopping httpd: \u001b[60G[\u001b[0;32m  OK  \u001b[0;39m]\n\nStarting httpd: \u001b[60G[\u001b[0;32m  OK  \u001b[0;39m]"
    ],
    "stdout_lines": [
        [
            "Stopping httpd: \u001b[60G[\u001b[0;32m  OK  \u001b[0;39m]",
            "",
            "Starting httpd: \u001b[60G[\u001b[0;32m  OK  \u001b[0;39m]"
        ]
    ]
}

##### ACTUAL RESULTS

The full traceback is:
Traceback (most recent call last):
  File "/Users/soumenabhishek/.ansible/tmp/ansible-tmp-1624614486.12447-196391471895238/AnsiballZ_bigip_command.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/soumenabhishek/.ansible/tmp/ansible-tmp-1624614486.12447-196391471895238/AnsiballZ_bigip_command.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/soumenabhishek/.ansible/tmp/ansible-tmp-1624614486.12447-196391471895238/AnsiballZ_bigip_command.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_command', init_globals=None, run_name='__main__', alter_sys=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 740, in <module>
  File "/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 733, in main
  File "/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 663, in exec_module
  File "/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py", line 589, in exec_module
  File "/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py", line 130, in send_teem
AttributeError: 'AnsibleModule' object has no attribute 'provider'

fatal: [f5 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/soumenabhishek/.ansible/tmp/ansible-tmp-1624614486.12447-196391471895238/AnsiballZ_bigip_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/soumenabhishek/.ansible/tmp/ansible-tmp-1624614486.12447-196391471895238/AnsiballZ_bigip_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/soumenabhishek/.ansible/tmp/ansible-tmp-1624614486.12447-196391471895238/AnsiballZ_bigip_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_command', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 740, in <module>\n  File \"/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 733, in main\n  File \"/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 663, in exec_module\n  File \"/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 589, in exec_module\n  File \"/var/folders/wd/s73xvjqx2kxcdsyvgt5c6j000000gn/T/ansible_bigip_command_payload_ck_1i_j1/ansible_bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/teem.py\", line 130, in send_teem\nAttributeError: 'AnsibleModule' object has no attribute 'provider'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

```

**Comment by wojtek0806** [comment]
Duplicate issue:
https://github.com/F5Networks/f5-ansible/issues/2061
Refer to the linked issue for solution
