### ISSUE TITLE
bigip_scf and bigip_scf_fetch module request

### ISSUE THREAD

**Issue by hyudra** [F5Networks/f5-ansible#2064]
### Is your feature request related to a problem? 
No

### Describe the solution you'd like
Same as UCS, I'd like to have SCF module backup

### Describe alternatives you've considered
For now, I have to use bigip_command to save scf file, and download the file from directory.

**Comment by trinaths** [comment]
Created INFRAANO-432 for internal PM tracking.

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
