### ISSUE TITLE
Profile module

### ISSUE THREAD

**Issue by pandamasta** [F5Networks/f5-ansible#2073]
### Is your feature request related to a problem? Please describe.

We would like to create a SMTP profile with ansible. 
No ansible module available to manage profile.

### Describe the solution you'd like

Avoid use raw tmsh commmand in ansible like:

```
- name: create SMTP profile
tags: smtpprofile
notify: save config
bigip_command:
commands: create ltm profile smtps super_smtps_profile defaults-from smtps activation-mode require
provider: "{{ provider }}"
```

### Describe alternatives you've considered

Raw tmsh command instead of dedicated bigip ansible module

**Comment by trinaths** [comment]
Created INFRAANO-440 for internal PM tracking

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
