### ISSUE TITLE
Missing NAT Module

### ISSUE THREAD

**Issue by ehm-wehb** [F5Networks/f5-ansible#2085]
### Is your feature request related to a problem? Please describe.
No, bigip_command documentation suggests filing an issue if a module is missing. "    If you are using this module, we recommend also filing an issue to have a real module created for your needs."

### Describe the solution you'd like
I need to manage NAT objects on our F5 and there doesn't appear to be a regular NAT module, just SNAT. 

### Describe alternatives you've considered
Attempting to use bigip_command in lieu of a NAT module.

**Comment by trinaths** [comment]
@ehm-wehb - Suggest use [AS3 ](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html) with [V2 Collection](https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/f5_bigip.html) for configuring NAT.
