### ISSUE TITLE
Add support for ISO file authenticity verification

### ISSUE THREAD

**Issue by merillr** [F5Networks/f5-ansible#2095]
### Is your feature request related to a problem? Please describe.
When using the `bigip_software_install` module to install a new image, installation fails if the **liveinstall.checksig** database key is enabled and the .sig for the ISO is not pre-uploaded to `/shared/images`. See [K15226](https://support.f5.com/csp/article/K15226).

### Describe the solution you'd like
Provide a new module to upload .sig files or modify the `bigip_software_image` or `bigip_software_install` module to include this functionality.

### Describe alternatives you've considered
I'm not sure that the `ansible.builtin.copy` module is an option because of the `connection: local` in the playbook and user accounts defaulting to tmsh. Disabling **liveinstall.checksig** prior to a `bigip_software_install` task is a workaround, but defeats the purpose.

### Additional context
Resulting error is:
`failed (Signature file not found - /shared/images/BIGIP-<Version-Build>.iso.sig)`

**Comment by KrithikaChidambaram** [comment]
Hi, there is checksum as output. Does that work for your use case?
Please check the documentation here:
https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_software_image_module.html#bigip-software-image-module-3

**Comment by pgouband** [comment]
Hi, closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
