### ISSUE TITLE
Existing SNMP Configuration Lookups

### ISSUE THREAD

**Issue by rgonzal1** [F5Networks/f5-ansible#2105]
### Is your feature request related to a problem? Please describe.
If the SNMP configuration changes and there is a conflict with the existing configuration (name = community_1 ip=ip2, change to name=community_2) the conflicting entry will cause a failure of the bigip_snmp_trap or bigip_snmp_community modules.

### Describe the solution you'd like
Utilize the API endpoints for viewing existing SNMP traps, communities, and global configuration to provide information with the bigip_device_info that can be referenced to remove configuration prior to pushing new configuration

### Describe alternatives you've considered
Currently, I am utilizing the bigip_command module to delete all trap destinations and community configurations before reconfiguring the trap destinations and community strings. 

### Additional context
Existing API endpoints available to retrieve the information:

mgmt/tm/sys/snmp/traps
* return['items']
* Interested in the name, host, network, port, and version fields in the items returned

mgmt/tm/sys/snmp/communities
* return['items']
* Interested in the name, access, community name, oidSubsets and source fields in the items

**Comment by Otimun** [comment]
I was trying to get SNMP information with bigip_device_info, but it doesn't seem implemented yet.

It would be nice to obtain this information.

**Comment by pgouband** [comment]
Hi @Otimun

What snmp information are you looking for?

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!

**Comment by rgonzal1** [comment]
@KrithikaChidambaram - I'm curious as to why this has been closed without the implementation of the requested feature. 

Is this just no longer under consideration? The SNMP modules today are not idempotent when attempting to perform implementations of SNMP strings and will result in failures if the SNMP community exists under a different name. This information for gathering the existing SNMP strings was meant to help remove any needed prior to making modification with the SNMP module. 

Please let me know if you need additional information.

**Comment by pgouband** [comment]
Hi @rgonzal1, I didn't receive any feedback on what snap information are you looking for on 5th Oct.
Have you tried using Declarative Onboarding?
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/declarations/observability.html#configuring-snmp-in-a-declaration

**Comment by rgonzal1** [comment]
Hello @pgouband,

I believe that the original issue specifically pointed out the endpoints that we would like to see added to the modules. The follow up on OCT 5 was to another user who I believe was following up (aka bumping) this issue. 

Declarative onboard is not currently an option to deploy in our environment and we must continue to use the imperative modules.
