### ISSUE TITLE
bigip_device_certificate transport mode through REST

### ISSUE THREAD

**Issue by fchmainy** [F5Networks/f5-ansible#2108]
the bigip_device_certificate only works through SSH. In our case SSH is not allowed to the BIG-IPs because it is forbidden per our security policy.

We need to use *REST transport* as a second choice for transport.

thank you very much.

**Comment by trinaths** [comment]
created INFRAANO-562 for internal tracking.

**Comment by pgouband** [comment]
After discussing with @fchmainy, closing this now.
