### ISSUE TITLE
Module bigip_command & Character Escaping

### ISSUE THREAD

**Issue by polskikrol** [F5Networks/f5-ansible#2111]
The manual for the bigip_command module states the following:

`When using the bigip_command module with the REST API, there are a number of places regex is used internally to escape characters such as quotation marks. If your TMSH command contains regex characters itself, such as datagroup wildcards *, then a large amount of escape characters may be needed.`

Looking at the samples on the same documentation page, the following can be found:

`  bigip_command:
    commands:
      - modify ltm data-group internal dg_string records add { "my test\\\\\\\*string"  { data "value" }}`

My issue is that I am trying to issue a TMSH command which has been confirmed working via CLI, specifically the following:

`- 'run /util sftp user@1.1.1.1:/some/path <<< "put /path/to/file.txt"'`

However, whatever combination I attempt, those quotes are not escaping properly. I end up with something like the following:

`tmsh run /util sftp user@1.1.1.1:/some/path <<< \\\"put /path/to/file.txt\\\"'`

How can I get this through all of the REGEX parsers?

**Comment by wojtek0806** [comment]
The deal is this, if you are using a linux based utility like SCP or SFTP on bigip use ansible modules dedicated for that. F5 ansible modules support only REST api calls, with very few exceptions, if there was no REST api endpoint to do something we never implemented it, or refered to existing ansible modules (in the case of executing bash utilities).

As far as bigip_command_module is concerned, it was meant as a stop gap to use tmsh commands until an option or feature within TMOS is made available through a module. It was never meant to run bash commands, you can run some simple bash commands and we use that in our modules to patch up some functionalities. If you start going into more complex cases then you are entering unexplored untested territory and you will be on your as bigip_command module was meant for parsing tmsh commands that relate strictly to TMOS configuration.

For UCS and SCF management, the functionalities that were in the modules are in line with what the REST api offers to us in regards to interaction and they are enough for most of the user base. We recently added an ability to only generate UCS files (as it was your request) on the device without download, if you need functionalities added to each module we can do so but only when the REST api permits.

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face any issue. Thanks!
