### ISSUE TITLE
bigip_wait module doesn't provide the status for ASM

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/f5-ansible#2116]
### Is your feature request related to a problem? Please describe
With bigip_wait module, you can wait for BIG-IP to be “ready”, meaning the BIG-IP is ready to accept configuration. While this applies for LTM/GTM, it doesn't apply for ASM. 
if the BIGIP is offline (for example ASM is restarting or getting provisioned) the module will still show as "bigip ready" while it cannot receive ASM configuration

### Describe the solution you'd like
We should have an option to specify if you want to have ASM ready to accept configuration. 
 

### Describe alternatives you've considered
A way that we can determine if the bigip is offline or online can be done through the endpoint "/mgmt/tm/cm/failover-status".
From this endpoint you can determine if the appliance is offline or active. 

### Additional context

![14d15c16-d287-416a-b54f-80838e9b99d5](https://user-images.githubusercontent.com/11005568/138062070-d9748c65-e379-4b04-a9c8-dfbf7ded0ab6.jpg)

**Comment by trinaths** [comment]
Created INFRAANO-590 for internal tracking.

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
