### ISSUE TITLE
Ansible Error While Deleting a node from the pool - \"code\":400,\"message\":\" \\\\' is referenced by a member of pool \\\\'.\",\"errorStack\":[],\"apiError\" 

### ISSUE THREAD

**Issue by NGSri** [F5Networks/f5-ansible#2125]
I'm getting an error while deleting a node from the pool in big IP F5 using an ansible script.

  \"code\"":400,\"message\":\" \\\\' is referenced by a member of pool \\\\'.\",\"errorStack\":[],\"apiError\" 

It is highly appreciable Could any one of you help with how to fix this error?

**Comment by trinaths** [comment]
@NGSri  Please share your playbook to retry this issue at our end.

**Comment by NGSri** [comment]
> @NGSri Please share your playbook to retry this issue at our end.

tasks:

    - name: Collect bigip facts for Pool name
      bigip_device_info:
        gather_subset:
          - ltm-pools
        provider: "{{ provider }}"
      register: abc
      delegate_to: localhost

    - name: "Show relevant information"
      set_fact:
       result: "{{abc.ltm_pools | json_query(query_string)}}"
      vars:
       query_string: "[?members[?address=='{{ node }}']].name"

    - name: Display Pool names and member names
      debug:"
          msg: "{{ item }}"

      with_items:
        - "{{ result }}"

    - debug: "msg={{result}}"

    - pause:
        prompt: "To disable a particular member enter member with format member_name:port \nTo disable all members of the pool enter 'all'"
      register: member_name

    - name: Force pool member offline
      bigip_pool_member:
        state: forced_offline
        pool: "{{ item }}"
        host: "{{ node }}"
        port: "{{ member_name.user_input.split(':')[1] }}"
        provider: "{{ provider }}"
      delegate_to: localhost
      when: '"all" in member_name.user_input'
      with_items:
          - "{{ result }}"

**Comment by NGSri** [comment]
Show Relevant Task - Getting Pool Address and Member Address name

> @NGSri Please share your playbook to retry this issue at our end.


    - name: Collect bigip facts for Pool name
      bigip_device_info:
        gather_subset:
          - ltm-pools
        provider: "{{ provider }}"
      register: abc
      delegate_to: localhost


    - name: "Associated Pool Info"
      set_fact:
       result: "{{abc.ltm_pools | json_query(query_string)}}"
      vars:

       query_string: "[?members[?address=='{{ node }}']].name"

- pause:
        prompt: "To disable a particular member enter member with format member_name:port \nTo disable all members of the pool enter 'all'"
      register: member_name

- name: Force pool member offline
      bigip_pool_member:
        state: forced_offline
        pool: "{{ item }}"
        host: "{{ node }}"
        port: "{{ member_name.user_input.split(':')[1] }}"
        provider: "{{ provider }}"
      delegate_to: localhost
      with_items:
          - "{{ result }}"

- name: Offline the pool members
vars:
nodename: "{{item[1]| join (' ')}}"
bigip_pool_member:
provider: "{{provider}}"
state: "absent"
pool: "{{item[0]}}"
port: "{{nodename.split(':')[1]}}"
host: "{{node}}"
when: '"all" in member_name.user_input'
with_items:
- "{{ result }}"

**Comment by NGSri** [comment]
> @NGSri Please share your playbook to retry this issue at our end.

    - name: Collect bigip facts for Pool name
      bigip_device_info:
        gather_subset:
          - ltm-pools
        provider: "{{ provider }}"
      register: abc
      delegate_to: localhost

    - name: "Associated Pool Info"
      set_fact:
       result: "{{abc.ltm_pools | json_query(query_string)}}"
      vars:
       query_string: "[?members[?address=='{{ node }}']].name"

    - pause:
        prompt: "To disable a particular member enter member with format member_name:port \nTo disable all members of the pool enter 'all'"
      register: member_name

   - name: Force pool member offline
      bigip_pool_member:
        state: forced_offline
        pool: "{{ item }}"
        host: "{{ node }}"
        port: "{{ member_name.user_input.split(':')[1] }}"
        provider: "{{ provider }}"
      delegate_to: localhost
      with_items:
          - "{{ result }}"

    - name: Offline the pool members
       vars:
          nodename: "{{item[1]| join (' ')}}"
       bigip_pool_member:
         provider: "{{provider}}"
         state: "absent"
         pool: "{{item[0]}}"
         port: "{{nodename.split(':')[1]}}"
         host: "{{node}}"
         when: '"all" in member_name.user_input'
         with_items:
            - "{{ result }}"

**Comment by NGSri** [comment]
Pasted my playbook. 
Thank You in Advance!!!!

**Comment by trinaths** [comment]
created INFRAANO-610 for internal tracking.

**Comment by wojtek0806** [comment]
This is not a bug, it is expected behavior, we have no way of knowing if a node is in use or not. It is up to the user to fix their playbooks and order tasks so that the node can be remove successfully, or use bigip_node module with bigip_device_info to manage their nodes after the desired pool members are removed.

**Comment by df-cgdm** [comment]
The documentation of the bigip_pool_member module is saying "When state is absent, the system attempts to remove the node the pool member references.
The node will not be removed if it is still referenced by other pool members. If this happens, the module will not raise an error.
Setting this to yes disables this behavior."
So the module should not failed and to my point of view it's a BUG
