### ISSUE TITLE
Fully Qualifying Module for ConfigSync Fails Finding Device Group

### ISSUE THREAD

**Issue by polskikrol** [F5Networks/f5-ansible#2130]
##### COMPONENT NAME

bigip_configsync_action_result

##### ANSIBLE VERSION
```
TOWER 3.8.4, ANSIBLE 2.9.27
```
##### BIGIP VERSION

```
BIGIP 14.1.2.6
```

##### SUMMARY
Have both v1 latest and v2 collections installed. When defaulting to v1 and using 'bigip_configsync_action:' everything works, however, when using 'f5networks.f5_modules.bigip_configsync_action:' (fully qualifying the module), receive an error as follows: 'The specified 'device_group' not not exist.'. Yes, looks like an error grammar mistake as well... should be 'does not' exist. Nevertheless, checking via debug output, the device_group variable being passed is essentially '/Common/device-group-name-here' as previously. So not sure why this is failing when fully qualifying the module.

**Comment by polskikrol** [comment]
Checking icrd logs, the following error is noticed: 'Ignorning unexpected json property at configuration item /cm/device-group. The json property is "Common".'

As a reminder, I am grabbing the name of the failover device group using the normal method of collecting facts and capturing the full_path param.

Oddly enough, removing the partition element this works when being fully qualified. Almost like the parsing is being done differently depending on how the module is referenced!

**Comment by polskikrol** [comment]
So that is messed up....

Using 'bigip_configsync_action' as the task you can pass device_group as '/Common/name_of_group'. HOWEVER,
Using 'f5networks.f5_modules.bigip_configsync_action' as the task, fully qualified, the parser cant handle the '/' forward slash and you need to filter through the variable through '| replace("/", "~")'. So something is a bit amiss here.

**Comment by trinaths** [comment]
@polskikrol - Please share the playbook to try this at our end.

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if you still face the issue. Thanks!
