### ISSUE TITLE
no_log ssl keys

### ISSUE THREAD

**Issue by rossbeehler** [F5Networks/f5-ansible#2132]
In the `bigip_ssl_key` and `bigip_ssl_key_cert` modules, the `content`/`key_content` parameters are allowed to be written to logs. It might be slightly acceptable if the key is encrypted with a passphrase, but it would be more secure to not ever log both `content`/`key_content` and `passphrase`.

**Comment by trinaths** [comment]
Created INFRAANO-593 for internal tracking.

**Comment by KrithikaChidambaram** [comment]
Hi, please try upgrading to the latest version, it should work. If not, please reach out, thanks!
