### ISSUE TITLE
Cipher Rule creation module and Cipher group creation module

### ISSUE THREAD

**Issue by architshorie** [F5Networks/f5-ansible#2135]
### Is your feature request related to a problem? Please describe.
I am unable to create a custom cipher rule and cipher group via f5networks.f5_modules collection (version 1.12.0).

### Describe the solution you'd like
Please provide a module for custom cipher rule and cipher group.

### Describe alternatives you've considered
There is only a provision to create cipher rule and groups via TMSH commands.

**Comment by trinaths** [comment]
Suggest use V2 collection with AS3. Please refer to below AS3 JSON. 

LTM ciphers rules (with AS3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#cipher-rule
LTM ciphers groups (with As3: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#cipher-group)

Closing this issue.
