### ISSUE TITLE
Issue with daily build?

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#2137]
Fetching today the daily build (https://f5-ansible.s3.amazonaws.com/collections/f5networks-f5_modules-devel.tar.gz) all files have the following timestamp:
2021-11-05 08:00

collections/ansible_collections/f5networks/f5_modules/changelogs/changelog.yaml has
`release_date: '2021-05-11'`

Is the daily build not issued anymore? I need it to get the latest fixes

**Comment by wojtek0806** [comment]
should be resolved now
