### ISSUE TITLE
bigip_policy_rule : enable SSL server action

### ISSUE THREAD

**Issue by Ozzy2eme** [F5Networks/f5-ansible#2144]
Hello,

I try to set the action "Activate SSL Server at request time" it must be explicitly set on my policy rule. Like this :
![image](https://user-images.githubusercontent.com/16778143/146038618-adccedb7-bfb3-4e4f-8462-a272053128c2.png)

How can I activate this action with Ansible. I didn't found anything on the documentation (https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_policy_rule_module.html)

Regards,

Ozzy2eme

**Comment by trinaths** [comment]
@Ozzy2eme - Suggest use V2 collection with AS3 - See the AS3 JSON schema reference - https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#policy-action-client-ssl 

policy-action-client-ssl actually maps to server-ssl in tmsh.

From the FAQ:
used a TLS_Server object in my AS3 declaration, why did it create a Client SSL profile on the BIG-IP?

The AS3 naming convention for TLS Server and TLS Client differs from traditional BIG-IP terminology to better comply with industry usage, but may be slightly confusing for long-time BIG-IP users. The AS3 TLS_Server class is for connections arriving to the BIG-IP, which creates a “client SSL profile” object on the BIG-IP. The AS3 TLS_Client class if for connections leaving the BIG-IP, which creates a “server SSL profile” on the BIG-IP. See TLS_Server and TLS_Client in the Schema Reference for more information.

**Comment by eddy-obs** [comment]
Hi everyone,

I'm trying to use all the capabilities from the f5networks.f5_modules.bigip_policy_rule collection but like @Ozzy2eme [Ozzy2eme](https://github.com/Ozzy2eme), natively It is not possible to call different actions or conditions especially Enable
or Disable.
Enable must be used with asm_policy for example.
I'm trying to use set_variable and tcl:[SSL::enable [serverside]] to validate SSL Serverside 

<img width="502" alt="capture_set_variable_f5" src="https://user-images.githubusercontent.com/38099739/154254216-f2fe3f2e-5a6a-4472-a79c-b438e4eec6b8.PNG">

            - type : "{{ item.1.act_type1 }}"
              event: "{{ item.1.act_event1 }}"
              variable_name: "{{ item.1.act_var }}"
              expression: "{{ item.1.act_exp }}"

              act_exp: tcl:[SSL::enable [serverside]]

For the moment we don't want to use AS3.

**Comment by KrithikaChidambaram** [comment]
Hi, closing this now. Please reach out if you face any issues. Thanks!
