### ISSUE TITLE
bigip_device_auth_ldap needs to mark the update_password parameter as loggable to silence warning message

### ISSUE THREAD

**Issue by jesmith18** [F5Networks/f5-ansible#2145]
##### COMPONENT NAME
bigip_device_auth_ldap

##### ANSIBLE VERSION
```
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/Users/jsmith18/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/jsmith18/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.5.2
  Build       0.0.10
  Edition     Point Release 2
  Date        Wed Jun 24 17:56:24 PDT 2020
```
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The bigip_device_auth_ldap task has a parameter named "update_password" that determines whether the module will always update the LDAP password or just on newly created authentications.

Because the parameter name contains the "password", ansible is concerned that it might contain a password that would be logged should verbose logging be enabled. To warn the user of this ansible displays a warning message:

[WARNING]: Module did not set no_log for update_password

This message is generated by ansible's basic.py module:

```
1378             # try to proactively capture password/passphrase fields
1379             if no_log is None and PASSWORD_MATCH.search(param):
1380                 log_args[param] = 'NOT_LOGGING_PASSWORD'
1381                 self.warn('Module did not set no_log for %s' % param)
```

By adding the no_log attribute to the parameter declaration in the task, ansible will know that it is safe to log this parameter and thereby will not issue a warning message in the output:

```
diff --git a/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py b/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
index a627c1c7..967085f1 100644
--- a/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
+++ b/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_auth_ldap.py
@@ -848,6 +848,7 @@ class ArgumentSpec(object):
             fallback_to_local=dict(type='bool'),
             use_for_auth=dict(type='bool'),
             update_password=dict(
+                no_log=False,
                 default='always',
                 choices=['always', 'on_create']
             ),
```

In this case, it is not so much the value of the no_log attribute than it is its prescience on the parameter that will suppress the warning message.

##### STEPS TO REPRODUCE
```
- name: Update the LDAP Password
  bigip_device_auth_ldap:
    provider: "{{ creds }}"
    bind_password: "{{ bind_password }}"
```

##### EXPECTED RESULTS
TASK [Update the LDAP Password] ********************************************************************************************************************************************
changed: [mybigip2a.ccg14.localdomain -> localhost]

##### ACTUAL RESULTS
TASK [Update the LDAP Password] ********************************************************************************************************************************************
[WARNING]: Module did not set no_log for update_password
changed: [mybigip2a.ccg14.localdomain -> localhost]

**Comment by wojtek0806** [comment]
update password is not a password field so we can log it

**Comment by jesmith18** [comment]
Wojciech, I think you may have not understood the problem.

Yes, the update_password parameter does not contain any sensitive information such as a password.

But the fact that the attribute has "password" in its name is causing the ansible logging subsystem to issue a warning that it might.

Adding no_log=False to the parameter declaration in the module does nothing to interfere with logging the parameter if verbose is enabled.

What it does do is tell the ansible logging subsystem that even though the parameter has "password" in its name, its OK to log it without a warning.

Currently, the fact that a warning is being issued by ansible may cause our security team to question it and demand that it addressed to eliminate it from the output.

Joel

**Comment by wojtek0806** [comment]
fair enough

**Comment by wojtek0806** [comment]
logged internally: INFRAANO-621

**Comment by jesmith18** [comment]
Thanks.

Here's the current regular expression used by ansible to determine whether to issue a warning:

PASSWORD_MATCH = re.compile(r'^(?:.+[-_\s])?pass(?:[-_\s]?(?:word|phrase|wrd|wd)?)(?:[-_\s].+)?$', re.I)

To avoid this in the future, you probably should stay away from having password, passphrase, passwrd & passwd in the name of any parameter that doesn't contain a password.

**Comment by wojtek0806** [comment]
no, we will be using update_password parameter as it is a set pattern and done on purpose and we have good reasons for it. This change was introduced by Ansible and I find it preposterous that modules that were there forever all of a sudden should change their parameter names, it should be the other way around if you introduce a change in a product that affect existing collections you should do a better job at the solution. I will add no_log=False to all update_password parameters to work around this, but i want to be clear on the message.

**Comment by jesmith18** [comment]
Wojciech, I completely concur with you on both of your points.

You cannot change the name of the update_password parameter because there are now existing playbooks coded to use it. And you are right to point out that this is an ansible change.

I was merely suggesting that going forward, you may wish to avoid anything that may match that regex in new parameters.
