### ISSUE TITLE
bigip_profile_tcp does not have minimum-rto parameter

### ISSUE THREAD

**Issue by ply1-ops** [F5Networks/f5-ansible#2147]

**Comment by trinaths** [comment]
Suggest use Ansible V2 collection with AS3. See the AS3 schema https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#tcp-profile to configure minimum-rto for bigip-profile-tcp.

**Comment by trinaths** [comment]
closing this issue.
