### ISSUE TITLE
bigip_profile_http_compression module doesn't have capability to include list of different file types

### ISSUE THREAD

**Issue by ply1-ops** [F5Networks/f5-ansible#2148]
### Describe the solution you'd like
Example: Application type list, Image type list, graphic type list, and etc... 

There is no way to add more lists of different file types in the current bigip_profile_http_compression module 

The tmsh command has the ability to modify the LTM http compression profile by adding extra file type lists with content-type-include parameter.   All I am seeing is that this module only specify a little bit on type of gzip compressions and buffer, but nothing else.

**Comment by trinaths** [comment]
@ply1-ops - suggest use AS3 with ansible - See as3 JSON schema https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-http-profilehttpcompression and using AS3 with ansible - https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/playbook_tutorial.html?highlight=as3
