### ISSUE TITLE
The requested profile (/Common/clientssl_my_application) was not found.\",\"errorStack\":[],\"apiError\":3}'"}

### ISSUE THREAD

**Issue by 1080dpi** [F5Networks/f5-ansible#2149]
Hello !!
I'm getting an error while creating a virtual server with bigip_virtual_server module. 

The error message i get : 
```
FAILED! => {"changed": false, "msg": "b'{\"code\":404,\"message\":\"01020036:3: The requested profile (/Common/clientssl_my_application) was not found.\",\"errorStack\":[],\"apiError\":3}'"}
```
But my client-ssl profile has been created in /My_application_part/clientssl_my_application.
And this issue appears only when i use the f5network galaxy. The ansible playbook works fine **without f5network collection**.

It is highly appreciable Could any one of you help with how to fix this error our help me to understand why that don't work ?

**Comment by trinaths** [comment]
@1080dpi please share complete playbook to further investigate this issue.

**Comment by 1080dpi** [comment]
Hello @trinaths, 
Thanks for your response but i found the solution by myself.
You can close this topic.
