### ISSUE TITLE
About bigip_ssl_pkcs12 module

### ISSUE THREAD

**Issue by olguarabaci** [F5Networks/f5-ansible#2152]
Hi Everyone!

I want to ask a question about the module which i mentioned in subject. I couldn't understand clearly from the website which related about F5 Ansible Collection v2. Is the source field in this module point to a path where is on a server(in which Ansible is working on) or f5 device?

_Tasks:
    - name: Install PKCS12 cert and key
      bigip_ssl_pkcs12:
        **source: /root/baz.p12**
        state: present_

**Comment by trinaths** [comment]
@olguarabaci - it must point to a path where is on a server

**Comment by KrithikaChidambaram** [comment]
Closing this now. Reopen if required. Thanks!
