### ISSUE TITLE
bigip_device_info needs to support listing of UCS backups

### ISSUE THREAD

**Issue by jesmith18** [F5Networks/f5-ansible#2156]
### Is your feature request related to a problem? Please describe.
There is no way to get a listing of the UCS backups that have been created on a system

### Describe the solution you'd like
The bigip_device_info should have a gather_subset option for UCS backups

### Describe alternatives you've considered
Using bigip_command to run "list /sys ucs" works but its output is difficult to work with.

### Additional context

**Comment by trinaths** [comment]
Fixed with  PR https://github.com/F5Networks/f5-ansible/pull/2166
