### ISSUE TITLE
[doc] bigiq_device_discovery module: update use_bigiq_sync comments

### ISSUE THREAD

**Issue by rjouhann** [F5Networks/f5-ansible#2169]
##### COMPONENT NAME
[bigiq_device_discovery](https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigiq_device_discovery_module.html) module

##### PROBLEM

The documentation for **use_bigiq_sync** parameter is incorrect and confusing.

**Replace:**
- use_bigiq_sync boolean | Choices: no ←yes | When set to **true**, BIG-IQ manually synchronizes configuration changes between members in a DSC cluster.

**With:**
- use_bigiq_sync boolean | Choices: no ←yes | When set to **no**, Initiate BIG-IP DSC sync when deploying configuration changes. When set to **yes**, Ignore BIG-IP DSC sync when deploying configuration changes.

**Comment by trinaths** [comment]
Created [INFRAANO-667] for internal tracking.
