### ISSUE TITLE
The UCS support in bigip_device_info needs include creation date & time

### ISSUE THREAD

**Issue by jesmith18** [F5Networks/f5-ansible#2177]
### Is your feature request related to a problem? Please describe.
The UCS support in bigip_device_info needs include creation date & time so that cleanup activities can remove old, out-of-date backups

### Describe the solution you'd like
The return from the bigip_device_info task should include the file_created_date of each UCS.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by trinaths** [comment]
Created [INFRAANO-674] for internal tracking.
