### ISSUE TITLE
Add zero_window_timeout to bigip_profile_tcp

### ISSUE THREAD

**Issue by dungfucious** [F5Networks/f5-ansible#2185]
Please add zero_window_timeout to bigip_profile_tcp

**Comment by trinaths** [comment]
@dungfucious - Refer to AS3 schema for this option - https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#tcp-profile

Suggest use F5 BIGIP Collection v2 - See https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/playbook_tutorial.html

**Comment by trinaths** [comment]
@dungfucious  - Please share your findings.

**Comment by trinaths** [comment]
@dungfucious  - Any update ?

**Comment by dungfucious** [comment]
looking to do this using the ansible **f5networks.f5_modules.bigip_profile_tcp** module

**Comment by KrithikaChidambaram** [comment]
Hi, have you tried the F5 BIG-IP v2 collection and AS3?

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
