### ISSUE TITLE
Enable template support for bigip_imish_config

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible#2201]
### Describe the solution you'd like
I would like the `bigip_imish_config` module to work with jinja template as a `src`. Currently it only accepts file as a source for the configuration.

### Describe alternatives you've considered
There are really no alternatives I could think of, I have to first template the config locally, then push to the Big-IP which should not be necessary, if we could template the config directly as part of the module.

### Additional context
If I try to use a template now, the module fails with following error:
```"msg": "path specified in src not found"``` (I do have the location specified correctly)

**Comment by m-kratochvil** [comment]
**Edit:**
It seems the module `src` parameter does not work with `lookup` at all, I got the same error described above when I try to use `lookup('file', 'xxxxxx')` - and the file lookup is presented in the module documentation as a viable option.

**Comment by wojtek0806** [comment]
@m-kratochvil src is a `path` type parameter it requires relative or absolute path to the file, the way it is handled internally makes it impossible to fulfill your request without introducing breaking change

**Comment by m-kratochvil** [comment]
@wojtek0806 thanks for the explanation, understood. I'll work around it.
