### ISSUE TITLE
How to get free disk space and power supply state  with ansible?

### ISSUE THREAD

**Issue by gaetanquentin** [F5Networks/f5-ansible#2212]
I would like to get the following informations from the f5 with ansible:

 - power supply state 
 - disk free space

How to do it with ansible f5 modules?

Regards

**Comment by Jerry-Lees** [comment]
I don't have a physical device handy to assist further, but things like that should be in 'tmsh show sys hardware' and some variant of 'df  -h' will get you what you need-- along with some sed/awk/grep wizardry. You should be able to run those with the bigip command module (or the Ansible shell module) via delegate_to specifying teh BIG-IP.
