### ISSUE TITLE
f5os_platform_info module

### ISSUE THREAD

**Issue by tmarfil** [F5Networks/f5-ansible#2225]
"If you're going to prioritize an Ansible module for F5OS, the first thing we need is a way to collect a comprehensive set of F5OS Ansible facts!" - Customer request

Similar concept to the bigip_device_info module
https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_device_info_module.html

This way, we can conveniently collect a comprehensive set of facts in one place, without having to collect them by running a bunch of random API GETs or parsing the output of show CLI commands. The Ansible facts can then be fed into the generic uri or shell module to configure just about anything, even if a native Ansible module is missing.

**Comment by trinaths** [comment]
Created [INFRAANO-824] for internal tracking.

**Comment by wojtek0806** [comment]
this has been completed in a new collection
