### ISSUE TITLE
bigip_parition giving error

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#224]
Playbook

'''
- name: Partition BIG-IP
  hosts: unmanaged_bigip1
  gather_facts: false

  tasks:

  - name: Add partition
    bigip_partition:
      server: "10.192.73.106"
      user: "admin"
      password: "admin"
      name: "foo"
      validate_certs: "False"
    delegate_to: localhost

Error:
fatal: [10.192.73.106 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_2ioY6p/ansible_module_bigip_partition.py\", line 357, in <module>\n    main()\n  File \"/tmp/ansible_2ioY6p/ansible_module_bigip_partition.py\", line 347, in main\n    result = obj.apply_changes()\n  File \"/tmp/ansible_2ioY6p/ansible_module_bigip_partition.py\", line 133, in apply_changes\n    changed = self.present()\n  File \"/tmp/ansible_2ioY6p/ansible_module_bigip_partition.py\", line 144, in present\n    if self.partition_exists():\n  File \"/tmp/ansible_2ioY6p/ansible_module_bigip_partition.py\", line 156, in partition_exists\n    return self.api.tm.sys.folder.exists(\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/mixins.py\", line 102, in __getattr__\n    raise AttributeError(error_message)\nAttributeError: '<class 'f5.bigip.tm.sys.Sys'>' object has no attribute 'folder'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

BIG-IP version
 Version     12.1.2
  Build       0.0.249

**Comment by caphrim007** [comment]
@payalsin this should now be fixed
