### ISSUE TITLE
Add filter documentation for the filter plugins

### ISSUE THREAD

**Issue by samccann** [F5Networks/f5-ansible#2257]
ansible-core 2.14 adds 'side car docs' which gives collection owners the ability to add documentation for previously undocumentable filter and test plugins.

This requires creating yaml files in the same directory as the filter or test plugin code, one yaml file per plugin.

See https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/b64decode.yml for an example.

**Comment by samccann** [comment]
The following filter plugins need documentation:

[abspath filter](https://docs.ansible.com/ansible/devel/collections/f5networks/f5_modules/abspath_filter.html#ansible-collections-f5networks-f5-modules-abspath-filter) –

[verchg filter](https://docs.ansible.com/ansible/devel/collections/f5networks/f5_modules/verchg_filter.html#ansible-collections-f5networks-f5-modules-verchg-filter) –

**Comment by samccann** [comment]
Ideal timeline would be to provide these by the time Ansible 7  releases at the end of November but we realize this information wasn't conveyed to collection owners on a more timely basis.

Related to https://github.com/ansible-community/community-team/issues/65

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this item is: INFRAANO-981, thanks!
