### ISSUE TITLE
bigip_ucs_fetch fail_on_missing is redundant - remove since create_on_missing exists

### ISSUE THREAD

**Issue by nwehrman** [F5Networks/f5-ansible#2258]
##### COMPONENT NAME
bigip_ucs_fetch

##### ANSIBLE VERSION
All

##### BIGIP VERSION
13.X, 14.x+
##### CONFIGURATION
The function fail_on_missing is largely irrelevant in the face of create_on_missing as an option. The module should probably just mark nothing changed if the ucs is missing and create_on_missing is not set.

##### EXPECTED RESULTS
only create_on_missing is needed for this module

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this item is: INFRAANO-980, thanks!

**Comment by wojtek0806** [comment]
After reviewing the source code we will be keeping the option, I have added some documentation entries to help clarify how the option is used, and what is the expecte behavior when using `fail_on_missing` with `create_on_missing`
