### ISSUE TITLE
Collection Requirements Violation - Repository Management  

### ISSUE THREAD

**Issue by gotmax23** [F5Networks/f5-ansible#2266]
Hi! The Ansible Community Steering Committee has determined that this collection does not tag its releases in its git repository. This violates the [repository management](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management) section of the Collection Requirements:

> Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be `git tag`ed and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a `v` prefix, but a collection's tag names MUST have a consistent format from release to release.
>
> Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

Note that this requirement has recently [been clarified](https://github.com/ansible-collections/overview/commit/6dbb5037c09dce9324cb39e322be2f42e068f117), but its intent remains the same. Please tag at least the previous 1-2 releases of your collection to come into compliance.

Please keep us updated and let us know if you have any questions. Thanks!

**Comment by wojtek0806** [comment]
We already do this, i will update galaxy.yaml so it points to the tagged repo, this repo you are on now is for development and issues only

Repository for releases: https://github.com/F5Networks/f5-ansible-f5modules
