### ISSUE TITLE
Replace mutual exclusion for the disabled_vlans and enabled_vlans in In the bigip_virtual_server module

### ISSUE THREAD

**Issue by jbericat** [F5Networks/f5-ansible#2276]
### Is your feature request related to a problem? Please describe.

Yes (described in the next section)

### Describe the solution you'd like

In the `bigip_virtual_server` module , the `disabled_vlans` and `enabled_vlans` parameters are inconsistent with the iControl REST-API data gathered by the `/mgmt/tm/ltm/virtual/{{ vserver_name}}/?expandSubcollections=true"` GET request. I'm using a REST API request here because the `bigip_device_info` module has not the ability to filter data by virtual server name. Not only that, but I'm gathering like **+1300 virtual servers** at once, which in my case takes more than 15 minutes and often produces an X-Auth-Token error due to its expiration (maybe that's a bug of the `bigip_device_info` module itself?). 

The most logical way to set disabled or enabled vlans would be to have 2 parameters (a boolean one and a list), instead of two mutually excluded parameters (lists)

```
enabled_vlans: true / false (boolean)
vlans: either a list of vlans or the string 'all' to set "All Vlans and Tunnels" 
```

So, if we set `enabled_vlans == false`, the list in the `vlans` parameter would set all these VLAN as `disabled on` for the ` VLAN and Tunnel Traffic` option in the F5-BIGIP LTM Virtual Server. On the other hand, if we set `enabled_vlans == true` the list in the `vlans` parameter would set all these VLAN as `enabled on` for the ` VLAN and Tunnel Traffic` option in the F5-BIGIP LTM Virtual Server. 

### Describe alternatives you've considered

I could use jinja templates or just `where` conditionals to workaround this mutual exclusion, but It would be a lot simpler and cleaner to do it the way I suggest.

### Additional context

**F5Networks.F5_Modules collection tested versions:** 1.16.0, 1.18.0
**Ansible version:** 2.9.27.post0

**Comment by KrithikaChidambaram** [comment]
Hi, internal ID to track this item is: INFRAANO-977, thanks!

**Comment by G-gonzalezjimenez** [comment]
We did another review of this issue, we have customers that are already using the parameters and changing them would introduce braking changes to the product. We won't be able to provide a fix for you.

**Comment by jbericat** [comment]
> 

Ok I understand. Anyway, thanks a lot for looking at it by twice @G-gonzalezjimenez. I'll just keep using the workaround I implemented using the REST API call via the ansible.builtin.uri module - I know that's kind of a bad practice, but in this very case it saves the day for me :) 

Cheers!
