### ISSUE TITLE
bigip_profile_http - response_chunking "sustain" fails

### ISSUE THREAD

**Issue by pkodzis** [F5Networks/f5-ansible#2277]
Test obj:
    - name: Create HTTP profile 
      bigip_profile_http:
        name: TEST
        response_chunking: sustain
      delegate_to: localhost

generates error:
    "msg": "value of response_chunking must be one of: rechunk, selective, preserve, got: sustain"

regardless of the doc saying:

"Specifies how to handle chunked and unchunked responses.
When creating a new profile, if this parameter is not specified, the default is provided by the parent profile.
Choices:
"rechunk"
"selective"
"preserve"
"sustain"
"unchunk""

**Comment by KrithikaChidambaram** [comment]
Hi, can you share the playbook with us to understand the issue better?
What version of BIG-IP and Ansible are you using?

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
