### ISSUE TITLE
bigip_selfip module enhancement request to add RD suffix in the IP address

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#228]
One way to use route domains is to add ip address's suffixed with the route domain ID, example 10.10.10.100%10

Right now if we do that we get an error:

---
- name: BIG-IP
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Configure SELF-IPs on the BIG-IP
    bigip_selfip:
     server: "10.192.73.218"
     user: "admin"
     password: "admin"
     validate_certs: False
     name: "selfip"
     address: "10.10.10.10%10"
     netmask: "255.255.255.0"
     vlan: "External"
    delegate_to: localhost

fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The provided address/netmask value was invalid"}

**Comment by caphrim007** [comment]
@payalsin try now

**Comment by caphrim007** [comment]
Closing as I believe this is now fixed
