### ISSUE TITLE
bigip_sys_global: Add support to enable gui auditing

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible#2299]
### Is your feature request related to a problem? Please describe.
Audit logging is a requirement for most deployments. While audit logging is active for most interfaces it is not enabled for the Web UI by default (GUI).

<img width="280" alt="image" src="https://user-images.githubusercontent.com/1498073/217629298-b0ec52cf-7749-4362-bda7-e3de93dba358.png">

This issue is explicitly asks to add support to enable GUI audit logging via ansible `bigip_sys_global`. It is related to an existing issue: #1515

### Describe the solution you'd like
Add a `gui_audit` parameter to `bigip_sys_global` to control the boolean tmsh field `gui-audit` / REST API field `guiAudit`.

### Describe alternatives you've considered
The parameter can be set via tmsh, hence workarounds via ansible are available.

**Comment by wojtek0806** [comment]
merged
