### ISSUE TITLE
Module support for vCMP

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#230]
Opening a request for vCMP module support.

1) Create a guest
2) Assign a VLAN list to a guest (update a guest after it is created)

**Comment by payalsin** [comment]
In the private cloud package (with Cisco ACI) we have used Ansible to configure the APIC and F5. 
There was one manual step (which is the step - assigning the VLAN from the vCMP host to the vCMP guest)

It would be nice if we can prioritize this module so that we have no manual step but an end-to-end automated solution for unmanaged mode integration with ACI. We don’t have to get all vCMP functionality just this one will do.

**Comment by payalsin** [comment]
For the above request the module features are satisfied. But to make it more flexible adding a field to specify the number of cores per vCMP guest would be very useful

**Comment by caphrim007** [comment]
@payalsin would you make that a separate issue?

**Comment by caphrim007** [comment]
PR for this is here https://github.com/ansible/ansible/pull/33024

**Comment by caphrim007** [comment]
this has been merged

**Comment by toro0411** [comment]
Hi 
If I wanna add new vlan into vcmp guest, how can I do?
