### ISSUE TITLE
Enhancement to upload cert,intermediate cert, and key to load balancer

### ISSUE THREAD

**Issue by fwissue** [F5Networks/f5-ansible#232]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME

bigip_ssl_certificate
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### PYTHON VERSION

```
2.7
```

##### BIGIP VERSION

```
12.1.2
```

##### CONFIGURATION

n/a
##### SUMMARY

When we install the cert,key, we also need to install intermediate cert.
current bigip_ssl_certificate module does not provide the function to install intermediate cert.
##### STEPS TO REPRODUCE

Tmsh install sys crypto cert certname from-local-file /var/tmp/<certname_cert>
Tmsh install sys crypto key keyname from-local-file /var/tmp/<keyname_key>
Tmsh install sys crypto cert bundlename from-local-file /var/tmp/<bundlename_bunlde>

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
#222 is also related to this issue. closing this one so that we can track it at the other issue. 

@fwissue please refer to the above issue where we'll track this. Thanks for the idea submission! if you believe your request includes more than what is mentioned in the mentioned issue, feel free to mention it here to clarify.

**Comment by fwissue** [comment]
Any update for #222

**Comment by caphrim007** [comment]
@fwissue this functionality is still in process

**Comment by caphrim007** [comment]
@fwissue i was speaking with a colleague who pointed out to me that a ca bundle is nothing more than a regular cert as far as bigip is concerned. are you able to install the intermediate cert if you use a second task that names it instead of your original key pair

**Comment by caphrim007** [comment]
@fwissue ping on this.
