### ISSUE TITLE
bigip_virtual_server tries to set "type" when modifying a virtual server, even when not specified

### ISSUE THREAD

**Issue by rbriancollins** [F5Networks/f5-ansible#2320]
##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION
```
ansible 2.9.27
  config file = None
  configured module search path = ['/Users/brian.collins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible@2.9/2.9.27_4/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/opt/ansible@2.9/bin/ansible
  python version = 3.9.16 (main, Dec  7 2022, 10:16:11) [Clang 14.0.0 (clang-1400.0.29.202)]
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.5.1
  Build       0.0.6
  Edition     Point Release 1
  Date        Thu Jul  7 06:30:32 PDT 2022
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When running a playbook to modify a virtual server using `bigip_virtual_server`, the module attempts to set `type` (to "standard", by default).  For our virtual servers that are set to something different, this causes the playbook to fail, since `type` cannot be changed after the virtual server is created.

##### STEPS TO REPRODUCE
1. Have a virtual server whose type is *not* set to "standard"
2. Run the following playbook to modify the virtual server
```---
- name: replace default pool for a VS
  hosts: all
  gather_facts: false
  - name: set the default pool
    bigip_virtual_server:
      name: "my-virtual-server"
      pool: "pool1"
      provider:
          server: lb.example.com
          user: admin
          password: supersecretpassword
    delegate_to: localhost```

##### EXPECTED RESULTS
The default pool is set to `pool1`.

##### ACTUAL RESULTS
Playbook failed with `"Changing the 'type' parameter is not supported."`

```
ansible-playbook 2.9.27
  config file = None
  configured module search path = ['/Users/brian.collins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible@2.9/2.9.27_4/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/opt/ansible@2.9/bin/ansible-playbook
  python version = 3.9.16 (main, Dec  7 2022, 10:16:11) [Clang 14.0.0 (clang-1400.0.29.202)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /Users/brian.collins/devel/ibm-playbooks/inventories/localhost as it did not pass its verify_file() method
script declined parsing /Users/brian.collins/devel/ibm-playbooks/inventories/localhost as it did not pass its verify_file() method
auto declined parsing /Users/brian.collins/devel/ibm-playbooks/inventories/localhost as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /Users/brian.collins/devel/ibm-playbooks/inventories/localhost inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible@2.9/2.9.27_4/libexec/lib/python3.9/site-packages/ansible/plugins/callback/default.py
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: x.yml ************************************************************************************************************************************
Positional arguments: x.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/Users/brian.collins/devel/ibm-playbooks/inventories/localhost',)
forks: 5
1 plays in x.yml

PLAY [replace default pool for a VS] ***************************************************************************************************************
META: ran handlers

TASK [set the default pool] ************************************************************************************************************************
task path: /Users/brian.collins/devel/ibm-playbooks/x.yml:6
<localhost> Using network group action bigip for bigip_virtual_server
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: brian.collins
<localhost> EXEC /bin/sh -c 'echo ~brian.collins && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/brian.collins/.ansible/tmp `"&& mkdir "` echo /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611 `" && echo ansible-tmp-1680109697.2384698-91761-13766708289611="` echo /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611 `" ) && sleep 0'
Using module file /usr/local/Cellar/ansible@2.9/2.9.27_4/libexec/lib/python3.9/site-packages/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> PUT /Users/brian.collins/.ansible/tmp/ansible-local-91757lckpfe21/tmpbze6hron TO /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611/AnsiballZ_bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611/ /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python3 /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/brian.collins/.ansible/tmp/ansible-tmp-1680109697.2384698-91761-13766708289611/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3658, in main
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3328, in exec_module
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3340, in present
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3362, in update
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3370, in should_update
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3400, in _update_changed_options
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 2981, in compare
  File "/var/folders/vg/pm2q12qj5g9d9lqzdf14l7qc0000gp/T/ansible_bigip_virtual_server_payload_4eefnlit/ansible_bigip_virtual_server_payload.zip/ansible/modules/network/f5/bigip_virtual_server.py", line 3277, in type
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address_translation": null,
            "clone_pools": null,
            "default_persistence_profile": null,
            "description": null,
            "destination": null,
            "disabled_vlans": null,
            "enabled_vlans": null,
            "fallback_persistence_profile": null,
            "firewall_enforced_policy": null,
            "firewall_staged_policy": null,
            "insert_metadata": true,
            "ip_intelligence_policy": null,
            "ip_protocol": null,
            "irules": null,
            "mask": null,
            "metadata": null,
            "mirror": null,
            "name": "my-virtual-sever",
            "partition": "Common",
            "policies": null,
            "pool": "pool1",
            "port": null,
            "port_translation": null,
            "profiles": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "lb.example.com",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "svc_f5-dashboard",
                "validate_certs": false
            },
            "rate_limit": null,
            "rate_limit_dst_mask": null,
            "rate_limit_mode": "object",
            "rate_limit_src_mask": null,
            "security_log_profiles": null,
            "security_nat_policy": null,
            "snat": null,
            "source": null,
            "source_port": null,
            "state": "present",
            "type": "standard"
        }
    },
    "msg": "Changing the 'type' parameter is not supported."
}

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by pgouband** [comment]
Hi, internal ID to track this item is: INFRAANO-1151, thanks!

**Comment by wojtek0806** [comment]
this is working as intended, when creating new VS if you do not specify the type standard type is assumed, it even tell you that in the docs: https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py#L36

**Comment by pgouband** [comment]
hi @rbriancollins,

As explained by @wojtek0806, type needs to be specified each time you want to modify the virtual server configuration.
for example for a FastL4 virtual server:

```ansible
  tasks:
    - name: set the default pool
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "myvs"
        pool: "mypool"
        type: "performance-l4"
        profiles:
          - fastL4
      delegate_to: localhost
```

**Comment by wojtek0806** [comment]
one more thing to add, if you find that you need to override the defaults, on regular basis, you can define module defaults in your playbook, see this link: https://docs.ansible.com/ansible/2.9/user_guide/playbooks_module_defaults.html

**Comment by rbriancollins** [comment]
I understand.
And I realize this is going to sound impolite, but that seems excessive.
In order to change the default pool, I must specify the VS type, even though it already has a type.
But on top of that, *if* I specify the type, I must *also* specify the profiles that go along with it, even though they also are already assigned.  If I do not, I get yet another error. 
All this - just to change the pool.  
It seems like a lot of extra work every time we want to change the default pool for a non-standard VS.

**Comment by G-gonzalezjimenez** [comment]
Hi @rbriancollins thanks for your comments, we would like to discuss this further to understand your need better. Could you send us an email at: automation_ecosystem@f5.com.

Thank you

**Comment by AtelierSnek** [comment]
> Hi @rbriancollins thanks for your comments, we would like to discuss this further to understand your need better. Could you send us an email at: [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com).
> 
> Thank you

The use-case where this becomes frustrating is in cases where you have non-standard types with existing configuration (such as a FastL4 VIP with a custom FastL4 profile), where you only want to change one thing, such as disabling the VIP, or changing attached pool. The module should allow non-specified type and profiles to just mean "do nothing, change nothing", and only change what has been requested.
