### ISSUE TITLE
daily build not created/up-to-date

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#2321]
##### COMPONENT NAME
The daily build, as downloaded today, is from 22-03-23.
Please fix the issue as I would like to get the build with https://github.com/F5Networks/f5-ansible/pull/2318 fix

##### ANSIBLE VERSION

```

```
##### BIGIP VERSION

```

```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by G-gonzalezjimenez** [comment]
Hi,  Can you write an email to automation_ecosystem@f5.com so we can talk more about this?  Thank you

**Comment by wojtek0806** [comment]
it should be fixed now, i created new build and automation is sorted
