### ISSUE TITLE
bigip_policy_rule - Support all 'server_name' conditions on ssl_extension type

### ISSUE THREAD

**Issue by clemmesserli** [F5Networks/f5-ansible#2350]
### Is your feature request related to a problem? Please describe.
This ansible module does not support a feature of the UI/API that we'd like to utilize from within Ansible playbook.

### Describe the solution you'd like
Support all of the various 'server_name_xx' conditions for a policy rule. 
This is something available in the F5 WebUI and in the REST API and should be similar to the 'host_xx' conditions:

server_name_begins_not_with_any
server_name_begins_with_any
server_name_contains
server_name_ends_not_with_any
server_name_ends_with_any
server_name_is_any
server_name_is_not_any

### Describe alternatives you've considered
  - Current workaround is to handle via PowerShell or Postman using the REST api instead of Ansible as AS3 is not presently an option at this time due to the level of time/effort that would be needed to restructure all of our present automation build repositories.
  - Have considered forking the present module and building our own support within 'bigip_policy_rule.py', however, we prefer to leverage the officially supported F5 Ansible collections.
  
### Additional context
msg: 'Unsupported parameters for (bigip_policy_rule) module: conditions.server_name_contains.

**Comment by pgouband** [comment]
Hi @clemmesserli,

Thanks for the request.
We will investigate the amount of effort that it takes to add this feature.

**Comment by G-gonzalezjimenez** [comment]
Hi, we are tracking internally with ticket INFRAANO-1273
