### ISSUE TITLE
bigiq_device_discovery - Failed to retrieve BIGIQ version

### ISSUE THREAD

**Issue by sdaynjax** [F5Networks/f5-ansible#2370]
##### COMPONENT NAME
bigiq_device_discovery

##### ANSIBLE VERSION
Ansible version is 2.9

##### BIGIP VERSION
Big-IP version 16.1.3.4
Big-IQ 8.3.0.0.0.118

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Running from Ansible Tower

##### SUMMARY
Trying to rediscover and import an existing device within my Big-IQ.  I'm using the 1.25.0 collection that is being pulled from the Ret Hat automation hub.  The error I'm getting is "Failed to retrieve BigIQ version". When I check it looks like that error is coming from the module-utils icontrol.py and not the bigiq_device_discovery.py.

##### STEPS TO REPRODUCE
Run in Ansible Tower

---
- name: Big-IQ Discovery
   hosts: F5-Big-IQ
   connection: local
   collections:
      - f5networks.f5_modules
   vars:
      f5_server: 10.1.1.2    # Big-IP address
    
    tasks:
     
    - name: Collect Big-IQ Info    # This works fine
       bigiq_device_info: 
          gather_subset:
            - managed-devices
          provider: 
             server: "{{ f5_server }}"
             user: "{{ ansible_user }}"
             password: "{{ ansible_password }}"
             validate_certs:  false
       delegate_to: localhost

    - name:  Force full device discovery
       bigiq_device_discovery:
          device_address:  "{{ f5_server }}"
          force: yes
          modules:
             - ltm
          provider: 
             server: "{{ f5_server }}"
             user: "{{ ansible_user }}"
             password: "{{ ansible_password }}"
             validate_certs:  false
       delegate_to: localhost

I expected Big-IQ to rediscovery the Big-IP and reimport.

Error message:

File "/tmp/ansible_bigiq_device_discovery_payload_yiqc9amg/ansible_bigiq_device_discovery_payload.zip/ansible_collection/f5networks/f5_modules/plugins/module_utils/icontrol.py", line 594, in bigiq_version raise F5ModuleError(

**Comment by rd060** [comment]
I suspect that is due to the provider/server being pointed towards the BIG-IP, instead of the BIG-IQ. You might be able to verify by performing a packet capture between the Ansible host and the BIG-IQ (or the BIG-IP) to see where Ansible sends the requests. Documentation may need to be updated.

**Comment by prateekramani** [comment]
Hi, 
Please try providing BIG-IQ credentials in the provider block , I made provider block point to BIG-IQ credentials, and its working for me.

**Comment by pgouband** [comment]
Hi,

We are closing this request now.
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
