### ISSUE TITLE
Import CA-Bundle with bigip_ssl_certificate

### ISSUE THREAD

**Issue by Kainik-sk** [F5Networks/f5-ansible#2385]
Currently I found no way to upload CA-Bundle via any existing f5 module. The only way to do it so far is to scp the cert into some tmp dir and then install it via command module. 
Could this functionality be added?

**Comment by pgouband** [comment]
Hi @Kainik-sk,

Have you checked the following page https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_ssl_certificate_module.html#bigip-ssl-certificate-module-3 ?


There are some example an here the example for a CA certificate chain but it works with a CA bundle.

```ansible
- name: Use a file lookup to import CA certificate chain
  bigip_ssl_certificate:
    name: ca-chain-name
    state: present
    content: "{{ lookup('file', '/path/to/ca-chain.crt') }}"
    provider:
      server: lb.mydomain.com
      user: admin
      password: secret
  delegate_to: localhost
```

**Comment by Kainik-sk** [comment]
Yes I used this exact example, and when I tried to upload CA bundle I get error msg: "Failed to upload file", but when I try to upload simple certificate it works no issues

**Comment by pgouband** [comment]
Hi @Kainik-sk,

I tried with a CA bundle without any issue so could you check your CA bundle file is correctly created (one line per -----END CERTIFICATE-----, -----BEGIN CERTIFICATE----- and per certificate)?

**Comment by Kainik-sk** [comment]
the CA bundle file looks like this. There are several certs contained and each looks like this:

subject=/****
issuer= /****
-----BEGIN CERTIFICATE-----
cert-string
-----END CERTIFICATE-----

Could the issue be with the subject and issuer?

**Comment by pgouband** [comment]
Hi @Kainik-sk,

I guess.
The file should only contain:
-----BEGIN CERTIFICATE-----
cert-string
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
cert-string
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
cert-string
-----END CERTIFICATE-----

**Comment by Kainik-sk** [comment]
OK but when I upload it via GUI or scp it to F5 /shared/tmp and istall it from there with: "tmsh install /sys crypto cert ..." all works fine. This certificates are provided in this form by customer and I can't modify them

**Comment by pgouband** [comment]
Hi @Kainik-sk,

I can't ask you to add -vvvv to ansible command as it will show all the content of the CA bundle file.
bigip_ssl_certificate module support PEM format only (without subject and issuer).
Have you tried to convert to PEM format the CA bundle?

**Comment by Kainik-sk** [comment]
Hi Patrick, 
no it didn't occur to me to convert it. But it seems it did the trick converting the .crt to .pem and the upload works as you described.
Thank you so much for assistance.
