### ISSUE TITLE
Manage Security Log Profile for application

### ISSUE THREAD

**Issue by slawekww** [F5Networks/f5-ansible#2397]
### Is your feature request related to a problem? Please describe.

It is not possible to manage F5 Security Log profile via ansible (nor Terraform BTW).

Please extend  task `https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_security_log_profile_module.html` to manage application properties.

For now it is only possible via tmsh command like:
```
create /security log profile /particition/name { application replace-all-with /partition/name { filter ... }}
```

### Describe the solution you'd like
Possibility to manage the same as ansible task like:

```
bigip_security_log_profile:
  application:
    <properties>
```

### Describe alternatives you've considered
Support it via Terraform if possible however preference is to support it via ansible.

### Additional context
Goal is to automate F5 Security Log Profile creation/modification for sending WAF event logs to remote system.

**Comment by pgouband** [comment]
Hi @slawekww,

Have you tried using AS3 and Ansible declarative collection?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#security-log-profile

**Comment by wojtek0806** [comment]
I think we did something on Declarative collection: https://github.com/F5Networks/f5-ansible-bigip/blob/devel/ansible_collections/f5networks/f5_bigip/plugins/modules/bigip_security_log_profile.py

See if this what you are looking for, otherwise AS3 will be next best thing

**Comment by wojtek0806** [comment]
@slawekww  this is the wrong repo to ask for this, raise issues here for Declarative collection:  https://github.com/F5Networks/f5-ansible-bigip/issues

**Comment by slawekww** [comment]
@pgouband No, I've not used AS3 and Ansible declarative collection. Could you share example how to use it?

@wojtek0806 Thanks for pointing it. Created new feature request at different repo: https://github.com/F5Networks/f5-ansible-bigip/issues/83
