### ISSUE TITLE
testing and usage of the ssl_certificate module

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#24]
There has been a fairly significant refactor of the ssl_certificate module to allow for modifying certs in place. Additionally, some argument names have changed to meet ansible-isms that are commonly used.

@waffie1 I'd like to make sure that these changes still offer a consistent user experience for you. Can you test them? In the roles/__bigip_ssl_certificate/tasks/main.yaml file you can find example usages.

**Comment by waffie1** [comment]
Ok, I will check it out.
