### ISSUE TITLE
bigip_dns_resolver is missing parameter forward_zones

### ISSUE THREAD

**Issue by nomike** [F5Networks/f5-ansible#2400]
##### COMPONENT NAME
bigip_dns_resolver

##### ANSIBLE VERSION

```
ansible 2.10.8
  config file = None
  configured module search path = ['/home/nomike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.3.5
  Build       0.0.5
  Edition     Point Release 5
  Date        Thu May 18 05:10:05 PDT 2023
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY
The module bigip_dns_resolver  lacks the `forward_zones` parameter. It is thus impossible, to configure a DNSResolver with proper forward zones directly in Ansible.

Workarounds are:
1. Add the forward zone manually in the gui or via tmsh
2. Run tmsh via `bigip_command`:

```ansible
- name: run show version on remote devices
  bigip_command:
    commands: "modify /net dns-resolver foo forward-zones replace-all-with { . { nameservers replace-all-with { 8.8.8.8:53 } } }"
    provider: "{{ provider}}"
```

##### STEPS TO REPRODUCE

As the lack of this parameter forces me to run tmsh commands directly, I consider this to be a bug rather than a feature request.

##### EXPECTED RESULTS

I would expect `bigip_dns_resolver` to have a parameter `forward_zones` which allows configuration of the forward zones of the resolver.

**Comment by pgouband** [comment]
Hi @nomike,

Have you tried using AS3 and Ansible Declarative collection?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#dns-cache-resolver

https://github.com/F5Networks/f5-ansible-bigip

**Comment by pgouband** [comment]
Hi @nomike,

There was no response from you.
Please reopen the issue if needed.
