### ISSUE TITLE
bigip_profile_http is missing parameter for explicit-proxy configuration

### ISSUE THREAD

**Issue by nomike** [F5Networks/f5-ansible#2401]
##### COMPONENT NAME
bigip_profile_http

##### ANSIBLE VERSION

```
ansible 2.10.8
  config file = None
  configured module search path = ['/home/nomike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.3.5
  Build       0.0.5
  Edition     Point Release 5
  Date        Thu May 18 05:10:05 PDT 2023
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY
The module bigip_profile_http lacks a parameter for configuring the "Default Connect Handling" flag.

Workarounds are:
1. Change the flag manually in the GUI
2. Run tmsh via `bigip_command`:

```ansible
- name: "Allow connect handling"
  bigip_command:
    chdir: "/PR"
    commands: "modify /ltm profile http HTTPProxyHTTP explicit-proxy { default-connect-handling allow }"
```

##### STEPS TO REPRODUCE

As the lack of this parameter forces me to run tmsh commands directly, I consider this to be a bug rather than a feature request.

##### EXPECTED RESULTS

I would expect `bigip_profile_http ` to have a parameter `explicit-proxy` which allows configuration of this.

**Comment by pgouband** [comment]
Hi @nomike,

Have you tried using AS3 and Ansible Declarative collection?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#http-profile-explicit

https://github.com/F5Networks/f5-ansible-bigip

**Comment by pgouband** [comment]
Hi @nomike,

There was no response from you.
Please reopen the issue if needed.
