### ISSUE TITLE
Does this collection support more than one host per playbook?

### ISSUE THREAD

**Issue by cardosocristian** [F5Networks/f5-ansible#2422]
I'm starting to use the f5_modules collection and whenever I try to use the ansible_host server field to search for more than one host in the hosts file, I can't use the playbook. The playbook only works correctly if the server field is the F5 I want to connect to. Does this collection support more than one F5 at a time in the playbook?

##### COMPONENT NAME

- name: show sys software
  bigip_command:
    commands:
      - 'run /util bash -c "tmsh show sys software > /tmp/backup/show-sys-software.txt"'
    provider:
      server: **"{{ ansible_host }}"**
      server_port: 443
      no_f5_teem: false
      password: "{{ f5_password }}"
      user: "{{ f5_user }}"
      validate_certs: no
  register: sys_software
  delegate_to: localhost
  tags:
  - show-sys

##### ANSIBLE VERSION

```
ansible [core 2.15.12]
  config file = None
  configured module search path = ['/home/cristian_cardoso/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /work/env/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/cristian_cardoso/.ansible/collections:/usr/share/ansible/collections
  executable location = /work/env/ansible/bin/ansible
  python version = 3.9.19 (main, May 20 2024, 05:19:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/work/env/ansible/bin/python3.9)
  jinja version = 3.1.4
  libyaml = True

```

**Comment by urohit011** [comment]
Hi @cardosocristian , I didn't face any problem when using multiple hosts. My hosts file looks like the following:

```
[host_grp]
xx.xx.xx.xx ansible_host="xx.xx.xx.xx" f5_user=user f5_password=password
yy.yy.yy.yy ansible_host="yy.yy.yy.yy" f5_user=user f5_password=password
```

Are you seeing an error in your case? Could you share the error message.
