### ISSUE TITLE
Removing of pool member is deleting the node

### ISSUE THREAD

**Issue by blod001** [F5Networks/f5-ansible#2443]
If a pool member is set to the status: absent, the node is not just removed from the pool, but the entire node is deleted. In my opinion, the node should remain and only be removed from the pool.

- name: Remove pool member from pool
  bigip_pool_member:
    state: absent
    pool: my-pool
    partition: Common
    name: my-member
    host: "{{ ansible_default_ipv4['address'] }}"
    port: 80
    provider:
      server: lb.mydomain.com
      user: admin
      password: secret
  delegate_to: localhost

##### COMPONENT NAME
bigip_pool_member

##### ANSIBLE VERSION
ansible [core 2.15.13]
  config file = None
  configured module search path = ['/PZIR/users/blod001/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/users/ggcninetsdms/py_venvs/nornir_v3.4.1/lib64/python3.9/site-packages/ansible
  ansible collection location = /PZIR/users/blod001/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/users/ggcninetsdms/py_venvs/nornir_v3.4.1/bin/ansible
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/home/users/ggcninetsdms/py_venvs/nornir_v3.4.1/bin/python3.9)
  jinja version = 3.1.4
  libyaml = True

##### BIGIP VERSION
BIGIP-17.1.1.1-0.0.2

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
N/A

##### SUMMARY
If a pool member is set to the status: absent, the node is not just removed from the pool, but the entire node is deleted. In my opinion, the node should remain and only be removed from the pool.

##### STEPS TO REPRODUCE
- name: Remove pool member from pool
  bigip_pool_member:
    state: absent
    pool: my-pool
    partition: Common
    name: my-member
    host: "{{ ansible_default_ipv4['address'] }}"
    port: 80
    provider:
      server: lb.mydomain.com
      user: admin
      password: secret
  delegate_to: localhost

##### EXPECTED RESULTS
In my opinion, the node should remain and only be removed from the pool.

##### ACTUAL RESULTS
If a pool member is set to the status: absent, the node is not just removed from the pool, but the entire node is deleted.

**Comment by pgouband** [comment]
Hi @blod001,

Is that node created by another Ansible resource?
Or is it created by inheritance from bigip_pool_member?

**Comment by pgouband** [comment]
Hi @blod001,

So the behavior is normal as the node is part of the resource.

**Comment by blod001** [comment]
I was able to remove an pool member from the pool, without deleting the node itself with the option "preserve_node: "true"".
So, there is no bug. This issue can be closed. 
Sorry.
