### ISSUE TITLE
refactor bigip virtual server

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#256]
required to address many bug and feature requests as this is our most used module

**Comment by caphrim007** [comment]
marking this as now complete

**Comment by AndrewSav** [comment]
What is the best way to get this in order for me to test?

**Comment by caphrim007** [comment]
@AndrewSav you can download the individual file from here, and then follow the steps for putting it in a local ansible directory here http://clouddocs.f5.com/products/orchestration/ansible/devel/usage/installing-modules.html#in-a-relative-location-recommended

follow the **Relative Location** directions

**Comment by caphrim007** [comment]
and if there are bugs, file new issues

**Comment by AndrewSav** [comment]
Is there a way for me, to find out when it's merged upstream?

**Comment by caphrim007** [comment]
I'll remove the upstream label from this issue. otherwise, if you watch the Ansible repository.

**Comment by andrewsav-datacom** [comment]
@caphrim007  you wrote
>I'll remove the upstream label from this issue. otherwise, if you watch the Ansible repository.

Hey, that was fixed about a year ago, do you know when it might make into Ansible?

**Comment by caphrim007** [comment]
@andrewsav-datacom the project says 2.5. that's when I'd guess it was merged

**Comment by AndrewSav** [comment]
@caphrim007 thanks - you mentioned that you would remove the upstream label above, so I was waiting for that. I also tested the latest and at did not work, so I assumed that given these two evidences it was not merged.

Turned out, the config format changed, so I had modify my original test case, and then it worked.
Thank you for the good job.

**Comment by caphrim007** [comment]
@AndrewSav my apologies for forgetting to do that. glad to hear that it is working.
