### ISSUE TITLE
Add Application Service (iApp) support

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-ansible#26]
##### ISSUE TYPE

- Feature Idea

Add support to f5-ansible for managing Application Services (iApps).

f5-sdk should be used for this.

**Comment by caphrim007** [comment]
Since we have boilerplate for this already, I can start there.

@erjac77 so you have a preference for iApps vs iAppLX as a place to start? (Assuming I would provide both eventually)

**Comment by erjac77** [comment]
Plain iApp for now. Can I give you a hand?

**Comment by caphrim007** [comment]
@erjac77 sure thing, I'd be happy to entertain PRs.

**Comment by erjac77** [comment]
@caphrim007 I worked on that issue during my spare time and I've come up with a new _F5 BIG-IP Ansible Module_ solely based on the F5 Python SDK.

The main idea behind it was to learn Ansible and Python, while working on some useful features needed at work to automate our F5 boxes that the actual f5-ansible module doesn't provide (like iApp). Moreover, I wanted to leverage the f5-sdk for all BIG-IP objects.

It is still a work in progress, but you can find an early version [here](https://github.com/erjac77/ansible-module-f5bigip). You need to install an utility library that you can find [here](https://github.com/erjac77/ansible-common-f5bigip).

This first version focus mainly on the LTM module. I plan to add some GTM features during the holidays. Like I said, I'm pretty new to Python and Ansible, so there may be some things that have not been done in the right way.

Let me know what you think. Happy Holidays!

**Comment by caphrim007** [comment]
@erjac77 I believe this module is addressed by the bigip_iapp_service module which is, tentatively, complete. Can you have a go at that and if you find an issue, please report.
