### ISSUE TITLE
RFE: Allow ssh key based authentication for F5 modules

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#261]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### SUMMARY
Allow ssh key based authentication for F5 modules. F5 allows ssh key based authentication outside Ansible but there is no way to use it with any of the F5 modules.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
original (closed) reference https://github.com/ansible/ansible/issues/26231

**Comment by caphrim007** [comment]
@jainnikhil30 we will track this here

**Comment by ismc** [comment]
Would a possible work around be to have one module that will accept an ssh key just to set the admin password?  That way, we could automate F5 bringup in cloud environments by setting the password from the vault, then using the other modules with that password.  Not optimal, but workable.

**Comment by caphrim007** [comment]
@ismc you can use the bigip_command via SSH to do this, though it requires the bash shell be enabled for the remote user.

```
bigip_command
    commands: 'printf "new_password\nnew_password\" | tmsh modify auth password root'
    transport: cli
```

**Comment by ismc** [comment]
It still seems to want a password:
'''
fatal: [smc_f5_demo_F5]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": "printf \"Cisc0123\\nCisc0123\\\" | tmsh modify auth password root",
            "interval": 1,
            "match": "all",
            "partition": "Common",
            "retries": 10,
            "server": "X.X.X.X",
            "server_port": 443,
            "state": "present",
            "user": "admin",
            "validate_certs": "yes"
        }
    },
    "msg": "missing required arguments: password"
}
'''

**Comment by delgadillo22** [comment]
Low - "nice to have"

**Comment by KrithikaChidambaram** [comment]
Hi, we are closing this item now. 
Please re-open if required or send an email to automation_ecosystem@f5.com. Thanks!
