### ISSUE TITLE
bigip_command fails to run

### ISSUE THREAD

**Issue by slavkv** [F5Networks/f5-ansible#27]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

bigip_command
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### PYTHON VERSION

```
Python 2.7.11
```
##### BIGIP VERSION

```
11.5.1
```
##### CONFIGURATION

```
[defaults]
hostfile = hosts
remote_user = admin
host_key_checking = False
ask_pass=False
```
##### OS / ENVIRONMENT

OS X, 10.11.6
Ansible was installed following http://f5-ansible.readthedocs.io/en/latest/usage/getting_started.html
pip install virtualenv
virtualenv ansible2
. ansible2/bin/activate
pip install git+git://github.com/ansible/ansible.git@devel

Also, I download all 'library' files from this repo and copy it into my structure.
$ ls -1
ansible.cfg
ansible2/
candidate_config.txt
hosts
library/
test_f5_cli.yml

$ ls library/
library/:
**init**.py                  bigip_dns_record.py          bigip_gtm_facts.py           bigip_iapp_template.py       bigip_node.py                bigip_routedomain.py         bigip_software.py            bigip_ucs.py                 bigip_virtual_server.py
bigip_command.py             bigip_dns_record_facts.py    bigip_gtm_virtual_server.py  bigip_irule.py               bigip_partition.py           bigip_routedomain_facts.py   bigip_software_update.py     bigip_ucs_fetch.py           bigip_vlan.py
bigip_device_dns.py          bigip_dns_zone.py            bigip_gtm_wide_ip.py         bigip_license.py             bigip_pool.py                bigip_selfip.py              bigip_ssl_certificate.py     bigip_user.py
bigip_device_ntp.py          bigip_facts.py               bigip_hostname.py            bigip_monitor_http.py        bigip_pool_member.py         bigip_service.py             bigip_sys_db.py              bigip_user_facts.py
bigip_device_sshd.py         bigip_gtm_datacenter.py      bigip_iapp_service.py        bigip_monitor_tcp.py         bigip_provision.py           bigip_snmp.py                bigip_sys_global.py          bigip_view.py
##### STEPS TO REPRODUCE

Run playbook version 1 or version 2. They both fail with different messages. I am confused which one I should use and why it fails.

I am trying to execute a playbook according to https://f5-ansible.readthedocs.io/en/latest/modules/bigip_command_module.html

My playbook version 1:

```

---
- hosts: f5
  gather_facts: false

  tasks:
  - name: List SSH config
    bigip_command:
      server: "{{ device_hostname | default(inventory_hostname) }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      command: "tmsh list sys ssh"
      validate_certs: "no"
```

My playbook version 2 (with 'delegate_to: localhost' option):

```

---
- hosts: f5
  gather_facts: false

  tasks:
  - name: List SSH config
    bigip_command:
      server: "{{ device_hostname | default(inventory_hostname) }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      command: "tmsh list sys ssh"
      validate_certs: "no"
    delegate_to: localhost
```

##### EXPECTED RESULTS

I expect to get a result of 'tmsh list sys ssh':
sys sshd { }
##### ACTUAL RESULTS

Playbooks fail.

Version 1 fails with

```
$ ansible-playbook test_f5_cli.yml -vvvv
Using /Users/user1/git/ansible2/playbooks/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /Users/user1/git/ansible2/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_f5_cli.yml ******************************************************
1 plays in test_f5_cli.yml

PLAY [f5] **********************************************************************

TASK [List SSH config] *********************************************************
task path: /Users/user1/git/ansible2/playbooks/test_f5_cli.yml:6
Using module file /Users/user1/git/ansible2/playbooks/library/bigip_command.py
<f5-box> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO f5-box
<f5-box> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837 `" && echo ansible-tmp-1473124050.61-152768438252837="` echo $HOME/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837 `" ) && sleep 0'
<f5-box> PUT /var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/tmpAnJPrq TO /root/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837/bigip_command.py
<f5-box> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837/ /root/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837/bigip_command.py && sleep 0'
<f5-box> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837/bigip_command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1473124050.61-152768438252837/" > /dev/null 2>&1 && sleep 0'
fatal: [f5-box]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_command"
    },
    "module_stderr": "",
    "module_stdout": "  File \"/tmp/ansible_llZvdf/ansible_module_bigip_command.py\", line 237\r\n    except paramiko.ssh_exception.SSHException as e:\r\n                                                ^\r\nSyntaxError: invalid syntax\r\n",
    "msg": "MODULE FAILURE"
}
        to retry, use: --limit @test_f5_cli.retry

PLAY RECAP *********************************************************************
f5-box                     : ok=0    changed=0    unreachable=0    failed=1
```

Version 2 fails with

```
$ time ansible-playbook test_f5_cli.yml -vvvv
Using /Users/user1/git/ansible2/playbooks/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /Users/user1/git/ansible2/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_f5_cli.yml ******************************************************
1 plays in test_f5_cli.yml

PLAY [f5] **********************************************************************

TASK [List SSH config] *********************************************************
task path: /Users/user1/git/ansible2/playbooks/test_f5_cli.yml:6
Using module file /Users/user1/git/ansible2/playbooks/library/bigip_command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user1
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818 `" && echo ansible-tmp-1473124154.18-20181639279818="` echo $HOME/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818 `" ) && sleep 0'
<localhost> PUT /var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/tmpn17ZLp TO /Users/user1/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818/bigip_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/user1/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818/ /Users/user1/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818/bigip_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/user1/git/ansible2/bin/python2.7 /Users/user1/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818/bigip_command.py; rm -rf "/Users/user1/.ansible/tmp/ansible-tmp-1473124154.18-20181639279818/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py", line 247, in <module>
    main()
  File "/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py", line 230, in main
    result = obj.flush()
  File "/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py", line 180, in flush
    if self.appliance_mode():
  File "/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py", line 144, in appliance_mode
    headers=headers)
  File "/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

fatal: [f5-box -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_command"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py\", line 247, in <module>\n    main()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py\", line 230, in main\n    result = obj.flush()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py\", line 180, in flush\n    if self.appliance_mode():\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_E2fr6o/ansible_module_bigip_command.py\", line 144, in appliance_mode\n    headers=headers)\n  File \"/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/api.py\", line 70, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/api.py\", line 56, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/sessions.py\", line 475, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/sessions.py\", line 596, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/user1/git/ansible2/lib/python2.7/site-packages/requests/adapters.py\", line 497, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
        to retry, use: --limit @test_f5_cli.retry

PLAY RECAP *********************************************************************
f5-box                     : ok=0    changed=0    unreachable=0    failed=1
```

Also, I don't understand why SSLV3_ALERT_HANDSHAKE_FAILURE happens as paramiko is SSH client and should SSH into the box, not establishing HTTPS connection.

What am I missing here? 

Please help.

**Comment by slavkv** [comment]
Ok. Looks like the issue is that connection can't be established to my F5 box until I add very weak SSL ciphers in bigip_command.py before "resp = requests.get(uri,"
`requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += ':RC4-SHA'`

Now it fails with "Failed to query the REST API to check appliance mode" which is expected.

How about to add a flag into bigip_command.py to specify if module should check for 'shell' type?

For example, if I say "check_for_shell: False" then module should try to SSH without making HTTPS request to find out a user shell type.

Do I need to make a feature request or fix code by myself and send a merge request?

Thanks for an awesome work.

**Comment by caphrim007** [comment]
@mhite is there an existing precedent like this in any modules that you know of? Figuring we can probably add this if the user knows ahead of time if they are using a configuration that would be raising errors like this.

@slavkv can you give me more feedback on this so that I can address it in notes for the module? Are you using a non-admin account? Is it just the weak cipher that is needed? Something else?

**Comment by mhite** [comment]
@caphrim007  -- I can't think of an existing precedent. Does the F5 REST https daemon only support  insecure ciphers during TLS setup? If so, it sounds like we should provide instructions on how to bring that up to date on the F5. 

I took a quick look at the code, and it sounds like this initial discovery using REST is only used to determine whether or not paramiko commands need to be prefaced with 'tmsh'? Is that correct, or is there some other use?

If that's the sole purpose, maybe this can determine using paramiko itself and just avoid hitting the REST API.

What are your thoughts?

**Comment by caphrim007** [comment]
Yes, the initial REST call is used to determine if the user account being used to access the system has their shell set to tmsh or bash. It's just a convenience so that the user does not need to know what shell they are using when connecting to the BIG-IP. Additionally, if you had multiple BIG-IPs with different shells for the user, it would "just work" with a single task.

It should support more than just insecure ciphers. I think this may be related to an older version of BIG-IP that @slavkv was using.

**Comment by mhite** [comment]
Do you think you can determine this using paramiko alone? IE. detect whether you see '(tmos)#' at the end of a prompt line and make the appropriate changes to the command payload.

**Comment by caphrim007** [comment]
Hmm. maybe? guess I'll have a look-see

**Comment by slavkv** [comment]
@caphrim007, root account. root can't login into HTTPS interface.
Also, if I use default Admin account -> it can't login to SSH. 
If a person works in a small company, then he does not need to create another account, as he can use 'admin' for web interface and 'root' for SSH.

And yes, it's possible to determine shell time based on shell prompt.

I just found docs confusing saying the module uses SSH connection to run commands, but it makes HTTPS requests and fails with SSL error :)

**Comment by slavkv** [comment]
@caphene , that's how I changed bigip_command.py module
https://github.com/slavkv/f5-ansible/commit/1133f8ab948f27621f4a49cadeb682ff03b722f6

**Comment by caphrim007** [comment]
@slavkv thanks for that gist. So for my own testing purposes, I would be able to see the same errors you saw if I configured my user accounts to have the limitations you mentioned, right?

Would a suitable fix (in the same spirit of your gist) be to discard the HTTPS checks all together and have a `shell` argument which defaults to `None`. When it is set to "tmsh" or "bash" it would do the appropriate cli substitutions? If none, then it will do the interrogation over paramiko instead of https?

**Comment by slavkv** [comment]
@caphrim007 Agree, sounds good.

**Comment by slavkv** [comment]
Just to follow up? Has it been integrated?
I've looked via documentation and source code and did not notice it :)

**Comment by caphrim007** [comment]
@slavkv readthedocs needs a couple minutes to run the update. then it should be there

**Comment by caphrim007** [comment]
@slavkv here ya go
https://f5-ansible.readthedocs.io/en/latest/modules/bigip_command_module.html
