### ISSUE TITLE
write module for log destinations

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#272]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by delgadillo22** [comment]
low by default given no documented requirements

**Comment by caphrim007** [comment]
dupe of #694
