### ISSUE TITLE
Ansible module for creating, deleting, and modifying AFM policies

### ISSUE THREAD

**Issue by torzillo** [F5Networks/f5-ansible#275]
Customers would like an Ansible module that can create, delete, and modify AFM policies and the related objects.  This includes creating the port lists, address lists, rules, and rule-lists.

The module should also support applying those policies to a context, such as a virtual server, route domain context, or global context.

The below example shows firewall objects being created and applied to a virtual server:

create security firewall port-list DIAMETER-TCP description "Diameter over TCP" ports add { 3868 }

create security firewall port-list SFTP-TCP description "SFTP over TCP" ports add { 22 }

create security firewall address-list DIAMETER-NODES-FOREIGNNET { addresses replace-all-with { 10.10.10.10-20.20.20.20 { } } description "Covers DIAMETER-NODES FOREIGNNET Range on TRUSTEDNETWORK Protected Net" }

create security firewall address-list DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA { addresses replace-all-with { 1.1.1.1 { } 2.2.2.2 { }  } description "Covers DIAMETER-NODES PARTNERNETWORK BILLING DRA Range on TRUSTEDNETWORK Direct Net" }

create security firewall address-list DIAMETER-NODES-PARTNERNETWORK-BILLING-UDR { addresses replace-all-with { 3.3.3.3 { } 4.4.4.4 { } } description "Covers DIAMETER-NODES PARTNERNETWORK BILLING UDR Range on TRUSTEDNETWORK Direct Net" }

create security firewall rule-list DIAMETER-NODES-RL-IPV4 {  description "Rule List for DIAMETER-NODES IPv4 Flows" rules replace-all-with {   ALLOW-FOREIGNNET-TCP { action accept  description "Allow DIAMETER-NODES FOREIGNNET to Originate TCP" ip-protocol tcp log yes destination { address-lists replace-all-with {    DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA     } port-lists replace-all-with {     DIAMETER-TCP     } } source { address-lists replace-all-with { DIAMETER-NODES-FOREIGNNET } } } DEFAULT-DROP { action drop  description "Drop Policy with Logging" log yes } } }

create security firewall policy DIAMETER-NODES-POLICY-IPV4 { description "Policy for DIAMETER-NODES IPv4" rules replace-all-with { DIAMETER-NODES-RULES { rule-list DIAMETER-NODES-RL-IPV4 } } }

create security firewall rule-list PARTNERNETWORK-RL-IPV4 {  description "Rule List for PARTNERNETWORK IPv4 Flows" rules replace-all-with {   ALLOW-PARTNERNETWORK-TCP { action accept  description "Allow PARTNERNETWORK BILLING DRA to Originate TCP" ip-protocol tcp log yes destination { address-lists replace-all-with {  DIAMETER-NODES-FOREIGNNET  } port-lists replace-all-with {     DIAMETER-TCP     } } source { address-lists replace-all-with { DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA } } } DEFAULT-DROP { action drop  description "Drop Policy with Logging" log yes } } }

create security firewall policy PARTNERNETWORK-POLICY-IPV4 { description "Policy for PARTNERNETWORK IPv4" rules replace-all-with { PARTNERNETWORK-RULES { rule-list PARTNERNETWORK-RL-IPV4 } } }

modify security firewall rule-list DIAMETER-NODES-RL-IPV4 rules add { ALLOW-FOREIGNNET-ICMP { place-before DEFAULT-DROP action accept description "Allow DIAMETER-NODES FOREIGNNET to Originate ICMP PING/TRACEROUTE" ip-protocol icmp icmp replace-all-with { 0 {} 8 {} 30 {} } log yes destination { address-lists add { DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA } } source { address-lists add { DIAMETER-NODES-FOREIGNNET }}}}

modify security firewall rule-list PARTNERNETWORK-RL-IPV4 rules add { ALLOW-PARTNERNETWORK-ICMP { place-before DEFAULT-DROP action accept description "Allow PARTNERNETWORK BILLING DRA to Originate ICMP PING/TRACEROUTE" ip-protocol icmp icmp replace-all-with { 0 {} 8 {} 30 {} } log yes destination { address-lists add { DIAMETER-NODES-FOREIGNNET } } source { address-lists add {  DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA }}}}

create security firewall rule-list DIAMETER-NODES-RL-UDR-IPV4 {  description "Rule List for DIAMETER-NODES UDR IPv4 Flows" rules replace-all-with {   ALLOW-UDR-TCP { action accept  description "Allow DIAMETER-NODES Originate TCP SSH UDR" ip-protocol tcp log yes destination { address-lists replace-all-with {    DIAMETER-NODES-PARTNERNETWORK-BILLING-UDR     } port-lists replace-all-with {     SFTP-TCP     } } source { address-lists replace-all-with { DIAMETER-NODES-FOREIGNNET } } } DEFAULT-DROP { action drop  description "Drop Policy with Logging" log yes } } }

create security firewall policy DIAMETER-NODES-POLICY-UDR-IPV4 { description "Policy for DIAMETER-NODES UDR IPv4" rules replace-all-with { DIAMETER-NODES-UDR-RULES { rule-list DIAMETER-NODES-RL-UDR-IPV4 } } }

modify ltm virtual TRUSTEDNETWORK-PROTECTED-NET-UDR fw-enforced-policy DIAMETER-NODES-POLICY-UDR-IPV4

**Comment by caphrim007** [comment]
@torzillo is this syntax here `$DIAMETER-NODES_FOREIGNNET_Server_Range_Start`, specifically the dollar sign part, a variable that you included? or is it literally the bigip syntax?

**Comment by torzillo** [comment]
This is a group variable defined in the env file.


On Nov 16, 2017, at 5:01 PM, Tim Rupp <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL MAIL: bounces+848413-2777-t.torzillo=f5.com@sgmail.github.com<mailto:bounces+848413-2777-t.torzillo=f5.com@sgmail.github.com>


@torzillo<https://github.com/torzillo> is this syntax here $DIAMETER-NODES_FOREIGNNET_Server_Range_Start, specifically the dollar sign part, a variable that you included? or is it literally the bigip syntax?

**Comment by caphrim007** [comment]
@torzillo do you have a suggestion for the names of these modules?

bigip_afm_(port_list|_address_list|_rule_list)
bigip_afm_policy

or should I use bigip_security_*?
or should I use bigip_firewall_*?

**Comment by torzillo** [comment]
bigip_security because it more closely matches the tmsh convention.

On Nov 17, 2017, at 8:41 PM, Tim Rupp <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL MAIL: bounces+848413-2777-t.torzillo=f5.com@sgmail.github.com<mailto:bounces+848413-2777-t.torzillo=f5.com@sgmail.github.com>


@torzillo<https://github.com/torzillo> do you have a suggestion for the names of these modules?

bigip_afm_(port_list|_address_list|_rule_list)
bigip_afm_policy

or should I use bigip_security_?
or should I use bigip_firewall_?

**Comment by caphrim007** [comment]
@torzillo so the following is what that would be?

bigip_security_port_list
bigip_security_address_list
bigip_security_rule_list
bigip_security_policy

Is that correct?

**Comment by caphrim007** [comment]
#487 blocks

**Comment by caphrim007** [comment]
#488 blocks

**Comment by caphrim007** [comment]
#489 blocks

**Comment by caphrim007** [comment]
#490 blocks

**Comment by caphrim007** [comment]
#491 blocks
