### ISSUE TITLE
add import/apply asm policy module

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#279]
as discussed

**Comment by wojtek0806** [comment]
Current design considerations:

- No update can be performed on the tasks endpoint for import and apply
- Module States:
    - present - will upload the file, or create the policy from template
    - activated - will upload if policy is not there and apply it, or just apply uploaded policy. Or create it from template and apply it
    - absent - will remove the policy in question
    
We can have 2 types of imports: inline and by filename(via file transfer endpoint), we will support both. We also allow creation of an asm policy from an asm policy templates present on device.

- Module parameters:
    **name** - _string_ - name of policy
    **inline** - _bool, default = false_ - if we want to use inline option or just upload the file
    **file_path** - _string_ - path to filename - this will be used in both inline and standard upload
    **template** - _string_ - link to policy template, maybe we use also name and search for the link on 
                                         user's behalf
    **## file, filename, policyTemplate reference are mutually exclusive parameters.**

- Api Attributes:
    **name** ->  self explanatory
    **file** -> for inline uploads
    **filename** -> for uploads done via file-transfer
    **isBase64** -> for encoding of inline
    **policyTemplateReference** -> to create option from an existing template using the reference for policy templates

**Comment by wojtek0806** [comment]
Current blockers for this module to happen:

https://github.com/F5Networks/f5-common-python/issues/1154
https://github.com/F5Networks/f5-common-python/issues/1153

**Comment by mikempw** [comment]
Any updates on this one? Looks like the blockers have been closed.

**Comment by caphrim007** [comment]
@mikempw there's a PR for this here that I am waiting on https://github.com/F5Networks/f5-ansible/pull/366

**Comment by caphrim007** [comment]
@mikempw @wojtek0806 this is now merged. will upstream this

**Comment by caphrim007** [comment]
PR is here https://github.com/ansible/ansible/pull/32281
