### ISSUE TITLE
bigip_gtm_facts missing 'availability status'

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#283]
Enhancement request to add Pool availability status to bigip_gtm_facts (for pools). (Green/Red/Blue status)

Right now rfacts have the following information:
"pool": [
        [
            {
                "alternate_mode": "round-robin",
                "dynamic_ratio": "disabled",
                "enabled": "True",
                "fallback_ip": "any",
                "fallback_mode": "return-to-dns",
                "full_path": "/Common/my_pool",
                "limit_max_bps": "0",
                "limit_max_bps_status": "disabled",
                "limit_max_connections": "0",
                "limit_max_connections_status": "disabled",
                "limit_max_pps": "0",
                "limit_max_pps_status": "disabled",
                "load_balancing_mode": "round-robin",
                "manual_resume": "disabled",
                "max_answers_returned": "1",
                "members": [],
                "monitor": "default",
                "name": "my_pool",
                "partition": "Common",
                "qos_hit_ratio": "5",
                "qos_hops": "0",
                "qos_kilobytes_second": "3",
                "qos_lcs": "30",
                "qos_packet_rate": "1",
                "qos_rtt": "50",
                "qos_topology": "0",
                "qos_vs_capacity": "0",
                "qos_vs_score": "0",
                "ttl": "30",
                "type": "a",
                "verify_member_availability": "enabled"

**Comment by caphrim007** [comment]
@payalsin this color is determined by several combinations of availabilityState and enabledState. I'm trying to determine what those combinations are.
