### ISSUE TITLE
add module to support tmshell scripts

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#284]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Add a module to support uploading tm shell scripts. These are kind of like iRules, but kinda not. In any event, there are some customer use cases that want to automate this.

**Comment by fwissue** [comment]
It will be great to have a f5-sdk module which can run any commands or scripts which on F5 ltm

So users can put customized scripts on F5 ltm.

i.e. To find not IP conflict (grep 10.10.10.5 /config/bigip.conf or bigip_base.conf)
