### ISSUE TITLE
add module to report asm facts

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#289]
* current number of policies (this is just the policies collection)
* current number of policies active (active means that it is attached to an LTM policy)
* current number of policies active and attached (means that the LTM policy is attached to a virtual server)
* current number of policies active and unattached (basically the same as "active" above)
* current number of policies inactive (asm policy is not attached to an LTM policy)

Because there is a total limit to the number of ASM policies one can have on versions of bigip (250 on 11.6, 1000? on 12+)

**Comment by delgadillo22** [comment]
Possible for 2.6 as ASM enhancement for what's being delivered in 2.5?

**Comment by caphrim007** [comment]
@delgadillo22 it is possible, but this is a module request that has not had nearly as much interest as other modules.
