### ISSUE TITLE
bigip_user produced unhandled Python exception AdminRoleNoModifyError

### ISSUE THREAD

**Issue by dbeckham** [F5Networks/f5-ansible#29]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

F5 bigip (bigip_user)
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### PYTHON VERSION

```
Python 2.7.12
```
##### F5 BIGIP LTM VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```
##### CONFIGURATION

```
retry_files_enabled = False
host_key_checking=False
```
##### OS / ENVIRONMENT

Alpine 3.4 (Docker Container)
##### SUMMARY

When attempting to modify the root user's password using `bigip_user`, an unhandled Python exception is thrown with the error `NameError: global name 'AdminRoleNoModifyError' is not defined`.

_NOTE: after running into this error, I noticed in the documentation that this module is only supported on BIGIP versions 13 and greater. Whether or not it is supported on the version of software I'm using, a reasonable error should be produced instead of an unhandled exception._
##### STEPS TO REPRODUCE

Create a task that uses the `bigip_user` to attempt to change the password of the root user. Additionally, the BIGIP software version being tested against may need to be lower than 13.x to produce this error.

```
- name: Set root user password
  bigip_user:
    password: "{{ bigip_password }}"
    server: "{{ inventory_hostname }}"
    user: "{{ bigip_username }}"
    username_credential: "root"
    password_credential: "mysecret"
    validate_certs: "{{ validate_certs }}"
```
##### EXPECTED RESULTS

It should handle the `AdminRoleNoModifyError` exception and return a reasonable error message indicating the actual problem.
##### ACTUAL RESULTS

The Ansible task fails with the following error: `NameError: global name 'AdminRoleNoModifyError' is not defined`.

```
TASK [Set root user password] **************************************************
task path: /playbooks/ltm_bootstrap.yaml:9
Using module file /playbooks/library/bigip_user.py
<lbl12.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<lbl12.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960 `" && echo ansible-tmp-1474561274.87-25040398694960="` echo $HOME/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960 `" ) && sleep 0'
<lbl12.example.com> PUT /tmp/tmpZGCFpX TO /root/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960/bigip_user.py
<lbl12.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960/ /root/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960/bigip_user.py && sleep 0'
<lbl12.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960/bigip_user.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1474561274.87-25040398694960/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_lYiZgE/ansible_module_bigip_user.py", line 714, in <module>
    main()
  File "/tmp/ansible_lYiZgE/ansible_module_bigip_user.py", line 689, in main
    except AdminRoleNoModifyError:
NameError: global name 'AdminRoleNoModifyError' is not defined

fatal: [lbl12.example.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_user"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lYiZgE/ansible_module_bigip_user.py\", line 714, in <module>\n    main()\n  File \"/tmp/ansible_lYiZgE/ansible_module_bigip_user.py\", line 689, in main\n    except AdminRoleNoModifyError:\nNameError: global name 'AdminRoleNoModifyError' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
        to retry, use: --limit @/playbooks/ltm_bootstrap.retry
```

**Comment by caphrim007** [comment]
you are correct on both points.

- it needs bigip 13.x because prior to that version bigip did not correctly list usernames when they were specified on partitions other than /Common.
- it should raise a better error (the error is clearly a bug)

I think this module may still be in the development phase, but even if it is, that there are folks using it is reason enough to accelerate its development to be production ready.

I will update said code and the associated tests with it.
