### ISSUE TITLE
@channel I have a question about bigip_license module and the prerequisites

### ISSUE THREAD

**Issue by aheilmaier** [F5Networks/f5-ansible#291]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

bigip_license

##### DISCUSSION / QUESTION
I need to onboard a F5 ltm system. 
Is there a best practice ? (no BigIQ; no BigIP access to activate.f5.com) 
Because usually I can only get a license file via a manual process on copy/paste the dossier file to activate.f5.com.
So an auto onboarding process breaks at this step. Because further BigIP configuration needs a valid license, right ?
Is Closed Circuit Network (CCN) license activation an option, e.g. to get upfront all my licenses ? https://secure.f5.com/ccn/programoverview.jsp

**Comment by caphrim007** [comment]
@aheilmaier if you have a valid license that you got manually, or automatically, from F5, I think you can provide this in the `license_file` argument. However I don't think this is being actively tested right now.

I'll change this to an `enhancement` request

**Comment by caphrim007** [comment]
@delgadillo22

**Comment by delgadillo22** [comment]
High if this type of information is being built into the Ansible documentation for supportbility (e.g. "how to" info)
