### ISSUE TITLE
Add module to copy file in F5-sdk

### ISSUE THREAD

**Issue by fwissue** [F5Networks/f5-ansible#301]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME

copy file and create directory
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /work/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### PYTHON VERSION

```
[root@65c5b31cdda5 work]# python -V
Python 2.7.5
```

##### BIGIP VERSION

```
[mliu@sj-lb-1:/S1-green-P:Standby:In Sync] ~ # tmsh show sys ver

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.93.249
  Edition     Engineering Hotfix
  Date        Fri Jan 20 15:48:38 PST 2017

Hotfix List
ID639492-1    ID623119  ID624457-5  ID624023-3

```

##### SUMMARY

There is a copy module in ansible, but that requires ssh key, I would prefer to use user/password in F5-sdk to transfer files, and create directory, and we could use vault to encrypted the user/password. so we don't need to share ssh key with other people.
##### STEPS TO REPRODUCE

- name: copy file
  hosts: testlb
  vars_files:
  - './password.yaml'
  gather_facts: no

  tasks:
  - name: copy files
    copy:
     src: /work/
     dest: /var/tmp/2017/

```
ansible-playbook -i labhost copyfile.yaml --vault-password-file ./vault-key.txt
```

##### EXPECTED RESULTS

copy files from local host to load balancer, that will help for key/cert/bundle upload.
##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@delgadillo22

**Comment by caphrim007** [comment]
@fwissue there are bigip_certificate and bigip_key modules today that can handle the use case you propose. BIG-IP has no such thing as a "general purpose" file upload facility. Can you elaborate more on what you want?

**Comment by fwissue** [comment]
Sure, Tim.

Will test that

**Comment by delgadillo22** [comment]
We should remove this item since we have a workaround.

**Comment by caphrim007** [comment]
closing due to existing cert/key/bundle modules
