### ISSUE TITLE
bigip-command.py giving error

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#302]
I have the following playbook:

- name: Set network address 
    bigip_command:
      server: "10.192.73.XXX"
      user: "admin"
      password: "admin"
      commands:
      - modify cm device bigip-ha2 unicast-address {{ effective-ip 1.1.1.3 } {effective-ip 10.192.73.XXX }}
    delegate_to: localhost

Error:
TASK [Set network address ] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "template error while templating string: expected token 'end of print statement', got 'float'. String: modify cm device bigip-ha1 unicast-address {{ effective-ip 1.1.1.2 } {effective-ip 10.192.73.108 }}"}

-----------------------------------
Am I inputting it incorrectly, the same tmsh command works directly on the bigip

**Comment by caphrim007** [comment]
@payalsin why are the duplicate {{ in there? that usually indicates a variable.

**Comment by payalsin** [comment]
@caphrim007 - yup my mistake, the two curly braces are needed for this tmsh command, but I gave a space now and that works 
modify cm device bigip-ha2 unicast-address { { effective-ip 1.1.1.3 } {effective-ip 10.192.73.XXX } } )

Closing issue
