### ISSUE TITLE
RFE: bigip_iapp_service module to deploy iApp in specific traffic-group

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#307]
##### ISSUE TYPE
 - Feature Idea
##### COMPONENT NAME
bigip_iapp_service

##### SUMMARY

Hi

AFAIK currently it is not possible to deploy an iApp service in a speficic traffic group and this is a must have for Active-Active deployments. 

Many thanks

     Ulises

**Comment by caphrim007** [comment]
https://github.com/F5Networks/f5-ansible/issues/258 blocks this request

**Comment by alonsocamaro** [comment]
Hi @caphrim007 

I don't understand why it is blocking.

My understanding is that #307 and #258 are complementary. Please note that this one is to deploy an iApp into a given previously created traffic group and #258 is about creating traffic-groups.

Regards

      Ulises

**Comment by caphrim007** [comment]
@alonsocamaro because I need the traffic group code to *test* the feature you're asking for

**Comment by caphrim007** [comment]
in any event, the traffic group module has been added, so I can work on this now
