### ISSUE TITLE
I don't see any modules for access policies. Will that be supported any time soon?

### ISSUE THREAD

**Issue by brian-s-dennis** [F5Networks/f5-ansible#318]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@brian-s-dennis would you please elaborate more on what in particular you're asking for? tmsh example commands would help. Thanks.

**Comment by brian-s-dennis** [comment]
I’ve reached out to our support provider to answer this. The modules I would like to see added are for Access Policy Manager (APM) and Application Security Monitor (ASM). One of the problems I’m finding with APM in particular is that the methods used by their gurus only addresses basic objects, as ansible appear to, and nothing as complicated as an access policy definitions. Even the methods used by their professional services guys don’t transfer access policies because there are objects that have to be in the file store before they can transfer successfully.

**Comment by wojtek0806** [comment]
@brian-s-dennis 

Let me jump in here, seeing that I have done SDK coding for ASM, I would need you to be even more specific in regards to what you are looking for in ASM, that is listing specific actions that you want automated, e.g exporting/importing ASM policies.

As far as APM is concerned this is is not yet coded into the SDK library so we need to know what actions you are performing. Those 2 products are quite complicated with a lot of moving parts so we need information on the actions you wish to automate. Also please be aware that we will only do that for version 12.x and above.

**Comment by brian-s-dennis** [comment]
APM is the module of immediate concern. I didn’t see any modules for APM or ASM listed for Ansible. Most specifically I’m looking for the ability in APM to export access policies, ACLs and ACEs but I typically use those through the GUI instead of the command line. According to our F5 support provider “Sorry, but no there is not a CLI command to export the APM policy.” Which is pretty disappointing. There is also a python API and a RESTful API but I have found the implementation in the Viprion VEs to be very different with respect to those APIs.

**Comment by wojtek0806** [comment]
I can check if this can be done in REST, but if there is no TMSH equivalent we will not be able to facilitate it over REST.

**Comment by brian-s-dennis** [comment]
Thanks

**Comment by wojtek0806** [comment]
@brian-s-dennis I have checked it and there are no ways to export APM policy or its individual elements. Basically you can think of this like so: what is possible in CLI usually is supported in REST. There are few exceptions where specific endpoints in REST do not have their equivalent in TMSH, but those are documented in REST guides.

**Comment by brian-s-dennis** [comment]
I was afraid of that. Thanks for your hard work.

**Comment by wojtek0806** [comment]
@brian-s-dennis i think i found a way to export/import apm policies, this uses a separate tool in bash, not widely documented on ASK F5, so we can technically use BASH over REST, i will need to investigate the feasibility of this first tho.

**Comment by brian-s-dennis** [comment]
Interesting, thanks for the update. Good luck.

**Comment by delgadillo22** [comment]
Looks like the requirements/solution aren't fully baked

**Comment by kleinsmk** [comment]
I was also beyond frustrated with the lack of ASM anything so I hunted down the REST calls to do it.  Give up looking for documentation, and start poking around the restui explorer to find what you need as for whatever reason a massive chunk of the rest endpoints are not documented nor implemented in the F5 SDK.  Would love either documentation or incorporation into.

**Comment by caphrim007** [comment]
@kleinsmk the reason that more ASM work is not part of the f5-sdk or ansible is because nobody has asked for it. if you ask for it, it will happen...provided that what you're asking for is possible.

To your comment about there being a lack of "ASM anything", that is absolutely wrong https://github.com/F5Networks/f5-common-python/tree/development/f5/bigip/tm/asm

**Comment by kleinsmk** [comment]
Get all ASM policies - 
$Uri = "https://" + $Hostname + "/mgmt/tm/asm/policies"
Invoke-RestMethod -Uri $Uri -Method GET

You need to refer to each policy via selflink to export and a filename to kick off the export on the F5

 $Uri = "https://" + $Hostname + "/mgmt/tm/asm/tasks/export-policy"
Invoke-RestMethod -Uri $Uri -Method POST -Body $body -ContentType 'application/json'

Then Pull the files 
$Uri = "https://" + $Hostname + "/mgmt/tm/asm/file-transfer/downloads/" + $fileName

I'm not sure what I did with my code for importing the files but its the same idea in reverse

**Comment by caphrim007** [comment]
@kleinsmk what's your point?

The part of this issue that is not possible is APM policies, not ASM policies.

**Comment by kleinsmk** [comment]
@caphrim007 ,

I was simply posting rest endpoints so the gentlemen could roll his own solution.  Timing of the post made it look like I was responding.

Thanks for showing me the location of dev python sdk stuff!  I  Can you guys add this somewhere prominent on Dev central ect.  I only started looking on the github after seeing at a conference most of the action in terms of F5 automation was happening on github.  I think most traditional OPS guys don't check github. 

As for the APM, what isn't possible ?  I know there appears to be 0 python code for this but the end points are there albeit not documented.  I'm not sure why APM isnt fully implemented in the SDK yet.  I'd guess its not nearly as popular a module as the LTM?  Either way as long as the endpoints are there is what matters.  I do agree with the previous poster that APM modules for Ansible would be nice as I have no idea who to code those.

In case anyone else sees this and wants examples for some APM endpoints,

/mgmt/tm/apm/acl  for getting all acls and setting acls 
/mgmt/tm/apm/policy/agent/resource-assign/  for setting role mappings

**Comment by caphrim007** [comment]
@kleinsmk the exporting of APM policies. Thats not something that is in the REST API like it is with ASM.

As the OP said

"""APM is the module of immediate concern. I didn’t see any modules for APM or ASM listed for Ansible. Most specifically I’m looking for the ability in APM to export access policies, ACLs and ACEs but I """
