### ISSUE TITLE
Try to use module partition, user, selfip (last version)

### ISSUE THREAD

**Issue by mordrake** [F5Networks/f5-ansible#320]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
- bigip_partition
- bigip_user
- bigip_selfip (last version)

##### ANSIBLE VERSION
2.2

##### PYTHON VERSION
2.7

##### SUMMARY
i've copied all of new module in my library but when i try to execute one of newest i can't.
The message is : "Couldn't find imported module support code for bigip_partition. Looked for either iControlUnexpecterHTTPerror or f5_utils"

##### STEPS TO REPRODUCE
1 - Copy new module from git to my ansible server
2 - Create new role to play one of them (like bigip_partition)
3 - Play

Could you help me plz ?

**Comment by caphrim007** [comment]
@mordrake the modules in this repo require ansible >= 2.3

**Comment by mordrake** [comment]
Oh... my bad, thx dude

**Comment by caphrim007** [comment]
not a problem. feel free to raise an issue if you have more troubles.
