### ISSUE TITLE
BIG-IP Auth Tokens as Auth Method for Module

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-ansible#322]
checked against all open issues containing "Token"

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
All Modules, though specifically the iRule Module as a customer request

##### ANSIBLE VERSION

```
2.4+
```

##### PYTHON VERSION

```
n/a, but latest
```

##### BIGIP VERSION

```
12.x +
```

##### SUMMARY

Looking for a method to use a BIG-IP auth token as auth method. Customer request:
```
Our Tech Arch team have reported that this module doesn’t currently support token authentication, and is probably expecting a built-in account on the BigIP.
```

**Comment by caphrim007** [comment]
@jmcalalang can you elaborate on what they want with token auth? There is no such thing as strict token auth on a BIG-IP. There is a session token that can be acquired after initial user/pass login, but that session token is time limited.

Token auth requires username and password when you are getting it initially. By default, this token is valid for 20 minutes. If you need to use token for longer time, you can renew the token until 10 hours. But one token cannot be used to generate another.

**Comment by jmcalalang** [comment]
You’re working late!

This is coming from a Security standpoint of a Rest call with credential vs
a single rest call to generate a token, then reuse the token in subsequent
calls (during the 20 min -10 Hour window). We’ve put a lot of work and
planning around moving our customers to a token solution (like BIG-IQ
wither is now basic auth disabled by default), and all to work with
iControl_LX and the F5 Newman wrapper w/postman.

I understand this isn’t quite something that fits the Ansible model, of
gathering something as a variable to be reused, but it is something that
might come up more.


On September 6, 2017 at 9:49:49 PM, Tim Rupp (notifications@github.com)
wrote:

@jmcalalang <https://github.com/jmcalalang> can you elaborate on what they
want with token auth? There is no such thing as strict token auth on a
BIG-IP. There is a session token that can be acquired after initial
user/pass login, but that session token is time limited.

Token auth requires username and password when you are getting it
initially. By default, this token is valid for 20 minutes. If you need to
use token for longer time, you can renew the token until 10 hours. But one
token cannot be used to generate another.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/F5Networks/f5-ansible/issues/322#issuecomment-327684454>,
or mute the thread

**Comment by caphrim007** [comment]
I gotcha, I just wanted to clear the air on the definition of "token". There are folks that think we have a means by which they can generate a long-lived token like something you might find in an online service, and then they are disappointed to find out we still require initial authentication to get such a thing.

There is not currently such a mechanism for stashing sharable data between tasks in Ansible, so we would need to investigate making something to use until there is.

**Comment by jmcalalang** [comment]
There is always room to be creative :), with APM provisioned you can use
APM as an Auth Method to login to the BIGIP, of course with APM comes OAuth
(long lived). This isn’t anything i think we’re ready for, or possibly even
the ecosystem, but its all sitting there waiting! SAML and or OAuth right
into the BIGIP would be pretty slick :).

I’ve haven’t even opened the can of worms thats Tower yet, though i did
think there might be a mechanism in there to do something like a response
cache. I’d ask them tomorrow at AnsibleFest if I was attending!


On September 6, 2017 at 10:46:30 PM, Tim Rupp (notifications@github.com)
wrote:

I gotcha, I just wanted to clear the air on the definition of "token".
There are folks that think we have a means by which they can generate a
long-lived token like something you might find in an online service, and
then they are disappointed to find out we still require initial
authentication to get such a thing.

There is not currently such a mechanism for stashing sharable data between
tasks in Ansible, so we would need to investigate making something to use
until there is.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/F5Networks/f5-ansible/issues/322#issuecomment-327693677>,
or mute the thread

**Comment by sdhughes1** [comment]
+1 on this issue. We'd like ansible administrators to use their own credentials (i.e. TACACS) when running playbooks. The F5 modules don't work with TACACS users, although the f5-sdk module allegedly allows the use of tokens (https://devcentral.f5.com/articles/getting-started-with-the-f5-common-python-sdk-27438)

**Comment by wojtek0806** [comment]
Having discussed this internally, we have made the decision that we will not be implementing this. There are few reasons:

1. Primary reason is that the TMOS tokens are short lived, i.e 20 minutes time-out

2. Even if you put a device like APM to protect BIGIP API (you need to have APM on a separate BIGIP to think of doing anything like OAuth),  the device will need to request these short lived tokens from the BIGIP on your behalf, this means you still need to provide credentials to BIGIP for those tokens to be issued.

3. Let say we overlooked first two, then the next problem arises: how do you actually get a token from BIGIP?
- there is no GUI or TMSH option to do that
- there is no proper documentation on getting a token for you to write something,  and we will not be writing a new module to get tokens, as this is what the modules are already doing automatically, via our F5RestClient class.

4. You could overcome this with a lookup plugin that queries the BIGIP for TMOS tokens (if you reverse engineered our solution from F5RestClient class, but this carries another issue: **what happens if the short lived token expired mid-flight of your playbook?**
- you will likely have half of your tasks succeeding, while the other half is failing
- ansible has no support for anything that will  "execute and then retry all failed tasks again", so you cannot just get a new token and retry again

Given the above we will be closing this.

**Comment by perzizzle** [comment]
Respectfully, I know this question has been asked a few times but wanted to take one more go at it. We are seeing issues with our F5 LTMs and GTMs becoming CPU bound thats gotten much worse after the most recent upgrade (https://support.f5.com/csp/article/K69245523). From our testing this appears directly related to the number of authentications ansible performs in a typical playbook.  We've doubled our vcpu count and sub-divided 1 LTM into 3 LTMs but still see intermittent failures when the CPU gets to 100%.

Our playbooks don't take 20 minutes to run but, I think using a block/rescue you could handle a timeout gracefully. We use this pattern elsewhere with token based authentication and its worked well.

In psuedo-code this would look like:

``` - name: Execute F5 Block
  block:
    - name: Generate F5 token
      bigip_login:
        username: "{{ username }}"
        password: "{{ password }}"
      register: token
      no_log: true

    - name: Disable LTM virtual server
      local_action:
        module: bigip_virtual_server
        name: "{{ f5_virtual_server_name }}"
        state: disabled
        partition: Common
        provider:
          server: "{{ f5_ltm_server }}"
          auth_provider: token
          token: "{{ token }}"
      register: ltm_virtual_server_status
        
  rescue:
    - name: Retry on token timeout
      include_tasks: main.yml
      when: ltm_virtual_server_status.msg == 'token timeout'

  always:
    - name: F5 Revoke Token
      bigip_login:
        username: "{{ username }}"
        token: "{{ token }}"
        state: absent
      no_log: true
