### ISSUE TITLE
Add deploy options to bigip_iapp_service

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#323]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_iapp_service

##### SUMMARY
Hi

The following options should be supported to deploy iApps in a wider range of scenarios:
    description
    metadata
    ~~traffic-group~~ ADDED
    device-group
    ~~strict-updates~~ ADDED

Many thanks

       Ulises

PD: This is a clone request of https://github.com/F5Networks/f5-openstack-heat-plugins/issues/107 for the f5-heat-plugins

**Comment by alonsocamaro** [comment]
This is a superset of https://github.com/F5Networks/f5-ansible/issues/307

**Comment by caphrim007** [comment]
duplicate of #137
