### ISSUE TITLE
RFE: create bigip_iapp_service_facts

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#327]
##### ISSUE TYPE
 - Feature Idea
##### COMPONENT NAME
New module: bigip_iapp_service_facts

##### SUMMARY
Hi

At present I find difficult / I cannot figure how a host could remove himself from a pool deployed with an iApp.

Given that each iApp might have different number of pools and pool names I would propose a new module called bigip_iapp_service_facts that just returns the variables and values of the instantiated iApp.

The way this bigip_iapp_service_facts would work is similar to os_networks_facts and similar _facts Openstack modules: the values can be registered and used to update the iApp.

Please note although the use case I have mentioned above is probably the most typical (pool member update) this new module would allow iApp service updates of any configuration not just pool members.

In general we need this mechanism to update the iApp parameters when these are triggered by something that didn't instantiate the iApp and we just want to update part of the parameters values (a single FDB entry, data-record, pool member, tunnel end-point, ... this list could be endless).

**Comment by caphrim007** [comment]
@alonsocamaro is it sufficient to just return the tables, lists, and vars? In their existing format? Do you want them formatted differently? Do you want other cars like the presentation blob, bigip min version, max version, required modules, etc?

Perhaps you can provide an example of the format you are interested in having and we can start with that as a basis using your pool members example as the initial release and growing from there

**Comment by alonsocamaro** [comment]
Yes, I would return all parameters used to instantiate the iapp: both iapp instantiation options and iapp's own variables and tables. In the existing format.

**Comment by alonsocamaro** [comment]
There are additional use cases for this module.

When asking about services a filter expression should be able to be applied, that way it would be able to:

1. Gather parameters from several iApp instances
2. Checking which iApp instances have been deployed, for example it should be possible to use "service_name: *" to know all the iApp instances deployed in a system. A regexp or filter expression would be needed.
