### ISSUE TITLE
Feature Idea - Add a trunk on BIG-IP

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#329]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Module to add a trunk on the BIG-IP. This is useful when configuring the bring up of the BIG-IP and setting up all the networking parameters. This is one piece missing for end-to-end network configuration.

##### STEPS TO REPRODUCE
Add a trunk. Parameters to take into account
- Interfaces
- LACP
- Link Selection Policy
- Frame distribution hash

**Comment by caphrim007** [comment]
this requires an enhancement to the python sdk because trunks is not yet part of it. I'm adding trunks as I type this

**Comment by caphrim007** [comment]
@payalsin trunk functionality is now in the f5-sdk. This ask can now be prioritized to be added to ansible

**Comment by MicSkr** [comment]
Bump. Additional request for this.
