### ISSUE TITLE
bigip_pool feature request

### ISSUE THREAD

**Issue by jmcgill298** [F5Networks/f5-ansible#340]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_pool

##### ANSIBLE VERSION

```
2.4.0.0
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
12.1.1 Build 0.0.184
```
##### FEATURE REQUEST
Add support for a `monitor_type` of "single" in bigip_pool. This looks just like "and_list" without the " and "

##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### STEPS TO REPRODUCE

NA

```

```

##### EXPECTED RESULTS

NA
##### ACTUAL RESULTS

NA

```

```

**Comment by caphrim007** [comment]
@jmcgill298 I believe this is now fixed. please let me know if you are still having issues

**Comment by jmcgill298** [comment]
@caphrim007 it is working
