### ISSUE TITLE
BIGIP_NODE: incorrect required_if format

### ISSUE THREAD

**Issue by jmcgill298** [F5Networks/f5-ansible#344]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_node
##### ANSIBLE VERSION

```
2.4.0.0
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
NA
```

##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### SUMMARY

The required_if should be a list of  lists with param, choice, list of required params.
```
self.required_if = [
    'availability_requirement', 'at_least', ['quorum']
]
```
should be
```
self.required_if = [
    ['availability_requirement', 'at_least', ['quorum']]
]
```
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

module errors with too many variables to unpack

```

```

**Comment by caphrim007** [comment]
@jmcgill298 I've just pushed a refactored bigip_node. Would you please try that and raise any issues you come across? Thanks.
