### ISSUE TITLE
BIGIP_NODE: self.config does not exist

### ISSUE THREAD

**Issue by jmcgill298** [F5Networks/f5-ansible#345]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_node
##### ANSIBLE VERSION

```
2.4.0.0
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
NA
```

##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### SUMMARY

The module fails execution (applied local fix for required_if first). The error reports that property config does not exist.

This code comes from class `BigIpNodeFacade`, method `apply_changes` where it tries to access the state parameter:
```
        try:
            if self.config['state'] == 'absent':
                changed = self.absent()
            else:
                changed = self.present()
```
##### STEPS TO REPRODUCE

this should be repeatable with any playbook

```

```

##### EXPECTED RESULTS

expected module to ensure node exists
##### ACTUAL RESULTS

module fails with config property not existing

```

```

**Comment by caphrim007** [comment]
bigip_node has been refactored. please download it and raise any issues you may encounter.
