### ISSUE TITLE
BIGIP_POOL: self.have raises exception when moving from multiple monitors to single

### ISSUE THREAD

**Issue by jmcgill298** [F5Networks/f5-ansible#348]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool
##### ANSIBLE VERSION

```
2.4.0.0
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
12.1.1
```

##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### SUMMARY

When changing the monitor configs from having multiple monitors to a single monitor, the module raises an exception because self.have is changed to type "single" but has multiple moniotrs.

Here is the code:
```
            elif len(self.have.monitors_list) > 1:
                raise F5ModuleError(
                    "When using a 'monitor_type' of 'single', only one monitor may be provided"
                )
```
There isn't a need to validate the existing configuration since it already exists on the device; this could be removed and resolves the issue.

##### STEPS TO REPRODUCE

Requires the pool to be configured with multiple monitors before execution

```
- name: BIGIP POOL
  bigip_pool:
    user: "{{ user }}"
    password: "{{ password }}"
    server: "{{ ansible_host }}"
    validate_certs: false
    state: "present"                                             
    name: "my_pool"                               
    monitors: 
      - "http"                       
    monitor_type: single                       
```

##### EXPECTED RESULTS

expected all monitors to be removed other than "http"
##### ACTUAL RESULTS

exception raised

```
The full traceback is:
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 919, in main
    results = mm.exec_module()
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 618, in exec_module
    changed = self.present()
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 680, in present
    return self.update()
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 700, in update
    if not self.should_update():
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 690, in should_update
    result = self._update_changed_options()
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 655, in _update_changed_options
    change = diff.compare(k)
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 547, in compare
    result = getattr(self, param)
  File "/tmp/ansible_ktx2uc/ansible_module_bigip_pool.py", line 578, in monitor_type
    "When using a 'monitor_type' of 'single', only one monitor may be provided"
```

**Comment by caphrim007** [comment]
the intention with that check is to prevent someone from only setting the monitor_type in a request and then expecting it to fail. Using your example (and having an existing set of multiple monitors)

```
- name: BIGIP POOL
  bigip_pool:
    user: "{{ user }}"
    password: "{{ password }}"
    server: "{{ ansible_host }}"
    validate_certs: false
    state: "present"                                             
    name: "my_pool"                               
    monitor_type: single  
```

So i think this check needs to probably be changed to look something like this.

elif len(self.have.monitors) > 1 and len(self.want.monitors_list) > 1:

because the intent is to prevent someone from only setting the monitor_type and expecting some different behavior

**Comment by caphrim007** [comment]
@jmcgill298 try the fix I recently pushed.

**Comment by jmcgill298** [comment]
monitor_type is a read-only property, so no one should be trying to update it. My thoughts are that it might be easier to deprecate monitor type, and just key off of quorum value for determining how to build the monitor string.

Below is generic code, not representative of actual module code:
```
self.want.quorum = module.params['quorum']
self.have.quorum = api.get('quorum')
if self.want.quorum and self.want.quorum > 0
    self.want.monitors = generate_mofn_monitor(self.want.monitors)
elif not self.want.quorum and self.have.quorum > 0:
    self.want.monitors = generate_mofn_monitor(self.want.monitors)
else:
    self.want.monitors = generate_list_monitor(self.want.monitors)
```

This is very generic, but the idea is to determine the appropriate format of the monitors based on the  value of quorum. The module params should override existing, but if quorum is not provided in the module params, then to use the currently configured quorum value as the guide.

**Comment by jmcgill298** [comment]
@caphrim007 the latest code resolved the issue
