### ISSUE TITLE
Is change mode supported for Big-IP Ansible module?

### ISSUE THREAD

**Issue by jcshelby** [F5Networks/f5-ansible#35]
Just wanted to see if the --check flag is enabled or supported in this module. I ran my playbook with this flag but didn't get a report of changes to be made or current state of the F5, which from the documentation would suggest this isn't enabled on this module hence the request for confirmation

**Comment by caphrim007** [comment]
which module?

**Comment by jcshelby** [comment]
bigip_pool is the only one I've tried so far but is one for which I'd need that option

**Comment by caphrim007** [comment]
it looks like it should handle it. I wasn't the original author of it, but is it not reporting anything?

**Comment by jcshelby** [comment]
For my edification where do you see that it should be supported? That way I know where to look for these sorts of features in the future. I didn't see it in the online doc but could have easily missed it. While there isn't an example output in the documentation [http://docs.ansible.com/ansible/playbooks_checkmode.html](url) that I found to confirm what I should see, what I do see when I run the command is that it reports a change made but doesn't actually execute. This behavior is consistent with what the documentation suggests would happen if this function isn't supported by the module. I'm running the most current version of Ansible (just pulled down the latest code today). I also tried to output this to a text file (ansible-playbook --checkout <playbook>) to see if that would give me more verbosity and it didn't. I also didn't a file created in my directory similar to a retry file with a report of what changes would be made or what the current state of the device is

**Comment by caphrim007** [comment]
Sure, np.

If a module supports check mode, it should say so by having the following argument when it creates the `AnsibleModule` object.

```
supports_check_mode=True
```

as we can see here (using pools as an example)

https://github.com/F5Networks/f5-ansible/blob/master/library/bigip_pool.py#L382

this doesn't guarantee that it does check mode correctly, that's a guarantee that can only come from correct module development. However, that the author took the time to add that key suggests that they are reasonably certain that check mode will work.

What you should see when you run in check mode is as you expressed; that you should see a change reported but no change actually occurs.

for example, when I run bigip_pools with check mode and verbose output, I get this output

```
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "host": null, 
            "lb_method": "round_robin", 
            "monitor_type": null, 
            "monitors": null, 
            "name": "foo.pool", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": "localhost", 
            "server_port": 10443, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": false
        }, 
        "module_name": "bigip_pool"
    }
}
```

If I do to check my bigip though, I do __not__ see a pool created. Check mode is telling me that a pool __would have__ been created.

**Comment by jcshelby** [comment]
Tim:

Apologies for the delay in response. I had another project come up that needed my attention. I did try running the playbook with the command syntax below and didn't get a similar output to yours. Is the verbosity of the output dependent on the type of changes to be executed? If not, can you please specify what syntax I should be using? Thanks!

ansible-playbook --check --verbose a5976023-e3ac-4113-8cc6-8b595391f713.json

**Comment by caphrim007** [comment]
what output did you get?

**Comment by jcshelby** [comment]
Well it's now failing so I'll have to see what's causing that but I've included my command syntax and the output including the failure

**Comment by jcshelby** [comment]
[root@enaic tmp]# ansible-playbook --check --verbose 228baa0c-0338-4d28-a8f0-9174407ad160.json 
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'

No config file found; using defaults

PLAY [Create a VIP] ************************************************************

TASK [setup] *******************************************************************
ok: [10.0.32.120]

TASK [Create a VIP] ************************************************************
fatal: [10.0.32.120]: FAILED! => {"changed": false, "failed": true, "msg": "received exception: <urlopen error [Errno -2] Name or service not known>"}
	to retry, use: --limit @/tmp/228baa0c-0338-4d28-a8f0-9174407ad160.retry

PLAY RECAP *********************************************************************
10.0.32.120                : ok=1    changed=0    unreachable=0    failed=1   

[root@enaic tmp]#

**Comment by caphrim007** [comment]
can you change --verbose to be "-vvvv"

**Comment by jcshelby** [comment]
Tim:

I think that will do it. Apologies for not knowing that on my own. I'll review the documentation more closely next time. Thanks!
