### ISSUE TITLE
Switch to clouddocs

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#355]
The current documentation for the F5 Ansible modules is hosted on readthedocs. There is a request that this be moved to clouddocs.f5.com to align with the other cloudy documentation efforts. @jputrino will assist with this.

**Comment by caphrim007** [comment]
@selhorn you can take this one if you want.

**Comment by selhorn** [comment]
@caphrim007 I can't see how to assign this to myself. Do you think I have permission to own issues in this repo? You're welcome to assign it to me. Thanks

**Comment by caphrim007** [comment]
@selhorn assigned
