### ISSUE TITLE
issue/slack request

### ISSUE THREAD

**Issue by mdobeck1** [F5Networks/f5-ansible#361]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```

```

##### SUMMARY

Having trouble understanding how you are using the profiles.
##### STEPS TO REPRODUCE

```
vs_profiles1:
    - http
    - clientssl
```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@mdobeck1 what's the link to the documentation you have a question about?

**Comment by mdobeck1** [comment]
Well I’m having trouble understanding how profiles of different types are tied to their associated
For example, the docs say use “all_profiles” to list all the required profiles for the virtual server. But how does it know what to tie with ssl_profile, client_profile, server_profile, etc?
In the devel docs (in the example) it shows ( http://f5-ansible.readthedocs.io/en/devel/modules/bigip_virtual_server_module.html )
      profiles_both:
          - http
          - fix
      profiles_server_side:
          - clientssl
      profiles_client_side:
          - ilx
And that makes total sense.

But in the master, it seems to suggest grouping them all under all_profiles. (
But lets say I have an SSL profile named tcp1 and lets say I have a server_side profile named tcp1. How does it know what to assign it to? (https://github.com/F5Networks/f5-ansible/blob/master/roles/bigip_virtual_server/defaults/main.yaml)
The reason I asked for slack access is because this may be more of an issue of my understanding and less of a problem with the module.

**Comment by caphrim007** [comment]
ahh ok, so to answer you question, in the module that is delivered with ansible today, you **only** have the ability to specify "all" profiles. there is no concept of client/server-side profiles.

This deficiency is what you see us trying to fix in the devel (f5-ansible) code.

I've sent a Slack invitiation to (what I think) is your email.
