### ISSUE TITLE
Add support for CMP hash to bigip_vlan

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#371]
this controls the traffic disaggregator and is used by SP customers. Valid values would be 'source-address', 'destination-address', and 'default'

**Comment by alonsocamaro** [comment]
FYI: it is possible to use tmsh2iapp to create a iapp that creates the vlan with these cmp hash settings or any other.

See https://github.com/f5devcentral/f5-tmsh2iapp/wiki and https://raw.githubusercontent.com/wiki/f5devcentral/f5-tmsh2iapp/examples/demo.network-config.t2i

**Comment by caphrim007** [comment]
@alonsocamaro yes i know that. I made this req after watching your presentation
