### ISSUE TITLE
Add GTM Virtual Server to GTM pool

### ISSUE THREAD

**Issue by delgadillo22** [F5Networks/f5-ansible#382]
- Feature Idea

Add GTM VS to GTM pool

Requested by Forrest Crenshaw for customer 10/13

**Comment by JoshPineda** [comment]
Please add me to this request as well. Currently there is no way to add a GTM VS to bigip_gtm_pool.

**Comment by delgadillo22** [comment]
Fidelity requirement

**Comment by realged13** [comment]
Add me to the list, this one is a pretty high priority to me as I see now easy way to get this to work, trying to do this with tmsh commands is not going well.

I might be doing something wrong, but curious to see how someone else is handling it.

**Comment by caphrim007** [comment]
@JoshPineda @realged13 this should now be possible. see the `members` argument of the `bigip_gtm_pool` module
