### ISSUE TITLE
bigip_partition

### ISSUE THREAD

**Issue by hemskgren** [F5Networks/f5-ansible#4]
Hi

It feels like the bigip_partition.py is a copy if bigip_sysdb.py but not ready.

ansible-doc -M bigip_partition talk about sysdb.

Regards
Christer

**Comment by caphrim007** [comment]
Indeed. I think this module is still under development and was probably copied from an existing module. Marking as a bug to address moving forward

**Comment by caphrim007** [comment]
@hemskgren I've merged the changes for bigip_partition. It passes the tests provided in the tests/ directory, so have a go at it and see if it works for you too.

**Comment by hemskgren** [comment]
Hi

Works fine with /Common and dedicated routedomain option.

Regards
Christer

**Comment by caphrim007** [comment]
Thanks for test @hemskgren !
