### ISSUE TITLE
bigip_selfip is missing floating property; unable to create floating self-ips

### ISSUE THREAD

**Issue by JoshPineda** [F5Networks/f5-ansible#401]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
bigip_selfip

##### ANSIBLE VERSION
Ansible 2.4

##### PYTHON VERSION
Python 2.7.6

##### BIGIP VERSION
12.1.2 HF1

**Comment by caphrim007** [comment]
this also requires that traffic groups be specifiable on the selfip

**Comment by caphrim007** [comment]
@JoshPineda floating IPs can be created today. You just need to provide a floating traffic group; for example `traffic-group-1`.

I've included an example of doing that here

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_selfip/tasks/issue-00401.yaml

Additionally, I pushed some changes to the bigip_selfip module here to address idempotency problems with the traffic group param
