### ISSUE TITLE
Is there supossed to be a new bigip_pool_member module?

### ISSUE THREAD

**Issue by drakrubt** [F5Networks/f5-ansible#426]
Is there supposed to be a new bigip_pool_member module?

Looking through the libraries I see that the old bigip_pool_member.py was deprecated to _bigip_pool_member.py but there is not a new bigip_pool_member.py. The new bigip_pool.py code mentions that using its host/port params is depricated as well ... this I am not seeing a current supported method for managing pool members.

**Comment by caphrim007** [comment]
@drakrubt eventually. but not right now

**Comment by caphrim007** [comment]
@drakrubt I believe this is now complete, though I would like some more eyes on it particularly in the area of test. I believe there are no breaking changes in it. Anything deprecated should be removed in 2.6
