### ISSUE TITLE
bigip_snat_pool member option alias looks incorrect (shows aliases: m,e,m,b,e,r)

### ISSUE THREAD

**Issue by dbeckham** [F5Networks/f5-ansible#43]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
bigip_snat_pool

##### SUMMARY

In the [documentation](https://f5-ansible.readthedocs.io/en/latest/modules/bigip_snat_pool_module.html) for the recently add `bigip_snat_pool` module, the alias list of the `members` option in the comments column of the [Options](https://f5-ansible.readthedocs.io/en/latest/modules/bigip_snat_pool_module.html#options) table displays: 

```
aliases: m, e, m, b, e, r
```
This is on [line #L52 in docs/modules/bigip_snat_pool_module.rst](https://github.com/F5Networks/f5-ansible/commit/535cf6da2109ae2f153fdc72bf304a47693257d5#diff-770ea84967cd8d1f3970decd8e43d52bR52).

**Comment by caphrim007** [comment]
this now fixed
