### ISSUE TITLE
Help on bigip_command

### ISSUE THREAD

**Issue by ric79** [F5Networks/f5-ansible#436]
Hello, I would like to remove all my shell command calls and to use your bigip_command module.

I need to create a monitor inside a partition BUT the code is provided by the user at runtime (I cannot change this behaviour). Let us suppose the the monitor provided is:

               create ltm monitor tcp-half-open tcp_half_open_5_min { \
                   defaults-from /Common/tcp_half_open \
                   description tcp_half_open_5_min \
                   destination *:* \
                   interval 30 \
                   time-until-up 0 \
                   timeout 16 \
               }

In my old implementation:
```
- name: "Add monitors in current partition"
  shell: >
          cd /{{lbf5_partition.name}};
          {{monitor_cmd}};
  args:
    executable: tmsh

```
Using the bigip_command I tried several ways without no luck. For example:
```
  bigip_command:
    commands: >
               tmsh \
               create cli transaction \
               cd /{{lbf5_partition.name}} \
               {{monitor_cmd}} \
               submit cli transaction
....

```
Maybe the best way could be to modify then monitor command in order to add the partition but I cannot. Is there a way to bypass the problem?

RR

**Comment by caphrim007** [comment]
@ric79 how is the monitor provided?

**Comment by ric79** [comment]
Via Excel :( 
From Excel I generate a  config.yaml which contains all the requested configurations

**Comment by caphrim007** [comment]
Ok, but are you putting the values in the spreadsheet, or is someone else?

Alternatively, you are the one that wrote the thing that converts it to yaml?

Does the spreadsheet contain a field for name? Partition?

**Comment by ric79** [comment]
yes the xlsx contains the partition name. i would like to avoid to ask the user to put the partition name in the creation command because I cannot check it.
I've seen that i can use something like tmsh -c "cd /<partitionname>; <monitor_command>" but with this approach I have to skip quotes...

At the moment I think I cannot remove the shell module for big_command. Sigh!

RR

**Comment by caphrim007** [comment]
@ric79 if you have both the partition name and the name of the monitor that you want to create, then you can specifically name the partition in the tmsh command and it will create it in that partition; without changing the directory like you do.

For example,

`tmsh create ltm pool /foo/my_pool` would create the pool in the `foo` partition even if i was in the `Common` partition when I ran the above command

**Comment by ric79** [comment]
You are right. But this means that I have to parse the monitor code proposed by the user or to trust that the user add the partition name in the code. I don't like it. However thanks a lot for spending your time in answering to my dubts!

RR

**Comment by ric79** [comment]
You are right. But this means that I have to parse the monitor code proposed by the user or to trust that the user add the partition name in the code. I don't like it. However thanks a lot for spending your time in answering to my dubts!

RR
