### ISSUE TITLE
bigip_virtual_server fails on subsequent runs based on sort order of iRule list

### ISSUE THREAD

**Issue by dbeckham** [F5Networks/f5-ansible#44]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### PYTHON VERSION

```
Python 2.7.12
```
##### F5 BIGIP LTM VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```
##### CONFIGURATION

```
retry_files_enabled = False
host_key_checking=False
```
##### OS / ENVIRONMENT

Alpine 3.4 (Docker Container)
##### SUMMARY

The sort order of irules in the `bigip_virtual_server` module can cause the task to fail if the first rule in the list has a lower alphanumeric sort order than the rules that follow it.

_NOTE: this only happens on subsequent runs; the virtual server is always successfully created on first run._

The error message received:

```
received exception: Error on updating Virtual Server : Server raised fault: 'Exception caught in System::urn:iControl:System/Session::submit_transaction()
Exception: Common::OperationFailed
    primary_error_code   : 16908390 (0x01020066)
    secondary_error_code : 0
    error_string         : 01020066:3: The requested virtual server rule (/Common/myvip /Common/myirule) already exists in partition Common.'
```
##### STEPS TO REPRODUCE

Create three iRules named `zrule`, `myrule`, and `myrule2`. I used the following TCL code in my tests:

```
when HTTP_REQUEST {
    HTTP::respond 200 content "OK"
}
```

Create a task that uses the `bigip_virtual_server` module with the following configuration parameters:

```
- name: Add virtual server
bigip_virtual_server:
  state: present
  name: myvip
  destination: "1.1.1.1"
  port: 80
  pool: mypool
  snat: Automap
  all_profiles:
    - http
    - tcp
  all_rules:
    - myirule
    - myirule2
  password: "{{ bigip_password }}"
  server: "{{ inventory_hostname }}"
  user: "{{ bigip_username }}"
  validate_certs: "{{ validate_certs }}"
```

Run this task once to create the virtual server, and then a second time to verify that there are no errors.

Change the `all_rules` option to include the `zrule` iRule at the top of the list:

```
all_rules:
  - zrule
  - myrule
  - myrule2
```

Run the task again, at which point it will fail.

If you remove the `zrule` iRule, the task will once again run successfully. The task will also run successfully if you put the `zrule` iRule at the end of the list.
##### EXPECTED RESULTS

The sort order of iRules should not cause the `bigip_virtual_server` module to fail.
##### ACTUAL RESULTS

The iRule is successfully created, but fails on every run after that:
##### Successful Creation

```
Using module file /playbooks/library/bigip_virtual_server.py
<lbl11.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<lbl11.example.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [lbl11.example.com] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "all_profiles": [
                "http",
                "tcp"
            ],
            "all_rules": [
                "myirule",
                "myirule2"
            ],
            "default_persistence_profile": null,
            "description": null,
            "destination": "1.1.1.1",
            "enabled_vlans": null,
            "name": "myvip",
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool": "mypool",
            "port": 80,
            "route_advertisement_state": "disabled",
            "server": "lbl11.example.com",
            "server_port": 443,
            "snat": "Automap",
            "state": "present",
            "user": "ansible",
            "validate_certs": false
        },
        "module_name": "bigip_virtual_server"
    }
}

PLAY RECAP *********************************************************************
lbl11.example.com     : ok=2    changed=0    unreachable=0    failed=0
```
##### Second Run that fails:

```
Using module file /playbooks/library/bigip_virtual_server.py
<lbl11.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<lbl11.example.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [lbl11.example.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "all_profiles": [
                "http",
                "tcp"
            ],
            "all_rules": [
                "zrule",
                "myirule",
                "myirule2"
            ],
            "default_persistence_profile": null,
            "description": null,
            "destination": "1.1.1.1",
            "enabled_vlans": null,
            "name": "myvip",
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool": "mypool",
            "port": 80,
            "route_advertisement_state": "disabled",
            "server": "lbl11.example.com",
            "server_port": 443,
            "snat": "Automap",
            "state": "present",
            "user": "ansible",
            "validate_certs": false
        },
        "module_name": "bigip_virtual_server"
    },
    "msg": "received exception: Error on updating Virtual Server : Server raised fault: 'Exception caught in System::urn:iControl:System/Session::submit_transaction()\nException: Common::OperationFailed\n\tprimary_error_code   : 16908390 (0x01020066)\n\tsecondary_error_code : 0\n\terror_string         : 01020066:3: The requested virtual server rule (/Common/myvip /Common/myirule) already exists in partition Common.'"
}
        to retry, use: --limit @/playbooks/bigip_testing.retry

PLAY RECAP *********************************************************************
lbl11.example.com     : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by dbeckham** [comment]
This one was crazy hard to turn into something that was reproducible. We happen to have a high priority iRule that starts with `w` on some of our virtual servers, so this would seem to randomly fail. If you have any questions about the testing and results, let me know.

**Comment by caphrim007** [comment]
odd. thanks for finding this, i'll have a look-see

**Comment by dbeckham** [comment]
Fwiw, I just noticed in a run that the order issue seems to be centered around the first item.  The sort order of the rest of the items seems unimportant as long as the first isn't alphanumerically sorted in ascending order.

**Comment by caphrim007** [comment]
Long story short, you wan5 the order you list them in in yaml to be the order they're listed in the bigip. Right?

**Comment by dbeckham** [comment]
Well, yes. In the docs for this module, the comments for the `all_rules` option says:

> List of rules to be applied in priority order

Anything to do with sorting that I've been talking about was just trying to identify some sort of reproducible test that could be used to find and fix the bug.

**Comment by caphrim007** [comment]
Okie doke. My apologies if I'm a bit unfamiliar with the code. I'm its adopted father, but we'll get things fixed

**Comment by caphrim007** [comment]
This should now be fixed in the most recent version of the bigip_virtual_server module in this repository. That module will be upstreamed as part of the ansible 2.5 release
