### ISSUE TITLE
Policy Modification/Creation not supported

### ISSUE THREAD

**Issue by amsinha2** [F5Networks/f5-ansible#45]
Local Traffic Policies cannot be managed via Ansible
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Local traffic Policies 
##### ANSIBLE VERSION

```
ansible 2.1.0
```
##### PYTHON VERSION

```
python 2.7.5
```
##### BIGIP VERSION

```
12.1.0
```
##### CONFIGURATION

tmsh create ltm policy Drafts/Policy strategy first-match rules replace-all-with { homepage { actions add { 0 { forward select pool pool1 } } conditions add { 0 { http-uri path contains values { \/HomePage } } } ordinal 0 } second { actions add { 0 { forward select pool pool2 } } conditions add { 0 { http-uri path contains values { \/second } } } ordinal 1 } ....... }
##### OS / ENVIRONMENT

RHEL 7
##### SUMMARY

need to be able to manage policies and add to them without resorting to tmsh, or command 
the following functionality would be needed:
1. Create a draft policy  -
    # create ltm policy Drafts/foo <...>
NOTE: this creates a policy - /Common/Drafts/foo  (if you were to do this in a different folder, the Drafts will hang off that, for example - /Common/bar/Drafts/foo)
1. Publish the above -
   # publish ltm policy Drafts/foo
   
   NOTE:  This step will delete the foo from Drafts folder and create a new policy foo (for example, /Common/Drafts/foo will be renamed/moved to /Common/foo)
2. To modify the policy, 3 steps are needed -
   # modify ltm policy foo create-draft
   
   ```
     - will create draft; so there will now be 2 foo's - /Common/foo and /Common/Drafts/foo
   ```
   # modify ltm policy Drafts/foo <...>
   
   ```
     - will only affect the draft copy
   ```
   # publish ltm policy Drafts/foo
   
   ```
     - will replace /Common/foo with /Common/Drafts/foo
   ```
3. assign to a vserver (https://github.com/F5Networks/f5-ansible/issues/39)

**Comment by caphrim007** [comment]
this is now merged upstream
