### ISSUE TITLE
bigip_gtm_facts returns empty list

### ISSUE THREAD

**Issue by rainierpineda2** [F5Networks/f5-ansible#465]
Bug Report

##### COMPONENT NAME
bigip_gtm_fact

##### ANSIBLE VERSION
ansible 2.4.0.0
  config file = /home/apined12/f5_ansible/playbooks/ansible.cfg
  configured module search path = [u'/home/apined12/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /data/automation/pylibext/lib/python2.7/site-packages/ansible-2.4.0.0-py2.7.egg/ansible
  executable location = /data/automation/pylibext/bin/ansible
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
Version     11.6.1

##### LIBRARY VERSIONS

ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "pool": [
            {
                "alternate_mode": "none",
                "dynamic_ratio": "disabled",
                "enabled": "True",
                "fallback_ipv4": "any",
                "fallback_ipv6": "any6",
                "fallback_mode": "none",
                "full_path": "/Common/NA-Test22",
                "limit_max_bps": "0",
                "limit_max_bps_status": "disabled",
                "limit_max_connections": "0",
                "limit_max_connections_status": "disabled",
                "limit_max_pps": "0",
                "limit_max_pps_status": "disabled",
                "load_balancing_mode": "global-availability",
                "manual_resume": "disabled",
                "max_address_returned": "1",
                "members": [],
                "monitor": "default",
                "name": "NA-Test22",
                "partition": "Common",
                "qos_hit_ratio": "5",
                "qos_hops": "0",
                "qos_kilobytes_second": "3",
                "qos_lcs": "30",
                "qos_packet_rate": "1",
                "qos_rtt": "50",
                "qos_topology": "0",
                "qos_vs_capacity": "0",
                "qos_vs_score": "0",
                "ttl": "30",
                "verify_member_availability": "enabled"
            }
        ]
    }
}

**Comment by rainierpineda2** [comment]
Please close. Jacob McGill's suggested solution worked. However, I'd like to comment and respectfully request Tim Rupp to have this fix should be included in the next Ansible 2.5 release. Many thanks and keep up the good work!

**Comment by caphrim007** [comment]
@rainierpineda2 any code changes in this repo should become upstream before 2.5. I think Jacob's fix is included.
