### ISSUE TITLE
Manage BIG-IP DNS Pools in a BIG-IP DNS WIP

### ISSUE THREAD

**Issue by KSI-Brian-Rossmeisl** [F5Networks/f5-ansible#470]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Manage (add/remove/last resort/etc) BIG-IP DNS (GTM) Pools in a BIG-IP DNS (GTM) WIP

**Comment by delgadillo22** [comment]
Fidelity requirement?
Add gtm pool to gtm wideip 
Add GTM vs to GTM pool 
GTM pool member monitor 
GTM VS Monitor

**Comment by KSI-Brian-Rossmeisl** [comment]
No, we have 3 customers, 2 banks and a large utility company that would like to use this asap.


[cid:image001.png@01D23F17.7A56C3F0]

Brian Rossmeisl
Sr Solutions Architect
Kudelski Security Inc.
5500 Interstate North Parkway NW
Suite 300, Atlanta GA 30328
Phone +1 980-275-1524
brian.rossmeisl@kudelskisecurity.com<mailto:brian.rossmeisl@kudelskisecurity.com>
https://www.kudelskisecurity.com/
This e-mail and any attachments may contain information that is confidential, proprietary, privileged or otherwise protected by law. The information contained herein is solely intended for the named addressee (or a person responsible for delivering it to the addressee). If you are not the intended recipient of this message, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this e-mail in error, please notify the sender immediately by return e-mail and delete it from your computer.

**Comment by WRJFontenot** [comment]
Is this a dupe of #124 ?

**Comment by KSI-Brian-Rossmeisl** [comment]
Robbie,
This is not a duplicate of #124. #470 subsumes #124.

Brian Rossmeisl
Sr Solutions Architect
Kudelski Security Inc.
Phone +1 980-275-1524
US Headquarters
5090 40th St., Suite 450
Phoenix, AZ 85018
brian.rossmeisl@kudelskisecurity.com<mailto:brian.rossmeisl@kudelskisecurity.com>
https://www.kudelskisecurity.com/
This e-mail and any attachments may contain information that is confidential, proprietary, privileged or otherwise protected by law. The information contained herein is solely intended for the named addressee (or a person responsible for delivering it to the addressee). If you are not the intended recipient of this message, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this e-mail in error, please notify the sender immediately by return e-mail and delete it from your computer.

**Comment by caphrim007** [comment]
@KSI-Brian-Rossmeisl can you refresh my memory on what you need besides a `pool` option to bigip_gtm_pool (which we appear to have)

**Comment by KSI-Brian-Rossmeisl** [comment]
Thank you for the additional info. I have reviewed the cloud docs documentation and with Ansible 2.6 it would appear that this ticket has been resolved. Thank you!
