### ISSUE TITLE
bigip_license

### ISSUE THREAD

**Issue by JoshPineda** [F5Networks/f5-ansible#474]
Bug Report

 ##### COMPONENT NAME
bigip_license

##### ANSIBLE VERSION
2.5

##### PYTHON VERSION
2.7.5

##### BIGIP VERSION
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017

##### LIBRARY VERSIONS
$ pip freeze | grep f5-sdk
f5-sdk==3.0.2
$ pip freeze | grep bigsuds
bigsuds==1.0.2

##### CONFIGURATION
NA

##### OS / ENVIRONMENT

Linux xxxxxxxxxxxxx 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY
Getting the following error

TASK [License Device] *************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'F5ModuleError' is not defined
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/home/apined12/.ansible/tmp/ansible-tmp-1511892451.53-150783681679521/bigip_license_v2.py\", line 528, in <module>\n    main()\n  File \"/home/apined12/.ansible/tmp/ansible-tmp-1511892451.53-150783681679521/bigip_license_v2.py\", line 523, in main\n    except F5ModuleError as e:\nNameError: global name 'F5ModuleError' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

STEPS TO REPRODUCE
- name: F5 Test License Module
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    mgmt_ip: 10.0.160.134
    setup_user: admin
    license: "{{ lookup('file', 'files/lb008_license.lic') }}"
    dossier: "{{ lookup('file', 'files/lb008_dossier.txt') }}"

  vars_prompt:
    - name: "setup_password"
      prompt: "Enter admin password"
      private: yes

  tasks:
  - name: License Device
    bigip_license_v2:
      server: "{{ mgmt_ip }}"
      user: "{{ setup_user }}"
      password: "{{ setup_password }}"
      license_content: "{{ license }}"
      dossier_content: "{{ dossier }}"
      validate_certs: no
    delegate_to: localhost

**Comment by JoshPineda** [comment]
I created a copy of the bigip_license into my own library directory to distinguish it from the other version I have which uses dossier_file and license_file as parameters. That one does not work either with a different error reported. The error for that is listed below:
TASK [License Device] *************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got an unexpected keyword argument 'port'
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8yyOoY/ansible_module_bigip_license.py\", line 633, in <module>\n    main()\n  File \"/tmp/ansible_8yyOoY/ansible_module_bigip_license.py\", line 594, in main\n    common = BigIpLicenseCommon(module)\n  File \"/tmp/ansible_8yyOoY/ansible_module_bigip_license.py\", line 205, in __init__\n    debug=True\nTypeError: __init__() got an unexpected keyword argument 'port'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by caphrim007** [comment]
#442 is part of this work
