### ISSUE TITLE
allow virtual server module to consume an AFM firewall policy setting

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#491]
modify ltm virtual TRUSTEDNETWORK-PROTECTED-NET-UDR fw-enforced-policy DIAMETER-NODES-POLICY-UDR-IPV4

**Comment by chen23** [comment]
I would also add "security-log-profiles"

modify ltm virtual TRUSTEDNETWORK-PROTECTED-NET-UDR  security-log-profiles replace-all-with { SECURITY-LOG }
