### ISSUE TITLE
Add static and float as parameters to bigip_selfip

### ISSUE THREAD

**Issue by mlowcher61** [F5Networks/f5-ansible#492]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_selfip
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       3.0.1679
  Edition     Hotfix HF3
  Date        Fri Nov 10 23:41:13 PST 2017

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==3.0.3
```

##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Currently the bigip_selfip module can only create static ip addresses.  Add static and float as options within the module.
bigip_selfip_static and bigip_selfip_float. 

##### STEPS TO REPRODUCE

The ability to create and both static and floating self ips

```
N/A
```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@mlowcher61 per this comment

"""
If you want the self IP address to be a floating IP address, that is, an address shared between two or more BIG-IP devices in a device group, you can assign a floating traffic group to the self IP address. A floating traffic group causes the self IP address to become a floating self IP address.
"""

in this article

https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos-routing-administration-13-0-0/5.html

This is already possible. You need to assign the self-ip a correct traffic group

**Comment by mlowcher61** [comment]
Tim,

Great! That’s even better. Looking at the examples in the python file it did not show traffic group as an option but now that I looked at docs.ansible.com under modules I see that as an option.
I will delete my feature request.

Sincerely,


Mark Lowcher CISSP CCSP |  F5 Systems Engineer – AT&T Cloud and Managed Services

F5 Networks

  P 888.88.BIG.IP

 M 512.745.6263

m.lowcher@f5.com<mailto:m.lowcher@f5.com>

   www.f5.com<http://www.f5.com/>
