### ISSUE TITLE
feature request routeing

### ISSUE THREAD

**Issue by hemskgren** [F5Networks/f5-ansible#5]
Hi

I missing a module to add static route /default route both in Common but preferred in Partition/RD.
Then I can convert from bigsuds to ansible for base deployments.

Regards
Christer

**Comment by caphrim007** [comment]
Do you have an existing bigsuds script that you would be able to share via a gist or something so that I could mock up a module?

**Comment by hemskgren** [comment]
Hi

Add and remove route via bigsuds like this?

!! create (default)route in Partition LB-EXT
import bigsuds
b = bigsuds.BIGIP(hostname ='10.1.1.10',username='admin',password='admin',debug=True)
#
b.Management.Partition.set_active_partition('LB-EXT')
#
print "# show/add/show Static RouteTable list:"
print(b.Networking.RouteTableV2.get_static_route_list())
b.Networking.RouteTableV2.create_static_route(routes = ['DefaultGW'],destinations = [{'netmask': '0.0.0.0', 'address': '0.0.0.0'}],attributes = [{'gateway': '1.1.1.4'}])
print(b.Networking.RouteTableV2.get_static_route_list())
#

We remove route (all) in Partision LB-EXT:
#
print "# Delete all Route:"
b.Management.Partition.set_active_partition('LB-EXT')
b.Networking.RouteTableV2.delete_all_static_routes()
#

**Comment by caphrim007** [comment]
Thanks! That helps!

**Comment by dano0b** [comment]
@caphrim007 would be great to have this feature. Would help us to set the right routes during our provisioning of a docker cluster.

**Comment by rklomp** [comment]
Just to let you know that with your latest commits static routes are now working for me 👍

**Comment by caphrim007** [comment]
@rklomp you got lucky then. The module should be complete now though. i need to push updated code and correct the unit tests. i will close this issue when that is complete
