### ISSUE TITLE
ssh-functionality-for-modules.rst needs to be edited

### ISSUE THREAD

**Issue by selhorn** [F5Networks/f5-ansible#503]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
ssh-functionality-for-modules.rst 

##### ANSIBLE VERSION
```

```

##### PYTHON VERSION
```

```

##### BIGIP VERSION
```

```

##### LIBRARY VERSIONS
```

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
This needs to be edited to make it slightly more formal.
- Remove opinions (this makes things easy or difficult)
- Change “it is my recommendation” to be generic

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
this is now fixed
