### ISSUE TITLE
parameters.rst should be edited or moved

### ISSUE THREAD

**Issue by selhorn** [F5Networks/f5-ansible#505]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
pulling-docker-containers.rst

##### ANSIBLE VERSION
```

```

##### PYTHON VERSION
```

```

##### BIGIP VERSION
```

```

##### LIBRARY VERSIONS
```

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
- This doc talks about ideas for solutions. The product documentation should cover things that are already implemented, or tell customers how to do something. If you’d like, maybe we can make a section called Tim’s Tips or Tim’s blog or whatever you’d like, and we can put stuff there? Or we can put on devcentral. We just need to separate it from product docs, or change it to be more affirmative.

- In the product docs, we can’t publish future plans, because (though it’s extreme) you could be sued for promising something and not delivering.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@selhorn I dont think your second bullet point there is sensible. We publish a lot of stuff in this repository that is not delivered. It's a development respository. Additionally, those files are in a "development" directory.

The implication of the repository as a whole is that nothing is promised. If things were promised, then we would have releases and people could get things from us.

None of that is true.

I'll move it to an internal resource though, at your request

**Comment by caphrim007** [comment]
the content of the parameters document is considered "implementation details" that have no influence on what the user does. This is a document that discusses the internals of the module code and how a developer looking at the module code should rectify what they are seeing.

"developer" here in the sense of "any individual that wants to contribute to the code base"

So this document should be **edited** it should not be removed.

**Comment by selhorn** [comment]
OK, thanks. So this text: 
These instructions are only relevant to you if you are an F5'er. If not, feel free to skip over this document.

OK to remove? When I was editing, I saw this at the top of the doc and so didn't look at it in much more detail.

**Comment by caphrim007** [comment]
you see that in the `parameters.rst` doc? I dont see it

**Comment by selhorn** [comment]
Sorry, wrong doc. I will edit again and if I still have questions, will open an issue on the specific text in question.
