### ISSUE TITLE
bigip_virtual_server tests need more coverage for enabled_vlans and disabled_vlans

### ISSUE THREAD

**Issue by RobCupples** [F5Networks/f5-ansible#520]
##### ISSUE TYPE

 - Test Enhancement

##### COMPONENT NAME

bigip_virtual_server

##### SUMMARY

After a virtual is created could add steps to -

~~Change enabled_vlans from something to nothing.~~ INVALID
~~Set disabled_vlans to all (which ironically is the above's twin)~~ INVALID
~~Change the value of disabled_vlans (changing the value of enabled_vlans seems to already be covered)~~ COMPLETE

**Comment by caphrim007** [comment]
@RobCupples the second item there, "Set disabled_vlans to all (which ironically is the above's twin)" is an invalid input. `all` is only valid for enabling vlans

**Comment by caphrim007** [comment]
what did you expect the first item to look like in yaml?

**Comment by RobCupples** [comment]
Ok.  It looks like I messed up and should of reviewed how enabled_vlans and disabled_vlans work in tmsh before writing this up.

**Comment by caphrim007** [comment]
closing due to the third bullet being addressed and the other two being invalid.
