### ISSUE TITLE
bigip_virtual_server tests need more coverage for pool

### ISSUE THREAD

**Issue by RobCupples** [F5Networks/f5-ansible#521]
##### ISSUE TYPE

 - Test Enhancement

##### COMPONENT NAME

bigip_virtual_server

##### SUMMARY

Coverage that I think could be added after a virtual server has been created:

- Switch the value of "pool:" from one pool to another pool
- Switch the value of "pool:" from one pool to nothing.

**Comment by caphrim007** [comment]
@RobCupples this should now be fixed
