### ISSUE TITLE
bigip_irule fails when using the 'src' parameter instead of the 'content' parameter

### ISSUE THREAD

**Issue by termlen0** [F5Networks/f5-ansible#543]
ISSUE TYPE

    Bug Report

COMPONENT NAME

bigip_irule 
ANSIBLE VERSION

ansible 2.4.2.0
  config file = /home/ajay/ansible.cfg
  configured module search path = [u'/home/ajay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

PYTHON VERSION

Python 2.7.12

BIGIP VERSION
 "Sys::Version", 
                "Main Package", 
                "  Product     BIG-IP", 
                "  Version     12.1.1", 
                "  Build       0.0.184", 
                "  Edition     Final", 
                "  Date        Thu Aug 11 17:09:01 PDT 2016", 
                "", 

CONFIGURATION
OS / ENVIRONMENT

Ubuntu 16.04
SUMMARY

This is an exact repeat of the issue #316. Possibly, the bug was reintroduced in this newer version of Ansible.

bigip_irule fails to create a new a new iRule when the src parameter is used instead of the content parameter, resulting in the exception: f5.sdk_exception.MissingRequiredCreationParameter: Missing required params: ['apiAnonymous']"

STEPS TO REPRODUCE

    - name: ADD AN iRULE
      bigip_irule:
        #content: "{{ lookup('file', './files/128-redirect.tcl') }}"  <--- Works
        src: "./files/128-redirect.tcl"
        state: present
        name: "RedirectInsecure"
        module: ltm
        server: "{{ inventory_hostname }}"
        user: "{{ un }}"
        password: "{{ pwd }}"
        validate_certs: no
      tags: irule

EXPECTED RESULTS

Expected the irule to be created, and the module to succeed without throwing an exception.
ACTUAL RESULTS

Module fails and throws exception.

TASK [ADD AN iRULE] ***************************************************************************************************************************************************************************************************************************************************
task path: /home/ajay/Projects/misc/f5-playbooks/pb1.yml:119
Using module file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_irule.py
<10.1.100.204> ESTABLISH LOCAL CONNECTION FOR USER: ajay
<10.1.100.204> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.1.100.204> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103 `" && echo ansible-tmp-1513960127.68-63185343513103="` echo /home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103 `" ) && sleep 0'
<10.1.100.204> PUT /tmp/tmp.FgwduiCtgX/tmpdQc3g4 TO /home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103/bigip_irule.py
<10.1.100.204> EXEC /bin/sh -c 'chmod u+x /home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103/ /home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103/bigip_irule.py && sleep 0'
<10.1.100.204> EXEC /bin/sh -c 'python /home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103/bigip_irule.py; rm -rf "/home/ajay/.ansible/tmp/ansible-tmp-1513960127.68-63185343513103/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 424, in <module>
    main()
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 417, in main
    results = mm.exec_module()
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 194, in exec_module
    return manager.exec_module()
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 216, in exec_module
    changed = self.present()
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 256, in present
    return self.create()
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 262, in create
    self.create_on_device()
  File "/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py", line 318, in create_on_device
    **params
  File "/home/ajay/venv2/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 1002, in create
    return self._create(**kwargs)
  File "/home/ajay/venv2/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 954, in _create
    self._check_create_parameters(**kwargs)
  File "/home/ajay/venv2/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 917, in _check_create_parameters
    raise MissingRequiredCreationParameter(error_message)
f5.sdk_exception.MissingRequiredCreationParameter: Missing required params: ['apiAnonymous']

fatal: [10.1.100.204]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 424, in <module>\n    main()\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 417, in main\n    results = mm.exec_module()\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 194, in exec_module\n    return manager.exec_module()\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 216, in exec_module\n    changed = self.present()\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 256, in present\n    return self.create()\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 262, in create\n    self.create_on_device()\n  File \"/tmp/tmp.FgwduiCtgX/ansible_WrfMwc/ansible_module_bigip_irule.py\", line 318, in create_on_device\n    **params\n  File \"/home/ajay/venv2/local/lib/python2.7/site-packages/f5/bigip/resource.py\", line 1002, in create\n    return self._create(**kwargs)\n  File \"/home/ajay/venv2/local/lib/python2.7/site-packages/f5/bigip/resource.py\", line 954, in _create\n    self._check_create_parameters(**kwargs)\n  File \"/home/ajay/venv2/local/lib/python2.7/site-packages/f5/bigip/resource.py\", line 917, in _check_create_parameters\n    raise MissingRequiredCreationParameter(error_message)\nf5.sdk_exception.MissingRequiredCreationParameter: Missing required params: ['apiAnonymous']\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
        to retry, use: --limit @/home/ajay/Projects/misc/f5-playbooks/pb1.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************
10.1.100.204               : ok=0    changed=0    unreachable=0    failed=1

**Comment by caphrim007** [comment]
@termlen0 are the modules in this repo affected?

**Comment by termlen0** [comment]
I only tested the core module that comes with `pip install ansible`, using the latest stable version.

**Comment by caphrim007** [comment]
can you test with the one in this repo? the tests we have for the previous issue you mentioned still work so I suspect you're providing an incorrect path to the `src` file. Are you using this in a role?

**Comment by termlen0** [comment]
The path is correct because the exact same path works fine while using the `content` parameter. Are you unable to replicate the issue with maybe a brand new venv and fresh install of ansible?

**Comment by caphrim007** [comment]
we do not fix changes in older versions of ansible. so if its not working in the release of code in this repository here, it's not something that we fix.

In terms of it working one way and not the other, you're incorrect. Use of a `lookup` will implicitly look in the `files` directory of a role. If you are using this task in a role and specifying a relative path (which you are in the example above) Ansible is looking in the path relative to the playbook file, not the role.

If you want to use the role's `files` directory, you need to specify the `{{ role_path }}` variable, followed by the path to the file from the root of the role directory (replace `.` with `{{ role_path }}`.

**Comment by termlen0** [comment]
Thanks. I am not using roles btw.

**Comment by caphrim007** [comment]
@termlen0 I've downloaded 2.4.2.0 and reproduced the issue.

The same issue does not exist in 2.5.0. You can either wait for that to release, or you can get the `bigip_irule` from this repo and use it in place of the 2.4.2.0 version

**Comment by termlen0** [comment]
Thanks! Works for me.
