### ISSUE TITLE
bigip_static_route.py support for route-domain

### ISSUE THREAD

**Issue by k-sumida** [F5Networks/f5-ansible#545]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_static_route.py

##### SUMMARY

Please add support for route domain for multi-tenant environment like other modules (bigip_routedomain or bigip_selfip).

**Comment by wanexa** [comment]
doesn't work with the gateway , gateway is stuck in Route domain 0 ansible 2.5.2
