### ISSUE TITLE
System SMTP Module

### ISSUE THREAD

**Issue by realged13** [F5Networks/f5-ansible#555]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
New Module For: System  ››  Configuration : Device : SMTP  ››  New SMTP Configuration

##### ANSIBLE VERSION
2.4.2

##### BIGIP VERSION
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2

##### LIBRARY VERSIONS
f5-icontrol-rest==1.3.4
f5-sdk==3.0.7

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
Would like to get a module created to handle this portion of creating SMTP contacts.

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
n/a

##### ACTUAL RESULTS
n/a

**Comment by caphrim007** [comment]
![image](https://user-images.githubusercontent.com/46956/34528883-20b48c38-f05f-11e7-9ad6-a8ce29d194d0.png)

**Comment by MicSkr** [comment]
Bump. Additional request for this.

**Comment by caphrim007** [comment]
smtp-server functionality has been added to the f5-sdk
