### ISSUE TITLE
bigip_partition does not set description on the sys folder object

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-ansible#557]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_partition

##### ANSIBLE VERSION

```
  config file = /home/snops/sscssli/ansible.cfg
  configured module search path = [u'/home/snops/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.4
```

##### CONFIGURATION

Running within F5 SNOPS Docker container with Ansible.cfg file as follows:
[snops@f5-super-netops] [~/sscssli] $ cat ansible.cfg
[defaults]
inventory = ./hosts
roles_path = ./roles
#library = ./library
retry_files_enabled = False
[snops@f5-super-netops]

##### OS / ENVIRONMENT

Running within F5 SNOPS Docker container

##### SUMMARY

bigip_partition successfully creates partitions, but does not correctly set the "Description" value for the corresponding "sys folder _[partition_name]_" object in the configuration.
Could the module be modified/augmented to set the "description" value for both of the corresponding configuration objects "auth partition" and "sys folder" (as seen in the resulting bigip_base.conf file)?
 
##### STEPS TO REPRODUCE

Successfully run a playbook with bigip_partition module to create new partition name: "Tenant-001" with description: "Steve is great" and then use Chrome to login to the BIG-IP GUI and browse to System >> Users:Partition List >> Tenant-001 to observe the content of the "Description" text field is blank. Login to the same BIG-IP with SSH to access TMSH and observe the "Description: Steve is great" is actually present, but for the wrong configuration object "list auth partition Tenant-001":

```
  - name: Create tenant partitions
    bigip_partition:
      server: "{{ inventory_hostname }}"
      user: admin
      password: admin
      name: Tenant-001
      description: "Steve is great"
    delegate_to: localhost

admin@(ip-10-1-1-4)(cfg-sync Standalone)(Eval:Active)(/Common)(tmos)# list auth partition Tenant-001
auth partition Tenant-001 {
    description Steve is great
}
admin@(ip-10-1-1-4)(cfg-sync Standalone)(Eval:Active)(/)(tmos)# list sys folder Tenant-001
sys folder Tenant-001 {
    device-group none
    inherited-devicegroup true
    inherited-traffic-group true
    traffic-group Common/traffic-group-1
}
admin@(ip-10-1-1-4)(cfg-sync Standalone)(Eval:Active)(/)(tmos)#
```

##### EXPECTED RESULTS

To login to BIG-IP GUI and find "Steve is great" when I browse to System >> Users:Partition List >> Tenant-001. 

##### ACTUAL RESULTS

Playbook runs successfully and creates the new partition named "Tenant-001", but BIG-IP GUI shows a blank "Description" filed when I browse to System >> Users:Partition List >> Tenant-001. 

```
admin@(ip-10-1-1-4)(cfg-sync Standalone)(Eval:Active)(/)(tmos)# list sys folder Tenant-001
sys folder Tenant-001 {
    device-group none
    inherited-devicegroup true
    inherited-traffic-group true
    traffic-group Common/traffic-group-1
}
admin@(ip-10-1-1-4)(cfg-sync Standalone)(Eval:Active)(/)(tmos)#

#The "auth partition Tenant-001" has the correct "Description" value set, but that's not the one used by the GUI:
admin@(ip-10-1-1-4)(cfg-sync Standalone)(Eval:Active)(/Common)(tmos)# list auth partition Tenant-001
auth partition Tenant-001 {
    description Steve is great
}
```

**Comment by caphrim007** [comment]
@danielcayer partitions are != folders. The reason that you are seeing TMUI not display anything is because there is a bug in TMUI.

The equivalent TMSH command will also not work; `tmsh modify auth partition foo description "my description"`.

Email me and I can provide you with the bug ID.

**Comment by danielcayer** [comment]
Thanks Tim. I did try, but could not find this TMUI bug ID you indicated above. The workaround you provided did indeed resolve my problem.
