### ISSUE TITLE
refactor the HAS_* checks to not raise exceptions

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#559]
https://github.com/ansible/ansible/issues/34517#issuecomment-355675866

sivel raised this issue and it requires a change in the module_utils. We need to get rid of the AnsibleF5Client stuff (at least as it pertains to the module params code) and use plain-old AnsibleModule. The bigip client stuff can live in a separate F5Client or similar.

This will be a breaking change for all modules in this repo.

**Comment by delgadillo22** [comment]
Need to sync on effort and breaking changes

**Comment by caphrim007** [comment]
this should now be complete
