### ISSUE TITLE
Add functionality to bigip_asm_policy module

### ISSUE THREAD

**Issue by danielcayer** [F5Networks/f5-ansible#561]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_asm_policy

##### ANSIBLE VERSION

```
  config file = /home/snops/sscssli/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.8
```

##### CONFIGURATION

I commented out the library line in my ansible.cfg file.
```
[root@f5-super-netops] [/home/snops/sscssli] $ cat ansible.cfg
[defaults]
inventory = ./hosts
roles_path = ./roles
#library = ./library
retry_files_enabled = False
[root@f5-super-netops] [/home/snops/sscssli] $
```

##### OS / ENVIRONMENT

"N/A"

##### SUMMARY

1 - Can the bigip_asm_policy module be modified to allow use of custom ASM policy templates? The module currently only allows use of built-in templates.
2- Can the bigip_asm_policy module be augmented to allow creation of a custom ASM policy template? In TMUI, this is achieved by selecting an existing ASM Policy and clicking the "Save as Template..." button. The resulting template can then be referenced when creating new ASM Policies (the "advanced" deployment scenario offered when you create a new ASM policy).

##### STEPS TO REPRODUCE

Using custom ASM policy templates would streamline the configuration for multi-tenant deployments by allowing us to create a new ASM policy by referencing an existing custom policy template already on BIG-IP instead of having to "push" the ASM policy template file each time we create a new ASM policy.
Unfortunately, for the creation of custom "on-box" ASM policy templates, I only know how to do this via TMUI (by clicking the "Save as Template" button in the GUI). I don't know what the corresponding TMSH command would be (can't find documentation or examples).

```

```

##### EXPECTED RESULTS

I would like to create new ASM policies from the same custom template without having to import the same .xml policy file every time.

##### ACTUAL RESULTS

```

```

**Comment by delgadillo22** [comment]
Is this out of scope of what is planned for ASM Policy Support in 2.5.0?

**Comment by caphrim007** [comment]
@delgadillo22 it cant be met for 2.5. It may be do-able for 2.6

**Comment by delgadillo22** [comment]
Ok changing to HIGH to keep visibility for 2.6. Thanks.

**Comment by wojtek0806** [comment]
this will be added to the new asm_policy_management_module , to avoid duplication I will close this and reference it in the proper issue
