### ISSUE TITLE
bigip_policy.py

### ISSUE THREAD

**Issue by agschwind** [F5Networks/f5-ansible#568]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_policy.py
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /....../ansible.cfg
  configured module search path = [u'/....../f5-ansible/library']
  ansible python module location = /...../lib/python2.7/site-packages/ansible
  executable location = /.....l/bin/ansible
  python version = 2.7.14 (default, Dec 11 2017, 14:52:53) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

```

##### PYTHON VERSION

```
Python 2.7.14
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.7

```

##### SUMMARY

In the code line 260 in def _get_builtin_strategy the function returns a strategy using the ansible supplied partition name. All the builtin strategies are on partition /Common. When supplying a partition name on ansible module it will never find the builtin strategies.

```
    def _get_builtin_strategy(self, strategy):
        return '/{0}/{1}-match'.format(
#            self.partition, strategy
            'Common', strategy
        )
```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
thanks @agschwind , will fix

**Comment by delgadillo22** [comment]
wide customer impact?
