### ISSUE TITLE
bigip_virtual_server.py and partition name with numbers

### ISSUE THREAD

**Issue by agschwind** [F5Networks/f5-ansible#569]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server.py
##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### PYTHON VERSION

```
python version = 2.7.14 (default, Dec 11 2017, 14:52:53) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.7

```

##### SUMMARY

When having partition names including numbers they are not handled correctly at some place.
In the code at line 648 the regex does not match numbers, i did change it as follow to get it to work:
        destination = re.sub(r'^/[a-zA-Z**0-9**_.-]+/', '', self._values['destination'])

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@agschwind can you provide an example task that shows the misbehavior?

**Comment by agschwind** [comment]
my vars:
---
partition: "VIEW_VLAN_21"
f5_hostname: "f.q.d.n"
f5_username: "user"

my task file which is called by a with_items loop
---
- name: Create Virtual Servers
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "{{ f5_username }}"
    state: "present"
    partition: "{{ partition }}"
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    destination: "{{ item.destination }}"
    enabled_vlans: "{{item.enabled_vlans }}"
    default_persistence_profile: "{{ item.default_persistence_profile | default(omit) }}"
    irules: "{{ item.irules | default(omit) }}"
    policies: "{{ item.policies | default(omit) }}"
    profiles: "{{ item.profiles | default(omit) }}"
    pool: "{{ item.pool | default(omit) }}"
    port: "{{ item.port }}"
    validate_certs: "no"
  delegate_to: localhost

When creating the Virtual server the first time everything runs correctly but calling the tasks afterwards for modifications will result in an error saying the destination is not a valid IP .
After investigation in the code i've found that the partition is not striped correctly since the regex doesn't match numbers and my partition name contains numbers.

**Comment by caphrim007** [comment]
@agschwind this is the error you're receiving?

```
fatal: [bigip1]: FAILED! => {"attempts": 1, "changed": false, "msg": "The provided destination is not a valid IP address"}
```
