### ISSUE TITLE
add module for bigiq utility licenses

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#581]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by gwolfis** [comment]
I have seen the additional functionality of the module in 2.6 and just wandering if it will be able to support assigning and revoking licenses from a BIG-IQ License Manager as well.

**Comment by caphrim007** [comment]
@gwolfis yes

The modules you currently see in the devel code here for **utility** licenses are not complete. We've completed the ones for **regkey** licenses
