### ISSUE TITLE
bigip_device_trust - delete not working

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#584]
```playbook
- name: Remove device from device trust
    bigip_device_trust:
      server: "{{bigip1_ip}}"
      user: "{{ bigip1_username }}"
      password: "{{ bigip1_password }}"
      peer_server: "{{ bigip2_ip }}"
      peer_hostname: "{{ bigip2_hostname }}"
      peer_user: "{{ bigip2_username }}"
      peer_password: "{{ bigip2_password }}"
      state: absent
      validate_certs: False
    delegate_to: localhost

```

Error:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py", line 342, in <module>
    main()
  File "/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py", line 333, in main
    results = mm.exec_module()
  File "/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py", line 228, in exec_module
    changed = self.absent()
  File "/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py", line 259, in absent
    return self.remove()
  File "/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py", line 265, in remove
    self.remove_from_device()
  File "/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py", line 290, in remove_from_device
    'run', deviceName=self.want.peer_hostname
  File "/usr/lib/python2.7/site-packages/f5/bigip/mixins.py", line 240, in exec_cmd
    self._check_command_parameters(**kwargs)
  File "/usr/lib/python2.7/site-packages/f5/bigip/resource.py", line 274, in _check_command_parameters
    raise MissingRequiredCommandParameter(error_message)
f5.sdk_exception.MissingRequiredCommandParameter: Missing required params: ['name']

fatal: [localhost -> localhost]: FAILED! => {
    "attempts": 1,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py\", line 342, in <module>\n    main()\n  File \"/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py\", line 333, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py\", line 228, in exec_module\n    changed = self.absent()\n  File \"/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py\", line 259, in absent\n    return self.remove()\n  File \"/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py\", line 265, in remove\n    self.remove_from_device()\n  File \"/tmp/ansible_nuCURQ/ansible_module_bigip_device_trust.py\", line 290, in remove_from_device\n    'run', deviceName=self.want.peer_hostname\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/mixins.py\", line 240, in exec_cmd\n    self._check_command_parameters(**kwargs)\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/resource.py\", line 274, in _check_command_parameters\n    raise MissingRequiredCommandParameter(error_message)\nf5.sdk_exception.MissingRequiredCommandParameter: Missing required params: ['name']\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by payalsin** [comment]
error with new code

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: f5.sdk_exception.UnsupportedMethod: Remove_From_Trust does not support the delete method
fatal: [localhost -> localhost]: FAILED! => {"attempts": 1, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wEFZFB/ansible_module_bigip_device_trust.py\", line 342, in <module>\n    main()\n  File \"/tmp/ansible_wEFZFB/ansible_module_bigip_device_trust.py\", line 333, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_wEFZFB/ansible_module_bigip_device_trust.py\", line 228, in exec_module\n    changed = self.absent()\n  File \"/tmp/ansible_wEFZFB/ansible_module_bigip_device_trust.py\", line 259, in absent\n    return self.remove()\n  File \"/tmp/ansible_wEFZFB/ansible_module_bigip_device_trust.py\", line 265, in remove\n    self.remove_from_device()\n  File \"/tmp/ansible_wEFZFB/ansible_module_bigip_device_trust.py\", line 293, in remove_from_device\n    result.delete()\n  File \"/usr/lib/python2.7/site-packages/f5/bigip/resource.py\", line 1154, in delete\n    \"%s does not support the delete method\" % self.__class__.__name__\nf5.sdk_exception.UnsupportedMethod: Remove_From_Trust does not support the delete method\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by caphrim007** [comment]
I believe this is now working per @payalsin's offline comments
