### ISSUE TITLE
bigip_device_connectivity module not found

### ISSUE THREAD

**Issue by bwearp** [F5Networks/f5-ansible#586]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_connectivity

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = <ansible playbook path>/ansible.cfg
  configured module search path = [u'<ansible playbook path>/f5_ansible-master/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       0.0.1645
  Edition     Final
  Date        Tue Jan 31 17:52:56 PST 2017
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.9


```

##### SUMMARY

I copied the example config from:
http://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_device_connectivity_module.html#examples

But it throws an error

##### STEPS TO REPRODUCE

```
  - name: Configure device connectivity for standard HA pair
    bigip_device_connectivity:
      config_sync_ip: 10.1.30.1
      mirror_primary_address: 10.1.30.1
      unicast_failover:
        - address: management-ip
        - address: 10.1.30.1
      server: bigipa.example.com
    delegate_to: localhost
```

##### EXPECTED RESULTS
No error

##### ACTUAL RESULTS
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '~/f5.yaml': line 98, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: Configure device connectivity for standard HA pair
    ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

```

$ ansible-doc bigip_device_connectivity
 [WARNING]: module bigip_device_connectivity not found in: <ansible playbook path>/library:/Library/Python/2.7/site-
packages/ansible/modules

$ ls /Library/Python/2.7/site-packages/ansible/modules/network/f5/
__init__.py			bigip_gtm_datacenter.py		bigip_irule.py			bigip_provision.py		bigip_sys_db.py
__init__.pyc			bigip_gtm_datacenter.pyc	bigip_irule.pyc			bigip_provision.pyc		bigip_sys_db.pyc
bigip_command.py		bigip_gtm_facts.py		bigip_monitor_http.py		bigip_qkview.py			bigip_sys_global.py
bigip_command.pyc		bigip_gtm_facts.pyc		bigip_monitor_http.pyc		bigip_qkview.pyc		bigip_sys_global.pyc
bigip_config.py			bigip_gtm_pool.py		bigip_monitor_tcp.py		bigip_routedomain.py		bigip_ucs.py
bigip_config.pyc		bigip_gtm_pool.pyc		bigip_monitor_tcp.pyc		bigip_routedomain.pyc		bigip_ucs.pyc
bigip_configsync_actions.py	bigip_gtm_virtual_server.py	bigip_monitor_tcp_echo.py	bigip_selfip.py			bigip_user.py
bigip_configsync_actions.pyc	bigip_gtm_virtual_server.pyc	bigip_monitor_tcp_echo.pyc	bigip_selfip.pyc		bigip_user.pyc
bigip_device_dns.py		bigip_gtm_wide_ip.py		bigip_monitor_tcp_half_open.py	bigip_snat_pool.py		bigip_virtual_address.py
bigip_device_dns.pyc		bigip_gtm_wide_ip.pyc		bigip_monitor_tcp_half_open.pyc	bigip_snat_pool.pyc		bigip_virtual_address.pyc
bigip_device_ntp.py		bigip_hostname.py		bigip_node.py			bigip_snmp.py			bigip_virtual_server.py
bigip_device_ntp.pyc		bigip_hostname.pyc		bigip_node.pyc			bigip_snmp.pyc			bigip_virtual_server.pyc
bigip_device_sshd.py		bigip_iapp_service.py		bigip_pool.py			bigip_snmp_trap.py		bigip_vlan.py
bigip_device_sshd.pyc		bigip_iapp_service.pyc		bigip_pool.pyc			bigip_snmp_trap.pyc		bigip_vlan.pyc
bigip_facts.py			bigip_iapp_template.py		bigip_pool_member.py		bigip_ssl_certificate.py
bigip_facts.pyc			bigip_iapp_template.pyc		bigip_pool_member.pyc		bigip_ssl_certificate.pyc

```

**Comment by caphrim007** [comment]
@bwearp this module was not included in Ansible 2.4 (which you have installed). It is included as of Ansible 2.5.

**Comment by bwearp** [comment]
Hi - thanks for replying so fast. 

Silly question - is 2.5 available yet?

Bens-iMac:documentation ben$ sudo -H pip install ansible==2.5
Collecting ansible==2.5
  Could not find a version that satisfies the requirement ansible==2.5 (from versions: 1.0, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0.1, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 2.0.0.0, 2.0.0.1, 2.0.0.2, 2.0.1.0, 2.0.2.0, 2.1.0.0, 2.1.1.0, 2.1.2.0, 2.1.3.0, 2.1.4.0, 2.1.5.0, 2.1.6.0, 2.2.0.0, 2.2.1.0, 2.2.2.0, 2.2.3.0, 2.3.0.0, 2.3.1.0, 2.3.2.0, 2.3.3.0, 2.4.0.0, 2.4.1.0, 2.4.2.0)
No matching distribution found for ansible==2.5

**Comment by caphrim007** [comment]
@bwearp no, but you can install it directly from Ansible's github repository

`pip install --upgrade git+https://github.com/ansible/ansible.git`

the stable version of 2.5 will be released sometime in march

**Comment by caphrim007** [comment]
@bwearp are you good to go?

**Comment by bwearp** [comment]
Hi - yep - perfect thanks!
