### ISSUE TITLE
RFE: bigip_command to have a base path option

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#589]
##### ISSUE TYPE
 - Feature Idea
##### COMPONENT NAME
bigip_command

##### SUMMARY

This option is about doing a cd /<basepath> before running the commands.

Most commands in BIG-IP can specify the full path to the objects it is going to operate. In these case this RFE is strictly necessarily needed. It would be just a convenience.

In the other hand there are some cases where a "cd /partition" or a cd /partition/folder is needed, ie:

```
root@(atom-bigip)(cfg-sync Standalone)(Active)(/Common)(tmos)# cd /openshift
root@(atom-bigip)(cfg-sync Standalone)(Active)(/openshift)(tmos)# load sys config merge file /tmp/l
Loading configuration...
  /tmp/l
root@(atom-bigip)(cfg-sync Standalone)(Active)(/openshift)(tmos)# list ltm rule /openshift/os.multidc 
ltm rule os.multidc {
    partition openshift
    when HTTP_REQUEST {
    log local0. ""
}
}

```

without that first "cd /openshift" the irule would have been loaded in the /Common partition . Having this base path option would be surely helpful for other commands as well.

Thanks

       Ulises

**Comment by caphrim007** [comment]
@alonsocamaro can you provide a generic content for the external monitor file?

**Comment by alonsocamaro** [comment]
@caphrim007 I would like to close this one. Thinking twice about it I think it is not worth it. The first case that I initially mentioned was wrong (it is possible to specify full path) and for the load sys config an alternative is to just use full paths in the config file.

**Comment by caphrim007** [comment]
@alonsocamaro ok np. Closing

**Comment by alonsocamaro** [comment]
@caphrim007 Found a case which cannot be workarounded

```delete <something> all```

ie:

```delete ltm node all```

Cannot specify the partition in the command line AFAIK

**Comment by alonsocamaro** [comment]
@caphrim007 Found another case which I don't find a workaround for

How to list all the nodes in a partition?

```
root@(atom-bigip)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm node /mcd/<TAB>
Configuration Items:
  /mcd/1.1.1.1        /mcd/10.130.0.244   /mcd/10.130.0.251   
```

**Comment by alonsocamaro** [comment]
Thanks Tim!
