### ISSUE TITLE
add support for snmp communities

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#591]
this is part 2 of #552

**Comment by caphrim007** [comment]
@neozoolook what SNMP versions do you want supported?

v1, v2c, and/or v3?

**Comment by neozoolook** [comment]
@caphrim007 v2c & v3 would be ideal.  I don't think anyone is leveraging v1 anymore due to security.

**Comment by caphrim007** [comment]
@neozoolook since BIG-IP seems to have such different parameters for v2c and v3, are you opposed to those parameters existing in the same module if possible? Documentation and examples would be included for the different combinations. Or, would you like them in separate modules?

**Comment by neozoolook** [comment]
@caphrim007 I have no issue with using same module, in fact I think that would probably be ideal as you can just have a parameter for the version, then depending on versions your other parameters are valid or not.

**Comment by caphrim007** [comment]
@neozoolook ok. i will move in that direction then. Thanks for the feedback!
