### ISSUE TITLE
Module to revoke a license

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#602]
There is a new feature is 13.1 to revoke a license through the BIG-IP itself as long as the license is BYOL.
From tmsh, to revoke the license, run the command tmsh revoke sys license.

For more details:
https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ve-setup-vmware-esxi-13-1-0/4.html#guid-d529e0e1-b37c-4e83-a970-fa68b266a6c7

It would be great to have an ansible module to revoke the license. This will come handy in automating end-to-end workflows from spinning up to tearing down a BIG-IP VE and then the end user being able to re-use the same license for the next spin up cycle.

**Comment by chen23** [comment]
Requires SDK support https://github.com/F5Networks/f5-common-python/issues/1357

**Comment by ArtiomL** [comment]
For now, we could potentially use the `bigip_command` module to execute that `tmsh` command from a playbook.

**Comment by caphrim007** [comment]
f5-sdk support has been added afaik

**Comment by caphrim007** [comment]
@payalsin @ArtiomL @chen23 this module would not work with closed-circuit networks; situations where the BIGIP is not connected to the public network. Unless you know differently

**Comment by chen23** [comment]
That is probably true. Not sure there is a sane way to test whether the device can connect to the license server before trying to issue the command.

**Comment by caphrim007** [comment]
@chen23 upon further investigation, my earlier statement may not be entirely true...
