### ISSUE TITLE
bigip_iapp_service module missing file

### ISSUE THREAD

**Issue by rainierpineda2** [F5Networks/f5-ansible#606]
- Bug Report
 
##### COMPONENT NAME
bigip_iapp_service

##### ANSIBLE VERSION

ansible 2.4.0.0
  config file = /home/apined12/f5_ansible/playbooks/ansible.cfg
  configured module search path = [u'/home/apined12/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /data/automation/pylibext/lib/python2.7/site-packages/ansible-2.4.0.0-py2.7.egg/ansible
  executable location = /data/automation/pylibext/bin/ansible
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
11.6.1 and 12.1

##### LIBRARY VERSIONS
bigsuds==1.0.2
f5-sdk==3.0.2

##### OS / ENVIRONMENT
NA

##### SUMMARY
I received this error after an Ansible playbook run using the bigip_iapp_service I downloaded to my local library 
fatal: [labusra5474lb005]: FAILED! => {"failed": true, "msg": "Could not find imported module support code for bigip_iapp_service.  Looked for either F5Client.py or bigip.py"}
fatal: [labusra5474lb004]: FAILED! => {"failed": true, "msg": "Could not find imported module support code for bigip_iapp_service.  Looked for either F5Client.py or bigip.py"}

Where can I find this file and how can I install this module properly?

**Comment by caphrim007** [comment]
@rainierpineda2 you need Ansible 2.5.

This repository constantly tracks the upstream `devel` branch of Ansible. Therefore, changes routinely happen that require the upstream Ansible `devel` branch to be installed. This is one of those changes.

Ansible 2.5 will be released sometime in March.

**Comment by rainierpineda2** [comment]
Thanks Tim. I downloaded this because the version that comes with Ansible 2.4 does not work on tmsh version 12.1.2 HF1, works only on our 11.6.1 box.

**Comment by caphrim007** [comment]
What is the error on version 2.4?

**Comment by rainierpineda2** [comment]
Hi Tim

I get this error. This 12.1.2 box has an ASM but I don’t see what that has to do with my tasks. Do I have to make some modifications on the template to ignore the ASM or is this some other error?

fatal: [labusra5474lb004 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://10.0.64.22:443/mgmt/tm/sys/application/service/\nText: u'{\"code\":400,\"message\":\"{\\\\\"code\\\\\":400,\\\\\"message\\\\\":\\\\\"script did not successfully complete: (can\\'t read \\\\\\\\\\\\\"::asm__use_asm\\\\\\\\\\\\\": no such variable\\\\\\\\n    while executing\\\\\\\\n\\\\\\\\\\\\\"subst $substa_out\\\\\\\\\\\\\"\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"if { [info exists [set substa_in]] } {\\\\\\\\n            set substa_out [subst $$substa_in]\\\\\\\\n            set substa_out [subst $substa_out]\\\\\\\\n        } else {\\\\\\\\n...\\\\\\\\\\\\\"\\\\\\\\n    (\\\\\\\\\\\\\"uplevel\\\\\\\\\\\\\" body line 3)\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"uplevel {\\\\\\\\n        append ::substa_debug \\\\\\\\\\\\\"\\\\\\\\\\\\\\\\n$substa_in\\\\\\\\\\\\\"\\\\\\\\n        if { [info exists [set substa_in]] } {\\\\\\\\n            set substa_out [subst $$substa_in]\\\\\\\\n ...\\\\\\\\\\\\\"\\\\\\\\n    (procedure \\\\\\\\\\\\\"iapp::substa\\\\\\\\\\\\\" line 9)\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"iapp::substa asm_policy($is_v11_4,$do_asm)\\\\\\\\\\\\\"\\\\\\\\n    (procedure \\\\\\\\\\\\\"v11_4_main\\\\\\\\\\\\\" line 454)\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"v11_4_main\\\\\\\\\\\\\"\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"subst $substa_out\\\\\\\\\\\\\"\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"if { [info exists [set substa_in]] } {\\\\\\\\n            set substa_out [subst $$substa_in]\\\\\\\\n            set substa_out [subst $substa_out]\\\\\\\\n        } else {\\\\\\\\n...\\\\\\\\\\\\\"\\\\\\\\n    (\\\\\\\\\\\\\"uplevel\\\\\\\\\\\\\" body line\",\"errorStack\":[]}’"}

**Comment by caphrim007** [comment]
@rainierpineda2 can you email me this playbook, the template, and any other relevant information **offline**? My email is in my github profile.

We can take the bug/problem you see there offline and in the meantime I'll close this issue.

**Comment by caphrim007** [comment]
Tracking in FMFA-2
