### ISSUE TITLE
How to upgrade all F5 ansible moudle ？

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/f5-ansible#609]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### PYTHON VERSION

```
Python 2.7.14
```

##### ISSUE

```
My used the git clone 'https://github.com/F5Networks/f5-ansible.git' to my centos6,Then unzip this file.
I used  "python setup.py install "will output any error.So,How to upgrade my ansible moudle?

[root@localhost f5-ansible]# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to f5_ansible.egg-info/requires.txt
writing f5_ansible.egg-info/PKG-INFO
writing top-level names to f5_ansible.egg-info/top_level.txt
writing dependency_links to f5_ansible.egg-info/dependency_links.txt
reading manifest file 'f5_ansible.egg-info/SOURCES.txt'
writing manifest file 'f5_ansible.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy 'bigip_pool.py': doesn't exist or not a regular file
[root@localhost f5-ansible]# error: can't copy 'bigip_pool.py': doesn't exist or not a regular file
-bash: error:: command not found

```

**Comment by caphrim007** [comment]
@lilongabc to install the modules in this directory requires three things (one of which is documented, but I will document the rest in a follow-up PR). They are,

1. Ensure that the latest copy of ansible `devel` is installed
2. Copy modules to a local location as described here http://clouddocs.f5.com/products/orchestration/ansible/devel/usage/installing-modules.html
3. Additionally, copy the `library/module_utils/network/f5` files to your devel installations similar location.

Lemme know if that helps or if you need more assistance

**Comment by lilongabc** [comment]
Hi caphrim007 

About 3, The  “devel installations similar location” and specific refers to which location? 
From library/module_utils/network/f5 copy to my /etc/ansible/ ?

Thanks for you help.

**Comment by caphrim007** [comment]
@lilongabc it means where ansible is installed. If you are installing as said in #1, then it would be somewhere like `/usr/local/lib/python3.6/site-packages/ansible/module_utils/network/f5`. this may (clearly) be different on your device.

**Comment by caphrim007** [comment]
@lilongabc does this answer your question? Are you good now?

**Comment by lilongabc** [comment]
@caphrim007  Is good,Thank you very much for your help：）
