### ISSUE TITLE
bigip_pool_member : setting a name for the pool member is raising an error

### ISSUE THREAD

**Issue by pcloup** [F5Networks/f5-ansible#614]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool_member
##### ANSIBLE VERSION

"ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]"

##### PYTHON VERSION

"Python 2.7.12"
##### BIGIP VERSION

"[admin@ip-10-0-0-30:Active:Standalone] ~ # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       3.0.1679
  Edition     Hotfix HF3
  Date        Fri Nov 10 23:41:13 PST 2017

Hotfix List
ID638215      ID637141-1  ID639767-1  ID570926     ID563165    ID508113-2
ID578017      ID644817-1  ID605792    ID631715-2   ID578076    ID635688
ID636155      ID642015-4  ID651476-1  ID649048     ID635680-1  ID638556-1
ID643404-1    ID572234-1  ID631688-8  ID600205-1   ID644805    ID648867-1
ID646511-2    ID639530    ID635116-3  ID638629-1   ID629921-3  ID366695-9
ID639630-1    ID627695-1  ID615372    ID636702-4   ID630610-1  ID610201-1
ID647962-1    ID640824-2  ID642090    ID603609-1   ID654368-1  ID642330
ID642211-1    ID638115-1  ID643326    ID632499-2   ID352957-2  ID639565
ID645203-1    ID610485-1  ID636675    ID624722     ID590091-4  ID649617-1
ID639744-3    ID598289    ID649571-2  ID606710-11  ID642058    ID541550-2
ID642874-2    ID569814    ID429213    ID550547-1   ID652151    ID643187-1
ID517756-5    ID648990-1  ID640457-3  ID641013-6   ID636700-1  ID635126-2
ID662108      ID639774-1  ID631572    ID629017     ID652959-1  ID648715-3
ID637308-1    ID608304-2  ID637181-1  ID643328     ID419741-4  ID561596
ID626594-3    ID649369-1  ID636289-1  ID620625-3   ID644490-2  ID630712
ID646719-1    ID632668-6  ID642983-2  ID247527-1   ID639288-1  ID633879-2
ID639406      ID622160    ID625892-1  ID641724     ID643325    ID640352-1
ID636853-4    ID641390-2  ID641083-1  ID639049-1   ID641360-1  ID641547-1
ID569100      ID596924-1  ID615267    ID632060-2   ID552988-1  ID641963
ID642613      ID649933-2  ID610307-4  ID638779     ID640510-2  ID624896-1
ID588414-1    ID635189-1  ID582773    ID638576-1   ID642124    ID647706-1
ID629085-2    ID637664-1  ID640854    ID641482-3   ID626861-1  ID635754-2
ID620659-4    ID417720    ID621379-1  ID635933     ID598024-1  ID638825-1
ID633391-2    ID648056-3  ID639526    ID644855-1   ID633564-1  ID645219
ID642449      ID641169    ID609200-1  ID636613     ID693211-2  ID637094
ID660170-2    ID489499-2  ID621976-5  ID638967-2   ID628337-2  ID651627
ID628164-4    ID627747    ID541320-8  ID367226-3   ID638219    ID642400-3
ID644870      ID639575-2  ID633091    ID664063     ID648786-1  ID639383
ID642221-1    ID642562    ID632504-2  ID638838     ID643330    ID627554-1
ID637847      ID644041    ID594228-1  ID641445-2   ID570855-1  ID640829-1
ID638495-1    ID645805-2  ID572272    ID630611-3   ID619593-1  ID639729-1
ID575642      ID636663    ID559080    ID651106-1   ID630390-1  ID611691-6
ID636016      ID639528    ID637561-2  ID636699-6   ID629752    ID618332-3
ID636790-4    ID643547-2  ID643396-1  ID598002-9   ID642119-1  ID636479
ID635111-1    ID629013    ID643327    ID581746-6   ID621974-5  ID636520-1
ID607246-8    ID620759-3  ID638799-2  ID626386-2   ID561592    ID643752-1
ID611161-4    ID633985-1  ID618430-1  ID623362-1   ID636044-2  ID643332
ID609995-1    ID639764-1  ID641612-1  ID640376-2   ID658764    ID637666-1
ID639500-1    ID633723-4  ID650450    ID638780     ID639486-1  ID608245-1
ID617901-9    ID642926-1  ID610122  
"

##### LIBRARY VERSIONS

"bigsuds==1.0.6
f5-sdk==3.0.10"

##### CONFIGURATION

no change done on ansible cfg of any variable

##### OS / ENVIRONMENT

ubuntu 16.04.3 LTS

##### SUMMARY

when adding a pool memebr to an empty pool, i receive the following error message:

    "msg": "received exception: Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/Pool::add_member_v2()\nException: Common::OperationFailed\n\tprimary_error_code   : 16908342 (0x01020036)\n\tsecondary_error_code : 0\n\terror_string         : 01020036:3: The requested node (/Common/twelvebox_member1) was not found.'"

if i remove the name parameter in the module call, it works (but the pool member is given a default name).

##### STEPS TO REPRODUCE

works perfectly like this:
  - name: Add pool member
    bigip_pool_member:
      server: "{{ my_big_ip }}"
      server_port: 8443
      validate_certs: false
      user: "{{ my_admin }}"
      password: "{{ my_password }}"
      state: "present"
      pool: "twelvebox_pool"
      partition: "{{ my_partition }}"
      host: "{{ my_pool_member1 }}"
      port: "{{ my_pool_member1_port }}"

but not like that (if the twelvebox_member1 node is not existing, of course)
  - name: Add pool member
    bigip_pool_member:
      server: "{{ my_big_ip }}"
      server_port: 8443
      validate_certs: false
      user: "{{ my_admin }}"
      password: "{{ my_password }}"
      state: "present"
      pool: "twelvebox_pool"
      name: “twelvebox_member1”
      partition: "{{ my_partition }}"
      host: "{{ my_pool_member1 }}"
      port: "{{ my_pool_member1_port }}"

```

```

##### EXPECTED RESULTS

"name" should not check if the node with this name exists, as a pool member is a combination of (node + port)
and a node is normally dynamically created if not existing.
here we work with pool members, which are "different" objects, even if they are linked to the node. But creating a pool member is creating a node if not existing. But if existing already, it is not conflicting AFAIK.
their is no need to enforce this node "name" in my opinion
##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@pcloup as I dont actively develop on Ansible 2.4, and we re-wrote that module completely for 2.6, please test with the Ansible devel code and the module in this repository. I dont think it should be raising such an issue anymore.
