### ISSUE TITLE
Docs: stubber.py renamed to f5ansible

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-ansible#615]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
stubber.py

##### SUMMARY

The dev docs reference a tool that no longer exists/renamed?

http://clouddocs.f5.com/products/orchestration/ansible/devel/development/writing-a-module.html#create-the-directory-layout

##### STEPS TO REPRODUCE
```
-bash: devtools/bin/stubber.py: No such file or directory
```

Looks like the new command is:

```
devtools/bin/f5ansible stub module bigip_chen
```

##### EXPECTED RESULTS

stub module

##### ACTUAL RESULTS

file not found

**Comment by caphrim007** [comment]
@chen23 it was renamed

**Comment by caphrim007** [comment]
these docs need to be updated as they are out of date

**Comment by caphrim007** [comment]
docs should now be updated and the stubber named correctly
