### ISSUE TITLE
New Module - Net Timer Policy leveraged in AFM use cases

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#621]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

TBD

##### ANSIBLE VERSION

```
Please target 2.6 release
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### SUMMARY

Currently we have to create timer policies to adjust TTL for services/port list modification in AFM which are used in AFM rule-lists/policies.  This is done to give the rule-list/port-list a different timer with respect to passing traffic, session clean up due to inactivity, etc.

##### STEPS TO REPRODUCE

```
Below is example of how we do this today using bigip_command;

---
- name: Check For Timer-Policy Existence
  bigip_command:
    commands:
      - list net timer-policy {{ item.name }}
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  register: result_net
  delegate_to: localhost
  with_items: "{{ timer_policy }}"

- name: Create For Rule-List
  bigip_command:
    commands:
      - create net timer-policy {{ item.name }} rules add {
           {{ item.rule1_name }} {
            destination-ports add {
              {{ item.rule1_dest_ports }}
            }
            ip-protocol {{ item.rule1_proto }}
            timers add {
              flow-idle-timeout {
                value {{ item.rule1_timeout }}
              }
            }
          }
          {{ item.rule2_name }} {
            destination-ports add {
              {{ item.rule2_dest_ports }}
            }
           ip-protocol {{ item.rule2_proto }}
          timers add {
            flow-idle-timeout {
              value {{ item.rule2_timeout }}
            }
          }
        }
      }
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  when:
    - '"was not found" in result_net.results[ item.index ].stdout|first'
  delegate_to: localhost
  with_items: "{{ timer_policy }}"

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
sdk code added

**Comment by delgadillo22** [comment]
Target release under investigation.

**Comment by caphrim007** [comment]
@neozoolook would you prefer 1 module for this purpose, or two.

The 1 module would allow for specifying the `rules` as a key. Adding/removing rules would require that the entire list be updated.

The two module approach would have one module for the timer policy itself and another module for the rules of the timer policy. Adding and removing rules to the policy would be done like normal modules; `present` and `absent` in a loop.

**Comment by caphrim007** [comment]
note that we've taken the two module approach in other situations (like ltm policies and like AFM policies) so there is some level of established patterns for this already

On the other hand, it bugs me that a timer policy, (the container itself) has so little that is configurable that it borders on the level of offensive that it would be two separate modules.

But...since this is automation....maybe you don't care.

**Comment by neozoolook** [comment]
@caphrim007 I'm fine with the approach of leveraging two separate models if this falls in line with already established development experiences your team has leveraged in AFM.  Honestly it's not a big deal in respect to ansible playbook automation, as we can just sequence with the secondary module once the overall timers are defined as needed.  In fact this may be desirable come to think of it, as it would allow you to run role that just uniformly defines the timers, however using different roles to apply/remove timers as needed in different environments.

**Comment by caphrim007** [comment]
@neozoolook thanks for the feedback. will get started on this right now

**Comment by caphrim007** [comment]
the posted commit is relevant to #622, not this issue. this issue is still under development

**Comment by caphrim007** [comment]
Upon closer examination, I have some reservations about the dual module approach. I think I'm still open to it, but let's try the current single module before we put the work into the second module.

The current module can do everything you should need at the moment.

**Comment by caphrim007** [comment]
re-opening this because i cant make up my mind. looking at the other modules i need to make, like with afm, i'm reconsidering things

**Comment by caphrim007** [comment]
@neozoolook we did some data mining, and discovered that the general use-case of the timer policies is that they tend to not get above 5 rules.

I'm going to close this work as finished, and open a future issue for a separate module to deal with piece-meal injecting rules into a timer policy (as the use cases today dont immediately suggest this is needed).

Interested in your feedback using the current timer policy as well. In particular if piece-meal creation is an absolute requirement of if you too have a limited set of rules that make piece-meal'ing overkill

**Comment by neozoolook** [comment]
@caphrim007 yes I think support of 5 rules initially is more than sufficient for our use cases, I will start to pull this one and test.  Thanks again!

**Comment by neozoolook** [comment]
@caphrim007 looking at the module, it looks like the documentation portion of the module doesn't show any examples on how to add rules and parameters, etc.

**Comment by caphrim007** [comment]
lemme fix that

**Comment by caphrim007** [comment]
@neozoolook try now

**Comment by neozoolook** [comment]
@caphrim007 works perfect! thank you again.
