### ISSUE TITLE
bigip_iapp_service cannot create HTTPS virtual server app

### ISSUE THREAD

**Issue by rainierpineda2** [F5Networks/f5-ansible#630]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_iapp_service

##### ANSIBLE VERSION
ansible 2.4.0.0
  config file = /home/apined12/f5_ansible/playbooks/ansible.cfg
  configured module search path = [u'/home/apined12/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /data/automation/pylibext/lib/python2.7/site-packages/ansible-2.4.0.0-py2.7.egg/ansible
  executable location = /data/automation/pylibext/bin/ansible
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
11.6.1 HF2

##### LIBRARY VERSIONS
bigsuds==1.0.2
f5-sdk==3.0.2

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA
##### SUMMARY
When I run an Ansible script calling bigip_iapp_service using a template JSON file that uses ssl__mode = client_ssl as outlined in the example provided on this link
https://devcentral.f5.com/wiki/iApp.APIRef-f5-http.ashx, the run fails but any normal HTTP VS works

##### STEPS TO REPRODUCE
My Jinja2 template looks like the one posted in the link above. The call is also simple
- name: Deploy F5 http iApp
  bigip_iapp_service:
    name: "{{ item.value.vip_name }}"
    template: "f5.http"
    parameters: "{{ lookup('template', item.key + '.json') }}"
    server: "{{ mgmt_ip }}"
    password: "{{ setup_password }}"
    user: "{{ setup_user }}"
    validate_certs: "no"
    state: "{{ item.value.state }}"
  delegate_to: localhost
  with_dict: "{{ f5_iapp_dict }}"

The dict looks like this:
mgmt_ip: "{{ ansible_host }}"
setup_user: "admin"
directory_path: roles/deploy_iapp/templates
f5_iapp_dict:
  f5.https:
    vip_name: VS_192.168.204.204-443
    vip_ip: 192.168.204.204
    vip_port: 443
    state: present
    members:
      - address: 172.16.100.3
        port: 80
      - address: 172.16.100.4
        port: 80
##### EXPECTED RESULTS
HTTPS VS app created on LTM

##### ACTUAL RESULTS
failed: [labusra5474lb005 -> localhost] (item={'key': u'f5.https', 'value': {u'vip_ip': u'192.168.204.204', u'state': u'present', u'vip_name': u'VS_192.168.204.204-443', u'members': [{u'port': 80, u'address': u'172.16.100.3'}, {u'port': 80, u'address': u'172.16.100.4'}], u'vip_port': 443}}) => {"changed": false, "failed": true, "item": {"key": "f5.https", "value": {"members": [{"address": "172.16.100.3", "port": 80}, {"address": "172.16.100.4", "port": 80}], "state": "present", "vip_ip": "192.168.204.204", "vip_name": "VS_192.168.204.204-443", "vip_port": 443}}, "msg": "400 Unexpected Error: Bad Request for uri: https://10.0.209.86:443/mgmt/tm/sys/application/service/\nText: u'{\"code\":400,\"message\":\"script did not successfully complete: (can\\'t read \\\\\"::pool__mask\\\\\": no such variable\\\\n    while executing\\\\n\\\\\"expr { $advanced && $::pool__mask ne \\\\\"\\\\\"  ? $::pool__mask : [iapp::destination -mask $::pool__addr] }\\\\\"\\\\n    (procedure \\\\\"v11_4_main\\\\\" line 405)\\\\n    invoked from within\\\\n\\\\\"v11_4_main\\\\\"\\\\n    invoked from within\\\\n\\\\\"subst $substa_out\\\\\"\\\\n    invoked from within\\\\n\\\\\"if { [info exists [set substa_in]] } {\\\\n            set substa_out [subst $$substa_in]\\\\n            set substa_out [subst $substa_out]\\\\n        } else {\\\\n...\\\\\"\\\\n    (\\\\\"uplevel\\\\\" body line 3)\\\\n    invoked from within\\\\n\\\\\"uplevel {\\\\n        append ::substa_debug \\\\\"\\\\\\\\n$substa_in\\\\\"\\\\n        if { [info exists [set substa_in]] } {\\\\n            set substa_out [subst $$substa_in]\\\\n ...\\\\\"\\\\n    (procedure \\\\\"iapp::substa\\\\\" line 9)\\\\n    invoked from within\\\\n\\\\\"iapp::substa main($do_v11_3,$upgrade,$downgrade)\\\\\" line:950)\",\"errorStack\":[]}'"}

**Comment by caphrim007** [comment]
@rainierpineda2 which example from that page are you using? the first? or the second?

**Comment by rainierpineda2** [comment]
The second one for HTTPS
Thanks!
Anthony

**Comment by caphrim007** [comment]
@rainierpineda2 does anything change if you use a `file` lookup instead of a `template` lookup?

**Comment by rainierpineda2** [comment]
I have not tried that. Is there an example I can reference?

**Comment by caphrim007** [comment]
@rainierpineda2 its the same syntax that you have except its, `"{{ lookup('file', item.key + '.json') }}"`, and your template needs to be in a `files/` directory instead of a `templates/` directory

**Comment by rainierpineda2** [comment]
Hi Tim
I tried your suggestion below and the HTTPS VS is still not created if ssl__mode is set to client_ssl is set in the template (along with the ssl__encryption_advanced_questions set to yes).
Thanks,
Anthony

**Comment by caphrim007** [comment]
@rainierpineda2 did you ever get this figured out? or should we re-visit?

**Comment by rainierpineda2** [comment]
Hi Tim - I have not tested this in a while becuase I lost access to the F5 device that allows me to test this but the last I checked it stillwasn't working for me. I now have a different use case where the iApp I need to use to use isn't this but another one called iApp Service Discovery using a different template.

**Comment by caphrim007** [comment]
@rainierpineda2 do I close this issue then?

**Comment by rainierpineda2** [comment]
It is unresolved but since I don’t have cycles to validate you may close the issue for now. I will just open a new one if it becomes an issue again

**Comment by caphrim007** [comment]
@rainierpineda2 understood.
