### ISSUE TITLE
Request for Ansible Modules and SDK support for specific new BIG-IQ APIs

### ISSUE THREAD

**Issue by DrewHolland** [F5Networks/f5-ansible#633]
- Feature Idea

##### COMPONENT NAME
Multiple BIG-IQ APIs 

##### ANSIBLE VERSION
```
2.6 target if possible
```

##### BIGIQ VERSION

```
6.0
```

##### SUMMARY
The BIG-IQ team is requesting Ansible module and SDK support for ~35 APIs. Given that most of the APIs have not yet been released I will not list them here but I have been working with Tim Rupp over this and he is aware of the APIs which we are requesting.

**Comment by caphrim007** [comment]
@DrewHolland we need individual issues for the different things you want. One large issue is not how we track work. You can file these on the internal tracker and create stubs to them as issues in this repo.

PM me if you need assistance with that.
