### ISSUE TITLE
LTM profiles for dns, tcp and UDP

### ISSUE THREAD

**Issue by vs926p** [F5Networks/f5-ansible#639]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
modules to support  profiles for dns, tcp and UDP custom profiles. 

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### SUMMARY
Modules to support  profiles for dns, tcp and UDP custom profiles. 
Tmsh commands that we use to create it:
create ltm profile dns DNS-PROFILE enable-dns-express no enable-dnssec no enable-gtm no process-rd no  use-local-bind no process-rd yes enable-dns-firewall yes
~~create ltm profile tcp DNS-TCP idle-timeout 61~~ COMPLETE
~~create ltm profile udp DNS-UDP idle-timeout 31 datagram-load-balancing disabled~~ COMPLETE

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by MichalTaratuta** [comment]
What is the realistic time line for delivery of this module?

**Comment by caphrim007** [comment]
@MichalTaratuta do you want the same configuration options as @vs926p specified in their issue? If not, what other options do you want?

**Comment by caphrim007** [comment]
closing this as requirements from OP have been met. @MichalTaratuta if you have other needs, please file a new issue

**Comment by vs926p** [comment]
I'm getting the following error when I try to use all of the above profiles created as part of this issue. 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name fq_name
fatal: [zrdm6bfdnt01dnt002 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tsy9QN/ansible_module_bigip_profile_dns.py\", line 241, in <module>\n    from ansible.module_utils.network.f5.common import fq_name\nImportError: cannot import name fq_name\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by caphrim007** [comment]
@vs926p you need to make sure you have the most up-to-date (from f5-ansible repo) module_utils files
