### ISSUE TITLE
Support to limit/modify SSL protocols  on sys httpd

### ISSUE THREAD

**Issue by vs926p** [F5Networks/f5-ansible#640]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_device_httpd.py 

##### ANSIBLE VERSION
2.6
```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION
12.x to 13.x

##### LIBRARY VERSIONS

```

```

##### SUMMARY
Need and enhancement to bigip_device_httpd.py  module to support the following configuration for httpd for limiting the SSL ciphers. 

modify /sys httpd ssl-protocol "ALL -SSLv2 -SSLv3"

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@vs926p this already exists https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_device_httpd.py#L82

**Comment by vs926p** [comment]
Thanks. I checked  ansible / lib / ansible / modules / network / f5 / bigip_device_httpd.py  and didn't find it there so opened a request. 

What would be the best way to know what is under development; so that we know and don't open a request for the same?

**Comment by caphrim007** [comment]
@vs926p everything in the f5-ansible repo is under development. Look in the `library/` directory here  before you open a request.
