### ISSUE TITLE
Support DDOS profile creation, modify and applying it to virtual 

### ISSUE THREAD

**Issue by vs926p** [F5Networks/f5-ansible#641]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Support DDOS profile creation, modify and applying it to virtual

##### ANSIBLE VERSION
Please support it as part of 2.6

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### SUMMARY
Support DDOS profile creation, modify and applying it to virtual

Configuring dos
```
create security dos profile DNS-TO-INET-PROFILE protocol-dns replace-all-with {
  DNStoINETProfile {
    dns-query-vector add {
      a {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      aaaa {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      any {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      axfr {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 8000
      }
      cname {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      ixfr {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 8000
      }
      mx {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      ns {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      other {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      ptr {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      soa {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      srv {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
      txt {
        rate-increase 100
        rate-limit 4294967288
        rate-threshold 120000
      }
    }
    prot-err-attack-detection enabled
    prot-err-atck-rate-incr 200
    prot-err-atck-rate-limit 80000
    prot-err-atck-rate-threshold 8000
  }
}
```

Devices
```
modify security dos device-config all log-publisher JSA-HSL-PUBLISHER

modify security dos device-config /Common/dos-device-config {
  dos-device-vector {
    tcp-ack-flood {
      default-internal-rate-limit infinite
      detection-threshold-percent infinite
      detection-threshold-pps infinite
    }
  }
}
```

~~Attaching to LTM virtuals~~ (this is part of profiles, so already complete)
```
create ltm virtual DNS-OUT-ANYCAST-UDP-V4
  destination 155.165.48.0:53
  fw-enforced-policy DNS-SERVERS-TO-SUPPORTZONE-POLICY-V4
  ip-protocol udp
  pool VROUTER-CORE-DIRECT-NET-V4
  profiles replace-all-with {
    DNS-UDP
    DNS-TO-INET-PROFILE DNS-PROFILE
  }
  security-log-profiles replace-all-with {
    HSL-LOGGING-PROFILE
  }
  vlans-enabled  vlans add {
    INT-FW-DNS-TRUSTED
  }
  source-address-translation { type automap }
  translate-address disabled
  translate-port disabled
```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by delgadillo22** [comment]
This is a large item for 2.6.0. 
Can we narrow the scope to "apply existing DDoS profile to virtual" as Phase 1 for consideration into 2.6.0?

**Comment by vs926p** [comment]
As part of all profiles attributes it is taking DDOS profile at virtual level. I tested it.

I will say sooner the better.


​​​​​
Thanks and Regards,

Vivek Shah

**Comment by delgadillo22** [comment]
Can we narrow the scope to "apply existing DDoS profile to virtual" as Phase 1 for consideration into 2.6.0?

And then follow-up with "create & modify" in a later Ansible release?

**Comment by vs926p** [comment]
What are the timelines for next release?

​​​​​
Thanks and Regards,

Vivek Shah

**Comment by delgadillo22** [comment]
Ansible runs on a 5-6 month cycle. 

2.6.0 is expected in August/September.
2.7.0 likely 5 months after 2.6.0.

**Comment by delgadillo22** [comment]
We are dependent on Ansible's release schedule.

**Comment by vs926p** [comment]
Apply plus create would be great if we can have it in 2.6.

​​​​​
Thanks and Regards,

Vivek Shah

From: SHAH, VIVEK
Sent: Monday, February 26, 2018 3:28 PM
To: F5Networks/f5-ansible <reply@reply.github.com>; F5Networks/f5-ansible <f5-ansible@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [F5Networks/f5-ansible] Support DDOS profile creation, modify and applying it to virtual (#641)

What are the timelines for next release?

​​​​​
Thanks and Regards,

Vivek Shah

**Comment by caphrim007** [comment]
For future reference, this is an AFM feature. Security > DoS Protection > DoS Profiles

**Comment by caphrim007** [comment]
@vs926p this feature request is *very* general. Can you pare it down to specifics? The feature set of DoS profiles is huge.

**Comment by caphrim007** [comment]
Reference: FMFA-122

**Comment by vs926p** [comment]
I have the create commands we use in added to the request. Let me know if you need anything more there.

​​​​​
Thanks and Regards,

Vivek Shah

**Comment by caphrim007** [comment]
indeed. I must have missed it when reading. no problem. thanks!

**Comment by neozoolook** [comment]
@vs926p do you have a working playbook leveraging the bigip_command.py to create the DDOS profile?  If so we can probably allow scoping for 2.6 to only add the ability to apply to the virtual as caphrim007 requested.

**Comment by caphrim007** [comment]
@vs926p @neozoolook the properties here (specified in the tmsh command that was posted) are reported by the BIG-IP as "read only" properties. The exact error is.

`Syntax Error: "prot-err-atck-rate-limit" is a read-only property`

* prot-err-attack-detection enabled
* prot-err-atck-rate-incr 200
* prot-err-atck-rate-limit 80000
* prot-err-atck-rate-threshold 8000

are you actually specifying these to create your profile? If so, what version of BIG-IP are you using that accepts this? Also, what platform? VE/Viprion/something else?

**Comment by caphrim007** [comment]
to support 12.x and 13.x, we'll need to use a branching format in the module, much like we do for the GTM modules.

The above mentioned functionality was deprecated insofar as there are no longer tmsh or REST API attributes for these parameters **directly**.

Instead, these parameters have been folded into the other DNS protocol security vectors under the vector named "dns-malformed"

The before and after of this changes means the following

Rate increased by – which is a % - now called detection_threshold_percent.
Rate threshold – which is a number – now called detection_threshold_eps
Rate limit – which is a number – now called mitigation_threshold_eps

**Comment by neozoolook** [comment]
@caphrim007 @vs926p I believe that Vivek is out this week on PTO.  I believe that his work has been relative to the 13.1 code level.  It would be good to support this in 12.1 train as well, but we are making an effort to move our deployments to 13.1 so I think if I was to prioritize I would go that route.  

Does this help you?  Let me know if you need other details/concerns/questions.

Thanks in advance

**Comment by vs926p** [comment]
Hi Tim,

The create commands were provided from 12.x VE configuration as we were on 12.x code then.

We have started to deploy 13.x code in our network. As long as the new module works on 13.x code release we are fine.

For 12.x command we would continue to use bipip cmd module.

​​​​​
Thanks and Regards,

Vivek Shah

**Comment by caphrim007** [comment]
bigip_firewall_dos_profile created. this is used as the container for (what will be) the addition of attack vectors.
