### ISSUE TITLE
pin version of F5-SDK?

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-ansible#644]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Is there any guidance on specific / tested version of the F5 Python SDK to use with specific version of Ansible (i.e. 2.4 vs. 2.5).

**Comment by caphrim007** [comment]
@chen23 for specific versions, no. The recommendation is to install the latest stable release. Moving forward, the F5-SDK is being removed from the Ansible modules. So longer term there will be no such dependency
