### ISSUE TITLE
msg": "Could not find imported module support code for bigip_device_ntp.  Looked for either F5Client.py or bigip.py

### ISSUE THREAD

**Issue by lilongabc** [F5Networks/f5-ansible#648]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

bigip_device_ntp
##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### PYTHON VERSION

```
Python 2.7.14
```

##### BIGIP VERSION

```
 Version     12.1.3
  Build       0.0.378
  Edition     Final

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.10
```

##### ISSUE
```
I used   bigip_device_ntp module  report error.
TASK [initialization : Configure NTP server on BIG-IP] **********************************************************************************************************************************************************************
task path: /etc/ansible/roles/initialization/tasks/main.yaml:2
fatal: [192.168.0.170]: FAILED! => {
    "msg": "Could not find imported module support code for bigip_device_ntp.  Looked for either F5Client.py or bigip.py"
}

```

**Comment by caphrim007** [comment]
@lilongabc if you're using the modules in this repository, they require you to have either

- Ansible 2.5, or
- the module utils from 2.5 copied into your Ansible installation

**Comment by lilongabc** [comment]
@caphrim007 
As far as I know, ansible 2.5 has not been released yet.Roadmap says about March 2018.
How do you install ansible 2.5?
Thanks

**Comment by caphrim007** [comment]
@lilongabc you're correct, it hasnt been released yet. This repo is for development code though, so YMMV when using the modules here.

To install 2.5, you can install the stable-2.5 branch of ansible from github, or, you can download one of the RC tarballs

* pip install --upgrade git+https://github.com/ansible/ansible.git@stable-2.5
* https://github.com/ansible/ansible/releases

**Comment by lilongabc** [comment]
@caphrim007  Thanks for your answer : )
