### ISSUE TITLE
META: Using Github Branches

### ISSUE THREAD

**Issue by clay584** [F5Networks/f5-ansible#67]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

META: Using Github branches

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
12.1.2
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY
Would it be possible for the devs to use a development branch and only move modules to the master branch that are functional.  It is hard to know if a given module is actually fully written/functional if everything is in the master branch with no other branches or tagging being used for this project.

**Comment by caphrim007** [comment]
@clay584 the purpose of this repository is to be for experimental code only. The stable code is upstreamed to ansible core.

**Comment by caphrim007** [comment]
@clay584 after some futher consideration over this, I've decided to take your suggestion. There is now a devel branch that will be used to commit breaking changes. The master branch will track the upstream ansible devel branch and should, therefore, be more stable.

There will also be future tags that pin themselves at releases that, likewise, track ansible's releases

**Comment by clay584** [comment]
Thanks so much!
