### ISSUE TITLE
Virtual server play not accepting string type for port

### ISSUE THREAD

**Issue by rajeshanne** [F5Networks/f5-ansible#675]
##### ISSUE TYPE
 Feature idea
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
 bigip_virtual_server

##### ANSIBLE VERSION

```2.6

```

##### PYTHON VERSION

```2.7

```

##### BIGIP VERSION
 13.1
```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@rajeshanne can you provide a reproduction? strings should be automatically converted to integers.

**Comment by rajeshanne** [comment]
Attached is the log...






Thanks,
Rajesh
________________________________

**Comment by caphrim007** [comment]
@rajeshanne I dont see an error in that output?

Can you provide a simple task that illustrates the problem? You do not need to include any internal addresses or names.

**Comment by rajeshanne** [comment]
Play:
---
- name: Build {{ virt_v4_forwarder_ftp }} Virtual Server
  bigip_virtual_server:
    state: present
    name: "{{ virt_v4_forwarder_ftp }}"
    description: "{{ virt_v4_forwarder_ftp_desc }}"
    destination: "{{ virt_v4_forwarder_ftp_dest }}"
    port: "{{ virt_v4_forwarder_ftp_port }}"
    all_profiles:
      - "{{ virt_v4_forwarder_ftp_profile_0 }}"
      - "{{ virt_v4_forwarder_ftp_profile_1 }}"
    enabled_vlans: "{{ trusted_vlan }}"
    snat: "automap"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost

vars:

virt_v4_forwarder_ftp: FORWARDER-FTP-IPV4
virt_v4_forwarder_ftp_desc: "UE to Internet IPV4 forwarder for FTP"
virt_v4_forwarder_ftp_dest: "0.0.0.0"
virt_v4_forwarder_ftp_port: "ftp"
virt_v4_forwarder_ftp_profile_0: "tcp"
virt_v4_forwarder_ftp_profile_1: "ftp"


error:
fatal:  [f5004 -> localhost]: FAILED! => {"changed": false, "msg": "argument port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: 'ftp'"}
fatal: [f5003 -> localhost]: FAILED! => {"changed": false, "msg": "argument port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: 'ftp'"}

________________________________

**Comment by rajeshanne** [comment]
________________________________

**Comment by caphrim007** [comment]
@rajeshanne this is expected behavior. the port takes a port number, not the name of a service.

**Comment by caphrim007** [comment]
If you want this changed (so that it takes a service name) the list that i'm willing to accept is the same list that tmui presents.

![screen shot 2018-03-20 at 3 27 44 pm](https://user-images.githubusercontent.com/46956/37686129-5e8bc8e8-2c53-11e8-82f8-76c716eb2455.png)

lemme know if this is sufficient

**Comment by rajeshanne** [comment]
Hello Tim,

     we can configure  port to be ftp via cli or gui fine. It is hard to to define ports for complex alg protocols like ftp. It should let accept string is I what i feel.



Thanks,
Rajesh
________________________________

**Comment by caphrim007** [comment]
@rajeshanne is the service list in tmui sufficient? or would you want more.

**Comment by rajeshanne** [comment]
Sufficient Tim.
________________________________

**Comment by delgadillo22** [comment]
Enhancement, not bug.
