### ISSUE TITLE
sys management routes

### ISSUE THREAD

**Issue by delgadillo22** [F5Networks/f5-ansible#676]
##### ISSUE TYPE

Module for sys management routes
Needed for neozoolook

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
duple of #551
