### ISSUE TITLE
'-' in hostname replaced with underscore when adding device trust (bigip_device_trust.py)

### ISSUE THREAD

**Issue by pmilot** [F5Networks/f5-ansible#687]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_trust.py

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /Users/pmilot/ansible/ansible-openshift-origin/ansible.cfg
  configured module search path = [u'/Users/pmilot/ansible/ansible-openshift-origin/library/vsphere_provisioner', u'/Users/pmilot/ansible/ansible-openshift-origin/library']
  ansible python module location = /Users/pmilot/.virtualenv/os/lib/python2.7/site-packages/ansible
  executable location = /Users/pmilot/.virtualenv/os/bin/ansible
  python version = 2.7.14 (default, Jan  6 2018, 12:16:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### PYTHON VERSION
```
Python 2.7.14
```

##### BIGIP VERSION
```
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       0.0.1645
  Edition     Final
  Date        Tue Jan 31 17:52:56 PST 2017
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.13
```

##### CONFIGURATION
"N/A"

##### OS / ENVIRONMENT
"N/A"

##### SUMMARY
When setting up device trust, the '-' (hyphen) character is replaced with underscore by the module.   
So what adding a device with a name such as (bigip-host.domain), the device on the peer will show as (bigip_host.domain), but on the local device with show correctly.

When using bigip_device_group_member after the trust is established will fail since the hostname will not be found.

I believe the issues is with this section:

    def peer_hostname(self):
        if self._values['peer_hostname'] is None:
            return self.peer_server
        regex = re.compile('[^a-zA-Z0-9.\-_]')
        result = regex.sub('_', self._values['peer_hostname'])
        return result

When making this change locally everything works as expected: 

    def peer_hostname(self):
        if self._values['peer_hostname'] is None:
            return self.peer_server
        regex = re.compile('[^a-zA-Z0-9.-_-]')
        result = regex.sub('_', self._values['peer_hostname'])
        return result

##### STEPS TO REPRODUCE
```
Create an HA device group with devices names that contain '-'
```

##### EXPECTED RESULTS
'-' is a valid character for hostnames/dns names.  No need to replace with '_'

##### ACTUAL RESULTS
```
```

**Comment by caphrim007** [comment]
@pmilot the version of ansible that you have installed, 2.5, has this bug

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_device_trust.py#L192

The change that your suggesting is not correct. If you look at the difference between the version you post and the erroneous one (linked above) you'll see that the two regex's are not the same.

The one you post is the correct one, and is what is fixed in (what will become) the ansible 2.6 code. The regex states that if the character is *not* a-z, A-Z, 0-9, -, or _, then replace it with _.

this was fixed in #664 and there are unit tests that illustrate the fix here https://github.com/F5Networks/f5-ansible/blob/devel/test/unit/test_bigip_device_trust.py#L117

**Comment by pmilot** [comment]
@caphrim007 thanks.  

I agree the regex that was in the code looked right, I was not aware this was a ansible bug.  I'll try 2.6.

**Comment by caphrim007** [comment]
@pmilot hold on a moment, the code fixes are not in upstream ansible yet. Suggested method is to get the code from this (f5-ansible) repo until it is upstream. instructions are here 

http://clouddocs.f5.com/products/orchestration/ansible/devel/usage/installing-modules.html#method-1-install-in-a-relative-location-recommended

**Comment by pmilot** [comment]
@caphrim007  Got it.  thx
