### ISSUE TITLE
Setup BIG-IP with static mgmt IP address in Openstack

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/f5-ansible#688]
##### ISSUE TYPE
 - How to?

##### COMPONENT NAME
Instantiate VE in Openstack environment and assign static mgmt IP address - 12.1.x or 13.1.x version

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
VE 12.1.3 or VE 13.1.0.4
```

##### LIBRARY VERSIONS

```

```

##### CONFIGURATION

BIG-IP VE instantiated without any issue, but tmsh command did not work to make any changes to configuration. 

Additionally, do I need patched version for both 12.1.x and 13.1.x? I tried unpatched version 13.1.0.4 and patched version 12.1.x.

Tried both with or without write_files, it seems executed, but i don't see /tmp file created or tmsh command runs. 

- hosts: localhost
  gather_facts: no  

  environment:
    OS_AUTH_URL: http://192.168.1.121:5000/v3
    OS_PROJECT_ID: 160e9ac1bcd34fe087413e828850a51e
    OS_PROJECT_NAME: "demo"
    OS_USERNAME: "demo"
    OS_PASSWORD: "openstack"
    OS_USER_DOMAIN_NAME: "default"

  tasks:
    - name: Create FW Instances
      os_server:
        state: present
        timeout: 500
        name: "test-bigip-ansible"
        image: "BIGIP-13-1"
        key_name: "mykey"
        flavor: "m1.xlarge"
        security_groups: "mgmt-secgroup-nnic"
        auto_ip: no
        nics: 
          - net-id: "4d85448b-0785-41ff-b520-576d1da2cee4"
#          - net-name: "demo-mgmt"
#      register: test-bigip1

        userdata: |
          #cloud-config 
          
          write_files:
            - path: /tmp/onboard.sh
              permissions: 0755
              owner: root:root
              content: |
                #!/bin/bash
                # Logging settings
                LOGGER_TAG="openstack-init"
                LOGGER_CMD="logger -t $LOGGER_TAG"
                
                # insert tag and log
                function log() {
                echo "$1" | eval "$LOGGER_CMD"
                }
                sleep 100
                log "Setting up mgmt IP address ...."
                tmsh modify /sys global-settings mgmt-dhcp disabled
                tmsh modify sys db dhclient.mgmt { value disable }
                tmsh create /sys management-ip 172.16.10.10/24
          
          runcmd:
            - /tmp/onboard.sh &

#          {%- raw -%}#!/bin/bash
#          sleep 300
#          echo "this is a test"
#          tmsh modify sys ntp timezone UTC
#          tmsh modify sys global-settings mgmt-dhcp disabled
#          tmsh delete sys management-ip 192.168.1.245/24
#          tmsh save sys config
#          {% endraw %}

**Comment by caphrim007** [comment]
@firefly2000 this is not an issue with the f5-ansible modules. This is a general bigip question, or openstack question. You may find more help in the f5cloudsolutions.slack.com slack channel.

**Comment by caphrim007** [comment]
One pointer though is that you provided config but no means of executing that config. You need a write_files and runcmd stanza in your cloud config

**Comment by firefly2000** [comment]
Got it working, forgot to enable cloud_drive. Here is updated example: 

- hosts: localhost
  gather_facts: no  

  environment:
    OS_AUTH_URL: http://192.168.1.121:5000/v3
    OS_PROJECT_ID: 160e9ac1bcd34fe087413e828850a51e
    OS_PROJECT_NAME: "demo"
    OS_USERNAME: "demo"
    OS_PASSWORD: "openstack"
    OS_USER_DOMAIN_NAME: "default"

  tasks:
    - name: Create FW Instances
      os_server:
        state: present
        timeout: 500
        name: "test-bigip-ansible"
        image: "BIGIP-13-1"
        key_name: "mykey"
        flavor: "m1.xlarge"
        security_groups: "mgmt-secgroup-nnic"
        auto_ip: no
        nics: 
          - net-id: "4d85448b-0785-41ff-b520-576d1da2cee4"
          - net-name: "demo-mgmt"

        config_drive: yes

        userdata: |
          #cloud-config 
          
          write_files:
            - path: /tmp/onboard.sh
              permissions: 0755
              owner: root:root
              content: |
                #!/bin/bash
                # Logging settings
                LOGGER_TAG="openstack-init"
                LOGGER_CMD="logger -t $LOGGER_TAG"
                
                # insert tag and log
                function log() {
                echo "$1" | eval "$LOGGER_CMD"
                }
                sleep 100
                log "Setting up mgmt IP address ...."
                tmsh modify /sys global-settings mgmt-dhcp disabled
                tmsh modify sys db dhclient.mgmt { value disable }
                tmsh create /sys management-ip 172.16.10.10/24
          
          runcmd:
            - /tmp/onboard.sh &
