### ISSUE TITLE
validate_certs must be one of: yes,no, got: False

### ISSUE THREAD

**Issue by rklomp** [F5Networks/f5-ansible#69]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_provision (and others)

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.12+
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       2.0.204
  Edition     Hotfix HF2
  Date        Fri Oct 21 17:35:48 PDT 2016
```

##### SUMMARY

validate_certs is validated as yes or no, but receives 'true' or 'false'
`FAILED! => {"changed": false, "failed": true, "msg": "value of validate_certs must be one of: yes,no, got: True"}`
`FAILED! => {"changed": false, "failed": true, "msg": "value of validate_certs must be one of: yes,no, got: True"}`

##### STEPS TO REPRODUCE

```
- name: Provision Module
  bigip_provision:
    server: "{{ inventory_hostname }}" 
    user: "{{f5_user}}" 
    password: "{{f5_pass}}"
    module: "afm"
    validate_certs: "yes"
```
Not setting, or setting the validate_certs to yes will give
`FAILED! => {"changed": false, "failed": true, "msg": "value of validate_certs must be one of: yes,no, got: True"}`

Setting it to  no will give
`FAILED! => {"changed": false, "failed": true, "msg": "value of validate_certs must be one of: yes,no, got: False"}`

##### EXPECTED RESULTS

Good execution of module

##### ACTUAL RESULTS

```
Using module file /home/osboxes/ansible2/f5-ansible/library/bigip_provision.py
<****> ESTABLISH LOCAL CONNECTION FOR USER: osboxes
<****> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905 `" && echo ansible-tmp-1486368011.32-161374750578905="` echo ~/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905 `" ) && sleep 0'
<****> PUT /tmp/tmpD3r2sJ TO /home/osboxes/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905/bigip_provision.py
<****> EXEC /bin/sh -c 'chmod u+x /home/osboxes/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905/ /home/osboxes/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905/bigip_provision.py && sleep 0'
<****> EXEC /bin/sh -c '/usr/bin/python /home/osboxes/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905/bigip_provision.py; rm -rf "/home/osboxes/.ansible/tmp/ansible-tmp-1486368011.32-161374750578905/" > /dev/null 2>&1 && sleep 0'
fatal: [****]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "connection": "rest", 
            "level": "nominal", 
            "module": "afm", 
            "password": "*****", 
            "server": "*****", 
            "state": "present", 
            "user": "admin", 
            "validate_certs": true
        }, 
        "module_name": "bigip_provision"
    }, 
    "msg": "value of validate_certs must be one of: yes,no, got: True"
}
```

##### TRIED
Removing `, choices=['yes', 'no']` from line 277, will allow execution, but than module will fail on line 227 with: `AttributeError: 'BigIpRest' object has no attribute '_key'`

I expect this module has never worked

**Comment by caphrim007** [comment]
This is likely caused by not using BOOLEANS in the choices. Your expectation about the bigip_provision module is True.

Also, there is a feature request in BIG-IP to make this "is it provisionable yet?" status reliable. So when that goes GA, this module will require that version of BIG-IP.

Detecting whether bigip is "ready" is currently impossible. So the best we can do is guess and this module inherits those flaws

**Comment by loudsong** [comment]
I just ran into this issue today too:

```
- name: Provision modules
  bigip_provision:
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      user: "{{ bigip_username }}"
      module: "{{ item.key }}"
      level: "{{ item.value }}"
  delegate_to: localhost
  with_dict: "{{ provisioning }}"
```
results in:
```
TASK [tmos_common : Provision modules] *****************************************
task path: /home/awalker/dev/repro_lib/roles/tmos_common/tasks/provision.yml:3
Using module file /home/awalker/dev/repro_lib/f5-ansible/library/bigip_provision.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awalker
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422 `" && echo ansible-tmp-1487373558.71-56087814350422="` echo ~/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422 `" ) && sleep 0'
<localhost> PUT /tmp/tmpt38jxp TO /home/awalker/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422/bigip_provision.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/awalker/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422/ /home/awalker/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422/bigip_provision.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/awalker/dev/repro_lib/bin/python /home/awalker/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422/bigip_provision.py; rm -rf "/home/awalker/.ansible/tmp/ansible-tmp-1487373558.71-56087814350422/" > /dev/null 2>&1 && sleep 0'
failed: [10.3.90.41 -> localhost] (item={'key': u'avr', 'value': u'nominal'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "level": "nominal", 
            "module": "avr", 
            "password": "xxxxxxx", 
            "server": "10.3.90.41", 
            "state": "present", 
            "user": "admin", 
            "validate_certs": true
        }, 
        "module_name": "bigip_provision"
    }, 
    "item": {
        "key": "avr", 
        "value": "nominal"
    }, 
    "msg": "value of validate_certs must be one of: yes,no, got: True"
}

```

**Comment by caphrim007** [comment]
@loudsong @rklomp try this copy https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_provision.py

**Comment by loudsong** [comment]
Still having trouble with that copy too. It looks like it needs `import socket`. Also, the class `BigIpRest` is calling `super(BigIpRest, self).__init__(module)` except that BigIpRest doesn't seem to inherit from another class.

**Comment by rklomp** [comment]
Same here, it is missing some imports

**Comment by caphrim007** [comment]
hey folks, this module needs to see an update as it's not complete and is missing many of the patterns that I've been using in other modules lately.

So I'm only going to monkeypatch fixes into it for now.

So here's @loudsong 's patches in this updated file on devel

https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_provision.py

Lemme know if you're still having issues.

As far as when the next version will be complete, the current Ansible dev cycle is winding down for their 2.3 release. So this will not go in to 2.3. It will have to wait until 2.4

**Comment by rklomp** [comment]
Now getting
`NameError: global name 'connection' is not defined` on line 201

But `test_icontrol` on line 205 will also not exist.

if using rest:
`obj = BigIpRest(module)` will give
`AttributeError: 'BigIpRest' object has no attribute '_key'` on line 132

**Comment by caphrim007** [comment]
@rklomp i'm refactoring this code right now to bring it up to date

**Comment by caphrim007** [comment]
@rklomp and @loudsong I believe the module code has been updated now to make this work.

A couple of things before you make an attempt.

* you need to have an updated F5-SDK installed. You can do this with the command `pip install --upgrade git+https://github.com/F5Networks/f5-common-python.git`
* This module includes boilerplate that is already part of Ansible core. When Ansible 2.4 is released, the code in the devel branch of f5-ansible will change to use that code and unless you have Ansible 2.4 installed, you will see the module in the f5-ansible/devel branch fail to run. I'm keeping it in in the meantime so that you folks can make use of the module. Just be forewarned.

Lemme know if you find any issues with the updated module here it is.

https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_provision.py

**Comment by rklomp** [comment]
@caphrim007 Thanks for the efforts so far!

Now I receive the following error
'<class 'f5.bigip.tm.sys.Sys'>' object has no attribute 'provision'
based on the call on line 233

I am using f5-sdk-2.2.2

**Comment by caphrim007** [comment]
@rklomp like I said in my previous comment, you need an update F5-SDK. See the first bullet above your comment
