### ISSUE TITLE
bigip_facts does not gather facts for profiles or monitors

### ISSUE THREAD

**Issue by Dan0maN** [F5Networks/f5-ansible#700]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

bigip_facts
##### ANSIBLE VERSION

```
All
```

##### PYTHON VERSION

```
N/A
```

##### BIGIP VERSION

```
N/A
```

##### LIBRARY VERSIONS

```
N/A
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The bigip_facts module does not return any information about profiles or monitors.  Looking at the code for the module, these are not supported options for the 'include' parameter, and there appears to be no code to support gathering information for them.
##### STEPS TO REPRODUCE

N/A

```

```

##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

```

```

**Comment by caphrim007** [comment]
@Dan0maN collectively this is 126 different APIs that need to be called (LTM + GTM monitors and LTM profiles).

Can you narrow this request down to the monitors and profiles you are specifically interested in?

**Comment by Dan0maN** [comment]
Sorry.  I meant the most common ones used for basic LTM module functionality.
Profiles:  client-ssl, fasthttp, fastl4, http, one-connect, server-ssl, tcp, udp
Monitors:  external, gateway-icmp, http, https, icmp, tcp, tcp-half-open

**Comment by delgadillo22** [comment]
Upgraded to high priority after consultation with Forrest.

**Comment by caphrim007** [comment]
all requested profiles are now part of the module

**Comment by caphrim007** [comment]
this is now complete

**Comment by amsinha2** [comment]
fix profiles also please ?

**Comment by caphrim007** [comment]
@amsinha2 profiles are part of the fix. the fix is part of ansible 2.7 in the bigip_device_facts module. do you need more profiles than what was mentioned by the OP?
