### ISSUE TITLE
Add an 'all' include parameter option to bigip_facts module

### ISSUE THREAD

**Issue by Dan0maN** [F5Networks/f5-ansible#701]
##### ISSUE TYPE

 - Feature Idea
##### COMPONENT NAME

bigip_facts
##### ANSIBLE VERSION

```
All
```

##### PYTHON VERSION

```
N/A
```

##### BIGIP VERSION

```
N/A
```

##### LIBRARY VERSIONS

```
N/A
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

There are times when you want to know everything about the controller that it is possible to gather.  Please allow an 'all' value for the include parameter that would essentially be the same as adding every possible value to the include parameter.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
this is part of bigip_device_facts now
