### ISSUE TITLE
Request: APM Network Access Module

### ISSUE THREAD

**Issue by realged13** [F5Networks/f5-ansible#707]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/e116173@xyz.com/venv/f5-test/ansible.cfg
  configured module search path = [u'/home/e116173@xyz.com/venv/f5-test/library']
  ansible python module location = /home/e116173@xyz.com/venv/f5-test/lib/python2.7/site-packages/ansible
  executable location = /home/e116173@xyz.com/venv/f5-test/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### PYTHON VERSION

```
2.7.5
```

##### BIGIP VERSION

```
12.1.2 HF2
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.10
```

##### OS / ENVIRONMENT

CentOS

##### SUMMARY
Would like to request a network access module for APM.  Be able to configure both full tunnel and split tunnel configurations.  Primary focused on IPV4 LAN Address Space editing.

##### STEPS TO REPRODUCE

Would be able to route certain IP addresses through the tunnel instead of going out public internet even though it is a public IP address.

```

```

##### EXPECTED RESULTS

Being able to add/remove networks to the network access list.

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
The API required to do this is `/mgmt/tm/apm/resource/network-access`

**Comment by caphrim007** [comment]
Needs APM provisioned
TMUI link is (in 13.1.0.4) Access > Connectivity/VPN > Network Access (VPN) > Network Access Lists

**Comment by caphrim007** [comment]
Here is the place in TMUI that this issue is reflected in.

<img width="546" alt="screen shot 2018-04-13 at 11 10 36 am" src="https://user-images.githubusercontent.com/46956/38750941-5f26497a-3f0b-11e8-93df-a5cda78097d4.png">

**Comment by wojtek0806** [comment]
I think i will work on it, given my APM background :) @caphrim007

**Comment by wojtek0806** [comment]
FMFA-245
