### ISSUE TITLE
add support for configuring tunnels

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#709]
this issue came up during a conversation about using ansible to configure the BIGIP portions of our kubernetes docs. For example,

* http://clouddocs.f5.com/containers/v2/openshift/kctlr-use-bigip-openshift.html
* http://clouddocs.f5.com/containers/v2/openshift/kctlr-openshift-bigip-ha.html#openshift-initial-bigip-setup-ha

On further inspection, there is no tunnel code at all in ansible. This seems like a big oversight, as it should be relevant to bootstrapping of the devices.

**Comment by caphrim007** [comment]
ideally this can be done with a single module, bigip_tunnel. looking at the options for tunnels, the key differentiator is the tunnel profile. based on that value, some extra params appear. it doesn't look like there are so many extra params though that it would require multiple modules

**Comment by caphrim007** [comment]
![screen shot 2018-04-17 at 9 50 21 am](https://user-images.githubusercontent.com/46956/38884529-c7c7dab8-4224-11e8-8e70-7899ac450057.png)

example ui

**Comment by sennerholm** [comment]
Hi!

I'm the person who hade the diskussion with @caphrim007 on Slack. We want to use ansible to set up the F5 <-> F5/Openshift integration. One of the key part of the integration is to set up the VXLAN tunnel. 

We are probably going to demo the integration and how we use ansible to setup some other part on a local user group and it should be a good demo case for booth the Ansible and Openshift integrations if we could make this works well. If I got the code working well I probably also make a pull request for adding them to the dockumentation of the F5/Openshift projekt. 

Sincerely
Mikael

**Comment by caphrim007** [comment]
@delgadillo22

**Comment by chen23** [comment]
FYI, need to capture "secondary" address as well for the tunnel and the ability to select the traffic group.

![image](https://user-images.githubusercontent.com/63689/38886749-dd0af552-4244-11e8-9cf5-a481bde612b4.png)

**Comment by caphrim007** [comment]
@chen23 vxlan-openshit does not appear to be a default profile. is this a special one you created? if not, what version do you see that on?
