### ISSUE TITLE
BIGIQ: Need Ansible Module for: Create a new application from a template

### ISSUE THREAD

**Issue by d-lavigne** [F5Networks/f5-ansible#712]
Workflow Documentation: Create a new application from a template

These APIs are being created for the next release. The APIs for this workflow include

As far as I understand this unit of work, you first list out all the information and templates, then use that to create health rules and application tasks. Given this is a lot of APIs this may be 2 units of work if I am not understanding it correctly, the ADC team can confirm this workflow

**Comment by caphrim007** [comment]
See FMFA-114

**Comment by caphrim007** [comment]
The following application templates were added as part of this issue

* Fast HTTP
* Fast L4 TCP
* Fast L4 UDP
* HTTP
* HTTPS Offload
* HTTPS WAF
