### ISSUE TITLE
BIGIQ: Need Ansible module: Monitor an application

### ISSUE THREAD

**Issue by d-lavigne** [F5Networks/f5-ansible#713]
Workflow documentation: Monitor an Application 

After an application has been created it will be need be monitored using these APIs:

-List Applicationsincluding deploy status (Config Sets)
-List details of existing application (such as AppIQ) (health, active alerts)

These APIs are being built out for the next BIGIQ release and I am not sure of the endpoints yet

**Comment by caphrim007** [comment]
See FMFA-114 and FMFA-115

**Comment by NojanMoshiri** [comment]
This is not necessary, per discussions.
