### ISSUE TITLE
BIGIQ: Need Ansible Module for: Manual Scale-Out / Manual Scale-In

### ISSUE THREAD

**Issue by d-lavigne** [F5Networks/f5-ansible#715]
Manual Scale-Out / Manual Scale-

Get DPSG configuration

GET cm/cloud/data-plane-scaling-group

(as of 2/22; endpoint subject to change – naming currently under discussion with marketing/legal/PM)

Edit DPSG configuration

To manually scale, a simple PATCH is required to indicate how many devices are desired in the DPSG:

PATCH cm/cloud/data-plane-scaling-group/<uuid>

{

    "desiredSize": <number of devices>

}

Value is subject to validation:

mixSize <= desiredSize <= maxSize

**Comment by caphrim007** [comment]
See FMFA-117

**Comment by caphrim007** [comment]
Roman asked me to close this for now until demand for the feature increases
