### ISSUE TITLE
bigip_gtm_server unable to set generic_server as the server_type, it just defaults to bigip, although on running the playbook again it changes it appropriately

### ISSUE THREAD

**Issue by Ramneekkhurana** [F5Networks/f5-ansible#728]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_gtm_server

##### ANSIBLE VERSION

```
root@jumpramneek[app] # ansible --version
ansible 2.5.2
  config file = /app/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
root@jumpramneek[app] #

```

##### PYTHON VERSION

```
root@jumpramneek[app] # python -V
Python 2.7.5

```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.4
  Build       0.0.2
  Edition     Point Release 4
  Date        Tue Apr 10 14:26:02 PDT 2018

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.14

```

##### SUMMARY
Playbook:

       bigip_gtm_server:
         server: "{{ inventory_hostname }}"
         user: "xxxx"
         password: "xxxx"
         validate_certs: no
         transport: rest
         name: WF_NEW
         datacenter: /Common/WF
         server_type: generic-host
         link_discovery: disabled
         virtual_server_discovery: disabled
         devices:
           - name: server_1
             address: 1.1.1.1

ok: [1.1.1.1] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "/Common/WF",
            "devices": [
                {
                    "address": "1.1.1.1",
                    "name": "server_1"
                }
            ],
            "link_discovery": "disabled",
            "name": "WF_NEW",
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "1.1.1.1",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "server": "1.1.1.1",
            "server_port": 443,
            "server_type": "generic-host",
            "state": "present",
            "transport": "rest",
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false,
            "virtual_server_discovery": "disabled"
        }
    }
}

But when you check in F5 server type shows as bigip single

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by Ramneekkhurana** [comment]
Thanks Tim, I have tried new code but it seems like issue still remains.

**Comment by caphrim007** [comment]
@Ramneekkhurana I'm pretty positive that it works. I suspect you're not using the updated file. How did you test it?

**Comment by Ramneekkhurana** [comment]
Thanks mate, I will retest it today and update back.

**Comment by Ramneekkhurana** [comment]
Hello Tim,

Thanks for your help so far I am able to make a lot of progress, I need
some further help, to implement multi tenancy and self service for various
users to manage their resources I am using partitions and I noticed that I
am unable to cross reference resources across partitions.

for example if server is created in /Common, I am unable to create virtual
server in different partition ( /abc )  as it looks for server in /abc and
it unable to find it there.

If possible can we have a call on this so I can explain this better ?

-Thanks
