### ISSUE TITLE
bigip_gtm_virtual_server module, can we please add capability to choose monitors

### ISSUE THREAD

**Issue by Ramneekkhurana** [F5Networks/f5-ansible#729]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_gtm_virtual_server 
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### PYTHON VERSION

```
Python 2.7.5

```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.4
  Build       0.0.2
  Edition     Point Release 4
  Date        Tue Apr 10 14:26:02 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.14

```

##### SUMMARY
It would be really great if we can have ability to choose monitors while creating virtual servers under GTM, same capability exists while creating pool members in GTM.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
this already exists

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_gtm_virtual_server.py#L87

**Comment by Ramneekkhurana** [comment]
Thanks mate, it’s beautiful
