### ISSUE TITLE
bigip_node autopopulate option

### ISSUE THREAD

**Issue by webminster** [F5Networks/f5-ansible#732]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_node

##### ANSIBLE VERSION

```ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sparksa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Any version
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.12
```

##### OS / ENVIRONMENT

Ubuntu Xenial

##### SUMMARY

Really need a way with this module to control the 'autopopulate' and DNS settings of a node.   If the node is used to link to (say) an AWS ELB, you need to make sure the node is created as an ephemeral node, and set up to refresh and autopopulate the FQDN if AWS changes the IP addresses of the FQDN without notice.

The bigip_node module current versions show nodes are created with autopopulate disabled, no options to override.

##### STEPS TO REPRODUCE

Add options to bigip_node to enabled/disable autopopulate, and the "interval" setting (use DNS / interval).

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@webminster can you elaborate on where this is in TMUI (web) interface? I dont see these settings for a node

**Comment by webminster** [comment]
Yes.   I see those settings in the Web interface in Local Traffic/ Nodes, for an FQDN node.  There’s a section “FQDN” with address type, Auto Populate, Interval, and Down Interval.  Trying to attach a screenshot.
-Alan

**Comment by caphrim007** [comment]
@webminster ok thanks, i see it now. will take a look
