### ISSUE TITLE
add modules for HA on bigip

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#74]

**Comment by delgadillo22** [comment]
Ansible for HA Pairing has been on the roadmap for 2.5 for sometime. Originally planned for 2.4.

**Comment by delgadillo22** [comment]
2.5 item?

**Comment by delgadillo22** [comment]
is this done in 2.5.0? (not labeled for 2.5.0 but should have been)

**Comment by caphrim007** [comment]
I think this is complete. There is an example in the `examples` directory which @payalsin verified on a pair of BIG-IPs. I think this can be closed
