### ISSUE TITLE
bigip_virtual_server breaks defining source parameter and having VIP with name

### ISSUE THREAD

**Issue by Fuochi-YNAP** [F5Networks/f5-ansible#751]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
  ansible 2.7.0.dev0
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Wed Feb 21 10:51:40 PST 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.15
```

##### SUMMARY

When the module is used with a specified source parameter AND the VIP has a name, the run breaks.
I think this is because, when a source is specified, it tries to verify that the source and the destination are of the same type. During the process, as stated in your code it tries to get the VIP but it actually checks the name:
```
        # Covers the following examples
        #
        # /Common/2700:bc00:1f10:101::6%2.80
        # 2700:bc00:1f10:101::6%2.80
        # 1.1.1.1%2:80
        # /Common/1.1.1.1%2:80
        # /Common/2700:bc00:1f10:101::6%2.any
        #
```
this is because, if the VIP has a name, you are receiving /PARTITION/VIP_NAME:PORT

##### STEPS TO REPRODUCE

it's quite simple, you just have to add the source parameter in the module and have a destination already set for the virtual server which has a name

##### EXPECTED RESULTS

you are going to receive an unexpected parameter error
##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2741, in <module>
    main()
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2732, in main
    results = mm.exec_module()
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2503, in exec_module
    changed = self.present()
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2517, in present
    return self.update()
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2531, in update
    if not self.should_update():
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2539, in should_update
    result = self._update_changed_options()
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2569, in _update_changed_options
    change = diff.compare(k)
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2173, in compare
    result = getattr(self, param)
  File "/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py", line 2253, in source
    have = netaddr.IPNetwork(self.have.destination_tuple.ip)
  File "/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 928, in __init__
    implicit_prefix, flags)
  File "/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 823, in parse_ip_network
    raise TypeError('unexpected type %s for addr arg' % type(addr))
TypeError: unexpected type <type 'NoneType'> for addr arg

fatal: [f5.example.com -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2741, in <module>\n    main()\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2732, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2503, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2517, in present\n    return self.update()\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2531, in update\n    if not self.should_update():\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2539, in should_update\n    result = self._update_changed_options()\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2569, in _update_changed_options\n    change = diff.compare(k)\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2173, in compare\n    result = getattr(self, param)\n  File \"/tmp/ansible_wmsXSI/ansible_module_bigip_virtual_server.py\", line 2253, in source\n    have = netaddr.IPNetwork(self.have.destination_tuple.ip)\n  File \"/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py\", line 928, in __init__\n    implicit_prefix, flags)\n  File \"/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py\", line 823, in parse_ip_network\n    raise TypeError('unexpected type %s for addr arg' % type(addr))\nTypeError: unexpected type <type 'NoneType'> for addr arg\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

```

**Comment by caphrim007** [comment]
@Fuochi-YNAP please provide a repro of this in the form of an ansible task/playbook

**Comment by Fuochi-YNAP** [comment]
```
---

- name: Create_virtual_server
  bigip_virtual_server:
    name: "{{ server.name }}"
    destination: "{{ vip.addr }}"
#    source: "{{ server.source }}" waiting to be fixed
    description: "{{ server.desc }}"
    port: "{{ server.port }}"    
    provider: "{{ f5 }}"
    partition: "{{ partition }}"
    snat: "{{ server.snat }}"
    address_translation: "{{ server.addr_translation }}"
    enabled_vlans: "{{ server.vlans }}"
    ip_protocol: "{{ server.protocol }}"
    port_translation: "{{ server.port_translation }}"
    pool: "{{ pool.name }}"
    irules: "{{ irule_names }}"
    profiles: "{{ profiles }}"
    policies: "{{asm_policy.name}}"
  delegate_to: localhost
```
@caphrim007 the point is: if {{ vip.addr }} has a name on the big-ip, which is different from the address itself, then the code breaks.

**Comment by wojtek0806** [comment]
@Fuochi-YNAP I have been looking at this issue and I do not understand the problem:

Are you trying to create a VS with a name {{ server.name }} but the VS with that name already exists on BIGIP? 

1. If yes, then the update operation would occur and the parameters that are different between your playbook and the existing VS will be updated, then I can try to use your playbook to verify.

I would need tmsh output of the existing VS config.

2. If not, then explain in detail what exactly you are trying to do, so I can build an example playbook to attempt to replicate this

**Comment by Fuochi-YNAP** [comment]
Hi @wojtek0806,
Thanks for taking this issue.
The problem is related to the check with source and destination parameter. If I remember correctly, you check if the two IPs are of the same type. However, you are supposing that the name of the VIP is the VIP itself. If you check from here, it should be clearer:
https://github.com/F5Networks/f5-ansible/blob/bd1b81ddb62097ca4b1579031be5f7741406435d/library/modules/bigip_virtual_server.py#L1146
Hence, when it's not true that /partition/VIP_NAME:port is the same as /partition/VIP_ADDRESS:port, then the check fails, because you are comparing a string with an IP, and the build breaks.
If you want to replicate this issue you should create a VIP with name that differs from its IP, then try to use the bigip_virtual_server module to create a virtual server using that VIP and specifying the source parameter.
Hope that this is clearer.
Thanks

**Comment by wojtek0806** [comment]
@Fuochi-YNAP I have read through what you said and I am sorry to say this is still unclear?

Name parameter for Virtual Server can be anything and it is unique to each Virtual Server created on the BIGIP. You cannot amend or change it once the Virtual Server is created. So if you provide a virtual server name in the playbook and some other parameters and that server exists it will amend the existing server settings. Moreover if the VS does not exist and you have not specified destination parameter the playbook should fail as destination is required.

I need to see your configuration of the target BIGIP, preferably output of the relevant TMSH commands, and the exact playbook with the values you would use that replicate the issue (not the variables so I do not have to guess what you have in them). Also full untruncated output from the play of the after-mentioned playbook with -vvvv flags set.
```
e.g.
ansible-playbook -i hosts your_playbook.yaml -vvvv
```

**Comment by Fuochi-YNAP** [comment]
@wojtek0806, for that I need time, I opened this issue 5 months ago.
However, I'm not talking about the name of the Virtual Server, The problem is with the name of the Virtual Address.

If there is a virtual address with a real name, like this one:

```
ltm virtual-address VIP_TESTIP {
    address 192.168.1.10
    description "Test IP"
    inherited-traffic-group true
    mask 255.255.255.255
    traffic-group traffic-group-1
}
``` 

Then, if in the ansible playbook the "source" parameter is defined, the playbook breaks as stated in the description. This is because it checks if the "source" and the "destination" are IP addresses of te same type (i.e. both IPv4 or both IPv6). But the check fails because the destination address used for the check is the name (VIP_TESTIP) when it should be the address (192.168.1.10). 
Hence, in order to replicate this issue you should set on your F5 a Virtual Address with a name that differs from the address itself. then, if you run your playbook using that virtual address like this:

``` 
---

- name: Create_virtual_server
  bigip_virtual_server:
    name: "Virtual_test"
    destination: "192.168.1.10"
    source: "192.168.5.1"
    port: "80"    
    provider: "{{ f5 }}"
  delegate_to: localhost
``` 

The playbook will fail because it's going to check if "192.168.5.1" and "VIP_TESTIP" are IP addresses of the same type while "VIP_TESTIP" is not even an address. 
Is it better now?

**Comment by wojtek0806** [comment]
@Fuochi-YNAP thanks for that, that makes much more sense now, will investigate and get back to you

**Comment by wojtek0806** [comment]
@Fuochi-YNAP This is also the case for TMSH, see below for output from TMSH:

````
//reproduction steps in tmsh//

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# create ltm virtual-address tmsh_created address 1.1.1.1 mask 255.255.255.255

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# create ltm virtual-address tmsh_created_2 address 1.1.1.0 mask 255.255.255.0


root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm virtual-address

ltm virtual-address tmsh_created {
    address 1.1.1.1
    inherited-traffic-group true
    mask 255.255.255.255
    traffic-group traffic-group-1
}

ltm virtual-address tmsh_created_2 {
    address 1.1.1.0
    arp disabled
    icmp-echo disabled
    inherited-traffic-group true
    mask 255.255.255.255
    traffic-group traffic-group-1
}

- In TMSH you can specify the IP (and optionally the mask) of the "named" Virtual Address and port:


root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# create ltm virtual tmsh_created_vs destination 1.1.1.0:80 source 2.2.2.2/32

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm virtual tmsh_created_vs

ltm virtual tmsh_created_vs {
    destination tmsh_created_2:http
    mask 255.255.255.255
    profiles {
        fastL4 { }
    }
    source 2.2.2.2/32
    translate-address enabled
    translate-port enabled
    vs-index 48
}


- or the name of the Virtual Address and the port:

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# create ltm virtual tmsh_created_vs_2 destination tmsh_created:80 source 5.5.5.5/32

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm virtual tmsh_created_vs_2

ltm virtual tmsh_created_vs_2 {
    destination tmsh_created:http
    mask 255.255.255.255
    profiles {
        fastL4 { }
    }
    source 5.5.5.5/32
    translate-address enabled
    translate-port enabled
    vs-index 50
}

````
One thing to note:

When you delete Virtual Server after it is created like above, the Virtual Address will also be removed, this is an expected behavior as leaving orphaned Virtual Addresses will lead to situations where BIGIP will respond to ARPs for those IPs even thou they are going nowhere.

I will need to look at implementing this in the Virtual module, so the error you have pointed out would not be raised

**Comment by wojtek0806** [comment]
@Fuochi-YNAP to add to the above, technically you should not be in the business of creating Virtual Addresses on their own as this will lead to network routing and L2 problems, however if you wish to retain this address after Virtual Server is deleted, you could set auto-delete option to false like in the example below, I believe this parameter is a part of virtual-address module already:

```
root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# create ltm virtual tmsh_created_vs destination 1.1.1.0:80 source 2.2.2.2/32

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm virtual-address all-properties
ltm virtual-address 1.1.1.0 {
    address 1.1.1.0
    app-service none
    arp enabled
    auto-delete true
    connection-limit 0
    description none
    enabled yes
    floating enabled
    icmp-echo enabled
    inherited-traffic-group false
    mask 255.255.255.255
    metadata none
    partition Common
    route-advertisement disabled
    server-scope any
    spanning disabled
    traffic-group traffic-group-1
    unit 1
}

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# modify ltm virtual-address 1.1.1.0 auto-delete false

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# delete ltm virtual tmsh_created_vs

root@(33b3fa21-5af7-4942-8751-a1486841dc59)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm virtual-address

ltm virtual-address 1.1.1.0 {
    address 1.1.1.0
    auto-delete false
    mask 255.255.255.255
    traffic-group traffic-group-1
}
```

**Comment by Fuochi-YNAP** [comment]
@wojtek0806 thanks for your reply, I confirm you that you did the correct steps in TMSH to replicate the situation.
I understand that the Virtual Address should be deleted when it's not used.
A use case, when you already have a Virtual Address before creating the virtual server, is when you have different Virtual Servers on different ports.
