### ISSUE TITLE
bigip_selfip module can't add self-ip on management network in different route domain

### ISSUE THREAD

**Issue by lmickey** [F5Networks/f5-ansible#753]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Creating self-ip with bigip_selfip module

##### ANSIBLE VERSION
```
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/ansible/f5-ansible-devel/library/modules']
  ansible python module location = /home/user/virtualenv-15.1.0/Ansible2.5/lib/python2.7/site-packages/ansible
  executable location = /home/user/virtualenv-15.1.0/Ansible2.5/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.1
  Build       0.49.8
  Edition     Engineering Hotfix
  Date        Wed Mar 21 13:49:58 PDT 2018

Hotfix List
ID686906-2    ID707585-1
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.14
```

##### CONFIGURATION
only settings in ansible.cfg are to reverence the experimental modules

##### OS / ENVIRONMENT
Running ansible in a virtual environment

##### SUMMARY
When creating a self-ip in the same subnet as the management interface it is not checking that the self-ip is not in the Common partition/Route domain 0.  This module should allow a self-ip to be created when in the same subnet as management if the route domain is not 0, or it's in a different partition where the default route domain is not 0.

##### STEPS TO REPRODUCE
Reproducing can be done by trying to create a self-ip using the bigip_selfip module that is in the same subnet as the management address but in a different route domain.

##### EXPECTED RESULTS
It should create the self-ip because it's a valid configuration as long as the self-ip is in a different route domain than 0.

##### ACTUAL RESULTS
The self-ip is not created and the command fails.
```
failed: [F5-FWx-01] (item={u'partition': u'Admin', u'ip': u'v6', u'vlan': 1, u'mask': u'ffff:ffff:ffff:ffff::', 
u'allow': u'none', u'address': u'fde1:461a:398a:5afc:ce:a::5', u'type': u'self'}) => {"changed": false,
"item": {"address": "fde1:461a:398a:5afc:ce:a::5", "allow": "none", "ip": "v6", "mask": "ffff:ffff:ffff:ffff::",
"partition": "Admin", "type": "self", "vlan": 1}, "msg": "400 Unexpected Error: Bad Request for uri:
https://[fde1:461a:398a:5afc:ce:a:0:7]:443/mgmt/tm/net/self/\nText:
u'{\"code\":400,\"message\":\"01070392:3: Self IP fde1:461a:398a:5afc:ce:a:0:5 / ffff:ffff:ffff:ffff:::
This IP shares a network with the management IP (fde1:461a:398a:5afc:ce:a:0:7 /
ffff:ffff:ffff:ffff::).\",\"errorStack\":[],\"apiError\":3}'"}
```

**Comment by delgadillo22** [comment]
FMFA-164

**Comment by caphrim007** [comment]
@lmickey do you have a repro task that illustrates this?

**Comment by lmickey** [comment]
huh, seems i did include everything but the task.  Here's the task i was using below, the loop included an ip address on the management subnet but the provided admin partition default route domain was 1 not 0.  I wasn't actually specifying the route domain in the command because the default route domain for the partition is configured.

`    - name: Create Self IPs
      bigip_selfip:
        partition: "{{ item.partition }}"
        address: "{{ item.address }}"
        netmask: "{{ item.mask }}"
        vlan: "{{ vlan_info[item.vlan].name }}"
        name: "{{ vlan_info[item.vlan].name + '-' + item.ip + '-' + item.type }}"
        traffic_group: "{{ traffic_group[item.type] }}"
        allow_service:
          - "{{ item.allow }}"
      loop: "{{ self_ips[host] }}"
      tags: self_ip`
