### ISSUE TITLE
New Module Requested - Modify Sys Disk 

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#756]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

New Module Request - Support for 'modify sys disk' values, etc.

##### ANSIBLE VERSION

```
N/A - Support in future Ansible Release Requested
```

##### PYTHON VERSION

```
2.7
```

##### BIGIP VERSION

```
13.1+ 
```

##### LIBRARY VERSIONS

```
N/A
```

##### SUMMARY

We can support below changes using bigip_command.py, however would be nice to support this with specific module at some point;

modify sys disk directory /var new-size 10485760

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by neozoolook** [comment]
@caphrim007 priority is low, nice to have.

**Comment by caphrim007** [comment]
some notes on this.

* To effect change, this needs to reboot the device.
* Sizes cannot shrink
* There is no REST API, that I am aware of, that can change this, so tmsh over REST will be required.

Output of commands to get disk space is shown below.

```
root@(e5a13d7d-2892-4ed4-9dfe-603bde0a90da)(cfg-sync Standalone)(Active)(/Common)(tmos)# show sys disk directory /var

Directory Name                  Current Size    New Size        
--------------                  ------------    --------        
/config                         3321856         -               
/shared                         20971520        -               
/var                            3145728         10485760        
/var/log                        3072000         -               
/appdata                        26128384        -       
```

Current size will change to New Size value after reboot if it succeeds.

Disk space should not be more than 1.9 TB. It's not clear to me though how to verify that there is enough space before you "pull the trigger" (in case you end up bricking your device).

* https://support.f5.com/csp/article/K14952

**Comment by delgadillo22** [comment]
As of now, item is not on our roadmap due to operational rarity of modifying sys disk.
