### ISSUE TITLE
Upload APM Policy

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-ansible#759]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
APM Import Policy

##### ANSIBLE VERSION
```
Looking to Upload an APM policy (per-session), which I can then reference from an AS3 declaration. Currently AS3 can not upload APM policies remotely, AS3 currently can only attach per-session policies, a module that can upload a per-session policy would give us some parity between the products for larger/security declarations.
```

##### PYTHON VERSION
```
Feature Idea
```

##### BIGIP VERSION
```
12.0+
```

##### SUMMARY
Feature idea for ASM parity

**Comment by jmcalalang** [comment]
Checkout ng_import, ng_export and ng_profile…
 
[root@I2800-R16-S35:Active:Standalone] config # ng_import
 
Incorrect arguments: <templatefile.conf.tar.gz> or <new_name> is not specified
 
Access Profile/Policy Access Import utility v12.1
Usage: ng_import [-s] <templatefile.conf.tar[.gz]> <new_name> [-p|-partition <partition>]
 
[root@I2800-R16-S35:Active:Standalone] config # ng_export
 
Incorrect arguments: <name> or <filename> is not specified
 
Access Profile Export utility v12.1
 
Usage: ng_export [-t|-type access_policy] <name> <filename> [-p|-partition <partition>]
       exported profile would be saved as /tmp/type-<filename>.conf.tar.gz
 
[root@I2800-R16-S35:Active:Standalone] config # ng_profile
 
Incorrect arguments: action is not specified
 
Profile/Policy Management Tool
Usage: ng_profile [-partition|-p <partition_name>] [-type|-t <type>] -command cparams
 
       -p <partition_name> or -partition <partition_name>: operating partition. Default: Common
       -t <type> or -type <type>: access_profile or policy_access. Default: access_profile
       -command: -list, -deleteall, -deletelisted, -copy
       cparams: see examples
 
ng_profile [-p <p>] [-t <t>] -list <name>[ <name_2>...]                     lists all shareable objects.
ng_profile [-p <p>] [-t <t>] -deleteall <name>[ <name_2>...]                deletes all shareable objects.
ng_profile [-p <p>] [-t <t>] -deletelisted <filename> <name>[ <name_2>...]  deletes only shareable objects listed in /tmp/filename.
ng_profile [-p <p>] [-t <t>] -copy <existing_name> <new_name>               copies object under exisiting_name and heirs to new_name.
[root@I2800-R16-S35:Active:Standalone] config #

**Comment by wojtek0806** [comment]
APM uses external tools to import/export policy, those were never mapped to the REST API as there are no TMSH equivalents.  I have found however some endpoints in 13.1.0.7 but given there is very little documentation on them I need to do some digging. In short v12.x would require the usage of REST bash command endpoint to import/export APM policies, for v13.x  it needs verification as there are new tmsh commands for apm policy

**Comment by caphrim007** [comment]
@wojtek0806 it does not concern me to use the ng_* tools via bash over rest. That was my plan from the beginning

**Comment by wojtek0806** [comment]
yes i know, I need to check something cause I remember this tool having some issues, gotta talk to some SMEs in ES. I want to also discuss something with you, lets take this to Slack @caphrim007

**Comment by ymartin59** [comment]
Hello. What are plans for this new module delivery?

**Comment by delgadillo22** [comment]
No committed plans at this time, still investigating.

**Comment by atechnicnate** [comment]
How is the investigation into this going? I specifically have another customer that would like to be able to create an apm policy-item, access-policy and profile because those commands fail if not all called within the same session so the bigip_command module doesn't offer a reliable workaround.  Any thoughts on a proposed timeline?

create apm policy policy-item
create apm policy access-policy
create apm profile access

**Comment by C0missar** [comment]
I'm looking to just do APM policy export/import, not policy manipulation, but it's a pretty important issue for us.  TMOS v13.1.1.

Stan
