### ISSUE TITLE
partition cross reference among different resources

### ISSUE THREAD

**Issue by Ramneekkhurana** [F5Networks/f5-ansible#766]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Pool member

##### ANSIBLE VERSION
2.7
```

```

##### PYTHON VERSION
2.7
```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@Ramneekkhurana does this answer your question?

**Comment by Ramneekkhurana** [comment]
Thanks very much mate it helped a lot I am able to build what I wanted up to some extent

**Comment by caphrim007** [comment]
closing, per the OP's comment above
