### ISSUE TITLE
Different responses from bigip_command for create operations

### ISSUE THREAD

**Issue by tdm00** [F5Networks/f5-ansible#785]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`bigip_command`

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /var/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### CONFIGURATION

```
[defaults]
inventory = ./hosts

```

##### OS / ENVIRONMENT

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

##### SUMMARY

I have two different tasks that use the bigip_command module to execute create actions. The first time I run the playbook and the configuration objects are created everything completes successfully. The second time I run the playbook the first create command returns the `changed` output, even though the configuration object already exists, and the second create command returns the `fatal` output.

##### STEPS TO REPRODUCE

```
- name: First - create CLI alias
  bigip_command:
    commands:
      - create /cli alias shared build_configlet { command 'load /sys config from-terminal merge' }
      - create /cli alias shared sync_device_to_bside { command 'save /sys config partitions all; run /cm config-sync to-group device-group-1' }
  delegate_to: localhost


- name: Second - create AVR statistics logging
  bigip_command:
    commands:
      - create /sys log-config destination management-port AVR_to_Loginsight { ip-address 1.1.1.1 port 514 protocol udp }
      - create /sys log-config destination remote-syslog syslog_for_avr { format rfc5424 remote-high-speed-log AVR_to_Loginsight }
      - create /sys log-config publisher loginsight_avr_publisher { description "AVR statistics logging to Loginsight" destinations replace-all-with { syslog_for_avr { } } }
  delegate_to: localhost

```

##### EXPECTED RESULTS

I would expect to have identical results on any subsequent runs of the playbook when the configuration object already exists, preferably the first one as that doesn't produce a fatal error that aborts the playbook from running. That said, this may be an issue with the response from the BIG-IP system itself and how Ansible is interpreting it. I may add a preceding task to check for the presence of the configuration object before using the bigip_command to create it as a way to fake idempotency and work around this issue for now.

Knowing that bigip_command is a stop-gap measure, I have filed issues #782 and #770 to have **real** modules created[[1]](https://docs.ansible.com/ansible/latest/modules/bigip_command_module.html#synopsis) for these two tasks.

##### ACTUAL RESULTS

```
TASK [common : Create CLI Alias] *******************************************************
 [WARNING]: Using "write" commands is not idempotent. You should use a module that is
specifically made for that. If such a module does not exist, then please file a bug. The
command in question is "create /cli alias shared build_configlet..."

 [WARNING]: Using "write" commands is not idempotent. You should use a module that is
specifically made for that. If such a module does not exist, then please file a bug. The
command in question is "create /cli alias shared sync_device_to_..."

changed: [192.168.1.230 -> localhost]
changed: [192.168.1.231 -> localhost]

TASK [common : Create AVR statistics logging to Loginsight] ********************************
fatal: [192.168.1.230 -> localhost]: FAILED! => {"changed": false, "msg": "01020037:3: The requested log destination management port (/Common/AVR_to_Loginsight) already exists."}
fatal: [192.168.1.231 -> localhost]: FAILED! => {"changed": false, "msg": "01020037:3: The requested log destination management port (/Common/AVR_to_Loginsight) already exists."}

```

**Comment by caphrim007** [comment]
@tdm00 the reporting of `changed` in this module is (intentionally) a bit undefined.

The module reports `changed`-ness if any of the commands are of the "write variety". Therefore, if you include any mention of the `create`, `modify` or `delete` commands, the module will report changed.

This is because tmsh itself has no well-defined meaning of changed-ness. It varies by command, and there are thousands of commands. We *could* begin adding some work to the module though that picks apart some of these common values (as you have evidenced above). This might alleviate some of the pain, but certainly not all. It would provide a foundation to easing more pain in the future though.

**Comment by caphrim007** [comment]
@tdm00 I've added prelim code to support this level of changed-ness checking (using your two examples). Have a try
