### ISSUE TITLE
Add module to manage file

### ISSUE THREAD

**Issue by agschwind** [F5Networks/f5-ansible#786]
Hi,

It would be great to have a module to handle files, upload and download and to manage iFiles.
Or is there may be an alternate method to do this.

Thanks a lot.
rgds,
Arsène

**Comment by caphrim007** [comment]
@agschwind I'm not familiar with how this feature is used in environments. Can you provide me with any examples on the kinds of files you put in ifiles?

You can PM me at my email address in my GitHub profile if necessary

**Comment by agschwind** [comment]
Hi,
We need to upload html and css files to be able to produce a page like a maintenance web page when target servers are not available or in case we have a maintenance window.
Those files are uploaded using System -> File Management -> IFile List and then we create iFiles for LTM using Local Traffic -> IRules -> IFile List.
The LTM IFiles are then used in IRules to present those page when necessary.
Next to them we also use the same method for a customized Login landing page.

Hope my explanation is clear enough.
rgds,
Arsene

**Comment by caphrim007** [comment]
thanks! that helps!

**Comment by focrensh** [comment]
Due the default ansible modules of Copy or Template work for this function?
[Copy](https://docs.ansible.com/ansible/2.6/modules/copy_module.html)
[Template](https://docs.ansible.com/ansible/2.6/modules/template_module.html)

**Comment by caphrim007** [comment]
it is not sufficient to use the `copy` or `template` modules because mcpd needs to know about the file and, to do this, it needs to be added via proper channels (rest, tmsh, etc). This process also stashes the file itself into the /config/filestore sub directory tree.

kinda a bummer, but it seems we need to create a module for this purpose. :-(
