### ISSUE TITLE
bigip_policy_rule.py extension

### ISSUE THREAD

**Issue by agschwind** [F5Networks/f5-ansible#787]
Hi,
I've extend bigip_policy_rule.py with additional action and options, is it possible to upload it so it may be integrated into the distribution?

Thanks.
rgds,
Arsène

**Comment by caphrim007** [comment]
@agschwind to make the contribution part of the f5 modules requires that you fill out an submit the CLA that is provided here

https://clouddocs.f5.com/products/orchestration/ansible/devel/development/cla-landing.html

After that, you can create a PR here as one normally would on Github projects.
