### ISSUE TITLE
bigip_profile_tcp custom settings

### ISSUE THREAD

**Issue by MichalTaratuta** [F5Networks/f5-ansible#809]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_profile_tcp

##### ANSIBLE VERSION

```
2.6
```

##### SUMMARY

How to edit fields in the setting section of profile?

##### ACTUAL RESULTS

```
I would like to be able to create a custom profile, with ability to set custom settings. (i.e.  Insert X-Forwarded-For) 
It looks like at the moment **bigip_profile_tcp** module doesn't allow such things.

Is there any plan to do this?
```

**Comment by delgadillo22** [comment]
Interesting idea nice to have

**Comment by caphrim007** [comment]
@MichalTaratuta what custom settings do you want. there are 75 such settings in a TCP profile and we historically have no spent time to add all features to all modules because not all features are used by all ansible customers.

If you can identify the settings you want, then we can add them.

**Comment by wojtek0806** [comment]
@MichalTaratuta can you update please?

**Comment by wojtek0806** [comment]
@MichalTaratuta have you had a chance to look at this ?

**Comment by caphrim007** [comment]
closing due to lack of response from OP. @MichalTaratuta if this is still needed, you can open a new issue and specify the relevant setting(s) you want to configure.
