### ISSUE TITLE
bigip_pool_member cannot add existing node to a pool

### ISSUE THREAD

**Issue by lukaszsedek** [F5Networks/f5-ansible#823]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool_member

##### ANSIBLE VERSION

```
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/lsedek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lsedek/bigip/env/lib/python2.7/site-packages/ansible
  executable location = /home/lsedek/bigip/env/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### PYTHON VERSION

```
Python 2.7.15

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.2
  Build       0.0.6
  Edition     Point Release 2
  Date        Tue Jan 16 08:46:28 PST 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18

```

##### SUMMARY

bigip_pool_member module is able to create new node, but when I try to run the same playbook once again it throws an error "msg": "The specified 'address' value is not a valid IP address.". I tested many combinations and looks like bigip_pool_member cannot add a node to the pool when the node already exists.

##### STEPS TO REPRODUCE

Best way to reproduce the issue is to create a nody using bigip_node module and try to add this node to a pool in next step. 

```
    - name: Add new node 
      bigip_node:
        user: "{{ username }}"
        password: "{{ password }}"
        server: "{{ ansible_host }}"
        server_port: "{{ ansible_port | default('443') }}"
        validate_certs: no
        transport: rest
        provider: "{{ provider }}"
        state: present
        partition: "ABC_TST_HS"
        host: 8.8.8.8
        name: "NODE_8.8.8.8"
      delegate_to: localhost 
    
    
    - name: Create new BIG IP POOL
      bigip_pool:
        provider: "{{ provider }}"
        state: present
        name: "POOL_TEST_80"
        partition: "ABC_TST_HS"
        lb_method: least-connections-member
        server_port: 80
      delegate_to: localhost

     

    - name: Add pool members to BIGIP POOL
      bigip_pool_member:
        provider: "{{ provider }}"
        state: present
        partition: "ABC_TST_HS"
        pool: "POOL_TEST_80"
        reuse_nodes: yes
        host: "8.8.8.8"
        name: "NODE_8.8.8.8"
        port: 80
      delegate_to: localhost
```

Another way to reproduce is to run the same bigip_pool_member module twice. 

##### EXPECTED RESULTS

If a node exists, it should be added/updated to the pool. It works in ansible 2.5. 

##### ACTUAL RESULTS

```
TASK [Add new node] **********************************************************************************************************************************************************************************************
task path: /home/lsedek/bigip/test.yml:43
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: lsedek
<localhost> EXEC /bin/sh -c 'echo ~lsedek && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483 `" && echo ansible-tmp-1533023177.8-251279073168483="` echo /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483 `" ) && sleep 0'
Using module file /home/lsedek/bigip/env/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_node.py
<localhost> PUT /home/lsedek/.ansible/tmp/ansible-local-4071HE_jlS/tmpDI8XZF TO /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483/bigip_node.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483/ /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483/bigip_node.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/lsedek/bigip/env/bin/python2 /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483/bigip_node.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/lsedek/.ansible/tmp/ansible-tmp-1533023177.8-251279073168483/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'transport' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server_port' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'validate_certs' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
changed: [lb0 -> localhost] => {
    "changed": true, 
    "fqdn": {
        "autopopulate": "enabled", 
        "downInterval": "5", 
        "interval": "3600"
    }, 
    "fqdn_address_type": "ipv4", 
    "fqdn_auto_populate": "enabled", 
    "fqdn_down_interval": "5", 
    "fqdn_up_interval": "3600", 
    "invocation": {
        "module_args": {
            "address": "8.8.8.8", 
            "description": null, 
            "fqdn": null, 
            "fqdn_address_type": null, 
            "fqdn_auto_populate": null, 
            "fqdn_down_interval": null, 
            "fqdn_up_interval": null, 
            "host": "8.8.8.8", 
            "monitor_type": null, 
            "monitors": null, 
            "name": "NODE_8.8.8.8", 
            "partition": "ABC_TST_HS", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "//cut//", 
                "server_port": //cut//, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "//cut//", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "server": "//cut//", 
            "server_port": //cut//, 
            "state": "present", 
            "transport": "rest", 
            "user": "//cut//", 
            "validate_certs": false
        }
    }, 
    "session": "user-enabled", 
    "state": "user-up"
}

TASK [Create new BIG IP POOL] ************************************************************************************************************************************************************************************
task path: /home/lsedek/bigip/test.yml:59
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: lsedek
<localhost> EXEC /bin/sh -c 'echo ~lsedek && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662 `" && echo ansible-tmp-1533023179.33-94124657207662="` echo /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662 `" ) && sleep 0'
Using module file /home/lsedek/bigip/env/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool.py
<localhost> PUT /home/lsedek/.ansible/tmp/ansible-local-4071HE_jlS/tmphLefM9 TO /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662/bigip_pool.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662/ /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662/bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/lsedek/bigip/env/bin/python2 /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662/bigip_pool.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/lsedek/.ansible/tmp/ansible-tmp-1533023179.33-94124657207662/ > /dev/null 2>&1 && sleep 0'
changed: [lb0 -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "description": null, 
            "lb_method": "least-connections-member", 
            "metadata": null, 
            "monitor_type": null, 
            "monitors": null, 
            "name": "POOL_TEST_80", 
            "partition": "ABC_TST_HS", 
            "password": null, 
            "priority_group_activation": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "//CUT//", 
                "server_port": 4423, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "lukasz", 
                "validate_certs": false
            }, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": null, 
            "server_port": 80, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "lb_method": "least-connections-member", 
    "name": "POOL_TEST_80", 
    "partition": "ABC_TST_HS", 
    "priority_group_activation": 0
}

TASK [Add pool members to BIGIP POOL] ****************************************************************************************************************************************************************************
task path: /home/lsedek/bigip/test.yml:71
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: lsedek
<localhost> EXEC /bin/sh -c 'echo ~lsedek && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160 `" && echo ansible-tmp-1533023180.49-33444223642160="` echo /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160 `" ) && sleep 0'
Using module file /home/lsedek/bigip/env/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_pool_member.py
<localhost> PUT /home/lsedek/.ansible/tmp/ansible-local-4071HE_jlS/tmp6rktU1 TO /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160/bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160/ /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/lsedek/bigip/env/bin/python2 /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/lsedek/.ansible/tmp/ansible-tmp-1533023180.49-33444223642160/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_jcFSQr/ansible_module_bigip_pool_member.py", line 904, in main
    results = mm.exec_module()
  File "/tmp/ansible_jcFSQr/ansible_module_bigip_pool_member.py", line 622, in exec_module
    changed = self.present()
  File "/tmp/ansible_jcFSQr/ansible_module_bigip_pool_member.py", line 647, in present
    return self.create()
  File "/tmp/ansible_jcFSQr/ansible_module_bigip_pool_member.py", line 759, in create
    if self.want.name and not any(x for x in [self.want.address, self.want.fqdn_name]):
  File "/tmp/ansible_jcFSQr/ansible_module_bigip_pool_member.py", line 440, in address
    "The specified 'address' value is not a valid IP address."

fatal: [lb0 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "address": "8.8.8.8", 
            "connection_limit": null, 
            "description": null, 
            "fqdn": null, 
            "fqdn_auto_populate": null, 
            "host": "8.8.8.8", 
            "monitor_state": null, 
            "name": "NODE_8.8.8.8", 
            "partition": "ABC_TST_HS", 
            "password": null, 
            "pool": "POOL_TEST_80", 
            "port": 80, 
            "preserve_node": null, 
            "priority_group": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "//cut//", 
                "server_port": //cut//, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "//cut//", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "reuse_nodes": true, 
            "server": null, 
            "server_port": null, 
            "session_state": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "The specified 'address' value is not a valid IP address."
}

```

**Comment by caphrim007** [comment]
@lukaszsedek what version of Ansible are you using?

There have been some changes made to fix issues like this in recent work within this repository. Are you able to try the module in this repository to see if it works?

**Comment by rfults** [comment]
Having the similar (if not the same) issue in ansible 2.6.2 with the following libs:

bigsuds==1.0.6
f5-sdk==3.0.18

Error:

 u'{"code":400,"message":"0107003a:3: Pool member node (/Common/192.168.1.50) and existing node (/Common/TESTNODE) cannot use the same IP Address (192.168.1.50).","errorStack":[],"apiError":3}'

**Comment by rfults** [comment]
@caphrim007 went ahead and deleted existing nodes then recreated them with this module instead.

**Comment by caphrim007** [comment]
@lukaszsedek I've included a set of integration tests using your example and am unable to re-produce this issue. I suspect it is due to an out-of-date (relative to the code in this repo) version of bigip_pool_member.

If you can reproduce it using the code in this repository, then I'd be happy to take another look. Otherwise, see the integration test in this commit https://github.com/F5Networks/f5-ansible/commit/f449bc4c52a8ff26dc828aa0db430afbae4cc56d

**Comment by lindeskar** [comment]
I have a very similar issue and think I've pinpointed the root cause, at least in our environment.

When adding existing nodes to a pool, **and the route domain is not 0**, the IP-address returned is `x.x.x.x%y` - where `y` is the route domain ID.

In the call to [`is_valid_ip`](https://github.com/F5Networks/f5-ansible/blob/673286e285ba9e2656af72adf7ed33e6f2379ab9/library/modules/bigip_pool_member.py#L387) in `bigip_pool_member` the input does not seem to be cleaned from `%y`. Which makes the function return false and `F5ModuleError` to be raised like above.

Also, the error cannot be reproduced in a device with only one route domain.

--

I'm using the devel modules as described [here](https://clouddocs.f5.com/products/orchestration/ansible/devel/usage/installing-modules.html) with Ansible 2.6.2, f5-sdk 3.0.18, and Python 2.7.12.

--

@lukaszsedek Is the existing nodes you're adding in a route domain other than 0?

@caphrim007 Can the issue be reopened, or should we create a new one? Sorry, but I'm new to the Github workflow.

**Comment by caphrim007** [comment]
@lindeskar let's file a new issue so that I can track it in the issue files I create to identify fixes

**Comment by lukaszsedek** [comment]
@lindeskar That might the the idea. I use partitions and inside each partition there is non-zero default route domain.

**Comment by lindeskar** [comment]
@caphrim007 @lukaszsedek Thanks! Issue #887 created

**Comment by amsinha2** [comment]
hey, this is causing a problem for us right now, any eta on a fix ?

**Comment by lukaszsedek** [comment]
I dived deeper into this issue and it seems like there's an issue with `reuse_node` parameter inside bigip_pool_member. 

[https://docs.ansible.com/ansible/latest/modules/bigip_pool_member_module.html#bigip-pool-member-module](https://docs.ansible.com/ansible/latest/modules/bigip_pool_member_module.html#bigip-pool-member-module)

I changed this parameter value to 'no' and it started working. Now I can use an existing node definition inside a pool. Rationally this param value should be opposite. If you want to reuse a node, it should be 'yes'.

**Comment by JapaneseMuscleDE** [comment]
Hi Lukas,

were you able to use the Name of the node as well?

If I want to use the nodename I get following error.

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "'name' is neither a valid IP address or FQDN name."}`

and my Playbook contains following code

`    - name: Add Member to Pool
      bigip_pool_member:
        server: f5-ltm
        user: admin
        password: ansible
        server_port: 443
        name: nd_192-168-1-241
        partition: Common
        pool: pl_ANS01_01
        reuse_nodes: no
        port: 80
        state: present
        validate_certs: no
`

If I change the name to the IP of the node I get

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "400 Unexpected Error: Bad Request for uri: https://f5-ltm:443/mgmt/tm/ltm/pool/~Common~pl_ANS01_01/members/\nText: u'{\"code\":400,\"message\":\"0107003a:3: Pool member node (/Common/192.168.1.241) and existing node (/Common/nd_192-168-1-241) cannot use the same IP Address (192.168.1.241).\",\"errorStack\":[],\"apiError\":3}'"}
`

Any thoughts?

`[root@ansible-tower ansible]# ansible --version
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
`

**Comment by JapaneseMuscleDE** [comment]
Hi Guys,

short update. Sometimes you just need to sleep a night and come up with a though the next day morning :-)

Was able to get it work now. Seems like the ADDRESS or the FQDN field is necessary if you want to add existing nodes to your pool with the NAME. Following playbook task worked for me now:

    - name: Add Member to Pool
      bigip_pool_member:
        server: f5-ltm
        user: admin
        password: ansible
        server_port: 443
        **name: nd_192-168-1-241
        address: 192.168.1.241**
        partition: Common
        pool: pl_ANS01_01
        reuse_nodes: no
        port: 80
        state: present
        validate_certs: no

Hope this can help u guys get it quicker than me

**Comment by csnyder78** [comment]
That's awesome, perhaps we can get someone to put that in the documentation.  This took 5 hrs of my day.

**Comment by chiccat** [comment]
Hello everyone,
I'm trying to do a similar task.
I have a set of nodes which are used in multiple pools.

But getting these errors:

`TASK [Add pool members] **********************************************************************************************************************************************************
failed: [127.0.0.1 -> localhost] (item=[{u'partition': u'APPS', u'name': u'POOL1', u'port': 10005}, u'node1.example.com']) => {"changed": false, "item": [{"name": "POOL1", "partition": "APPS", "port": 10005}, "node1.example.com"], "msg": "400 Unexpected Error: Bad Request for uri: https://192.168.1.10:443/mgmt/tm/ltm/pool/~APPS~POOL1/members/\nText: u'{\"code\":400,\"message\":\"0107003a:3: Pool member node (/APPS/node1.example.com) and existing node (/Common/node1.example.com) cannot use the same IP Address (192.168.1.200).\",\"errorStack\":[],\"apiError\":3}'"}
failed: [127.0.0.1 -> localhost] (item=[{u'partition': u'APPS', u'name': u'POOL1', u'port': 10005}, u'node2.example.com']) => {"changed": false, "item": [{"name": "POOL1", "partition": "APPS", "port": 10005}, "node2.example.com"], "msg": "400 Unexpected Error: Bad Request for uri: https://192.168.1.10:443/mgmt/tm/ltm/pool/~APPS~POOL1/members/\nText: u'{\"code\":400,\"message\":\"0107003a:3: Pool member node (/APPS/node2.example.com) and existing node (/Common/node2.example.com) cannot use the same IP Address (192.168.1.201).\",\"errorStack\":[],\"apiError\":3}'"}`

I do specify both name & address as suggested

Any thought on this?

Thanks!

**Comment by chiccat** [comment]
I changed to reuse_nodes: yes and I see another problem.
My Pool on one partition, but nodes in Common.
Is it possible to add nodes from Common partition to Pools in other partitions?
Thank yo

**Comment by infrascripting** [comment]
>Seems like the ADDRESS or the FQDN field is necessary if you want to add existing nodes to your pool with the NAME. Following playbook task worked for me now:
>
>```
>- name: Add Member to Pool
>  bigip_pool_member:
>    server: f5-ltm
>    user: admin
>    password: ansible
>    server_port: 443
>    name: nd_192-168-1-241
>    address: 192.168.1.241
>    partition: Common
>    pool: pl_ANS01_01
>    reuse_nodes: no
>    port: 80
>    state: present
>    validate_certs: no
```

This solved the issue that brought me here too.
