### ISSUE TITLE
Is any module I can simulate 'cisco' style config merge?

### ISSUE THREAD

**Issue by slavkv** [F5Networks/f5-ansible#87]
##### ISSUE TYPE

 - Feature Idea

Since version 11.5 (at least), F5 'tmsh' shell supports the following way to apply configuration:

load sys config from-terminal merge [verify]
<copy past config here>
CTLR+D

Is any module which I can use to deploy config in this way?

It would be ideal if we could do something like that:

- name: config change
  bigip_config_merge:
    verify_only: false
    template_source: ./<path to config file>.j2

Please advice.

**Comment by caphrim007** [comment]
@slavkv at this time no. The configuration of a bigip is only partially supported in that way of merging. If there is future support for it though, it would be via the bigip_config file.

**Comment by caphrim007** [comment]
@slavkv a module like this is now available to test with here

https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_config.py

Let me know how it works for you.

**Comment by slavkv** [comment]
@caphrim007 Thank you, I will test.
