### ISSUE TITLE
ensure bigip_facts supports provider connection method

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#871]
args connection method is going away in 2.9, but the bigip_facts module is not being removed until 2.11. Therefore, we need to ensure that provider method works with this module until the module is removed.

**Comment by caphrim007** [comment]
@dbpiv we're aware that there is no code in the module to support it. It is going away, however the replacement is not available until Ansible 2.7 is released. Replacement module is bigip_device_facts.

This issue is to provide bigip_facts with the provider method until we fully remove the module in 2.11 because the args method (what it supports today) is going away before 2.11

**Comment by dbpiv** [comment]
@caphrim007 Excellent news.... One less bug report to file!  

Thanks for the info on the replacement.  

dp
