### ISSUE TITLE
bigip_profile_client_ssl options, invalid parameter type

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#873]
There was an omission in my previous PR, whereby `options` module parameter was defined inside with `type=list` instead of `type='list'`, which is not in line what we do at the moment. 

However, because of this I have stumbled upon what I think looks like Ansible bug, here is what I have seen so far:

With `type=list` defined the issue goes like this:

When we the argument in question is specified as an empty string in the playbook:

``` 
 - options: ""
```
Internally we will end up with [''] , luckily this does not matter to the API as it accepts it as an empty string. The problem arises when we are comparing changes, which is very visible during idempotency tests. Unless we code for this, because our API will always return [], and the user provides "", we always compare:

```
[] != [""]
```
Which to API does not matter. I have coded to accommodate this in bigip_profile_http, but the same work needs to be done in the bigip_profile_client_ssl.

**Comment by wojtek0806** [comment]
@caphrim007 

 I am not sure if you want to file this as a bug in Ansible, as I have seen similiar problem but it was with 'aliases', it is not clear if this was fixed at all:

https://github.com/ansible/ansible/issues/9254

Would you also considered, if we allowed 'none' keyword to be used in the same manner as "" in the list type arguments to indicate an empty list?

**Comment by caphrim007** [comment]
@wojtek0806 we have a pattern for handling the [''] condition. https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_gtm_pool.py#L534

Yes, we can add another condition for the "none" value, but we need to adapt it across all modules that use it if we do.

**Comment by wojtek0806** [comment]
@caphrim007 what about filing bug in Ansible? I think this is a reasonable expectation that an empty string for the list parameter should equal to [] not [""]

**Comment by caphrim007** [comment]
@wojtek0806 filing bugs in ansible core is more difficult than fixing things here because you change expectations of thousands of people and modules. It was not fixed for aliases. That issue was closed and people were redirected to create a proposal in ansible core. A proposal is a major change to the ansible system; as this would be.

**Comment by wojtek0806** [comment]
ok then we just fix it here :)
