### ISSUE TITLE
Playbook fails with all_rules & default_persistence_profile set to None 

### ISSUE THREAD

**Issue by chennadi-ravi** [F5Networks/f5-ansible#88]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.2.1.0 (stable-2.2 5f5d143194)
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.4
  Build    2.0.291
  Edition  Hotfix HF2
```

##### OS / ENVIRONMENT
NA

##### SUMMARY

While using bigip_virtual_server module to build VIP's, have a task defined as below. Running ansible playbook fails if i set any off the fields on "None" (default value) on the group/host vars. 

- name: Add virtual server
  bigip_virtual_server:
    server: "{{ inventory_hostname }}"
    user: "{{ bigip_username }}"
    password: "{{ bigip_password }}"
    state: "{{ state }}"
    partition: "{{ item.partition }}"
    name: "{{ item.name }}"
    destination: "{{ item.destination }}"
    port: "{{ item.port }}"
    pool: "{{ item.pool }}"
    snat: "{{ item.snat }}"
    all_profiles: "{{ item.profiles }}"
    validate_certs: "{{ validate_certs }}"
    all_rules: "{{ item.all_rules }}"
    default_persistence_profile: "{{ item.default_persistence_profile }}"
    route_advertisement_state: "{{ item.route_advertisement_state }}"
    enabled_vlans: "{{ item.enabled_vlans }}"
  register: result
  with_items: "{{ virtuals }}"

- debug: var=result
##### STEPS TO REPRODUCE

```
For the task defined above, have below values.

virtuals:

  - destination: 2.2.2.200%4
    pool: test.abc.com_443_pool
    route_advertisement_state: enabled
    partition: FGID-00072
    port: 8443
    snat: /Common/zone4
    enabled_vlans:
       - /Common/v2495-zone4
    all_rules: None   --->>>>> playbook errors out reporting there is no irule by name None
    default_persistence_profile: None  --->> playbook errors out saying theres no persistence None
    name: test.abc.com_443
    profiles:
      - /Common/http
      - /Common/tcp
      - /Common/serverssl

```

##### EXPECTED RESULTS

On running the playbook, setting default_persistence_profile: None & all_rules: None, it should create the VIP by setting the values to None. 

##### ACTUAL RESULTS

Ansible documentation states default values of persistence & all_rules as None, but on running the playbook, F5 is looking to find the persistence/irule by the name "None" but not as expected. 

```
Below are error messages seen on setting values of playbook fails on setting default_persistence_profile: None & all_rules: None

failed: [xxx] (item={u'route_advertisement_state': u'enabled', u'destination': u'2.2.2.200%4', u'name': u'test.abc.com_443', u'default_persistence_profile': u'None', u'partition': u'FGID-00072', u'profiles': [u'/Common/http', u'/Common/tcp', u'/Common/serverssl'], u'all_rules': u'None', u'enabled_vlans': [u'/Common/v2495-zone4'], u'snat': u'/Common/zone4', u'port': 8443, u'pool': u'test.abc.com_443_pool'}) => {"failed": true, "item": {"all_rules": "None", "default_persistence_profile": "None", "destination": "2.2.2.200%4", "enabled_vlans": ["/Common/v2495-zone4"], "name": "test.abc.com_443", "partition": "FGID-00072", "pool": "test.abc.com_443_pool", "port": 8443, "profiles": ["/Common/http", "/Common/tcp", "/Common/serverssl"], "route_advertisement_state": "enabled", "snat": "/Common/zone4"}, "module_stderr": "No handlers could be found for logger \"suds.client\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_y6jtN7/ansible_module_bigip_virtual_server.py\", line 826, in <module>\n    main()\n  File \"/tmp/ansible_y6jtN7/ansible_module_bigip_virtual_server.py\", line 776, in main\n    set_rules(api, name, all_rules)\n  File \"/tmp/ansible_y6jtN7/ansible_module_bigip_virtual_server.py\", line 300, in set_rules\n    raise Exception('Error on setting rules : %s' % e)\nException: Error on setting rules : Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/VirtualServer::add_rule()\nException: Common::OperationFailed\n\tprimary_error_code   : 17236801 (0x01070341)\n\tsecondary_error_code : 0\n\terror_string         : 01070341:3: Virtual server /FGID-00072/test.abc.com_443 references rule /FGID-00072/None which does not exist.'\n", "module_stdout": "", "msg": "MODULE FAILURE"}


failed: xxx] (item={u'route_advertisement_state': u'enabled', u'partition': u'FGID-00072', u'name': u'test.abc.com_443', u'default_persistence_profile': u'None', u'destination': u'2.2.2.200%4', u'profiles': [u'/Common/http', u'/Common/tcp', u'/Common/serverssl'], u'enabled_vlans': [u'/Common/v2495-zone4'], u'snat': u'/Common/zone4', u'port': 8443, u'pool': u'test.abc.com_443_pool'}) => {"failed": true, "item": {"default_persistence_profile": "None", "destination": "2.2.2.200%4", "enabled_vlans": ["/Common/v2495-zone4"], "name": "test.abc.com_443", "partition": "FGID-00072", "pool": "test.abc.com_443_pool", "port": 8443, "profiles": ["/Common/http", "/Common/tcp", "/Common/serverssl"], "route_advertisement_state": "enabled", "snat": "/Common/zone4"}, "module_stderr": "No handlers could be found for logger \"suds.client\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_t68TZT/ansible_module_bigip_virtual_server.py\", line 826, in <module>\n    main()\n  File \"/tmp/ansible_t68TZT/ansible_module_bigip_virtual_server.py\", line 812, in main\n    raise Exception(\"Error on updating Virtual Server : %s\" % e)\nException: Error on updating Virtual Server : Server raised fault: 'Exception caught in System::urn:iControl:System/Session::submit_transaction()\nException: Common::OperationFailed\n\tprimary_error_code   : 16908342 (0x01020036)\n\tsecondary_error_code : 0\n\terror_string         : 01020036:3: The requested persist profile (/FGID-00072/None) was not found.'\n", "module_stdout": "", "msg": "MODULE FAILURE"}


```

**Comment by caphrim007** [comment]
@chennadi-ravi is your goal to just change the BIG-IP configuration so that the values of

  * default_persistence_profile
  * all_rules

are unset back on the BIG-IP? Or is your goal to create the VIP using with_items and if that particular setting (persistence_profile or all_rules) is not in the with_items list, to just not create a VIP with it?

**Comment by caphrim007** [comment]
by "not create a VIP with it" i meant, just leave it empty

**Comment by chennadi-ravi** [comment]
@caphrim007 This playbook is being used to create new VIP's & modify existing. Playbook fails if the values of persistence & all_rules are set to none & also failed leaving empty

**Comment by caphrim007** [comment]
@chennadi-ravi 

For the create new, you want to ensure that VIPs do not have those settings.
For modify you want to ensure that those settings are removed from the VIP.

Is that correct?

**Comment by chennadi-ravi** [comment]
No, I want all_rules & persistence_profile to be part of my playbooks for new or modifynVIp's. If certain VIP's don't need them, I expect the playbook to still work by setting it to "None". Is that not how its supposed to work?

**Comment by chennadi-ravi** [comment]
@caphrim007

**Comment by caphrim007** [comment]
@chennadi-ravi if certain VIPs needs them and other VIPs do not, then you can use the `omit` default filter in the playbook.

To use your example,

In your variables, just remove the keys that you do not need

```
...
    enabled_vlans:
       - /Common/v2495-zone4
#    all_rules: None   --->>>>> playbook errors out reporting there is no irule by name None
#    default_persistence_profile: None  --->> playbook errors out saying theres no persistence None
    name: test.abc.com_443
...
```

And your playbook can use omit to set them if they exist, otherwise dont set them

```
...
validate_certs: "{{ validate_certs }}"
all_rules: "{{ item.all_rules|default(omit) }}"
default_persistence_profile: "{{ item.default_persistence_profile|default(omit) }}"
route_advertisement_state: "{{ item.route_advertisement_state }}"
...
```

"None" cannot be specified by the user. It's None in the context of python, but the "None" that you are specifying there becomes the string "None", which is a valid word, and could potentially be a valid rule.

So try to use `omit` instead

**Comment by chennadi-ravi** [comment]
@caphrim007 I ran the playbook setting "default_persistence_profile: omit", still have the error

Exception: Error on updating Virtual Server : Server raised fault: 'Exception caught in System::urn:iControl:System/Session::submit_transaction()\nException: Common::OperationFailed\n\tprimary_error_code   : 16908342 (0x01020036)\n\tsecondary_error_code : 0\n\terror_string         : **01020036:3: The requested persist profile (/FGID-00066/omit) was not found.'\n", "module_stdout": "", "msg": "MODULE FAILURE"}**

**Comment by caphrim007** [comment]
@chennadi-ravi 

you need to familiarize yourself with the ansible omit filter as you are still setting a value and not using the omit filter. here is the reference in their documentation

http://docs.ansible.com/ansible/playbooks_filters.html#omitting-parameters

**Comment by caphrim007** [comment]
re-opened issue as I clicked the wrong button

**Comment by chennadi-ravi** [comment]
@caphrim007 
On setting default_persistence_profile: "{{ item.default_persistence_profile|default(omit) }}" & commented out default_persistence_profile in the host_vars file worked this time. Thanks for your help.

**Comment by caphrim007** [comment]
alrighty. closing this issue for now then.
