### ISSUE TITLE
bigip_profile_client_ssl does not support SNI 

### ISSUE THREAD

**Issue by slavkv** [F5Networks/f5-ansible#905]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_profile_client_ssl

##### ANSIBLE VERSION

```
ansible 2.6.3
```

##### PYTHON VERSION

```
Python 2.7.15
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.4
  Build       0.0.2
  Edition     Point Release 4
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.20
```

##### CONFIGURATION

[defaults]
remote_user = admin
host_key_checking = False
ask_pass=False

##### OS / ENVIRONMENT

OSX, virtualenv

##### SUMMARY

bigip_profile_client_ssl is not able to configure **'Default SSL Profile for SNI'** on a profile.

##### STEPS TO REPRODUCE
No option to configure Default SNI.

    - name: Create BASE client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ f5_cli }}"
        state: present
        name: TEST_BASE_profile
        ciphers: "TLSv1_2:TLSv1_1"
        cert_key_chain:
          - cert: test_self_signed.crt
            key: test_self_signed.key
      delegate_to: localhost

Results:

```
ltm profile client-ssl TEST_BASE_profile {
    app-service none
    cert test_self_signed.crt
    cert-key-chain {
        test_self_signed {
            cert test_self_signed.crt
            key test_self_signed.key
        }
    }
    chain none
    ciphers TLSv1_2:TLSv1_1
    defaults-from clientssl
    inherit-certkeychain false
    key test_self_signed.key
    passphrase none
}

# list ltm profile client-ssl TEST_BASE_profile sni-default
ltm profile client-ssl TEST_BASE_profile {
    sni-default false
}
```

##### EXPECTED RESULTS

```
ltm profile client-ssl TEST_GUI {
    app-service none
    cert test_self_signed.crt
    cert-key-chain {
        test_self_signed {
            cert test_self_signed.crt
            key test_self_signed.key
        }
    }
    chain none
    defaults-from TEST_BASE_profile
    inherit-certkeychain true
    key test_self_signed.key
    passphrase none
    sni-default true
}
```
```
# list ltm profile client-ssl TEST_GUI sni-default
ltm profile client-ssl TEST_GUI {
    sni-default true
}
```

I understand it must not be set by default.
Please add this functionality to this module.

If possible, it will be great to have a parameter as a dictionary where a user could pass through other optional parameters which the module does not support explicitly.

**Comment by wojtek0806** [comment]
We will implement these 3 options as they are related to SNI, so it makes sense to do so:
```
  "sniDefault" 
  "sniRequire"
  "serverName"

```

**Comment by slavkv** [comment]
@wojtek0806 thank you; is it going to be a part of Ansible 2.7 modules?

**Comment by caphrim007** [comment]
@slavkv no, the merge window for partner submissions (ie, F5) to ansible core closed at the end of last month.

The earliest it would go into the stable product is ansible 2.8.

However, during our work for 2.8, you will likely see it appear in **this** repo long before it shows up in 2.8.

So if you have tolerance for development code, you will be able to get it here early
