### ISSUE TITLE
Using Provider Dict in Modules

### ISSUE THREAD

**Issue by JapaneseMuscleDE** [F5Networks/f5-ansible#919]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_facts (but seem to apply to more modules)

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### PYTHON VERSION
```
python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### BIGIP VERSION
```
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION
- set static inventory file in the ansible.cfg
- 

##### OS / ENVIRONMENT
RedHat 7.5

##### SUMMARY
Multiple modules seem to ignore the provider dictionary which should replace the deprecated username, password, server ... and so on ...

##### STEPS TO REPRODUCE
I tried to use the provider auth with the bigip_facts module as well as other modules like bigip_pool. For the bigip_command module the provider dict is getting picked up but the facts module throws an error that the port is not specified (it only works when i put all information -> server, username, password, server_port etc <- in the playbook but then i get a warning that the params are deprecated and soon to be removed

```
---

-
  hosts: localhost

  vars:
    f5:
      user: admin
      password: ansible
      server: f5-ltm
      server_port: 443
      validate_certs: no

  tasks:
    - name: Provider test
      bigip_command:
        commands:
          - tmsh list ltm pool
        provider: "{{ f5 }}"
      register: ltm_pools

    - name: Output LTM Pools
      debug:
        var: ltm_pools

    - name: Facts Test
      bigip_facts:
        include:
          - pool
        provider: "{{ f5 }}"
...

```

##### EXPECTED RESULTS
Successful gathering of the facts in this example

##### ACTUAL RESULTS
the provider dict does not get picked up by the module

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "received exception: no                                       nnumeric port: 'None' .... and much mure
```

**Comment by caphrim007** [comment]
@JapaneseMuscleDE bigip_facts did not support `provider` until Ansible 2.7.

The other modules, such as bigip_command and bigip_pool, support it. If you're using provider, then you can ignore the warnings you see. They are there as a result of how the modules get the information from the provider and store them in argument spec variables.

If you want to use provider in bigip_facts, then you can do so as of Ansible 2.7. Our recommendation, however, is to switch to using `bigip_device_facts` in ansible 2.7 as `bigip_facts` is deprecated in 2.7 and will be removed in a future release of ansible.

**Comment by JapaneseMuscleDE** [comment]
Thanks @caphrim007 

Tried to find this information but wasnt able to. So sorry for the duplicate I that has been already discussed :-(

**Comment by caphrim007** [comment]
@JapaneseMuscleDE np
