### ISSUE TITLE
module for bigiq regkey licenses

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#92]
create a module to support BIG-IQ regkey pool licenses.

**Comment by torzillo** [comment]
I would like to add to this request.  Several customers use BigIQ for managing licenses.  The idea is that they would like to assign pool licenses, but also to assign individual key licenses to unmanaged devices.

Here is some example Python code to do this from Vernon:

#!/usr/bin/env python

# coding=utf-8

from f5.bigiq import ManagementRoot
import time

def wait_for_state(obj, state):
    for x in range(60):
        obj.refresh()
        if obj.state == state:
            return
        time.sleep(1)

mgmt = ManagementRoot( '192.168.50.5', 'admin', 'abc123!@' )

pools = mgmt.cm.shared.licensing.pools_s.get_collection()

for pool in pools:
    if pool.name == 'BestPool4':
        print "Found."
        member = pool.members_s.member.create(
            deviceAddress='172.17.32.168',
            username='admin',
            password='abc123!@',
        )
        wait_for_state(member, 'LICENSED')
        print "State = {0}".format(member.state)

print "Done."

**Comment by caphrim007** [comment]
this is now complete
