### ISSUE TITLE
Add BIG-IQ certificate module

### ISSUE THREAD

**Issue by HidingUnderMyRock** [F5Networks/f5-ansible#987]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- bigiq_ssl_certificate (proposed)

##### SUMMARY
Need to be able to deploy certificates and keys for BIG-IQ like we can to BIG-IPs.  Creating applications/services via BIG-IQ's service catalog requires certificates and keys to be managed by BIG-IQ before being used in a template.

**Comment by caphrim007** [comment]
@HidingUnderMyRock contact Roman about this. He has instructed me that this functionality (in applications) can/will be made available in the AS3 versions of Applications and that this issue should be closed for now
